Walkover-Web-Solution/Giddh-New-Angular4-App

src/app/ledger/ledger.component.html

Removed Select on Single Click

Ledger Date focus Issue Fix

---

src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.css
src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html

Go to the Invoice Templateclick on editselect content go to the third partselect slogan option and type company name and then press enter and type anything in the bracket and save it.
it will show in the same line enter will not work in this case.
For more details BUG-328

Enter is not working in Slogan option of invoice template

---

apps/web-giddh/src/app/sales/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts

when create new sock from sales invoice no need to create group. Main group will selected default. 
need to create group first then able to create stock under that group
no need to create group. Default main group will be selected

inventory : create stock default selected is main group fixed

---

apps/web-giddh/src/app/shared/helpers/pipes/ghSortByPipe/ghSortByPipe.pipe.ts

ERROR in apps/web-giddh/src/app/shared/helpers/pipes/ghSortByPipe/ghSortByPipe.pipe.ts(14,39): error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'Many<boolean | "asc" | "desc">'.
Type 'string[]' is not assignable to type 'ReadonlyArray<boolean | "asc" | "desc">'.
Type 'string' is not assignable to type 'boolean | "asc" | "desc"'.

Lodash import issue on latest Typescript

---

apps/web-giddh/src/app/sales/create/sales.invoice.component.ts

customer name is not selected bug fixed ...
when we double click on any sundry debtors/creditors in trial balance or profit loss or balance sheet a popup appears and when we click on generate invoice then sales invoice page is opened but customer name is not selected

Bug 527 point no 8 

---

apps/web-giddh/src/app/sales/create/sales.invoice.component.html

https://giddha.atlassian.net/browse/BUG-527
8. When we update the state from intra state to inter state in invoice via Edit invoice, then the tax is correctly converted from CGST-SGST to IGST. However when we update the state from inter to intra, then tax is not updated from IGST to SGST-CSGT. Please refer attached video “Issue no. 8“.  Update:-(Sameer, 4th June) - As discussed with Shubhendra Agrawal we can disable the shipping and billing details fields till this issue is resolved.

BUG-527, Point 8, Disabled State and GST input

---

apps/web-giddh/src/app/inventory/inventory.component.html
apps/web-giddh/src/app/inventory/inventory.component.ts

8. Linking issue when we select "Job work" option from "All Modules" option it navigates to “job work“ but if we select “inventory“ again from all module so it displayed the same page.(refer video issue8)

BUG-531 - 8 navigation bug fixed ..

---

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts

…ocal date range set earlier
1. On invoices page, when we set the global date range as app date, then the local date range also sets to the same. Now edit an invoice and select cancel button. The local date range set earlier is changed to last one month date range. Please refer attached video "Issue no.1". : Done
2. Also one more issue related to invoice list page is that when we move from one page to another the loader appears out of table. Please refer attached video "Issue no.2". : Done

Test/Stage- In edit invoice selecting the cancel button changes the local date range set earlier 

---

apps/web-giddh/src/app/contact/contact.component.html
apps/web-giddh/src/app/contact/contact.component.ts

in customer and vendor module column filter toggle state is saved in local storage 
No need to select column field in customer and vendor table agin and again

table column add and remove is managed via local storage

---

apps/web-giddh/src/app/shared/helpers/directives/decimalDigits/decimalDigits.directive.ts

In ledger copy with special character will be able to pest for make Tx
In ledger copy with special character amt will not be able to pest and return 0
In ledger copy with special character amt will be able to pest and return clipboard copy content with removed special char

BUG 578 : Ledger copy pest for special character issue has been resolved

---

apps/web-giddh/src/app/sales/create/sales.invoice.component.ts

In Case of Page Change Check event the isSales Invoice flag was getting set to true by Default and was never set to false if the IsCashInvoice is true
Fixes the Change in case if the sales invoice is enables when the case is cash invoice.
Right now the Balance amount was getting displayed in case of Cash Invoice
Balance invoice can only be displayed in Case of SALE Invoice

BUG - 609 - Handled the Cash Invoice Scenario in Case of Page Change

---

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
apps/web-giddh/src/app/ledger/ledger.component.html

Removed Cross Button From Ledger

remove cross button from ledger

---

apps/web-giddh/src/app/contact/contact.component.html

point no 2,3 fixed of G0-332
In vendor module field Amount due field "Add Cashfree" button is getting displayed instead of the Amount due value
table row issue fixed 

contact issue fixed

---

apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.ts

It was swaping date DD-MM-YYYY to MM-DD-YYYY on second time, but now its fixed

Date filter issue fixed

---

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html

Multi currency added
TCS, TDS in subtotal section and
TCS table removed

Stage_TDS/TCS- PDF is not similar with Template

---

apps/web-giddh/src/app/aging-report/aging-report.component.html

aging report duplicate total due bug fixed 
currently there is two total due columns 
now we have removed duplicate total due column

column issue fixed

---

apps/web-giddh/src/app/actions/invoice/receipt/receipt.actions.ts

wrong message displayed when voucher delete api is fired ==> fixed
wrong message displayed when voucher delete api is fired
success message will be displayed on success and error on error 

voucher delete issue fixed

---

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts

Bug fix
Prod -Tax is removed when clicked anywhere on the ledger page outside the entry window 
State of tax field is retained

changes for G0-295

---

apps/web-giddh/src/app/services/apiurls/gstR.api.ts

passing page params in pagination for GSTR 2 in get Transactions API
Gstr 2 pagination page params was not passing in API
Gstr 2 pagination page params is passing

HOTFIX-G0-793-stage: Gstr 2 pagination issue solved

---

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts

Bug fix
Prod -Tax is removed when clicked anywhere on the ledger page outside the entry window 
State of tax field is retained

staging changes for G0-295

---

apps/web-giddh/src/app/services/apiurls/gstR.api.ts

passing page params in pagination for GSTR 2 in get Transactions API
Gstr 2 pagination page params was not passing in API
Gstr 2 pagination page params is passing

HOTFIX-G0-793-prod: Gstr 2 pagination issue solved for prod

---

apps/web-giddh/src/app/sales/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts

product/ service not displaying after creating from aside pane
product/ service is not displayed after creating from aside pane
now product/ service should de displayed after that created in aside pane 

product service not displayed bug fixed

---

apps/web-giddh/src/app/sales/create/sales.invoice.component.ts

find customer field accepts email and contact as filter parameter
Bug Fix
filter was applied only on name for search customer
filter applied on name email and contact

G0-273 fix

---

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
apps/web-giddh/src/app/sales/create/sales.invoice.component.html
apps/web-giddh/src/app/sales/create/sales.invoice.component.ts

* **What is the current behaviour?** (You can also link to an open issue here)
1) In the sales invoice, search customer by mobile number and email-id is not working.
2) Edit sales invoice name is Invoice. 
3) In invoice list page mail icon is getting displayed for all invoices even though it is not sent through e-mail.  (Refer img Issue 3) 
4) Through settings “User custom invoice no“ is checked and set invoice no then in “sales Invoice” Invoice no field is disabled and customer set invoice no is displayed in that field, If “User custom invoice no“ is not checked then In sales invoice Invoice no field will not be reflected. (refer video Issue 4)
5) When we generate sales invoice with full payment amount entered in deposit section, then on invoice list page and on invoice voucher the …

G0-273 staging changes

---

apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.scss
apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
apps/web-giddh/src/app/sales/create/sales.invoice.component.html
apps/web-giddh/src/app/sales/create/sales.invoice.component.ts

In Inventory module user should not be allowed to apply more than 1 GST tax at a time on a stock. So disable other GST taxes in dropdown when user select a GST tax.
In Inventory module user should not be allowed to apply more than 1 InputGST tax at a time on a stock. So disable other InputGST taxes in dropdown when user select an InputGST tax.
In Inventory module user can apply GST and InputGST simultaneously on a stock.
4. In Inventory module when user apply GST and InputGST simultaneously on a stock and:
a) In Sales invoice when user selects the same stock then only GST tax should be pre-applied and not InputGST.
b) In Purchase invoice when user selects the same stock then only InputGST tax should be pre-applied and not GST.
c) In Cash invoice when user selects the same stock then only …

G0-324 : Inventory Allow to Apply Multiple GST tax

---

apps/web-giddh/src/app/contact/contact.component.html

feature
In Vendor section the labels Sales and Receipt under Result total section were Sales and Receipt
In Vendor section the labels Sales and Receipt under Result total section  renamed as Purchase and Payment

vendor tab updated

---

apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts

BUG FIX
Spelling of Purchase is not correct in "Voucher Type" drop down in inventory stock table.
Purchse changed tO Purchase

typo changes

---

apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.ts

feature
On "Create New Trigger" page in "Scope" dropdown currently there values i.e. "Entry" "Invoice" and "Closing Balance" are displayed.
On "Create New Trigger" page in "Scope" dropdown only "Closing Balance" is displayed.

option hidden

---

apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html

feature
The SKU code should be accepted alphanumeric keys, currently in SKU field not accepted alphanumeric characters. 
The SKU code is accepting alphanumeric keys,

sku input type edited

---

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html

bug fix
Additional amount is not displaying in red in color.
Additional amount is now displaying in red in color.

additional charges in red

---

apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.ts

bug
quarter 1 for that drop-down is missing and in footer label and values are not displayed. 
Quarter is now displayed as label. It is not clickable

Quaterly isssue

---

apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
apps/web-giddh/src/app/theme/tax-control/tax-control.component.html

bug fix
In sales invoice discount and tax drop-down is overlapped.
dropdown issue resolved

dropdown overlapped resolved

---

apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.html
apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.ts

cr
Bank details fields are not displayed via Add Vendor link in Purchase Invoice
Bank details fields are now displayed via Add Vendor link in Purchase Invoice

bank details added

---

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html

Prod-In invoice template "Total rate" and "Total discount" is displayed which is not as per the part of design document

G0-2618 : Removed Total rate, Total discount

---

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts

bug fix
On debit/credit note and Estimate/Proforma page SKU field is not displayed.
On debit/credit note and Estimate/Proforma page SKU field is now displayed.

display SKU Code

---

apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts

bug fix
If other tax is selected then, in linked account drop-down duties and taxes should be displayed
If other tax is selected then, in linked account drop-down duties and taxes are displayed

Linked account tax list

---

apps/web-giddh/src/app/shared/header/components/account-add-new/account-add-new.component.html

bug fix
In create account state field is not displaying mandatory star mark in manage and groups 
In create account state field is now displayed mandatory star mark in manage and groups 

state field compulsory

---

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html

In case of null company address will showing hard coded walkover address in template a
In case of null company address will showing hard coded walkover address in template a
In case of null company address will showing null address in template a

gst template a company address issue fixed in case of null address

---

apps/web-giddh/src/app/app-login-success/app-login-success.html
apps/web-giddh/src/app/app-login-success/app-login-success.scss
apps/web-giddh/src/app/app-login-success/app-login-success.ts
apps/web-giddh/src/app/app.module.ts
apps/web-giddh/src/app/app.routes.ts

* **What kind of change does this PR introduce?** (Bugfix, feature, docs update, ...)
this PR is to add app-login-success page. So after electron login User can see the below page. 
currently, it is not showing any page. 
after Electron login they see a success login page.

added app-login-success route for electron success call back,

---

apps/web-giddh/src/app/actions/invoice/receipt/receipt.actions.ts
apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts
apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
apps/web-giddh/src/app/services/receipt.service.ts

Proper navigation to Edit Sales invoice from GST edit invoice flow
Currently, it doesn't navigate and stays on the same page

fix: Issue #G0-4641, Edit invoice in GST summary is working incorrect

---

apps/web-giddh/src/app/actions/accounts.actions.ts
apps/web-giddh/src/app/actions/ledger/ledger.actions.ts
apps/web-giddh/src/app/actions/sales/sales.action.ts
apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html

This issue is reported by Sheba. Virtual account error is displayed for those existing Production users who had enabled virtual account feature before this Cash free feature i.e. Cash free API was removed from Prod. So this error should not be displayed now.

Fixed | 4126 | Prod - Virtual account error is displayed for users who had enabled virtual account before this feature was removed

---

apps/web-giddh/src/app/gst/gst.component.html
apps/web-giddh/src/app/gst/gst.component.ts

Steps
1. Go to GST module
2. Click on the Date picker > Custom range
3. Click on the left/right arrows to set the range
4. Then the calendar shifts to the upward direction which is not expected
Actual- The calendar shifts to the upward direction which is not expected
Expected- The calendar should not be shifted upward side when the user tries to set the date range

Fixed G0-3980 | Prod- In the GST module date picker issue

---

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts

It avoids the API call to currency rate api if either of the from or to date is a falsy value

fix: Add nullity check in get currency rate method in proforma

---

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts

It fixes the total not getting calculated for expense category as the bottom UI row is not visible if more than one expense categories is found

fix: Issue #G0-4641

---

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts

It adds the missing calculation of compound total for expense category transactions

fix: Calculate compound total

---

apps/electron-giddh/src/main-auth.config.ts

It renames the URL of TEST for electron to HTTPS

fix: Rename URL to HTTPS

---

apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.html

Default template is not highlighted in blue color for Credit and Debit notes in templates.

Fixed G0-4743 | Prod - Default template is not highlighted in blue color for Credit and Debit notes in templates

---

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts

- It fixes the focus change issue when user type CMD + K on Proforma Invoice component
- It fixes the flickering issue that is caused due to any API call on Proforma Invoice component
Currently the code subscribes to global loader service to show and hide loader (`showLoader`) on Proforma Invoice component that runs change detection every time any service call is made in Giddh application which is the root cause for wrong focus and flickering issue
The code no longer subscribes to the global loading service and sets the `showLoader` flag when the API used in that …

Auto focus issue on CMD+K

---

apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts

It displays an error toast if the user during stock creation only provides either of unit or rates
Currently no error message is displayed and on form submit first Group creation API is called and then Stock creation API is called. Former call succeeds and the latter call fails.
Unless the user enters both unit and rate or leave both blank he will neither be able to create Group nor Stock.

fix: Issue #G0-4824

---

apps/web-giddh/src/app/ledger/ledger.component.html

1. For all the vouchers type the text should be “download voucher “.
2. And for the invoice, it should download the invoice the same as it is working currently.

Fixed G0-3353 | Label of download for vouchers other than Invoice needs to be made more appropriate 

---

apps/web-giddh/src/app/invoice/invoice.component.ts

Steps to recreate
1. Click on to the invoice management page2. then click on Invoices3. Then click on the Recurring Hensding is displayed as Invoice> Recurring4. Then click on the pending no heading changes displayed the same as for the setting and templatesThe same issue is for the credit and debit note heading issue
Expected-  When user click on the pending then heading should be Invoice> PendingInvoice> SettingsInvoice> Template

Fixed - G0-4892 | Prod- Heading is wrongly displayed when click on the other module

---

apps/web-giddh/src/app/invoice/invoice.component.ts

Steps to recreate
1. Click on to the invoice management page
2. then click on Invoices
3. Then click on the Recurring Hensding is displayed as Invoice> Recurring
4. Then click on the pending no heading changes displayed the same as for the setting and templatesThe same issue is for the credit and debit note heading issue
Expected-  When user click on the pending then heading should be Invoice> PendingInvoice> SettingsInvoice> Template

G0 - 4892 | Prod- Heading is wrongly displayed when click on the other module

---

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html

According to Sir, If stock has a hsn number and sac number is not there and manage inventory in company-setting is false then also we have to show hsn number in invoice and vice-versa.
If both HSN and SAC number are present in stock then we need to check manageInventory setting -
if true → show HSN
if false → show SAC

G0-2348 | fixed UI logic to show SAC number

---

apps/web-giddh/src/app/invoice/preview/models/confirmation/confirmation.model.component.html
apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
apps/web-giddh/src/app/invoice/proforma/proforma-list.component.ts

- It adds the confirmation popup for Estimate and Proforma for deletion and also changes the confirmation popup heading text to make it more generic so that it can be reused in other modules

Bugfix/G0-4846 | Prod- On the estimates and proforma after click on the delete voucher option not confirmation msg not displayed 

---

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html

Steps
1. Go to the subscription module
2. Then Professional plan is displayed as default which is not expected
Expected- Selected plan name should be displayed instead of Professional plan

Fixed G0-4906 | Prod- On the subscription module Professional Plan is displayed as default instead of plan name

---

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
apps/web-giddh/src/app/ledger/ledger.component.ts

It merges the taxes of ledger account and particular account with autofill only the taxes that are pre-applied to those accounts

Feature/G0-4885 | Default Tax applied on Sales account in Manage Accounts is not applied by default in Sales Ledger

---

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts

Calculation takes place only for `assets` category, this check was removed
Currently through ledger any entry is allowed to become an Advance Receipt entry and therefore limiting the calculation only for `assets` category will give issues for other category accounts

fix: Calculation not taking place if the involved account is liability

---

apps/web-giddh/src/app/home/home.component.ts
apps/web-giddh/src/app/shared/header/header.component.ts

It removes the redundant incorrect call to show modal method

fix: User not navigated to subscription page after selecting change plan

---

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts

- It resets the the selectedInvoiceList array after successful deletion of voucher

fix: On the invoice management page if we delete the invoice then getting the error

---

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts

It removes the hard coded tax types used due to which tax of particular type is not disabled if the same type of tax is already selected

G0-4886 | On the sales invoice page after selecting one gst tax other gst taxes are not displayed disabled

---

apps/web-giddh/src/app/ledger/underStandingTextData.ts

I have confirmed with @Akanksha that Increasing should be on left side and Decreasing on right side.

Prod - Text of ledger heading on CR and DR side for Reverse Charge ledger is incorrect

---

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts

Prod- On the update sales invoice page error is displayed for the invalid GST no

Bugfix/g0 5113 dev | Prod- On the update sales invoice page error is displayed for the invalid GST no

---

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts

This PR limits the call to exchange rate API to components where it is actually required and adds the code to fetch the currency exchange rate for Invoice in proforma invoice component

fix: Avoid unnecessary currency exchange rate call

---

apps/web-giddh/src/app/app.component.ts
apps/web-giddh/src/app/login/login.component.ts

It fixes the navigation issue from vendor module caused due to shadowing of `isCordova` in webpack config due to `isCordova()` of Giddh utils

fix: Navigation issue from vendor module

---

apps/web-giddh/src/app/home/components/datepickeroptions/datepickeroptions.component.ts

G0-5366 | Prod - "This Financial Year to Date" filter is not working on date picker for "Total Overdues" section in Dashboard module

G0-5366 | Prod - "This Financial Year to Date" filter is not working on date picker for "Total Overdues" section in Dashboard module

---

apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts

It adds the integration with clear filter button even when user searches in customer name, invoice and receipt number or sets the type of receipt.

feat: Integrate clear filter button with all search query filter and receipt type filter

---

apps/web-giddh/src/app/home/components/datepickeroptions/datepickeroptions.component.ts

G0 5356 | | Prod - "This Financial Year to Date" filter is not working on date picker for "Total Overdues" section in Dashboard module

G0 5356 | | Prod - "This Financial Year to Date" filter is not working on date picker for "Total Overdues" section in Dashboard module

---

apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.html
apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.ts
apps/web-giddh/src/app/models/defaultMenus.ts
apps/web-giddh/src/app/reports/components/receipt-advance-search/receipt-advance-search.component.html

Hide unused amount when normal receipt is selected

fix: Hide unused amount when normal receipt is selected

---

apps/web-giddh/src/app/contact/aside-menu-account/aside.menu.account.component.ts
apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts

This PR fixes the state not mandatory while creating account within sundry creditor or sundry debtor.
Currently the code only compares for current active group unique name with hard coded value '`sundrydebtor`' or '`sundrycreditor`'.
Now the code searches for all the parent groups and if any of the groups lies in '`sundrydebtor`' or '`sundrycreditor`' then state is made mandatory

fix: State not mandatory for sundary Debtor

---

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts

in case of edit invoice we will show the deposit section and only the adjust amount button will display in that.
If no advance receipt of any particular debtor is present then we will disable that button. As 
from the management page, we will provide both the action that is if the user wants to adjust the amount from here he can do that and also if he wants to update the adjusted amount he can also do that.
When an invoice is adjusted multiple times with the same advance we will club that invoice and display a single time.

advance receipts new flow with edit and create invoice implemented

---

apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.ts
apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts

Make tax amount zero for future taxes in CREATE and UPDATE ledger
Currently the tax amount is calculated only during instantiation and not when user changes the entry date
Tax will be calculated on ledger CREATE and UPDATE flow and future taxes will have amount set to 0 if entry date is changed to a past date and is less than tax date

fix: Make tax amount zero for future taxes in CREATE and UPDATE ledger

---

apps/web-giddh/src/app/vat-report/vatReport.component.html
apps/web-giddh/src/app/vat-report/vatReport.component.scss

Show a default message when TRN is not provided in Settings Profile

G0-5462 | fix: VAT report is not working, nothing happens on selecting any filter

---

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts

It checks for GST length if it is 0 then no checks are applied as the issue occurs when GST length is neither equal to 15 nor greater than 2 and country is India then state code is set to null which invalidates the form and hence the issue

PROD: G0-5478 | fix: Save button gets disabled on moving the cursor in GSTIN field on Create Account page for Sundry Debtor/Sundry Creditor

---

apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
apps/web-giddh/src/app/shared/header/header.component.html

From the side panel option when we click on the android option download option is not available  
https://giddha.atlassian.net/browse/G0-5524
-------------------------------------------------
Test on the adjustment of advanced receipt popup box if amount is displayed on the next line and symbol is displayed 
https://giddha.atlassian.net/browse/G0-5548

Sadique| android url issue

---

apps/web-giddh/src/app/settings/financial-year/financial-year.component.ts
apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts

Pass string value in sh-select label, convert non-string value in sh-select to string and then apply operation

G0-5649 | TEST + /pages/settings/financial-year

---

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
apps/web-giddh/src/app/store/proforma/proforma.reducer.ts

fix: Prevent infinite loading in Proforma and Estimate when API fails

---

apps/web-giddh/src/app/actions/login.action.ts

Fixed G0-6661 | Prod- After login message is displayed please wait
{
"user_agent": "Mozilla/5.0 (Windows NT 6.1; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
"user": "Name: Madhur N. Agrawal Email: madhurna@govpro.in Company Uniquename: ",
"page": "/token-verify?token=ya29.a0Ae4lvC0vdJx1zMRxWCgDYf9XMY-ahQiMWOmo3P2svfxFIOmhVqDfVSJ2e6dmwlN8iH4_5_xdWNM1V1LnwWbnmjq08zwraAoZ6CiLCNaZPN_gp5nluyZ0K5lWRWWG-s9wizJ0U7j4tF7F0-ilG9j16ANzjx0VfYwQKiQ",
"error": "TypeError: Cannot read property 'uniqueName' of undefined\n    at e.doSameStuffs (https://app.giddh.com/main.15b6e39a0045fc651d89.js:1:20407)\n    at …

Fixed G0-6661 | Prod- After login message is displayed please wait

---

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts

Fixed GIDK-412 | Prod - On Firefox browser Subscription details are not getting displayed on Susbscription page

Fixed GIDK-412 | Prod - On Firefox browser Subscription details are not getting displayed on Susbscription page

---

apps/web-giddh/src/app/contact/contact.component.html

Ravinder | Development | GIDK-643 | In Vendor and Customer modules Closing and Opening balances must be negative depending on the type i.e. CR/DR

Ravinder | Development | GIDK-643 | In Vendor and Customer modules Closing and Opening balances must be negative depending on the type i.e. CR/DR

---

apps/web-giddh/src/app/contact/contact.component.html

Ravinder | Staging | GIDK-643 | In Vendor and Customer modules Closing and Opening balances must be negative depending on the type i.e. CR/DR

Ravinder | Staging | GIDK-643 | In Vendor and Customer modules Closing and Opening balances must be negative depending on the type i.e. CR/DR

---

apps/web-giddh/src/app/contact/contact.component.html

Ravinder | Production | GIDK-643 | In Vendor and Customer modules Closing and Opening balances must be negative depending on the type i.e. CR/DR

Ravinder | Production | GIDK-643 | In Vendor and Customer modules Closing and Opening balances must be negative depending on the type i.e. CR/DR

---

apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.ts

previosly, for flattenAccouts data, component was relaing on api now data is being gathered by general store.   

Gidk 115 | yogesh | Prod - Search with uniquename in Audit log "Group" and "Account" columns is not working

---

apps/web-giddh/src/app/services/general.service.ts

Prod - On mozilla when we open giddh, it is not showing the time of Tally Sync in  'Import data from Tally'

Prod - On mozilla when we open giddh, it is not showing the time of Tally Sync in  'Import data from Tally'

---

apps/web-giddh/src/app/services/general.service.ts

Stage - On mozilla when we open giddh, it is not showing the time of Tally Sync in  'Import data from Tally'

Stage - On mozilla when we open giddh, it is not showing the time of Tally Sync in  'Import data from Tally'

---

apps/web-giddh/src/app/services/general.service.ts

Beta - On mozilla when we open giddh, it is not showing the time of Tally Sync in  'Import data from Tally'

Beta - On mozilla when we open giddh, it is not showing the time of Tally Sync in  'Import data from Tally'

---

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts

https://app.clickup.com/t/1xbq8g

fix: GIDK-#1xbq8g | Prateek | Test | Reverse charge data is not going on GSTR 3B when PB is created from ledger

---

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts

https://app.clickup.com/t/1xbq8g

fix: GIDK-#1xbq8g | Prateek | Stage | Reverse charge data is not going on GSTR 3B when PB is created from ledger

---

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts

https://app.clickup.com/t/1xbq8g

fix: GIDK-#1xbq8g | Prateek | Prod | Reverse charge data is not going on GSTR 3B when PB is created from ledger

---

apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts

Electron Build < Blank page is displayed when user clicks on any invoice to preview in GST module.

Electron Build < Blank page is displayed when user clicks on any invoice to preview in GST module.

---

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html

…
https://app.clickup.com/t/2ne6a4

fix: GIDK-#2ne6a4 | Prateek | Test | Prod - Shipping address field should be enable by default on sales/cash invoice creation page

---

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html

https://app.clickup.com/t/2ne6a4

fix: GIDK-#2ne6a4 | Prateek | Beta | Prod - Shipping address field should be enable by default on sales/cash invoice creation page

---

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts

This PR reverts the PR [#6202](https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/pull/6202) as the issue [#37dmwh](https://app.clickup.com/t/37dmwh) is raised due to it. Can't find the card for which the PR [#6202](https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/pull/6202) changes were made (discussed with all the team members).
The current behavior is for RCM entry the taxes are sent as particular during UPDATE entry flow which is not acceptable and is returning error to the user. This issue can be recreated by converting a normal entry (with taxes) to a RCM entry.
* **What is the new behavior …

fix: Prateek | Test | Revert PR #6202 which is causing issue clickup-#37dmwh

---

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts

This PR reverts the PR [#6202](https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/pull/6202) as the issue [#37dmwh](https://app.clickup.com/t/37dmwh) is raised due to it. Can't find the card for which the PR [#6202](https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/pull/6202) changes were made (discussed with all the team members).
The current behavior is for RCM entry the taxes are sent as particular during UPDATE entry flow which is not acceptable and is returning error to the user. This issue can be recreated by converting a normal entry (with taxes) to a RCM entry.
* **What is the new behavior …

fix: Prateek | Stage | Revert PR #6202 which is causing issue clickup-#37dmwh

---

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts

This PR reverts the PR [#6202](https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/pull/6202) as the issue [#37dmwh](https://app.clickup.com/t/37dmwh) is raised due to it. Can't find the card for which the PR [#6202](https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/pull/6202) changes were made (discussed with all the team members).
The current behavior is for RCM entry the taxes are sent as particular during UPDATE entry flow which is not acceptable and is returning error to the user. This issue can be recreated by converting a normal entry (with taxes) to a RCM entry.
* **What is the new behavior …

fix: Prateek | Beta | Revert PR #6202 which is causing issue clickup-#37dmwh

---

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts

This PR reverts the PR [#6202](https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/pull/6202) as the issue [#37dmwh](https://app.clickup.com/t/37dmwh) is raised due to it. Can't find the card for which the PR [#6202](https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App/pull/6202) changes were made (discussed with all the team members).
The current behavior is for RCM entry the taxes are sent as particular during UPDATE entry flow which is not acceptable and is returning error to the user. This issue can be recreated by converting a normal entry (with taxes) to a RCM entry.
* **What is the new behavior …

fix: Prateek | Prod | Revert PR #6202 which is causing issue clickup-#37dmwh

---

.github/workflows/build.yml

It changes the Slack channel from Giddh default channel to UI build channel

Change the Slack channel for posting PROD build notification
