Walkover-Web-Solution/Giddh-New-Angular4-App

apps/web-giddh/src/app/contact/contact.component.scss
=> Customer module checkbox bug

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/assets/css/style-2.scss
=> error msg code correct

apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.html, apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.html, apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.ts, apps/web-giddh/src/app/reports/components/columnar-report-table-component/columnar.report.table.component.html, apps/web-giddh/src/app/reports/components/columnar-report-table-component/columnar.report.table.component.ts
=> G0 8080 prod: CR/DR and +/- implemented on columnar

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
hide datepicker on orientation change
=> hide datepicker on orientation change

apps/web-giddh/src/app/accounting/accounting.component.css, apps/web-giddh/src/app/accounting/accounting.component.html, apps/web-giddh/src/app/accounting/accounting.module.ts, apps/web-giddh/src/app/accounting/accouting-sidebar/accounting-sidebar.component.scss, apps/web-giddh/src/app/accounting/invoice-grid/invoice-grid.component.ts, apps/web-giddh/src/app/accounting/journal-voucher/invoice/invoice.component.html, apps/web-giddh/src/app/accounting/journal-voucher/invoice/invoice.component.scss, apps/web-giddh/src/app/accounting/journal-voucher/invoice/invoice.component.ts, apps/web-giddh/src/app/accounting/journal-voucher/journal-voucher.component.html, apps/web-giddh/src/app/accounting/journal-voucher/journal-voucher.component.scss, apps/web-giddh/src/app/accounting/journal-voucher/journal-voucher.component.ts, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts, apps/web-giddh/src/app/accounting/keyboard.directive.ts, apps/web-giddh/src/app/accounting/voucher-grid/voucher-grid.component.ts, apps/web-giddh/src/assets/css/color.scss, apps/web-giddh/webpack.cordova.local.partial.js
=> Build error

apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.ts, apps/web-giddh/src/app/reports/components/columnar-report-table-component/columnar.report.table.component.html, apps/web-giddh/src/app/reports/components/columnar-report-table-component/columnar.report.table.component.ts
=> PR changes done

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> mobile issues fixed of invoice

apps/web-giddh/src/app/contact/contact.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> Staging to PROD

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html
displayed active date on focus
=> displayed active date on focus

apps/web-giddh/src/app/userDetails/components/deactivate-company/deactivate-company.component.html
=> removed functions call

apps/web-giddh/src/environments/environment.stage.ts, apps/web-giddh/webpack.stage.partial.js
=> fix: Change API url for staging

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html
=> Displayed expired date

apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
=> UI issues fixed

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/reports/components/cash-flow-statement-component/cash.flow.statement.component.html, apps/web-giddh/src/app/reports/components/cash-flow-statement-component/cash.flow.statement.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/shared/datepicker-wrapper/datepicker.wrapper.component.ts
updated code to fix position issue in datepicker
=> updated code to fix position issue in datepicker

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/helpers/pipes/currencyPipe/currencyType.pipe.ts
=> fix: Calculation issue and remove trailing zeros

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/color.scss, apps/web-giddh/src/assets/css/style-2.scss
=> UI issue fixed

apps/web-giddh/src/app/login/token-verify.component.ts, apps/web-giddh/src/app/services/general.service.ts
=> fix: Login issue

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
=> fix design and dropdown toggle event

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.scss
=> make table responsive

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
=> fixed mobile issues

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
=> added padding bottom of the datepicker

apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html, apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
GIDK-41 Fixed Subscription issues
=> GIDK-41 Fixed Subscription issues

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
=> fix: Aside pane is visible at the start

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Issue #GIDS-136 | From the edit sales invoice if user move to ctrl +k credit note then invoice number list is getting displayed

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
=> fix: Issue #G0-8304 | Download PDF icon is displayed for blank rows as well in Ledger

apps/web-giddh/src/app/vat-report/vatReport.component.ts
removed universal date involvement in vat report
=> removed universal date involvement in vat report

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/models/api-models/Contact.ts
=> fix: Filters not retaining value during module change, remove unused filter closing balance, improper functioning of select-all functionality

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
=> fix: Bank account details getting sent in API request of UPDATE account:

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html
removed active company plan from top and displayed in bottom
=> removed active company plan from top and displayed in bottom

apps/web-giddh/src/app/app.constant.ts
Updated default trial plan and popular plan for test
=> Updated default trial plan and popular plan for test

apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/settings/permissions/form/form.component.html, apps/web-giddh/src/app/settings/permissions/form/form.component.ts
Prod - Unable to enter more than 6 digits in IP address field in Permissions module
=> GIDS-259 | Prod - Unable to enter more than 6 digits in IP address field in Permissions module

apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/settings/permissions/form/form.component.html, apps/web-giddh/src/app/settings/permissions/form/form.component.ts
=> Gids 259 | Prod - Unable to enter more than 6 digits in IP address field in Permissions module

apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
=> fix: Issue of sh-select resetting

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/contact.module.ts, apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
=> fix: Remove cash free API call and pay now modal from contact component

apps/web-giddh/src/app/contact/contact.component.ts
=> fix: Remove single character

apps/web-giddh/src/app/accounting/journal-voucher/journal-voucher.component.ts, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
=> fix: Hide calendar on escape key press, show current assets in account creation group, show only By when JV is launched

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts, apps/web-giddh/src/app/models/api-models/Invoice.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/store/Common/common.reducer.ts, apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
User can generate pending invoice
pending Invoice implemented for Sales Invoice, CN,DN and Cash 
Multicurrency implemented for all (Sales Invoice, CN,DN and Cash )
=> Gids 37 : Preview pending implemented for cash sales invoice with multi currency

apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts, apps/web-giddh/src/app/ledger/components/ledger-columnar-report-table/ledger.columnar.report.table.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html
=> Ledger pagination and GST invoice download implemented

apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts, apps/web-giddh/src/app/ledger/components/ledger-columnar-report-table/ledger.columnar.report.table.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html
=> Gidk 85 developement: Ledger pagination and GST invoice download implemented

apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
=> date format issue fixed

apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts, apps/web-giddh/src/app/ledger/components/ledger-columnar-report-table/ledger.columnar.report.table.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html
=> Gidk 85 prod: Implement GST download invoice and ledger pagination

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts, apps/web-giddh/src/app/models/api-models/Invoice.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/store/Common/common.reducer.ts, apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
User can generate pending invoice
pending Invoice implemented for Sales Invoice, CN,DN and Cash
Multicurrency implemented for all (Sales Invoice, CN,DN and Cash )
=> Gids 37 stage: Preview pending implemented for cash sales invoice with multi currency 

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
=> update color name

apps/web-giddh/src/app/theme/ng-social-login-module/auth.service.ts
"Error: Uncaught (in promise): Error: Loading chunk 1 failed.
(error: https://app.giddh.com/1.0a112ebebb27e5fc6d55.js)
Error: Loading chunk 1 failed.
=> fix: GIDS-236

apps/web-giddh/src/app/actions/login.action.ts
=> added condition to redirect to mobile-home for mobile app

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/ledger.component.html
=> feat: Rename Generate Invoice to Generate Voucher

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.ts
=> Stage bug fix

apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.scss, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> datepicker ledger issue resolved

apps/web-giddh/src/app/actions/settings/settings.integration.action.ts, apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Gids 81 staging 2: issues 

apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.scss, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Cherry pick mobile issue

apps/web-giddh/src/app/actions/settings/settings.integration.action.ts, apps/web-giddh/src/app/models/api-models/SettingsIntegraion.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> DUpdate succes and message body issue solved

apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts, apps/web-giddh/src/app/inventory/inventory.component.ts
=> fix: Issue GIDK-297 & GIDK-306

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/contact.module.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/models/interfaces/registration.interface.ts, apps/web-giddh/src/app/services/apiurls/comapny.api.ts, apps/web-giddh/src/app/services/companyService.service.ts
=> Pay and resend OTP API implemented

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/contact.module.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/models/interfaces/registration.interface.ts, apps/web-giddh/src/app/services/apiurls/comapny.api.ts, apps/web-giddh/src/app/services/companyService.service.ts
=> Gids 81 staging 2: Pay and resend OTP API implemented 

apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.scss
=> fixed close button issue

apps/web-giddh/src/index.prod.html
=> GTM issues fixed

apps/web-giddh/src/app/app.component.html, apps/web-giddh/src/index.prod.html
=> Google tag manaager no-script tag added in index prod and remove from app.component

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/services/apiurls/settings.integration.api.ts, apps/web-giddh/src/app/services/settings.integraion.service.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/app/settings/settings.module.ts
=> Gids 81 bugs: implemented validations on bulk and bank integration

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/permissions/form/form.component.ts, apps/web-giddh/src/app/settings/permissions/setting.permission.component.html, apps/web-giddh/src/app/settings/permissions/setting.permission.component.ts
=> Build issues fixed and addd validations

apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk19 header today option implemented on universal datepicker

apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk19: header today option is implemented 

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
Gids 362 | Remove astrick mark in case of Advance receipt creation/updation from UI
=> Gids 362 | Remove astrick mark in case of Advance receipt creation/updation from UI

apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
fixed issue were api was getting called even if cancel button was clicked in datepicker
=> fixed issue were api was getting called even if cancel button was clicked in datepicker

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/index.cordova.local.html, apps/web-giddh/src/index.cordova.prod.html, apps/web-giddh/src/index.cordova.stage.html, apps/web-giddh/src/index.dev.html, apps/web-giddh/src/index.electron.prod.html, apps/web-giddh/src/index.html, apps/web-giddh/src/index.local.html, apps/web-giddh/src/index.prod.html, apps/web-giddh/src/index.stage.html, apps/web-giddh/src/index.test.html
fixed app component selector isuse and GTM code
=> fixed app component selector isuse and GTM code

apps/web-giddh/src/index.html, apps/web-giddh/src/index.stage.html, apps/web-giddh/src/index.test.html
=> Removed GTM code from dev

apps/web-giddh/src/index.html, apps/web-giddh/src/index.stage.html, apps/web-giddh/src/index.test.html
=> Removed GTM code from stage

apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts
=> fix: Wrong file extension and wrong date in export ledger

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/models/interfaces/registration.interface.ts, apps/web-giddh/src/app/services/contact.service.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.scss, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/assets/css/style-2.scss
=> Gids 081: Implement pagination limit 50 in vendor module

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/assets/locale/en.json
=> IImplement mask issue resolved

apps/web-giddh/src/app/ledger/ledger.component.ts
=> fix: Build fail issue

apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
=> fix: JV date picker issue

apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
=> fix: Object object visible in drop down

apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 266 16 june

apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 266 16 june dev

apps/web-giddh/src/app/shared/header/header.component.ts
=> Datepicker issue resolved for today dev env

apps/web-giddh/src/app/shared/header/header.component.ts
=> Datepicker issue resolved for today

apps/web-giddh/src/app/models/api-models/Subscriptions.ts, apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html
=> fix: Change binding of total balance on subscription page

apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html, apps/web-giddh/src/assets/css/style-2.scss
=> sadique | group & accounts design on firefox

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Demo issues resolved

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/shared/header/header.component.scss
=> sadique | logo drop down issue

apps/web-giddh/src/app/shared/header/header.component.ts
=> Datepicker issue resolved for today prod env

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Default sh-select issue fixed

apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
=> fix: Update the API call for activation key

apps/web-giddh/src/app/invoice/proforma/proforma-list.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fixing issues

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
fixed due date message and loader issue
=> fixed due date message and loader issue

apps/web-giddh/src/app/settings/permissions/setting.permission.component.html
=> Fixed permission issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> Fixed GIDK-399

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
=> remove downlaod icon

apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 266 18 june prod

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
fixed round off issue in edit for proforma/estimate
=> fixed round off issue in edit for proforma/estimate

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
Remove mandatory tax in case of advance receipt
=> Remove mandatory tax in case of advance receipt

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Payment bank add congratulations message added

apps/web-giddh/src/app/settings/integration/setting.integration.component.html
=> sadique | remove br

apps/web-giddh/src/app/login/token-verify.component.ts, package.json
Fixed internet issue for login
=> Fixed internet issue for login

apps/web-giddh/src/app/login/token-verify.component.ts, package.json
=> Internet connection issue

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts, apps/web-giddh/src/app/services/settings.permission.service.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Duplicate amount form validation implemented

apps/web-giddh/src/app/login/token-verify.component.ts
=> fix: Observable subscription

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | GIDK-457-dev | GIDK-457 | Prod - Amount of last Sales Invoice created is displayed in Amount field in deposit section
=> Ravinder | GIDK-457-dev | GIDK-457 | Prod - Amount of last Sales Invoice created is displayed in Amount field in deposit section

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | GIDK-457-stage | GIDK-457 | Prod - Amount of last Sales Invoice created is displayed in Amount field in deposit section
=> Ravinder | GIDK-457-stage | GIDK-457 | Prod - Amount of last Sales Invoice created is displayed in Amount field in deposit section

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
=> Invoice Template document title added for tax as well

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
=> sadique | logo dropdown issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | GIDK-457-prod | GIDK-457 | Prod - Amount of last Sales Invoice created is displayed in Amount field in deposit section
=> Ravinder | GIDK-457-prod | GIDK-457 | Prod - Amount of last Sales Invoice created is displayed in Amount field in deposit section

apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/assets/css/style-2.scss
Ravinder | Development | Gidk 44 | Prod- Settings >switch company scroll is working with background
=> Ravinder | Development | Gidk 44 | Prod- Settings >switch company scroll is working with background

apps/web-giddh/src/app/inventory/components/custom-stock-components/inventory.customstock.component.ts
=> fix:  Increase the unit accuracy from 4 digits to 16 digits

apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/assets/css/style-2.scss
Ravinder | Staging | Gidk 44 | Prod- Settings >switch company scroll is working with background
=> Ravinder | Staging | Gidk 44 | Prod- Settings >switch company scroll is working with background

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
Ravinder | Development | GIDK-152 | Prod - Wrong message is displayed for Magic link expiry case after two days
=> Ravinder | Development | GIDK-152 | Prod - Wrong message is displayed for Magic link expiry case after two days

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
Ravinder | Staging | GIDK-152 | Prod - Wrong message is displayed for Magic link expiry case after two days
=> Ravinder | Staging | GIDK-152 | Prod - Wrong message is displayed for Magic link expiry case after two days

apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.scss
=> sadique | Sales Register drop down button whote

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/services/apiurls/settings.integration.api.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/app/settings/permissions/form/form.component.html, apps/web-giddh/src/app/settings/permissions/form/form.component.ts, apps/web-giddh/src/app/settings/permissions/setting.permission.component.html, apps/web-giddh/src/assets/locale/settings/integration/en.json
=> Gids 081: Demo issues resolved for payment permission

apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
Ravinder | Development | GIDK-478 | Prod - Unable to edit existing Razor Pay details added in Settings > Integration >> Collection
=> Ravinder | Development | GIDK-478 | Prod - Unable to edit existing Razor Pay details added in Settings > Integration >> Collection

apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
Ravinder | Staging | GIDK-478 | Prod - Unable to edit existing Razor Pay details added in Settings > Integration >> Collection
=> Ravinder | Staging | GIDK-478 | Prod - Unable to edit existing Razor Pay details added in Settings > Integration >> Collection

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/assets/locale/contact/payment-aside/hi.json
=> E-waybill Register person added GSTIN

apps/web-giddh/src/app/inventory/components/custom-stock-components/inventory.customstock.component.ts
=> fix: Increase the unit accuracy from 4 digits to 16 digits

apps/web-giddh/src/app/inventory/components/custom-stock-components/inventory.customstock.component.ts
=> Bugfix/GIDK-127 |  Increase the unit accuracy from 4 digits to 16 digits

apps/web-giddh/src/app/app.component.ts
=> fix: GIDK-459 | Prateek | Development | Giddh stops anytime while working, either on the application or on the browser

apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list-menu.component.scss, apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html, apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.scss, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.html, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.scss, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.html, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.scss, apps/web-giddh/src/assets/css/color.scss, apps/web-giddh/src/assets/css/style-2.scss
=> sadique | sh-select design

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
=> Fix | Gidk 123: Daybook page loader issue

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/services/apiurls/settings.integration.api.ts, apps/web-giddh/src/app/services/companyService.service.ts, apps/web-giddh/src/app/services/contact.service.ts, apps/web-giddh/src/app/services/settings.integraion.service.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Payment permission demo bugs and  PR changes

apps/web-giddh/src/app/shared/header/components/group-add/group-add.component.ts, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
=> feat: GIDK-438 | Prateek | Dev | UI task to fix 404 -GROUP_NOT_FOUND issue

apps/web-giddh/src/app/shared/header/components/group-add/group-add.component.ts, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
=> feat: GIDK-438 | Prateek | Staging | UI task to fix 404 -GROUP_NOT_FOUND issue

apps/web-giddh/src/app/shared/header/components/group-add/group-add.component.ts, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
=> feat: GIDK-438 | Prateek | Prod | UI task to fix 404 -GROUP_NOT_FOUND issue

apps/web-giddh/src/app/app.component.ts
=> fix: GIDK-459 | Prateek | Staging | Giddh stops anytime while working, either on the application or on the browser

apps/web-giddh/src/app/app.component.ts
=> fix: GIDK-459 | Prateek | Production | Giddh stops anytime while working, either on the application or on the browser

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Development | GIDK-466 | Remove tax amount filed in case of edit invoice in export invoice feature
=> Ravinder | Development | GIDK-466 | Remove tax amount filed in case of edit invoice in export invoice feature

apps/web-giddh/src/app/app.component.ts
=> Resolve conflicts

apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/shared/helpers/defaultDateFormat.ts
=> fix: GIDK-477 | Prateek | Dev | Invalid date issue in Firefox

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
Ravinder | Development | GIDK-495 | Prod - Giddh hangs on navigating to Subscription page
=> Ravinder | Development | GIDK-495 | Prod - Giddh hangs on navigating to Subscription page

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
Ravinder | Staging | GIDK-495 | Prod - Giddh hangs on navigating to Subscription page
=> Ravinder | Staging | GIDK-495 | Prod - Giddh hangs on navigating to Subscription page

apps/web-giddh/src/app/settings/permissions/form/form.component.ts
=> fix: GIDK-248 | Prateek | Dev | In permissions module date range is getting added automatically on just hitting update button in Edit mode

apps/web-giddh/src/app/settings/permissions/form/form.component.ts
=> fix: GIDK-248 | Prateek | Stage | In permissions module date range is getting added automatically on just hitting update button in Edit mode

apps/web-giddh/src/app/settings/permissions/form/form.component.ts
=> fix: GIDK-248 | Prateek | Prod | In permissions module date range is getting added automatically on just hitting update button in Edit mode

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
Ravinder | Production | GIDK-495 | Prod - Giddh hangs on navigating to Subscription page
=> Ravinder | Production | GIDK-495 | Prod - Giddh hangs on navigating to Subscription page

apps/web-giddh/src/app/onboarding/onboarding.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
=> fix: GIDK-534 | Prateek | Dev | Remove Superform js which is unused and takes too much time to load

apps/web-giddh/src/app/onboarding/onboarding.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
=> fix: GIDK-534 | Prateek | Stage | Remove Superform js which is unused and takes too much time to load

apps/web-giddh/src/app/onboarding/onboarding.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
=> fix: GIDK-534 | Prateek | Prod | Remove Superform js which is unused and takes too much time to load

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Staging | GIDK-466 | Remove tax amount filed in case of edit invoice in export invoice feature
=> Ravinder | Staging | GIDK-466 | Remove tax amount filed in case of edit invoice in export invoice feature

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
=> z-index increase

apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/shared/helpers/defaultDateFormat.ts
=> fix: GIDK-477 | Prateek | Stage | Invalid date issue in Firefox

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html, apps/web-giddh/src/assets/css/style-2.scss
=> sadique | inventory table content overlaping issue

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | Prod - Scrolling stops randomly on any page in Giddh
=> Ravinder | Development | Prod - Scrolling stops randomly on any page in Giddh

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Staging | Prod - Scrolling stops randomly on any page in Giddh
=> Ravinder | Staging | Prod - Scrolling stops randomly on any page in Giddh

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts, apps/web-giddh/src/app/services/apiurls/inventory.api.ts
=> fix: GIDK-558 | Prateek | Dev | Email for Inventory stock download is not received for both CSV and Excel files

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts, apps/web-giddh/src/app/services/apiurls/inventory.api.ts
=> fix: GIDK-558 | Prateek | Stage | Email for Inventory stock download is not received for both CSV and Excel files

apps/web-giddh/src/app/gst/gst.component.scss, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.scss, apps/web-giddh/src/app/vat-report/vatReport.component.scss, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/src/assets/css/style-magic.css
=> Gidk 525 ledger dev

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
=> incerease zindex

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts, apps/web-giddh/src/app/services/apiurls/inventory.api.ts
=> fix: GIDK-558 | Prateek | Prod | Email for Inventory stock download is not received for both CSV and Excel files

apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/shared/helpers/defaultDateFormat.ts
=> fix: GIDK-477 | Prateek | Prod | Invalid date issue in Firefox

apps/web-giddh/src/app/shared/header/header.component.ts
=> fix: GIDK-534 | Prateek | Dev | VAT Report page API is pending around for 60 seconds but after 60 sec API call from UI and got data in less than a sec

apps/web-giddh/src/app/gst/gst.component.ts, apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts, apps/web-giddh/src/app/settings/profile/setting.profile.component.html, apps/web-giddh/src/app/settings/profile/setting.profile.component.ts, apps/web-giddh/src/app/store/Settings/Settings.reducer.ts
=> Issues resolved for company profile and GSTIN and manufacturing

apps/web-giddh/src/app/gst/gst.component.ts, apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts, apps/web-giddh/src/app/settings/profile/setting.profile.component.html, apps/web-giddh/src/app/settings/profile/setting.profile.component.ts, apps/web-giddh/src/app/store/Settings/Settings.reducer.ts
=> Gidk 461 dev: company profile loader implemented and manufacturing stock quantity issues fixed 

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Production | Prod - Scrolling stops randomly on any page in Giddh
=> Ravinder | Production | Prod - Scrolling stops randomly on any page in Giddh

apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.ts, apps/web-giddh/src/app/inventory/components/sidebar-components/stockList.component.ts, apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
=> Inventory sorting is implemented using API and removed from UI

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Development | Datepicker scrolls Slow
=> Ravinder | Development | Datepicker scrolls Slow

apps/web-giddh/src/app/actions/session.action.ts, apps/web-giddh/src/app/services/authentication.service.ts, apps/web-giddh/src/app/store/General/session.reducer.ts, apps/web-giddh/src/app/userDetails/userDetails.component.html, apps/web-giddh/src/app/userDetails/userDetails.component.ts
=> fix: GIDK-571 | Prateek | Dev | Deleted session record is removed only after page is refreshed

apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
=> fix: GIDK-93 | Prateek | Dev | Groups not getting refreshed when new groups are added

apps/web-giddh/src/app/login/login.component.html, apps/web-giddh/src/app/login/login.component.scss, apps/web-giddh/src/app/signup/signup.component.html, apps/web-giddh/src/app/signup/signup.component.scss
=> sadique | login signup page design

apps/web-giddh/src/index.prod.html
=> fix: Make async call to Calendly widget

apps/web-giddh/src/app/actions/session.action.ts, apps/web-giddh/src/app/services/authentication.service.ts, apps/web-giddh/src/app/store/General/session.reducer.ts, apps/web-giddh/src/app/userDetails/userDetails.component.html, apps/web-giddh/src/app/userDetails/userDetails.component.ts
=> fix: GIDK-571 | Prateek | Stage | Deleted session record is removed only after page is refreshed

apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
=> fix: GIDK-93 | Prateek | Stage | Groups not getting refreshed when new groups are added

apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Avoid multiple API calls, defer eagerly API calls

apps/web-giddh/src/app/actions/session.action.ts, apps/web-giddh/src/app/services/authentication.service.ts, apps/web-giddh/src/app/store/General/session.reducer.ts, apps/web-giddh/src/app/userDetails/userDetails.component.html, apps/web-giddh/src/app/userDetails/userDetails.component.ts
=> fix: GIDK-571 | Prateek | Prod | Deleted session record is removed only after page is refreshed

apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
=> fix: GIDK-93 | Prateek | Prod | Groups not getting refreshed when new groups are added

apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
Ravinder | Development | GIDK-526 | Uniquename showing in sh-select instead of label
=> Ravinder | Development | GIDK-526 | Uniquename showing in sh-select instead of label

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts
Ravinder | Development | GIDK-627 | Prod - Unable to navigate to from first page to any other page in Vendor module, loader keeps loading
=> Ravinder | Development | GIDK-627 | Prod - Unable to navigate to from first page to any other page in Vendor module, loader keeps loading

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts
Ravinder | Staging | GIDK-627 | Prod - Unable to navigate to from first page to any other page in Vendor module, loader keeps loading
=> Ravinder | Staging | GIDK-627 | Prod - Unable to navigate to from first page to any other page in Vendor module, loader keeps loading

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts
Ravinder | Production | GIDK-627 | Prod - Unable to navigate to from first page to any other page in Vendor module, loader keeps loading
=> Ravinder | Production | GIDK-627 | Prod - Unable to navigate to from first page to any other page in Vendor module, loader keeps loading

apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
Ravinder | Staging | GIDK-526 | Uniquename showing in sh-select instead of label
=> Ravinder | Staging | GIDK-526 | Uniquename showing in sh-select instead of label

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, libs/utils/platform.ts
=> fix: GIDK-268 | Prateek | Test | ReferenceError: device is not defined

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
Ravinder | Development | GIDK-636 | UI - In template A & E - Add GST composition scheme text box template preview
=> Ravinder | Development | GIDK-636 | UI - In template A & E - Add GST composition scheme text box template preview

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-555 | Prateek | Prod | Page keeps loading when Purchase Record is marked applicable for RCM on update Purchase Record page

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
Ravinder | Development | GIDK--636 | UI - In template A - Add GST composition scheme text box template preview
=> Ravinder | Development | GIDK--636 | UI - In template A - Add GST composition scheme text box template preview

apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.scss, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-magic.css
=> revert ledger design commit

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
Ravinder | Development | GIDK-636 | Fixed GSTIN Field for Template A and E
=> Ravinder | Development | GIDK-636 | Fixed GSTIN Field for Template A and E

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
Ravinder | Staging | GIDK-636 | UI - In template A & E- Add GST composition scheme text box template preview
=> Ravinder | Staging | GIDK-636 | UI - In template A & E- Add GST composition scheme text box template preview

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
Ravinder | Production | GIDK-636 | UI - In template A & E- Add GST composition scheme text box template preview
=> Ravinder | Production | GIDK-636 | UI - In template A & E- Add GST composition scheme text box template preview

apps/web-giddh/src/app/audit-logs/audit-logs.module.ts, apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts, apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.module.ts, apps/web-giddh/src/app/gst/filing/tabs/overview/summary/summary.component.html, apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html, apps/web-giddh/src/app/gst/gst.routing.module.ts, apps/web-giddh/src/app/gst/gstR3/gstR3.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/theme/discount-control/discount-control-component.html, apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts, apps/web-giddh/src/app/theme/discount-control/discount-control.module.ts
=> Currency pipe for decimal point number applied

apps/web-giddh/src/app/contact/contact.component.scss
=> vendor-list-ui-done

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.scss
=> datepicker issue fixed and invoice dropdown issue fixed

apps/web-giddh/src/app/shared/header/header.component.scss
=> width increase

apps/web-giddh/src/app/contact/contact.component.scss, package-lock.json
=> Gidk 659 vendor ui

apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/assets/css/style-2.scss
Ravinder | Production | GIDK-723 | Prod - Menu is not getting displayed in Giddh
=> Ravinder | Production | GIDK-723 | Prod - Menu is not getting displayed in Giddh

apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/assets/css/style-2.scss
Ravinder | Staging | GIDK-723 | Prod - Menu is not getting displayed in Giddh
=> Ravinder | Staging | GIDK-723 | Prod - Menu is not getting displayed in Giddh

apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/assets/css/style-2.scss
Ravinder | Development | GIDK-723 | Prod - Menu is not getting displayed in Giddh
=> Ravinder | Development | GIDK-723 | Prod - Menu is not getting displayed in Giddh

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts, apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html, apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.module.ts, apps/web-giddh/src/app/search/components/search-grid/search-grid.component.html, apps/web-giddh/src/app/search/search.module.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/store/Invoice/invoice.reducer.ts, apps/web-giddh/src/assets/locale/settings/integration/en.json
=> Gidk 446 dev: Payment permission label changes and pending invoice loader clear filter issue solved

apps/web-giddh/src/app/search/components/search-grid/search-grid.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/assets/locale/settings/integration/en.json
=> Label changed Approval to Approver

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.vm.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> feat: GIDK-279 | Prateek | Test | Increase the precision of rate to 16 digits for calculation

apps/web-giddh/src/app/gst/gstR3/gstR3.component.ts
=> moment date formate issue for download gstr 3 data fixed

apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
Ravinder | Production | GIDK-526 | Uniquename showing in sh-select instead of label
=> Ravinder | Production | GIDK-526 | Uniquename showing in sh-select instead of label

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
=> shalinee | prod | GIDK-629|  UI fixes of datepicker

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-555 | Prateek | Stage | Page keeps loading when Purchase Record is marked applicable for RCM on update Purchase Record page

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, libs/utils/platform.ts
=> fix: GIDK-268 | Prateek | Stage | ReferenceError: device is not defined

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, libs/utils/platform.ts
=> fix: GIDK-268 | Prateek | Prod | ReferenceError: device is not defined

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html
=> OTP type "number" changed to "text"

apps/web-giddh/src/app/tb-pl-bs/components/export/data-formatter.class.ts
Ravinder | Development | GIDK-429 | Grand total issue in export pdf/csv in trial balance
=> Ravinder | Development | GIDK-429 | Grand total issue in export pdf/csv in trial balance

angular.json, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/models/api-models/Ledger.ts, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts, apps/web-giddh/webpack.partial.js
=> Squashing commits

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html
=> OTP type number changed to text

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
Ravinder | Development | GIDK-674 | Hide GST Composition field for UAE Company
=> Ravinder | Development | GIDK-674 | Hide GST Composition field for UAE Company

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.vm.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> feat: GIDK-279 | Prateek | Stage | Increase the precision of rate to 16 digits for calculation

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.vm.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> feat: GIDK-279 | Prateek | Prod | Increase the precision of rate to 16 digits for calculation

apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.scss
=> shalinee | staging | GIDK-545-ldeger | transction design issue fixed

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
Ravinder | Staging | GIDK-674 | Hide GST Composition field for UAE Company
=> Ravinder | Staging | GIDK-674 | Hide GST Composition field for UAE Company

apps/web-giddh/src/app/actions/inventory/customStockUnit.actions.ts, apps/web-giddh/src/app/models/api-models/Inventory.ts, apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
Updated Unit value is not displayed on Create Unit window unless we move Back and navigate again to the Window
=> commit bug  Updated Unit value is not displayed on Create Unit window unless we move Back and navigate again to the Window

apps/web-giddh/src/app/gst/gst.component.scss, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.scss, apps/web-giddh/src/assets/css/style-1.scss
=> Gidk 545 cherry pick ledger dev

apps/web-giddh/src/app/tb-pl-bs/components/export/data-formatter.class.ts
Ravinder | Development | GIDK-429 | Fixed total issue
=> Ravinder | Development | GIDK-429 | Fixed total issue

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/assets/css/style-1.scss
=> shalinee | dev | GIDK-525 | cherry-pick transaction map design

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.scss
=> shalinee | dev | GIDK-395 | margin reduce

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/assets/css/style-1.scss
=> shalinee | staging | GIDK-545 | Transaction map design issue fixed

apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss
=> Gidk 395 dev

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
Ravinder | Production | GIDK-674 | Hide GST Composition field for UAE Company
=> Ravinder | Production | GIDK-674 | Hide GST Composition field for UAE Company

apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
=> GIDK-101 | Yogesh | (Word "Invoice" is used instead of "Estimate" in "Enable Send invoice via SMS" in Estimate settings module)

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> Gidk 99 | yogesh | (Word "Invoice" is used instead of Credit Note in Credit Note/Debit Note modules )

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
GIDK-(497) fix add loader on uploading file and disable submit button
add loader with Font awesome spinner icon while uploading file and disable save and update button in purchase invoice 
=> GIDK-497 | yogesh | (Prod - Attachment attached in Purchase Record is not displayed on Purchase Management.)

apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
fire api on update successfull, so componnet can get updated data. 
=> GIDK-369 | yogesh | (Prod - Name of the stock is not getting updated on Stock table unless page is refreshed)

apps/web-giddh/src/app/audit-logs/components/audit-logs-form/Vm.ts, apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.html
=> Build issue fixed

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
=> shalinee | stage | GIDK-525 | ngClass formate correct

apps/web-giddh/src/app/contact/contact.component.scss
=> aditi | prod | GIDK-659 | vendor table ui

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
=> shalinee | prod | GIDK-395 | ngclass issue formate correct

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
=> fix: Build issue

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/models/api-models/recipt.ts
=> feat: GIDK-439 | Test | Prateek | Add linked invoice column in CN

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.module.ts
Ravinder | Development | GIDK-739 | Datepicker Scroll issue
=> Ravinder | Development | GIDK-739 | Datepicker Scroll issue

apps/web-giddh/src/app/tb-pl-bs/components/export/data-formatter.class.ts
Ravinder | Development | GIDK-429 | Fixed Number formatting
=> Ravinder | Development | GIDK-429 | Fixed Number formatting

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html
Ravinder | Development | GIDK-739 | Updated mouse event
=> Ravinder | Development | GIDK-739 | Updated mouse event

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Development | GIDK-739 | Datepicker financial year issue
=> Ravinder | Development | GIDK-739 | Datepicker financial year issue

apps/web-giddh/src/app/tb-pl-bs/components/export/data-formatter.class.ts
Ravinder | Staging | GIDK-429 | Grand total issue in export pdf/csv in trial balance
=> Ravinder | Staging | GIDK-429 | Grand total issue in export pdf/csv in trial balance

apps/web-giddh/src/app/tb-pl-bs/components/export/data-formatter.class.ts
Ravinder | Production | GIDK-429 | Grand total issue in export pdf/csv in trial balance
=> Ravinder | Production | GIDK-429 | Grand total issue in export pdf/csv in trial balance

apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Gidk 716 dev: Rohit | dev-Custom sorting implemented for approver name in bank integration

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Development | GIDK-739 | Fixed Scrolling Speed
=> Ravinder | Development | GIDK-739 | Fixed Scrolling Speed

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
=> GIDK-446-staging | Rohit | Invoice document title issue fixed

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
text change in table placeholder
=> GIDK-104 | yogesh | (Test- On the delivery chalan and receipt note hsn/sac no is displayed instead of line item)

apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
=> aditi | test | GIDK-778 | sales and purchase ui

apps/web-giddh/src/app/audit-logs/audit-logs.component.html, apps/web-giddh/src/app/audit-logs/audit-logs.component.scss, apps/web-giddh/src/app/audit-logs/audit-logs.component.ts, apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.html, apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.ts, apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts, apps/web-giddh/src/app/models/defaultMenus.ts
=> Gidk 783 dev: Rohit | New Audit log for stock V2.1

apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.html
=> Audit log dor account and stock Old and new edit/update operation design done

apps/web-giddh/src/app/shared/header/header.component.scss
=> Gidk 739 datepicker dev

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
=> fix: exception in [ngClass]

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
=> aditi | test | GIDK-778 | remove dropdown from header

apps/web-giddh/src/app/actions/inventory/customStockUnit.actions.ts, apps/web-giddh/src/app/models/api-models/Inventory.ts, apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
=> Gidk 479| yogesh |Prod - Updated Unit value is not displayed on Create Unit window unless we move Back and navigate again to the Window

apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
=> GIDK-101| yogesh | Word "Invoice" is used instead of "Estimate" in "Enable Send invoice via SMS" in Estimate settings module 

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
=> GIDK-446-prd | Rohit | Invoice document title issue fixed

apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Gidk 716 prod:  Rohit | prod-Custom sorting implemented for approver name in bank integration

apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> GIDK-716: Rohit | stage-Custom sorting implemented for approver name in bank integration

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> GIDK-99 | yogesh | stage |Word "Invoice" is used instead of Credit Note in Credit Note/Debit Note modules 

apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
=> GIDK-101| yogesh | Word "Invoice" is used instead of "Estimate" in "Enable Send invoice via SMS" in Estimate settings module

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> GIDK-99 | yogesh | production |Word "Invoice" is used instead of Credit Note in Credit Note/Debit Note modules 

apps/web-giddh/src/app/actions/inventory/customStockUnit.actions.ts, apps/web-giddh/src/app/models/api-models/Inventory.ts, apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
=> Gidk 479 prod | yogesh | Prod - Updated Unit value is not displayed on Create Unit window unless we move Back and navigate again to the Window

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js, apps/web-giddh/src/meta/magic.html
=> Gidk 653 dev| Rohit | Magic link ledger entry for attached file instead of generate invoice file download implemented

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js, apps/web-giddh/src/meta/magic.html
=> Gidk 653| development| Rohit | Magic link ledger entry for attached file instead of generate invoice file download implemented

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
=> font-size of dropdown

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
add loader in ledger attach file
=> GIDK-497 | Yogesh | Development | Add loader while attachment is uploading on purchase management and ledger

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
=> Gidk-104 | Yogesh | Production | Test- On the delivery chalan and receipt note hsn/sac no is displayed instead of line item

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.module.ts, apps/web-giddh/src/app/ledger/ledger.vm.ts, apps/web-giddh/src/app/models/api-models/AdvanceReceiptsAdjust.ts, apps/web-giddh/src/app/models/api-models/Ledger.ts, apps/web-giddh/src/app/models/api-models/Sales.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/apiurls/sales.api.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.scss, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts, apps/web-giddh/src/app/theme/ng-virtual-select/sh-options.interface.ts, apps/web-giddh/src/assets/css/style-2.scss
https://giddha.atlassian.net/browse/GIDK-751
https://giddha.atlassian.net/browse/GIDK-752
=> feat: GIDK 751 | Prateek | Test | Advance receipt and receipt adjustment from ledger and voucher module

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
disable dropdown & button while hasNoVoucher entry
=> GIDK-757 | yogesh | (disable save and update button on create invoice until user input the valid(amount and account uniqename) voucher entry)

apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.html
=> Gidk 784 dev| Rohit | Voucher audit log implemented

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Development | GIDK-817 | Prod - There is a lag while selecting date and even while scrolling in new date picker
=> Ravinder | Development | GIDK-817 | Prod - There is a lag while selecting date and even while scrolling in new date picker

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Staging | GIDK-817 | Prod - There is a lag while selecting date and even while scrolling in new date picker
=> Ravinder | Staging | GIDK-817 | Prod - There is a lag while selecting date and even while scrolling in new date picker

apps/web-giddh/src/app/version-check.service.ts
Ravinder | Staging | GIDK-878 | Loading issue after Login
=> Ravinder | Staging | GIDK-878 | Loading issue after Login

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/version-check.service.ts
Ravinder | Development | GIDK-878 | Loading issue after Login
=> Ravinder | Development | GIDK-878 | Loading issue after Login

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-890 | Prateek | Stage | Warehouse not getting loaded for new company

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | GIDK-896 | Changed min width to show/hide sidebar to 1020px
=> Ravinder | Development | GIDK-896 | Changed min width to show/hide sidebar to 1020px

apps/web-giddh/src/app/inventory/inventory.component.html
add placeholder in inventory.component.html
=> GIDK-103 | Yogesh | Development | Test- On the inventory page Placeholder should be displays for the HQ and Warehouse

apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.html, apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/settings/financial-year/financial-year.component.ts
=> Gidk 750 dev| Rohit | Dashboard Cr-Dr date picker issue and setting FY select issue fixed

apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.html, apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.ts, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/settings/financial-year/financial-year.component.ts
=> Gidk 750 stage| Rohit | Dashboard Cr-Dr date picker issue and setting FY select issue fixed 

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Staging | GIDK-896 | Changed min width to show/hide sidebar to 1020px
=> Ravinder | Staging | GIDK-896 | Changed min width to show/hide sidebar to 1020px

apps/web-giddh/src/app/app.component.ts
Moved version code to execute after view init
=> Ravinder | Staging | GIDK-878 | Moved version code to execute after view init

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | GIDK-897/817/878 | Fixed 3 issues
=> Ravinder | GIDK-897/817/878 | Fixed 3 issues

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-890 | Prateek | Test | Warehouse not getting loaded for new company

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-890 | Prateek | Prod | Warehouse not getting loaded for new company

apps/web-giddh/src/app/ledger/ledger.component.html
=> GIDK-880-prod | Rohit | Bank e-ledger design issue fixed

apps/web-giddh/src/app/ledger/ledger.component.html
=> GIDK-880-staging | Rohit | Bank e-ledger design issue fixed

apps/web-giddh/src/app/ledger/ledger.component.html
=> GIDK-880| Rohit| Bank e-ledger issue fixed

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
update entry loader while attach file
=> Gidk-497 | yogesh | development | (Add loader while attachment is uploading on purchase management and purchase ledger)

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Development | GIDK-795 | Prod - NAN is getting displayed for Amount field in Sales Invoice
=> Ravinder | Development | GIDK-795 | Prod - NAN is getting displayed for Amount field in Sales Invoice

apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.html, apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.ts, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/settings/financial-year/financial-year.component.ts
=> Gidk 750 prod| Rohit | Dashboard Cr-Dr date picker issue and setting FY select issue fixed

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Staging | GIDK-907 | Fixed financial years issue
=> Ravinder | Development | GIDK-907 | Fixed financial years issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Staging | GIDK-795 | Prod - NAN is getting displayed for Amount field in Sales Invoice
=> Ravinder | Staging | GIDK-795 | Prod - NAN is getting displayed for Amount field in Sales Invoice

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html
Ravinder | Development | GIDK--907 | Fixed date fields change event
=> Ravinder | Development | GIDK--907 | Fixed date fields change event

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/models/api-models/AdvanceReceiptsAdjust.ts, apps/web-giddh/src/app/services/apiurls/sales.api.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.scss, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> feat: GIDK-751 | Prateek | Test | Voucher adjustments

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
=> aditi | test | GIDK-778 | deposit box content align right

apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.html
=> GIDK-785-dev | Rohit | Entries log block is implemented

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Production | GIDK-907 | Fixed financial years issue
=> Ravinder | Production | GIDK-907 | Fixed financial years issue

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Staging | GIDK-907 | Fixed financial years issue
=> Ravinder | Staging | GIDK-907 | Fixed financial years issue

apps/web-giddh/src/app/onboarding/onboarding.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | GIDK-878 | working on loading issue
=> Ravinder | Development | GIDK-878 | working on loading issue

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> feat: GIDK-751 | Prateek | Test | Adding DN and CN adjustment

apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.html, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss
=> shalinee | stage | GIDK-41 | alignmenet fixes of subscription buy plan

apps/web-giddh/src/assets/css/ngx-bootstrap/bs-datepicker.css
=> shalinee | stage | GIDK-909 | datepicker button alignment

apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss
=> shalinee | test | GIDK-41 | alignment of all feature - subscription

apps/web-giddh/src/app/welcome/welcome.component.ts
Ravinder | Development | GIDK-895 | Prod -Sign up process is not smooth i.e. Signup is not completed successfully in one attempt
=> Ravinder | Development | GIDK-895 | Prod -Sign up process is not smooth i.e. Signup is not completed successfully in one attempt

apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.html, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss
=> Gidk 41 subscription staging

apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.html, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss
=> Gidk 41 prod

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-439 | Prateek | Test | Invoice list not prepared in UPDATE flow of CN linking

apps/web-giddh/src/app/welcome/welcome.component.ts
Ravinder | Staging | GIDK-895 | Prod -Sign up process is not smooth i.e. Signup is not completed successfully in one attempt
=> Ravinder | Staging | GIDK-895 | Prod -Sign up process is not smooth i.e. Signup is not completed successfully in one attempt

apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
Ravinder | Development | GIDK-925 | Test/Stage - Sign up info is being received in CRM for test and stage env
=> Ravinder | Development | GIDK-925 | Test/Stage - Sign up info is being received in CRM for test and stage env

apps/web-giddh/src/app/shared/header/header.component.html
=> HOTFIX | Prod Rohit |Prod Menu navigation issue fixed

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Update Purchase record issue

apps/web-giddh/src/app/contact/aging-report/aging-report.component.html, apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss, apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html, apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.scss, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss, apps/web-giddh/src/app/inventory/components/welcome-inventory/welcome-inventory.component.html, apps/web-giddh/src/app/inventory/components/welcome-inventory/welcome-inventory.component.ts, apps/web-giddh/src/app/inventory/components/welcome-inventory/welcome-inventory.scss, apps/web-giddh/src/assets/css/color.scss, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/src/assets/css/table.scss
=> aditi | test | GIDK-873 | inventory mobile responsiveness

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> aditi | test | GIDK-778 | dropdown padding and alignment

apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.html, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts, apps/web-giddh/src/app/inventory/inventory.component.html, apps/web-giddh/src/app/inventory/inventory.component.scss, apps/web-giddh/src/app/inventory/inventory.component.ts, apps/web-giddh/src/app/models/defaultMenus.ts
=> GIDK-454-dev | Rohit | Inventory new design issues implemented

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js, apps/web-giddh/src/meta/magic.html
=> Gidk 653 prod| Rohit | Magic link ledger entry for attached file instead of generate invoice file download implemented

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
=> Yogesh | production | GIDK-497 | Add loader while attachment is uploading on purchase management and purchase ledger

apps/web-giddh/src/app/inventory/inventory.component.html
add placeholder in inventory.component.html
=> Yogesh | production | GIDK-103 | Test- On the inventory page Placeholder should be displays for the HQ and Warehouse

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/ledger/ledger.module.ts, apps/web-giddh/src/app/ledger/ledger.vm.ts, apps/web-giddh/src/app/models/api-models/AdvanceReceiptsAdjust.ts, apps/web-giddh/src/app/models/api-models/Ledger.ts, apps/web-giddh/src/app/models/api-models/Sales.ts, apps/web-giddh/src/app/models/api-models/recipt.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/apiurls/sales.api.ts, apps/web-giddh/src/app/services/ledger.service.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.scss, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts, apps/web-giddh/src/app/theme/ng-virtual-select/sh-options.interface.ts, apps/web-giddh/src/assets/css/style-2.scss
=> Voucher link prod

apps/web-giddh/src/index.stage.html
Ravinder | Staging | GIDK-878 | Added GTM for staging
=> Ravinder | Staging | GIDK-878 | Added GTM for staging

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
=> shalinee | stage | GIDK-963 | datepicker scroll desgin update

apps/web-giddh/src/app/onboarding/onboarding.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
Revert "Ravinder | Development | GIDK-878 | working on loading issue"
=> Revert "Ravinder | Development | GIDK-878 | working on loading issue"

apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html, apps/web-giddh/src/assets/css/style-2.scss
=> aditi | stage | GIDK-778 | sales and purchase ui

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | GIDK-878 | Added consoles for debugging
=> Ravinder | Development | GIDK-878 | Added consoles for debugging

apps/web-giddh/src/index.html, apps/web-giddh/src/index.test.html
=> Updated GTM code

apps/web-giddh/src/app/home/components/profit-loss/profit-loss.component.html, apps/web-giddh/src/app/home/components/total-overdues/total-overdues-chart.component.html, apps/web-giddh/src/app/home/home.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
=> Gidk 963 prod

apps/web-giddh/src/app/theme/command-k/command.k.component.html
=> shalinee | prod | GIDK-595 | command K icon update

apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 778 prod

apps/web-giddh/src/app/inventory/inventory.component.html
add placeholder in inventory.component.html
=> Yogesh | staging | GIDK-103 | Test- On the inventory page Placeholder should be displays for the HQ and Warehouse

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
=> fix: Prateek | Test | Advance receipt not visible in adjustment modal

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
=> fix: Prateek | Stage | Advance receipt not visible in adjustment modal

apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
Ravinder | Staging | GIDK-925 | Test/Stage - Sign up info is being received in CRM for test and stage env
=> Ravinder | Staging | GIDK-925 | Test/Stage - Sign up info is being received in CRM for test and stage env

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
=> fix: Prateek | Prod | Advance receipt not visible in adjustment modal

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> Yogesh | Gidk-757 | Gidk-757 | on update and copy previous invoice bug fix  

apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.scss, apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.ts
=> Yogesh | staging | GIDK-115 | Prod - Search with uniquename in Audit log "Group" and "Account" columns is not working

apps/web-giddh/src/app/login/login.component.html, apps/web-giddh/src/app/login/login.component.scss, apps/web-giddh/src/app/login/login.component.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/app/signup/signup.component.html, apps/web-giddh/src/app/signup/signup.component.ts, apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
=> Gidk 637 dev | Rohit | Loader is implemented for login signup

apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
=> Yogesh | development | GIDK-369 | issue after update stock fixed 

apps/web-giddh/src/app/userDetails/userDetails.module.ts
Ravinder | Development | GIDK-661 | Readded component in module to fix build issue
=> Ravinder | Development | GIDK-661 | Readded component in module to fix build issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Prateek | Test | Loader not getting stopped when RCM tax is not provided

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Prateek | Stage | Loader not getting stopped when RCM tax is not provided

apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
…for check unique name availability
=> Yogesh | development | GIDK-757 | remove api call for uniquename availability as this is now handled at api end.

apps/web-giddh/src/assets/css/ngx-bootstrap/bs-datepicker.css
=> shalinee | prod | GIDK-909 | datepicker button alignment

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Prateek | Prod | Loader not getting stopped when RCM tax is not provided

apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts, apps/web-giddh/src/app/welcome/welcome.component.ts
Ravinder | Production | GIDK-925 | Test/Stage - Sign up info is being received in CRM for test and stage env
=> Ravinder | Production | GIDK-925,GIDK-895 | Sign up info is being received in CRM for test and stage env, Signup process not smooth

apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.scss, apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.ts
=> Yogesh | production | GIDK-115 | Prod - Search with uniquename in Audit log "Group" and "Account" columns is not working

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html, apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
=> Inventory changes done

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html, apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
=> Gidk 967 stage| stage | Rohit | Inventory changes and vendor payment pay loader added

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html, apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
=> GIDK-967-prod| Rohit | Inventory changes done

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/app.module.ts, apps/web-giddh/src/app/login/login.component.html, apps/web-giddh/src/app/login/login.module.ts, apps/web-giddh/src/app/shared/shared.module.ts, apps/web-giddh/src/app/theme/ng-social-login-module/auth.service.ts
=> feat: GIDK-647 | Prateek | Test | Add loader while route is loaded and when user is logging in

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
Ravinder | Development | GIDK-661 | Hide Loader if no subscriptions available from api
=> Ravinder | Development | GIDK-661 | Hide Loader if no subscriptions available from api

apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.html, apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.scss, apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/bs/bs.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html, apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss, apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid.component.html, apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid.component.scss, apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/pl/pl.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.html, apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.scss, apps/web-giddh/src/assets/css/style-1.scss
=> Gidk 977 dev

apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
Ravinder | Staging | GIDK-661 | Hide Loader if no subscriptions available from api
=> Ravinder | Staging | GIDK-661 | Hide Loader if no subscriptions available from api

apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list-menu.component.scss, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.scss, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.scss
=> shalinee | dev | sh-select design update

apps/web-giddh/src/app/settings/constants/settings.constant.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/app/settings/settings.component.html, apps/web-giddh/src/app/settings/settings.component.ts, apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
=> fix: GIDK-126 | Prateek | Test | Settings API should be called only when user navigates to particular section

apps/web-giddh/src/app/contact/contact.component.ts
=> fix: GIDK-835, GIDK-1009: Prateek | Test | Incorrect values in footer in customer and vendor module

apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list-menu.component.scss, apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.html, apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.scss, apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/bs/bs.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html, apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss, apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid.component.html, apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid.component.scss, apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/pl/pl.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.html, apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.scss, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.scss, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.scss, apps/web-giddh/src/assets/css/style-1.scss
=> Gidk 977 prod

apps/web-giddh/src/app/userDetails/userDetails.component.html
Ravinder | Development | GIDK-1019 | Prod - Click on other tabs is not working once we click on Auth-key field
=> Ravinder | Development | GIDK-1019 | Prod - Click on other tabs is not working once we click on Auth-key field

apps/web-giddh/src/app/userDetails/userDetails.component.html
Ravinder | Staging | GIDK-1019 | Prod - Click on other tabs is not working once we click on Auth-key field
=> Ravinder | Staging | GIDK-1019 | Prod - Click on other tabs is not working once we click on Auth-key field

apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 266 dev

apps/web-giddh/src/app/userDetails/userDetails.component.html
Ravinder | Production | GIDK-1019 | Prod - Click on other tabs is not working once we click on Auth-key field
=> Ravinder | Production | GIDK-1019 | Prod - Click on other tabs is not working once we click on Auth-key field

apps/web-giddh/src/app/contact/contact.component.ts
=> fix: Due amount calculation

apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/models/api-models/Ledger.ts, apps/web-giddh/webpack.partial.js
=> feat: GIDK-91 | Prateek | Prod | Remove dependency on flatten account API in ledger, new ledger and update ledger component

apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/assets/css/style-2.scss
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#5478
=> Revert "Gidk 266 dev"

apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 266 test

apps/web-giddh/src/assets/css/style-2.scss
=> shalinee | stage | GIDK-266 | correct sidebar for user page

apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 266 prod

apps/web-giddh/src/app/contact/contact.component.ts
=> fix: GIDK-835, GIDK-1009: Prateek | Stage | Incorrect values in footer in customer and vendor module

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/app.module.ts, apps/web-giddh/src/app/login/login.component.html, apps/web-giddh/src/app/login/login.module.ts, apps/web-giddh/src/app/shared/shared.module.ts, apps/web-giddh/src/app/theme/ng-social-login-module/auth.service.ts
=> feat: GIDK-647 | Prateek | Stage | Add loader while route is loaded and when user is logging in

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/app.module.ts, apps/web-giddh/src/app/login/login.component.html, apps/web-giddh/src/app/login/login.module.ts, apps/web-giddh/src/app/shared/shared.module.ts, apps/web-giddh/src/app/theme/ng-social-login-module/auth.service.ts
=> feat: GIDK-647 | Prateek | Prod | Add loader while route is loaded and when user is logging in

apps/web-giddh/src/app/contact/contact.component.ts
=> fix: GIDK-835, GIDK-1009: Prateek | Prod | Incorrect values in footer in customer and vendor module

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
=> feat: Prateek | Test | Remove unnecessary API calls

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.ts
=> fix: GIDK-123 | Test | Prateek | Issues of loader not hiding and API call when calendar is closed

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
=> fix: Prateek | Test | Entry loosing discount and taxes in UPDATE ledger flow, TCS/TDS issue  and multi currency issue

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
=> fix: Prateek | Stage | Entry loosing discount and taxes in UPDATE ledger flow, TCS/TDS issue  and multi currency issue

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
=> fix: Prateek | Prod | Entry loosing discount and taxes in UPDATE ledger flow, TCS/TDS issue  and multi currency issue

apps/web-giddh/src/app/settings/settings.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | GIDK-266 | Design issue due to new header
=> Ravinder | Development | GIDK-266 | Design issue due to new header

apps/web-giddh/src/app/settings/settings.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Staging | GIDK-266 | Design issue due to new header
=> Ravinder | Staging | GIDK-266 | Design issue due to new header

apps/web-giddh/src/app/settings/settings.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Production | GIDK-266 | Design issue due to new header
=> Ravinder | Production | GIDK-266 | Design issue due to new header

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
=> fix: Multicurrency issue

apps/web-giddh/src/app/tb-pl-bs/components/tb/tb.component.ts
=> fix: GIDK-244 | Prateek | Test | Trial balance hang issue

apps/web-giddh/src/app/services/httpWrapper.service.ts, apps/web-giddh/src/app/services/settings.financial-year.service.ts
Ravinder | Development | Applied Condition to not show loader for financial year limits api
=> Ravinder | Development | Applied Condition to not show loader for financial year limits api

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
=> feat: Prateek | Stage | Remove unnecessary API calls

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.ts
=> fix: GIDK-123 | Stage | Prateek | Issues of loader not hiding and API call when calendar is closed

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Development | Fixed active month name
=> Ravinder | Development | Fixed active month name

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.scss, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
=> GIDK-1002 | Rohit | Select vendor checkbox and multiple pages contacts selection implemenetd

apps/web-giddh/src/app/contact/contact.component.scss, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss, apps/web-giddh/src/app/inventory/inventory.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> GIDK-454-dev | Rohit | Inventory desin fixes

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Development | Fixed Issue to directly going to month
=> Ravinder | Development | Fixed Issue to directly going to month

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts, apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.ts
=> fix: GIDK-123 | Prod | Prateek | Issues of loader not hiding and API call when calendar is closed

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
=> feat: Prateek | Prod | Remove unnecessary API calls

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Development | Datepicker input fix
=> Ravinder | Development | Datepicker input fix

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts, apps/web-giddh/src/app/inventory/components/sidebar-components/stockList.component.ts, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.html, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.ts, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts, apps/web-giddh/src/app/inventory/inv.view.service.ts, apps/web-giddh/src/app/inventory/inventory.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html
=> Inventory group stock list collapse issue and routing issue done

apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Development | GIDK-1134 | Test - Call financial year api only when date picker opens
=> Ravinder | Development | GIDK-1134 | Test - Call financial year api only when date picker opens

apps/web-giddh/src/app/audit-logs/audit-logs.component.ts, apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.html, apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
=> GIDK-1115 dev | Rohit | Descriptions is added and Audit log issue resolved

apps/web-giddh/src/app/shared/header/header.component.ts
=> GIDK-531 | Stage | Rohit | Ctrl + click last state and parent tab route prevented for ledger

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts, apps/web-giddh/src/app/inventory/components/sidebar-components/stockList.component.ts, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.html, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.ts, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts, apps/web-giddh/src/app/inventory/inv.view.service.ts, apps/web-giddh/src/app/inventory/inventory.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html
=> Gidk 476 stage| Rohit | Inventory group stock list collapse issue and routing issue done

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
=> Gidk 1119 prod | Rohit | account create and update bank details number validation added  and pending preview issue resolved

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts, apps/web-giddh/src/app/inventory/components/sidebar-components/stockList.component.ts, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.html, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.ts, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts, apps/web-giddh/src/app/inventory/inv.view.service.ts, apps/web-giddh/src/app/inventory/inventory.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html
=> Gidk 476 prod| Rohit | Inventory group stock list collapse issue and routing issue done

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Prateek | Test | Multiple address issue on invoice and prevent unused API call to credit note invoices in sales invoice

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Prateek | Stage | Multiple address issue on invoice and prevent unused API call to credit note invoices in sales invoice

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Prateek | Prod | Multiple address issue on invoice and prevent unused API call to credit note invoices in sales invoice

apps/web-giddh/src/app/ledger/ledger.component.html
=> GIDK-94-stage | Rohit |Ledger B/F balance display on first page implemented

apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.html
=> GIDK-1097-dev | Rohit | Audit log entity issue resolved

apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.html, apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
=> GIDK-115 | Rohit | audit log STOCK_GROUP issue fixed

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | GIDK-1212 | Prod-Side menu bar is getting blank sometimes
=> Ravinder | Development | GIDK-1212 | Prod-Side menu bar is getting blank sometimes

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.scss, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts
=> Gidk 1002 stage| Rohit | Select vendor checkbox and multiple pages contacts selection implemenetd

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.scss, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss, apps/web-giddh/src/app/invoice/invoice.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
=> shalinee | test | PO UI fixes

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | GIDK-1213 | Prod - Bell icon is not working on tablet mode
=> Ravinder | Development | GIDK-1213 | Prod - Bell icon is not working on tablet mode

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Staging | GIDK-1212 | Prod-Side menu bar is getting blank sometimes
=> Ravinder | Staging | GIDK-1212 | Prod-Side menu bar is getting blank sometimes

apps/web-giddh/src/app/accounting/accounting.module.ts, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts, apps/web-giddh/src/app/all-modules/all-modules.component.html, apps/web-giddh/src/app/gst/gstR3/gstR3.component.html, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
=> GIDK-1186-dev | Rohit | currency pipe decimal number applied at JV

apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | GIDK-1213 | Bell icon issue
=> Ravinder | Development | GIDK-1213 | Bell icon issue

apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.scss, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts, apps/web-giddh/src/assets/css/color.scss
=> shalinee | test | GIDK-1155 | modal design fixes

apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html
=> Gidk 1155 dev| share pop up issue done and  user field added when email and user name are different

apps/web-giddh/src/app/models/defaultMenus.ts, apps/web-giddh/src/app/models/interfaces/invoice.setting.interface.ts, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts, apps/web-giddh/src/app/purchase/purchase-advance-search/purchase-advance-search.component.ts, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html, apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html, apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss, apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.ts, apps/web-giddh/src/app/purchase/purchase.routing.module.ts, apps/web-giddh/src/app/services/apiurls/purchase-order.api.ts, apps/web-giddh/src/app/services/purchase-order.service.ts
Ravinder | Development | Purchase order Settings work and bug fixes
=> Ravinder | Development | Purchase order Settings work and bug fixes

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | Removed Dummy Class Initialization
=> Ravinder | Development | Removed Dummy Class Initialization

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Staging | Removed Dummy Class Initialization
=> Ravinder | Staging | Removed Dummy Class Initialization

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.html, package-lock.json
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#5559
=> Revert "shalinee | test | GIDK-1135 | added ID on ledger"

apps/web-giddh/src/app/shared/helpers/pipes/currencyPipe/currencyType.module.ts, apps/web-giddh/src/app/shared/helpers/pipes/currencyPipe/currencyType.pipe.ts
=> fix: GIDK-1177 | Prateek | TEST | Not able to create warehouse and branch

apps/web-giddh/src/app/shared/helpers/pipes/currencyPipe/currencyType.module.ts, apps/web-giddh/src/app/shared/helpers/pipes/currencyPipe/currencyType.pipe.ts
=> fix: GIDK-1177 | Prateek | STAGE | Not able to create warehouse and branch

apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.html, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.html
=> fix: GIDK-1194 | Prateek | Test | Auto complete issue of sh-select

apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> fix: GIDK-126 | Prateek | Test | Avoid multiple API calls, prevent tab selected event from calling on keyboard tab press

apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html, apps/web-giddh/src/assets/css/style-2.scss
Ravinder | Development | Purchase order bugs
=> Ravinder | Development | Purchase order bugs

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.html, package-lock.json
=> cherry-pick & reolved

apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
=> fix: GIDK-124 | Prateek | Test | Prevent cancelled call for stock creation

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.scss, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
=> GIDK-1265-dev | Rohit | balance due for get all invoice binding changed

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
=> GIDK-1265-stage | Rohit | balance due for get all invoice binding changed

apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.scss, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts
=> GIDK-1155-staging | Rohit | Account share module design issue resolved

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
=>  Gidk 1179 prod | Rohit | supply Date picker disabled in case of edit

apps/web-giddh/src/app/settings/permissions/form/form.component.html, apps/web-giddh/src/app/settings/permissions/form/form.component.ts
=> fix: GIDK-854 | Prateek | Test | Issues related to company setting permission module

apps/web-giddh/src/app/purchase/purchase-advance-search/purchase-advance-search.component.ts, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
Ravinder | Development | Fixed Bugs
=> Ravinder | Development | Fixed Bugs

apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts, apps/web-giddh/src/app/purchase/purchase-advance-search/purchase-advance-search.component.ts, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
Ravinder | Development | Fixed PO Bugs
=> Ravinder | Development | Fixed PO Bugs

apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
Ravinder | Development | Fixed PO Bug
=> Ravinder | Development | Fixed PO Bug

apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
Ravinder | Development | PO sppecial character issue
=> Ravinder | Development | PO sppecial character issue

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
Ravinder | Development | Removed wrong code
=> Ravinder | Development | Removed wrong code

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
=>  GIDK-1179-stage | Rohit | supply Date picker disabled in case of edit

apps/web-giddh/src/app/reports/components/cash-flow-statement-component/cash.flow.statement.component.html, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/shared/datepicker-wrapper/datepicker.wrapper.component.ts
Ravinder | Development | GIDK-834 | Fixed Datepicker Position issue
=> Ravinder | Development | GIDK-834 | Fixed Datepicker Position issue

apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.scss, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss, apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss, apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html, apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html, apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss, apps/web-giddh/src/assets/css/color.scss
inline css, spelling corrections and color variables
=> inline css, spelling corrections and color variables

apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
=> fix: GIDK-124 | Prateek | Prod | Prevent cancelled call for stock creation

apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.html, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.html
=> fix: GIDK-1194 | Prateek | Prod | Auto complete issue of sh-select

apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
=> fix: GIDK-124 | Prateek | Stage | Prevent cancelled call for stock creation

apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
=> Removed closing div

apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> fix: Prateek | Test | Handle null currency issue

apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> fix: Prateek | Stage | Handle null currency issue

apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> fix: Prateek | Prod | Handle null currency issue

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | GIDK-916 | Subscription Issue
=> Ravinder | Development | GIDK-916 | Subscription Issue

apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.ts
=> perf: Prateek | GIDK-244 | Improve trial balance performance

angular.json, apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html, apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerDiscount/updateLedgerDiscount.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.scss, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.html
=> Gidk 1135 test

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
=> resolved conflicts

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/models/api-models/recipt.ts
=> GIDK-1265| Rohit | vendor payment issue resolved for multiple in different page

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/models/api-models/recipt.ts
=> GIDK-1265-staging | Rohit | vendor payment issue resolved for multiple in different page

apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
=> GIDK-1266-stage | Rohit | advance search date-picker close issue resolved

apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
=> GIDK-1266-dev | Rohit | advance search date-picker close issue resolved #5608

apps/web-giddh/src/app/ledger/ledger.component.html
=> resolve click issue

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/models/api-models/recipt.ts
=> GIDK-1265-production | Rohit | vendor payment issue resolved for multiple in different page

apps/web-giddh/src/app/settings/permissions/form/form.component.html, apps/web-giddh/src/app/settings/permissions/form/form.component.ts
=> fix: GIDK-854 | Prateek | Stage | Issues related to company setting permission module

apps/web-giddh/src/app/shared/helpers/directives/ngx-mask/mask-applier.service.ts
Fixes issue: https://walkover.slack.com/archives/CA2NG4J9E/p1599048406002500
=> fix: Prateek | Test | Cannot access length of undefined error

apps/web-giddh/src/app/shared/helpers/directives/ngx-mask/mask-applier.service.ts
Fixes issue: https://walkover.slack.com/archives/CA2NG4J9E/p1599048406002500
=> fix: Prateek | Stage | Cannot access length of undefined error

apps/web-giddh/src/app/shared/helpers/directives/ngx-mask/mask-applier.service.ts
Fixes issue: https://walkover.slack.com/archives/CA2NG4J9E/p1599048406002500
=> fix: Prateek | Prod | Cannot access length of undefined error

apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/tb/tb.component.ts
=> fix: GIDK-244 | Prateek | Stage | Trial balance hang issue

apps/web-giddh/src/app/settings/permissions/form/form.component.html, apps/web-giddh/src/app/settings/permissions/form/form.component.ts
=> fix: GIDK-854 | Prateek | Prod | Issues related to company setting permission module

apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.ts, apps/web-giddh/src/app/tb-pl-bs/components/tb/tb.component.ts
=> fix: GIDK-244 | Prateek | Prod | Trial balance hang issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-1246 | Prateek | Test | State field focus issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-1246 | Prateek | Stage | State field focus issue

apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts, apps/web-giddh/src/app/shared/helpers/defaultDateFormat.ts
=> GIDK-1436-stage | Rohit | account and group share pop up email regex changed

apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts, apps/web-giddh/src/app/shared/helpers/defaultDateFormat.ts
=> GIDK-1436-prod | Rohit |account and group share pop up email regex changed

apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts, apps/web-giddh/src/app/shared/helpers/defaultDateFormat.ts
=> GIDK-1436-dev | Rohit |account and group share pop up email regex changed

apps/web-giddh/src/assets/pdfjs/web/viewer.js
=> fix: GIDK-1440 | Prateek | Stage | Improve PDF quality on print

apps/web-giddh/src/assets/pdfjs/web/viewer.js
=> fix: GIDK-1440 | Prateek | Test | Improve PDF quality on print

apps/web-giddh/src/app/ledger/ledger.component.ts
=> fix: Rate api called with undefined error

apps/web-giddh/src/assets/pdfjs/web/viewer.js
=> fix: GIDK-1440 | Prateek | Prod | Improve PDF quality on print

apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html, apps/web-giddh/src/assets/css/style-2.scss
=> test | aditi | GIDK-1442 | tabs overlapping issue

apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.ts
=> fix: Prateek | Test | Advance search filter misbehaving

apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.ts
=> fix: Prateek | Stage | Advance search filter misbehaving

apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.ts
=> fix: Prateek | Prod | Advance search filter misbehaving

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Gidk 1168 | Prateek | Stage | Not able to generate recurring invoice, it is redirecting on the dashboard page

apps/web-giddh/src/app/all-modules/all-modules.component.html, apps/web-giddh/src/app/all-modules/all-modules.component.scss, apps/web-giddh/src/app/all-modules/all-modules.component.ts, apps/web-giddh/src/app/services/apiurls/permission.api.ts, apps/web-giddh/src/app/services/permission.service.ts
=> Gidk 1153 d | Rohit | create all module dynamic 

apps/web-giddh/src/app/all-modules/all-modules.component.html, apps/web-giddh/src/app/all-modules/all-modules.component.scss, apps/web-giddh/src/app/all-modules/all-modules.component.ts, apps/web-giddh/src/app/services/apiurls/permission.api.ts, apps/web-giddh/src/app/services/permission.service.ts
=> Gidk 1153 new| Rohit | create all module dynamic

apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Development | GIDK-916 | Fixed Subscription Refresh Issue
=> Ravinder | Development | GIDK-916 | Fixed Subscription Refresh Issue

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
=> Development build issue

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/models/api-models/recipt.ts
=> GIDK-1487 | Rohit | balance due for multi-currency json binding changed

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/models/api-models/recipt.ts
=> Gidk 1487 deve | Rohit | balance due for multi-currency json binding changed 

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/models/api-models/recipt.ts
=> GIDK-1487-prod | Rohit | balance due for multi-currency json binding changed

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Prateek | Test | Multicurrency issue dev

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Prateek | Stage | Multicurrency issue dev

apps/web-giddh/src/assets/css/style-1.scss
=> fix: GIDK-1490 | Test | Prateek | Prod/beta - Trial balance is not loading data, loader is not coming and Reload button is also not working.

apps/web-giddh/src/assets/css/style-1.scss
=> fix: GIDK-1490 | Stage | Prateek | Prod/beta - Trial balance is not loading data, loader is not coming and Reload button is also not working.

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-1168 | Prateek | Test | Recurring issue

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 1489 chat icon

apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> fix: GIDK-1360 | Prateek | Test | Adjustment handling from invoice preview page

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss
=> remove z-index

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Gidk 1168 | Prateek | Prod | Not able to generate recurring invoice, it is redirecting on the dashboard page

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: GIDK-1168 | Prateek | Stage | Recurring issue

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.module.ts
Ravinder | Development | Removed Scroll from datepicker
=> Ravinder | Development | Removed Scroll from datepicker

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/loader/loader.component.html, apps/web-giddh/src/app/loader/loader.component.ts, apps/web-giddh/src/app/services/http.interceptor.ts
=> fix: GIDK-1182 | Prateek | Test | Giddh keeps on loading randomly after 15-20 mins

apps/web-giddh/src/app/loader/loader.component.html, apps/web-giddh/src/app/loader/loader.component.ts
=> fix: Loader issue

apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> fix: GIDK-1360 | Prateek | PROD | Adjustment handling from invoice preview page

apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> fix: GIDK-1360 | Prateek | Stage | Adjustment handling from invoice preview page

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html, apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss
=> Ravinder | Development | Purchase order 1.2

apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.html, apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.scss, apps/web-giddh/src/app/theme/tax-control/tax-control.component.html
=> Gidk 1535 dev

apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.html, apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.scss, apps/web-giddh/src/app/theme/tax-control/tax-control.component.html
=> Gidk 1535 ledger dropdown

apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.html, apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.scss, apps/web-giddh/src/app/theme/tax-control/tax-control.component.html, apps/web-giddh/src/assets/css/toastr.css
=> Gidk 1535 prod

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/loader/loader.component.html, apps/web-giddh/src/app/loader/loader.component.ts, apps/web-giddh/src/app/services/http.interceptor.ts
=> fix: GIDK-1182 | Prateek | Stage | Giddh keeps on loading randomly after 15-20 mins

apps/web-giddh/src/assets/css/style-1.scss
=> fix: GIDK-1490 | Prod | Prateek | Prod/beta - Trial balance is not loading data, loader is not coming and Reload button is also not working.

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts, apps/web-giddh/src/app/loader/loader.component.html, apps/web-giddh/src/app/loader/loader.component.ts, apps/web-giddh/src/app/services/http.interceptor.ts
=> fix: GIDK-1182 | Prateek | Prod | Giddh keeps on loading randomly after 15-20 mins

apps/web-giddh/src/app/mobile-home/mobile-search-company/mobile-search-company.component.html, apps/web-giddh/src/app/mobile-home/mobile-search-company/mobile-search-company.component.ts
=> remove function

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
=> fix: Petty cash nullity issue

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/commandk.service.ts
=> fix: GIDK-1542 | Prateek | Test | Handle special characters in search

apps/web-giddh/src/app/services/purchase-order.service.ts
=> fix: Handling of special characters in PO

apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/services/purchase-order.service.ts
=> fix: GIDK-1235 | Prateek | Test - On ledger arrow key is not working correct

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Development | Fixed PO Linking add/remove issue
=> Ravinder | Development | Fixed PO Linking add/remove issue

apps/web-giddh/src/app/ledger/ledger.vm.ts
=> fix: Nullity issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Development | Fixed Nulity check on discount
=> Ravinder | Development | Fixed Nulity check on discount

apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/sales/discount-list/discountList.component.html, apps/web-giddh/src/app/sales/tax-list/sales.tax.list.component.html, apps/web-giddh/src/app/theme/discount-control/discount-control-component.html, apps/web-giddh/src/app/theme/tax-control/tax-control.component.html
=> cherry-pick commit

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts
Ravinder | Development | Added discount type nulity check
=> Ravinder | Development | Added discount type nulity check

apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.html
Ravinder | Development | Loaded component only if required
=> Ravinder | Development | Loaded component only if required

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Development | Removed items only if belonged to PO
=> Ravinder | Development | Removed items only if belonged to PO

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
Ravinder | Development | Fixed Delete issue for invoice
=> Ravinder | Development | Fixed Delete issue for invoice

apps/web-giddh/src/app/billing-details/billingDetail.component.ts, apps/web-giddh/src/app/userDetails/userDetails.component.ts
Ravinder | Fixed Subscription and billing issue
=> Ravinder | Fixed Subscription and billing issue

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.scss
=> invoice table status column fixed

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts, apps/web-giddh/src/app/services/account.service.ts, apps/web-giddh/src/app/services/contact.service.ts, apps/web-giddh/src/app/services/expences.service.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/services/purchase-invoice.service.ts, apps/web-giddh/src/app/services/purchase-order.service.ts, apps/web-giddh/src/app/services/purchase-record.service.ts, apps/web-giddh/src/app/services/receipt.service.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/services/search.service.ts, apps/web-giddh/src/app/services/settings.linked.accounts.service.ts
=> fix: Special character handling throughout the application

apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.scss, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.scss
=> shalinee | dev | share account modal UI fixes

apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.scss, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.scss
=> shalinee | stage | share account modal UI fixes

apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
=> fix: Remove min character check

apps/web-giddh/src/app/onboarding/onboarding.component.html
=> Hotfix: Rohit | onboarding tally sync url changed

apps/web-giddh/src/app/ledger/ledger.component.ts
=> fix: GIDK-932 | Prateek | Test | ICICI transaction mapping, entries got made twice

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/shared/helpers/directives/ngx-mask/mask.directive.ts
=> fix: Petty cash entry issue

apps/web-giddh/src/app/ledger/ledger.component.ts
=> fix: GIDK-932 | Prateek | Stage | ICICI transaction mapping, entries got made twice

apps/web-giddh/src/app/ledger/ledger.component.ts
=> fix: GIDK-932 | Prateek | Prod | ICICI transaction mapping, entries got made twice

apps/web-giddh/src/assets/pdfjs/web/viewer.js, package.json
=> fix: Improve PDF quality

apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.scss, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.scss
=> shalinee | prod | share account modal UI fixes

apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/sales/discount-list/discountList.component.html, apps/web-giddh/src/app/sales/tax-list/sales.tax.list.component.html, apps/web-giddh/src/app/theme/discount-control/discount-control-component.html, apps/web-giddh/src/app/theme/tax-control/tax-control.component.html
=> shalinee | GIDK-1d6w9k| prod | cherry-pick ID commits

apps/web-giddh/src/app/ledger/ledger.component.html
=> fix: GIDK-1235 | Prateek | Stage - On ledger arrow key is not working correct

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/ledger/ledger.vm.ts, apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts, apps/web-giddh/src/app/services/account.service.ts, apps/web-giddh/src/app/services/commandk.service.ts, apps/web-giddh/src/app/services/contact.service.ts, apps/web-giddh/src/app/services/expences.service.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/services/purchase-invoice.service.ts, apps/web-giddh/src/app/services/purchase-order.service.ts, apps/web-giddh/src/app/services/purchase-record.service.ts, apps/web-giddh/src/app/services/receipt.service.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/services/search.service.ts, apps/web-giddh/src/app/services/settings.linked.accounts.service.ts, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
=> fix: GIDK-1542 | Prateek | Stage | Handle special characters in search

apps/web-giddh/src/app/ledger/ledger.component.html
=> fix: GIDK-1235 | Prateek | Prod - On ledger arrow key is not working correct

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/ledger/ledger.vm.ts, apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts, apps/web-giddh/src/app/services/account.service.ts, apps/web-giddh/src/app/services/commandk.service.ts, apps/web-giddh/src/app/services/contact.service.ts, apps/web-giddh/src/app/services/expences.service.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/services/purchase-invoice.service.ts, apps/web-giddh/src/app/services/purchase-order.service.ts, apps/web-giddh/src/app/services/purchase-record.service.ts, apps/web-giddh/src/app/services/receipt.service.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/services/search.service.ts, apps/web-giddh/src/app/services/settings.linked.accounts.service.ts, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
=> fix: GIDK-1542 | Prateek | Prod | Handle special characters in search

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
=> fix: GIDK-1603 | Prateek | Test - On invoice in deposit section cash account is not getting display

apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.ts
=> GIDK-1570-dev | Rohit | Universal Today case implemented as in case of today hide daterange

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
=> fix: GIDK-1603 | Prateek | Stage - On invoice in deposit section cash account is not getting display

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
=> fix: GIDK-1603 | Prateek | Prod - On invoice in deposit section cash account is not getting display

apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/models/api-models/Account.ts
=> fix: GIDK-1067 | Prateek | Test | Prod - Tax and discount field is not displaying when user is doing entry from ledger

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
=> Petty cash prod issue of debit and credit transaction

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
=> fix: Petty cash issue of credit/debit

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.html, apps/web-giddh/src/app/purchase/purchase-advance-search/purchase-advance-search.component.html, apps/web-giddh/src/app/settings/discount/discount.component.html, apps/web-giddh/src/assets/css/ngx-bs-datepicker.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 1dcrrf datepicker test

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Gidk 1600 | Prateek | Prod | Prod - On create voucher form, When user is selecting customer/vendor the focus is shifting to state field 

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
=> fix: GIDK-1102 | Prateek | Test | Asterisk not visible on State field

apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
=> Ravinder | Fixed GIDK-1579

apps/web-giddh/src/app/invoice/create/invoice.create.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/sales/create/sales.invoice.component.html, apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
=> shalinee | stage | resolve sales invoice scroll issue

apps/web-giddh/src/app/invoice/create/invoice.create.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/sales/create/sales.invoice.component.html, apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
=> Gidk 1dc05b dev

apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.ts, cypress/plugins/index.js
=> Ravinder | Fixed Bugs

angular.json
Ravinder | Added cypress in build
=> Ravinder | Added cypress in build

apps/web-giddh/src/app/invoice/create/invoice.create.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/sales/create/sales.invoice.component.html, apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
=> Gidk 1dc05b prod

apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
… link in left hand menu module is not switched
=> fix: GIDK-1610 | Prateek | Test | When we switch from one Import module to another by clicking the link in left hand menu module is not switched

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Fixed Tax Control/Discount popup close issue
=> Ravinder | Fixed Tax Control/Discount popup close issue

apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.ts, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts, apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html, apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.scss, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/onboarding/onboarding.component.html
=> Rohit | Daybook ng-10 issue resolved

cypress/plugins/index.js
Ravinder | Fixed directory path
=> Ravinder | Fixed directory path

apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.ts
Ravinder | Fixed datepicker and dropdown issue
=> Ravinder | Fixed datepicker and dropdown issue

apps/web-giddh/src/app/import-excel/import-report/import-report.component.html, apps/web-giddh/src/app/ledger/components/updateLedgerDiscount/updateLedgerDiscount.component.ts
=> Rohit | update Ledger discount issue and import pagination issue fixed

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html, apps/web-giddh/src/app/manufacturing/report/mf.report.component.html, apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
=> Aditi | test | inventory button hide on mobile

apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/assets/css/style-2.scss
=> Ravinder | Fixed issues

apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
Ravinder | Fixed JV Duplicate account issue
=> Ravinder | Fixed JV Duplicate account issue

apps/web-giddh/src/app/audit-logs/audit-logs.component.html, apps/web-giddh/src/app/audit-logs/audit-logs.component.scss, apps/web-giddh/src/app/audit-logs/audit-logs.component.ts, apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.html, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss, apps/web-giddh/src/app/login/login.component.html, apps/web-giddh/src/app/permissions/components/list/permission-list.html, apps/web-giddh/src/app/permissions/components/list/permission.component.scss, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.scss, apps/web-giddh/src/app/vat-report/vatReport.component.html, apps/web-giddh/src/assets/css/style-2.scss
=> Aditi | test | test sanity issues done

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss, apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html, apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.html, apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html, apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html, apps/web-giddh/src/assets/css/ngx-bs-datepicker.scss, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/src/meta/magic.html
=> Gidk 1dend2 sanity ui issue

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss, apps/web-giddh/src/assets/css/ngx-bootstrap/bs-datepicker.css, apps/web-giddh/src/assets/css/style-1.scss
=> Aditi | test | test-sanity-new issues

apps/web-giddh/src/app/audit-logs/audit-logs.component.html, apps/web-giddh/src/app/audit-logs/audit-logs.component.ts, apps/web-giddh/src/app/daybook/daybook.component.ts
=> Rohit | Daybook pagination issue and clear filer audit log issues resolved

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
=> Aditi | test | sanity issue of CR/DR

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
=> CN/DN Total alignment

apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/userDetails/userDetails.component.ts
Ravinder | Fixed Subscription Refresh issue and user details
=> Ravinder | Fixed Subscription Refresh issue and user details

apps/web-giddh/src/app/invoice/invoice.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
=> Rohit invoice preview height and setting tab removed in case of cr/dr resolved

apps/web-giddh/src/app/accounting/journal-voucher/journal-voucher.component.html, apps/web-giddh/src/app/accounting/journal-voucher/journal-voucher.component.ts, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html, apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html, apps/web-giddh/src/assets/css/ngx-bootstrap/bs-datepicker.css, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/src/assets/css/toastr.css
=> Gidk 1b74u6 intercom

apps/web-giddh/src/app/all-modules/all-modules.component.html, apps/web-giddh/src/app/invoice/invoice.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
=> all module coming soon issue resolved

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
=> Rohit | update account country change code change issue resolved

apps/web-giddh/src/app/invoice/invoice.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
=> invoice preview height and setting tab removed in case of cr/dr resolved

apps/web-giddh/src/app/invoice/invoice.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
=> prod | Rohit | invoice preview height and setting tab removed in case of cr/dr resolved

apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html, apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.scss, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.scss
=> GIDK-1fb4yh-test | test | Aditi | share group popup

apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html, apps/web-giddh/src/app/settings/permissions/form/form.component.html, apps/web-giddh/src/assets/css/toastr.css
=> shalinee | UI fixes

apps/web-giddh/src/app/actions/common.actions.ts, apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-receiver-details.component.ts, apps/web-giddh/src/app/login/token-verify.component.ts, apps/web-giddh/src/app/services/common.service.ts, apps/web-giddh/src/app/settings/profile/setting.profile.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/shared/on-boarding/on-boarding.component.ts, apps/web-giddh/src/app/store/Common/common.reducer.ts, apps/web-giddh/src/app/welcome/welcome.component.ts
Ravinder | Removed unnecessary API cals
=> Ravinder | Removed unnecessary API cals

apps/web-giddh/src/app/app.component.ts
Called currency api if page refreshed
=> Called currency api if page refreshed

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/invoice/preview/models/purchase-bill-template-preview/purchase-bill-template-preview.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss, apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.scss, apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> shalinee | dev | scroll design fix

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html, apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
=> add cursor pointer

apps/web-giddh/src/app/actions/accounts.actions.ts, apps/web-giddh/src/app/actions/login.action.ts, apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/settings/permissions/form/form.component.ts, apps/web-giddh/src/app/settings/permissions/setting.permission.component.html, apps/web-giddh/src/app/settings/settings.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/store/Permission/permission.reducer.ts
Ravinder | Improvements and permission edit issue
=> Ravinder | Improvements and permission edit issue

angular.json
Ravinder | Removed baseUrl since it's giving error in build creation
=> Ravinder | Removed baseUrl since it's giving error in build creation

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/invoice/preview/models/purchase-bill-template-preview/purchase-bill-template-preview.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss, apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.scss, apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 1f9jcr stage

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/shared/header/header.component.html
=> Click 1f9w2v dev| daybook advance search issue and universal today case implemented

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/invoice/preview/models/purchase-bill-template-preview/purchase-bill-template-preview.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss, apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.scss, apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 1f9jcr scroll

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
=> fix: GIDK-1644 | Prateek | Test | PDF is not displayed in full frame

apps/web-giddh/src/assets/css/style-2.scss
=> shalinee | increase scroll height

apps/web-giddh/src/app/actions/accounts.actions.ts, apps/web-giddh/src/app/actions/common.actions.ts, apps/web-giddh/src/app/actions/login.action.ts, apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-receiver-details.component.ts, apps/web-giddh/src/app/login/token-verify.component.ts, apps/web-giddh/src/app/services/common.service.ts, apps/web-giddh/src/app/settings/permissions/form/form.component.ts, apps/web-giddh/src/app/settings/permissions/setting.permission.component.html, apps/web-giddh/src/app/settings/profile/setting.profile.component.ts, apps/web-giddh/src/app/settings/settings.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/shared/on-boarding/on-boarding.component.ts, apps/web-giddh/src/app/store/Common/common.reducer.ts, apps/web-giddh/src/app/store/Permission/permission.reducer.ts, apps/web-giddh/src/app/welcome/welcome.component.ts
=> Ravinder | Beta improvements

apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.scss, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss
=> shalinee | prod | fixed intercom  overlap issue

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
=> fix: GIDK-1644 | Prateek | Stage | PDF is not displayed in full frame

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
=> fix: GIDK-1644 | Prateek | Prod | PDF is not displayed in full frame

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/invoice/preview/models/purchase-bill-template-preview/purchase-bill-template-preview.component.scss, apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss, apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.scss, apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.ts, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Cheery pick giddh 2.0

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss, apps/web-giddh/src/app/shared/header/header.component.html
=> shalinee | resolved header issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Fixed Entry date to not take entry date from copied invoice
=> Ravinder | Fixed Entry date to not take entry date from copied invoice

apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.scss
=> shalinee | UI fixes of brnach switcher

apps/web-giddh/src/app/actions/common.actions.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
=> Fixed issues

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/search.service.ts, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.html, apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.ts
=> feat: GIDK-1639 | Prateek | Stage | Initial commit: Search API call on page load

apps/web-giddh/src/app/shared/header/header.component.scss
=> Architecture v1 ui issue

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
=> Click 1fb7e4: dev| Rohit | Select group create account form field change dynamically API integrated

apps/web-giddh/src/app/contact/contact.component.ts
Ravinder | Fixed Sorting issue after payment in vendor
=> Ravinder | Fixed Sorting issue after payment in vendor

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts, apps/web-giddh/src/assets/css/ngx-bs-datepicker.scss
=> Gidk 1fd61k datepicker align

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts, apps/web-giddh/src/assets/css/ngx-bs-datepicker.scss
=> Gidk 1fd61k datepicker align beta

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Fixed Entry date for PB
=> Ravinder | Fixed Entry date for PB

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
=> shalinee | increase width of adjustment policy

apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
=> shalinee | increase width of adjustment field

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
Ravinder | Fixed Account create/update issue with invalid mobile no
=> Ravinder | Fixed Account create/update issue with invalid mobile no

apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.html, apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
=> shalinee | giddh-2.0 | cherry-pick setting delete icon issue

apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss
=> shalinee | GIDDH-2.0 | E-way bill table issue resloved

apps/web-giddh/src/app/actions/groupwithaccounts.actions.ts, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts, apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
Ravinder | Fixed Move group issue
=> Ravinder | Fixed Move group issue

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Fixed Vendor and Datepicker issue
=> Ravinder | Fixed Vendor and Datepicker issue

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.scss, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/theme/tax-control/tax-control.component.html, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 1h80fb test issue

apps/web-giddh/src/app/actions/groupwithaccounts.actions.ts, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html, apps/web-giddh/src/app/models/api-models/Group.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/authentication.service.ts, apps/web-giddh/src/app/settings/settings.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts, apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Merged Bugs in Beta
=> Ravinder | Merged Bugs in Beta

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html, apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.scss, apps/web-giddh/src/app/shared/header/header.component.html, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/theme/tax-control/tax-control.component.html, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 1h80fb beta

apps/web-giddh/src/app/services/settings.profile.service.ts, apps/web-giddh/src/app/settings/address-settings/address-settings.component.html, apps/web-giddh/src/app/settings/address-settings/address-settings.component.ts, apps/web-giddh/src/app/settings/profile/setting.profile.component.html, apps/web-giddh/src/app/settings/profile/setting.profile.component.ts, apps/web-giddh/src/meta/yodlee-success.html
=> Architecture v1

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
=> Click 1fb7e4 giddh 2.0| | Rohit | Select group create account form field change dynamically API integrated

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
=> GIDK-1f7ca3-CF-dev | Rohit | custom field delete pop up implemented

cypress/integration/Giddh/ledger.js
=> +Chirag | Added code for ledger testing

apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
=> test | GIDK-1h8ukq | Aditi | apply button UI

apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
=> stage | GIDK-1h8ukq | Aditi | apply button UI

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Fixed PB Stock Issue
=> Ravinder | Fixed PB Stock Issue

apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss, apps/web-giddh/src/app/contact/contact.component.scss, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.scss, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss, apps/web-giddh/src/app/inventory/jobwork/jobwork.component.scss, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss, apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss, apps/web-giddh/src/app/invoice/recurring/recurring.component.scss
=> shalinee | make cusror pointer
