- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
> Dev: clickUp-1f9w2v | Rohit | Today selected refresh page issue resolved

- apps/web-giddh/src/app/services/apiurls/settings.profile.api.ts
- apps/web-giddh/src/app/services/settings.profile.service.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.ts
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
- apps/web-giddh/src/app/settings/services/settings-utility.service.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/Settings/Settings.reducer.ts
> feat: Branch profile

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Datepicker implementation

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Datepicker beta branch

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Datepicker beta stage

- apps/web-giddh/src/app/all-modules/all-modules.component.html
- apps/web-giddh/src/app/all-modules/all-modules.component.ts
- apps/web-giddh/src/index.html
Ravinder | Saved clicked menu from All modules page and removed duplicate code from index.html
> Ravinder | Saved clicked menu from All modules page and removed duplicate code from index.html

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
> Gidk 1f7ca3 custom ui changes| custom field design issue and bugs resolved

- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss
> shalinee | correct height

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
> beta | GIDK-1h9822 | Aditi | clear button ui

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
> test | GIDK-1h9822 | Aditi | clear filter button

- apps/web-giddh/src/app/models/api-models/SettingsDiscount.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/index.html
Ravinder | Merging test issues on beta
> Ravinder | Merging test issues on beta

- apps/web-giddh/src/app/models/api-models/SettingsDiscount.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/index.html
Ravinder | Merging test issues on stage
> Ravinder | Merging test issues on stage

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
>  stage | Aditi | inventory ui mobile-app

- apps/web-giddh/src/app/app.constant.ts
Ravinder | Added Staging ENV for default plan for new signup
> Ravinder | Added Staging ENV for default plan for new signup

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-reciver-details.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss
> Gidk 1h9q8t giddh 2.0

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-reciver-details.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
> Gidk 1h9q8t beta env

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-reciver-details.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
> Gidk 1h9q8t beta stage

- apps/web-giddh/src/app/all-modules/all-modules.component.html
Ravinder | Fixed PO link issue
> Ravinder | Fixed PO link issue

- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> shalinee | reduce width of today and increase height of custom field

- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.ts
- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html
- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> fix: Replace typeaheads with sh-select in linked accounts and eway bill

- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> Gidk cherry pick beta stage

- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> Gidk cherry pick beta branch

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.html
> ClickUp-1h9rj2-2.0 | Rohit | angular 10 issues resolved

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.html
> ClickUp-1h9rj2 | Rohit | angular 10 issues resolved

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/meta/magic.html
> Ravinder | Fixing bugs

- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html
> test | GIDK-1hah64 | Aditi | connect modal design

- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html
> stage | GIDK-1hah64 | Aditi | connect modal

- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
Ravinder | Fixed Magic link issue and discount not showing issue
> Ravinder | Fixed Magic link issue and discount not showing issue

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
> Click up 1h8fnb | Rohit | angular 10 issues fixed

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
> login-stage-issue | Rohit | login for stage change as discussed with ravinder ji

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
> shalinee | giddh-2.0 | resolved ledger PO and header spacing issue

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/contact.service.ts
> Ravinder | Fixing beta issues

- apps/web-giddh/src/app/all-modules/all-modules.component.html
- apps/web-giddh/src/app/models/defaultMenus.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/proforma-invoice/services/proforma-invoice-utility.service.ts
- apps/web-giddh/src/app/purchase/purchase-invoice/purchase.invoice.component.html
- apps/web-giddh/src/app/purchase/purchase.routing.module.ts
Ravinder | Hotfix for PO/PB url and name issue
> Ravinder | Hotfix for PO/PB url and name issue

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
Ravinder | Uncheck Shipping checkbox on warehouse change
> Ravinder | Uncheck Shipping checkbox on warehouse change

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/models/api-models/Company.ts
- apps/web-giddh/src/app/services/apiurls/settings.profile.api.ts
- apps/web-giddh/src/app/services/settings.profile.service.ts
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.ts
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.scss
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/constants/settings.constant.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/settings/edit-branch/edit-branch.component.html
- apps/web-giddh/src/app/settings/settings.module.ts
- apps/web-giddh/src/app/settings/settings.routing.module.ts
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.html
> feat: CREATE branch

- apps/web-giddh/src/app/settings/branch/branch.component.ts
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
> fix: Issue related to branch and warehouse

- cypress/integration/Giddh/ledger.js
- cypress/support/commands.js
- package.json
> +Chirag | added TC for ledger and working on parallel TC running

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
> test | GIDK-1hb5ry | Aditi | PB image hiding issue fix

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Fixed Link PO Issue
> Ravinder | Fixed Link PO Issue

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/contact.service.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/meta/magic.html
Ravinder | Merge issues from beta to test
> Ravinder | Merge issues from beta to test

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
> shalinee | new architecture UI issue fixed

- apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Build css issue|Rohit | permission issue and style issue resolved

- apps/web-giddh/src/app/services/apiurls/settings.profile.api.ts
- apps/web-giddh/src/app/services/settings.profile.service.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.scss
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.ts
> feat: Warehouse complete and issue fixes

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/assets/css/color.scss
> test | GIDK-1h9822 | Aditi | clear button ui fixed

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
> beta | GIDK-1h9822 | Aditi | clear filter ui fixed

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
> fix: Issue fixes

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
> fix: Warehouse related fixes

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
Ravinder | Fixed Shipping same as billing checkbox issue
> Ravinder | Fixed Shipping same as billing checkbox issue

- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.scss
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/webpack.partial.js
> Gidk 1hbj4z scroll issue

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
Ravinder | Po issue beta -> giddh2
> Ravinder | Po issue beta -> giddh2

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
> beta | GIDK-1hb5ry | Aditi | PB image hiding issue fix

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
> stage | GIDK-1hb5ry | Aditi | PB image hiding issue fix

- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
> shalinee | giddh-2.0 | correct inventory dropdown

- apps/web-giddh/src/app/contact/contact.component.ts
Ravinder | Hotfix - Vendor sorting issue after bulk payment
> Ravinder | Hotfix - Vendor sorting issue after bulk payment

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> fix: Architecture Issues

- apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
> fix: Issue fix for aliass

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Fixed Stock Rate Issue
> Ravinder | Fixed Stock Rate Issue

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> fix: Add toast message to API calls

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
> fix: Branch and warehouse issues

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Ravinder | Fixed PO Issue

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.scss
- apps/web-giddh/src/app/settings/create-address/create-address.component.scss
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.scss
- apps/web-giddh/webpack.partial.js
> Gidk font bold issue

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> Petty cash issue

- apps/web-giddh/src/app/shared/header/header.component.ts
> Ravinder | Added missed code

- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> shalinee | test | correct setting-help sidebar

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: Petty cash issue

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> Petty cash issue dev

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> Petty cash issue beta stage

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> Petty cash beta

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> Petty cash issue stage

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
> fix: Inventory issue

- apps/web-giddh/src/app/ledger/ledger.component.ts
> Prod | Rohit | shared ledger with permission issue fixed

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Fixed Settings back button issue
> Ravinder | Fixed Settings back button issue

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
> fix: Syntax

- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
Ravinder | Beta/Stage Sanity>when delete the group from Current Assets >Sundry debtors then  then groups columns are showing repeated
> Ravinder | Beta/Stage Sanity>when delete the group from Current Assets >Sundry debtors then  then groups columns are showing repeated

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
> Ravinder | Beta -> giddh 2.0

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/inventory.component.scss
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/login/login.component.html
- apps/web-giddh/src/app/login/login.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/signup/signup.component.html
- apps/web-giddh/src/app/signup/signup.component.scss
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.html
- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1hfa0h stage

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/inventory.component.scss
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/login/login.component.html
- apps/web-giddh/src/app/login/login.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/signup/signup.component.html
- apps/web-giddh/src/app/signup/signup.component.scss
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.html
- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1hfa0h beta

- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
Ravinder | Settings back button functionality on beta
> Ravinder | Settings back button functionality on beta

- apps/web-giddh/src/app/import-excel/import-wizard/import-wizard.component.html
- apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.html
- apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.scss
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.html
> beta | GIDK-1hdvk6 | Aditi | Ipad UI fixes

- apps/web-giddh/src/app/settings/routing-guards/settings-deactivate.guard.ts
> fix: Navigation issue

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
- apps/web-giddh/src/app/inventory/inventory.component.scss
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/mobile-home/mobile-search-company/mobile-search-company.component.html
- apps/web-giddh/src/app/permissions/components/list/permission-list.html
- apps/web-giddh/src/app/permissions/components/list/permission.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/toastr.css
> Gidk 1k7tkm res ui test

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/models/defaultMenus.ts
Ravinder | Merging beta bug fixes on test
> Ravinder | Merging beta bug fixes on test

- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gst.component.scss
- apps/web-giddh/src/app/gst/gst.component.ts
- apps/web-giddh/src/app/gst/gst.module.ts
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.ts
- apps/web-giddh/src/app/services/GstReconcile.service.ts
- apps/web-giddh/src/app/services/apiurls/purchase-invoice.api.ts
- apps/web-giddh/src/app/services/settings.profile.service.ts
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
- apps/web-giddh/src/app/vat-report/transactions/vatReportTransactions.component.html
- apps/web-giddh/src/app/vat-report/transactions/vatReportTransactions.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.scss
- apps/web-giddh/src/app/vat-report/vatReport.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.module.ts
> feat: VAT and GST changes

- apps/web-giddh/src/app/settings/branch/branch.component.ts
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> fix: Branch and warehouse name and alias validation

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
Ravinder | Fixed On PO/PB create form the tax and discount dropdown is overlapping
> Ravinder | Fixed On PO/PB create form the tax and discount dropdown is overlapping

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
Ravinder | Merge beta -> giddh2.0 issue
> Ravinder | Merge beta -> giddh2.0 issue

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> fix: Prateek | Stage | Multicurrency issue, remove dependency from multi currency profile flag

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> fix: Prateek | Dev | Multicurrency issue, remove dependency from multi currency profile flag

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> fix: Prateek | Test | Multicurrency issue, remove dependency from multi currency profile flag

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> fix: Prateek | Release | Multicurrency issue, remove dependency from multi currency profile flag

- apps/web-giddh/src/app/audit-logs/audit-logs.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.ts
- apps/web-giddh/src/app/home/components/profit-loss/profile-loss.component.ts
- apps/web-giddh/src/app/home/components/total-overdues/total-overdues-chart.component.ts
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/purchase/purchase-advance-search/purchase-advance-search.component.ts
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts
- apps/web-giddh/src/app/reports/components/cash-flow-statement-component/cash.flow.statement.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Don't call api when user clicks on cancel button on date picker
> Ravinder | Don't call api when user clicks on cancel button on date picker

- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
> feat: Remove the multicurrency checkbox from profile page

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.css
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/assets/css/style-1.scss
> beta | GIDK-1he59k | Aditi | mobile and ipad ui issues

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
> fix: Incorrect amount displayed when fraction is used

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> fix: Prateek | Beta | Multicurrency issue, remove dependency from multi currency profile flag

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/inventory/inventory.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss
- apps/web-giddh/src/app/mobile-home/mobile-search-company/mobile-search-company.component.html
- apps/web-giddh/src/app/mobile-home/mobile-search-company/mobile-search-company.component.scss
- apps/web-giddh/src/app/settings/permissions/setting.permission.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1k84j9 res ui test

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/inventory/inventory.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss
- apps/web-giddh/src/app/mobile-home/mobile-search-company/mobile-search-company.component.html
- apps/web-giddh/src/app/mobile-home/mobile-search-company/mobile-search-company.component.scss
- apps/web-giddh/src/app/settings/permissions/setting.permission.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | resolved conflict

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> fix: Prateek | Prod | Multicurrency issue, remove dependency from multi currency profile flag

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.scss
- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.scss
> test | GIDK-1k7qe0 | Aditi | beta-ui-issues

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.scss
- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.ts
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/fonts/icomoon/icomoon.css
> beta | GIDK-1k7qe0 | Aditi | beta-ui-issues

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/services/general.service.ts
Ravinder | Worked on saving last state on customer/vendor/aging-report
> Ravinder | Worked on saving last state on customer/vendor/aging-report

- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Validation is not working as expected for 'day to up today' field in calendar functionality for resolution 320*568
> Ravinder | Validation is not working as expected for 'day to up today' field in calendar functionality for resolution 320*568

- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Removed code to toggle week days
> Ravinder | Removed code to toggle week days

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
Ravinder | test - with resolution 800*1024, unable to add entry on PO/PB
> Ravinder | test - with resolution 800*1024, unable to add entry on PO/PB

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
Ravinder | Beta - with resolution 800*1024, unable to add entry on PO/PB
> Ravinder | Beta - with resolution 800*1024, unable to add entry on PO/PB

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1k953j calender issue test

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | resolved issue

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/assets/css/style-1.scss
> Gidk 1k7rjp test

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/settings/permissions/form/form.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | datepicker issue solved

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/assets/css/style-1.scss
> beta-ui-issues

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/assets/css/style-1.scss
> Gidk 1k7rjp beta

- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
Ravinder | Removed sh-select value if manually removed
> Ravinder | Removed sh-select value if manually removed

- apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-receiver-details.component.html
- apps/web-giddh/src/app/inventory/components/custom-stock-components/inventory.customstock.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/modals/template-modal/template-modal.component.html
- apps/web-giddh/src/app/sales/aside-menu-sales-other-taxes/aside-menu-sales-other-taxes.html
- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | PR issue solved

- apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.html
- apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.scss
> import data mobile page

- apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.html
- apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.scss
> import data mobile page beta

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.ts
- apps/web-giddh/src/app/invoice/recurring/recurring.component.ts
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts
- apps/web-giddh/src/app/store/purchase-order/purchase-order.reducer.ts
Worked on saving last state on estimate/proforma/invoice/recurring/pending
> Worked on saving last state on estimate/proforma/invoice/recurring/pending/purchase bill/purchase order

- apps/web-giddh/src/app/all-modules/all-modules.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/locale/accounts/en.json
> Permission isssues, shared ledger issue and universal today issue fixed

- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.ts
Worked on saving last state on search, commented code which was causing issue
> Worked on saving last state on search, commented code which was causing issue

- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
Ravinder | Fixed date comparision issue
> Ravinder | Fixed date comparision issue

- apps/web-giddh/src/app/settings/warehouse/action/warehouse.action.ts
- apps/web-giddh/src/app/settings/warehouse/reducer/warehouse.reducer.ts
- apps/web-giddh/src/app/welcome/welcome.component.html
- apps/web-giddh/src/app/welcome/welcome.component.ts
> fix: GIDK-1760 | Prateek | Beta | Warehouse issue on beta

- angular.json
> fix: index.html replacement changes

- apps/web-giddh/src/index.prod.html
> fix: Typography issue

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
> resolved header conflict

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/login/token-verify.component.ts
- apps/web-giddh/src/app/services/general.service.ts
Ravinder | Auto login with giddh.com/login when session exists for the user
> Ravinder | Auto login with giddh.com/login when session exists for the user

- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/app/settings/create-address/create-address.component.scss
- apps/web-giddh/src/app/settings/profile/setting.profile.component.scss
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> shalinee | UI fixes of architecture

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
> resovled conflict

- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> beta issue solved

- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
> shalinee | correct placeholder

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | resolved and cherry-pick

- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
> Rohit | Today issue resolved for universal date design

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
- apps/web-giddh/src/app/models/api-models/Account.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
> Update account discount and tax issue resolbved

- apps/web-giddh/src/app/shared/header/header.component.ts
> Universal today implemented

- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.html
- apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.scss
- apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.scss
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.ts
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/services/expences.service.ts
- package.json
Ravinder | Worked on saving last state on Petty cash, reverse charge, fixed customer search issue
> Ravinder | Worked on saving last state on Petty cash, reverse charge, fixed customer search issue

- apps/web-giddh/src/app/ledger/ledger.component.ts
Ravinder | While applying universal date on a ledger, it is applying the wrong date period on the ledger
> Ravinder | While applying universal date on a ledger, it is applying the wrong date period on the ledger

- apps/web-giddh/src/index.prod.html
Ravinder | Fixed Pay Issue on subscription page
> Ravinder | Fixed Pay Issue on subscription page

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts
Ravinder | Prod - After login giddh is not working properly, not showing anything
> Ravinder | Prod - After login giddh is not working properly, not showing anything

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
Ravinder | Added other tax calculation method in Request
> Ravinder | Added other tax calculation method in Request

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
Ravinder | Fixed search field issue on preview page
> Ravinder | Fixed search field issue on preview page

- apps/web-giddh/src/index.cordova.local.html
- apps/web-giddh/src/index.cordova.prod.html
- apps/web-giddh/src/index.cordova.stage.html
- apps/web-giddh/src/index.dev.html
- apps/web-giddh/src/index.electron.prod.html
- apps/web-giddh/src/index.html
- apps/web-giddh/src/index.local.html
- apps/web-giddh/src/index.prod.html
- apps/web-giddh/src/index.stage.html
- apps/web-giddh/src/index.test.html
Ravinder | Updated index.html for all ENV
> Ravinder | Updated index.html for all ENV

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts
Ravinder | Fixed calculation formula for other tax
> Ravinder | Fixed calculation formula for other tax

- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test UI issue solved

- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.ts
- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.scss
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | resolved confict and cherry-pick

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
> fix: PO issue

- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/services/authentication.service.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.ts
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
> Discount E-waybill and mac version issue resolved

- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/services/authentication.service.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.ts
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
> Rohit | beta-Discount E-waybill and mac version issue resolved #6152

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> fix: Select tab issue in setting integration

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Ravinder | Fixed condition which was resetting the calculation method
> Ravinder | Fixed condition which was resetting the calculation method

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.ts
Ravinder | Fixed Sort/Search issue on Dr/Cr
> Ravinder | Fixed Sort/Search issue on Dr/Cr

- apps/web-giddh/src/app/models/api-models/Account.ts
- apps/web-giddh/src/app/services/apiurls/group.api.ts
- apps/web-giddh/src/app/services/group.service.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
> custom field story implemented

- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/expenses/expenses.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts
> Merge bug fixes

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> fix: PO issue on PROD

- apps/web-giddh/src/app/expenses/expenses.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
Ravinder | Test/Beta>Inventory/Report>Date Sorting changed when user changed the Sorting option of Total amount
> Ravinder | Test/Beta>Inventory/Report>Date Sorting changed when user changed the Sorting option of Total amount

- apps/web-giddh/src/assets/css/style-2.scss
> Fix: Stage issue

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
Ravinder | Fixed Tcs tds issue in invoice other tax
> Ravinder | Fixed Tcs tds issue in invoice other tax

- apps/web-giddh/src/app/sales/aside-menu-sales-other-taxes/aside-menu-sales-other-taxes.ts
Fixed other tax popup value reset issue from ledger
> Fixed other tax popup value reset issue from ledger

- apps/web-giddh/src/app/contact/contact.component.ts
Ravinder | Test>Search and check box selected option removed when Make the Payment in Vendor Page.
> Ravinder | Test>Search and check box selected option removed when Make the Payment in Vendor Page.

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
Updated Condition for tax only transactions
> Updated Condition for tax only transactions

- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | resolved confict

- apps/web-giddh/src/app/ledger/ledger.component.ts
> fix: Hide space when ledger is reset

- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | scroll and dropdwon address issue fixed

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
> Gidk 1kf9f0 architecure

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.scss
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.scss
- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1b74u6 intercom prod

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.scss
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.scss
- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1b74u6 intercom beta

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> fix: move popover outside, nullity issues

- apps/web-giddh/src/assets/locale/invoice/ewaybill/en.json
- apps/web-giddh/src/assets/locale/invoice/ewaybill/hi.json
> fix: Add eway bill JSON

- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.scss
> branch and warehouse button

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
> responsive changes of architecture

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
> customer /vendor added new fields for custom field

- apps/giddh-cordova/giddh/config.xml
> Fixed mobile plugin versions

- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | resolved

- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | resolve UI issue

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.scss
> increase height of blank div of ledger

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.scss
> shalinee | increase height of blank div of ledger

- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
Prod - when PO is expired then cancel PO option is not getting display on PO preview >change status dropdown
> Prod - when PO is expired then cancel PO option is not getting display on PO preview >change status dropdown

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.scss
> shalinee | increase height

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
Fixed other tax calculation issue on ledger
> Fixed other tax calculation issue on ledger

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Fixed Deliver to address not prefill issue
> Fixed Deliver to address not prefill issue

- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
Fixed search reset issue after sorting
> Fixed search reset issue after sorting

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
Prod - Two same download icon is coming when user update the PB by removing attachment and invoice download POP is opening
> Prod - Two same download icon is coming when user update the PB by removing attachment and invoice download POP is opening

- apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.html
> shalinee | correct - hamburger menu name

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Fixed bug where taxes were removing total
> Fixed bug where taxes were removing

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | custom field overlap, vat report alignment

- apps/web-giddh/src/app/audit-logs/components/audit-logs-table/audit-logs-table.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
> Discount on ledger calculation issue fixed

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | correct master Tab design

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Prod - while recording a purchase bill it is not fetching the address of the company in deliver to
> Prod - while recording a purchase bill it is not fetching the address of the company in deliver to

- apps/web-giddh/src/app/settings/permissions/form/form.component.html
- apps/web-giddh/src/app/settings/permissions/form/form.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
> create custom permission button hide in case of super admin company

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Test - while recording a purchase bill it is not fetching the address of the company in deliver to
> Test - while recording a purchase bill it is not fetching the address of the company in deliver to

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Stage - while recording a purchase bill it is not fetching the address of the company in deliver to
> Stage - while recording a purchase bill it is not fetching the address of the company in deliver to

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
> custom field validation toaster added

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | correct UI of menu icon on tabs pages

- apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
> test | GIDK-1naka2 | Aditi | ui issues

- apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
> beta | GIDK-1naka2 | Aditi | ui issues

- apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
> stage | GIDK-1naka2 | Aditi | ui issues

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: Transaction total not getting updated in UDPATE PB

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
> shalinee | correct ledger alignment

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/all-modules/all-modules.component.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
> fix: Prateek | Stage | Issues: GIDK-1857, GIDK-1870, GIDK-1869, GIDK-1846, GIDK-1827

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
> fix: Prateek | Test | Issues: GIDK-1857, GIDK-1870, GIDK-1869, GIDK-1846, GIDK-1827

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
> fix: Prateek | Archv2 | Issues: GIDK-1857, GIDK-1870, GIDK-1869, GIDK-1846, GIDK-1827

- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
> fix: Remove mandatory address check for GULF countries

- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
> fix: Prateek | Stage | Remove mandatory address check for GULF countries

- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
> fix: Prateek | Test | Remove mandatory address check for GULF countries

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> feat: Prateek | Test | Need to enable the 'Generate Sales' and 'Generate Sales & Update A/C' buttons should be enabled when the user fills in details

- apps/web-giddh/src/app/ledger/ledger.component.html
> feat: GIDK-1281 Prod - Opening balance is not displaying on the ledger

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/inventory/inventory.component.html
- apps/web-giddh/src/app/invoice/invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/sales-register-component/sales.register.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.html
> shalinee | added ID on tabs/dropdown and breadcrumb

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
Renamed purchaseorder.pdf to purchasebill.pdf
> Renamed purchaseorder.pdf to purchasebill.pdf

- apps/web-giddh/src/assets/css/toastr.css
> shalinee | TEST | toaster text aligned

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/models/api-models/BranchTransfer.ts
- apps/web-giddh/src/app/models/interfaces/invoice.setting.interface.ts
- apps/web-giddh/src/app/models/interfaces/nameUniqueName.interface.ts
- apps/web-giddh/src/app/settings/constants/settings.constant.ts
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
- apps/web-giddh/src/app/store/Settings/Settings.reducer.ts
> fix: Prateek | Stage | Merge Architecture v1 to Stage

- apps/web-giddh/src/app/app.component.html
- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
Called increment-session API only if session is close to expiry
> Called increment-session API only if session is close to expiry

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/overview/overview.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/overview.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/overview/summary/summary.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.ts
> feat: GIDK-1593 | Prateek | Test | Show HSN summary page when clicked on in GSTR1

- apps/web-giddh/src/app/home/components/revenue/revenue-chart.component.html
- apps/web-giddh/src/app/home/components/revenue/revenue-chart.component.ts
Integrated new parameter from API.
> Integrated new parameter from API.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: GIDK-1648 | Prateek | Test | Invoice selected in CN/DN not retained for windows system

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: GIDK-1648 | Prateek | Stage | Invoice selected in CN/DN not retained for windows system

- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/assets/locale/gst/en.json
- apps/web-giddh/src/assets/locale/gst/hi.json
- apps/web-giddh/src/assets/locale/vat-report/en.json
- apps/web-giddh/src/assets/locale/vat-report/hi.json
> Architecture v1 to v2

- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
- apps/web-giddh/src/app/invoice/recurring/recurring.component.scss
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/app/settings/profile/setting.profile.component.scss
- apps/web-giddh/src/app/settings/settings.component.scss
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.scss
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | menu icon align issue on ipad

- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/assets/locale/gst/en.json
- apps/web-giddh/src/assets/locale/gst/hi.json
- apps/web-giddh/src/assets/locale/vat-report/en.json
- apps/web-giddh/src/assets/locale/vat-report/hi.json
> feat: Prateek | Stage | Change addition of tax message for VAT and GST report

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> feat: Prateek | Stage | Need to enable the 'Generate Sales' and 'Generate Sales & Update A/C' buttons should be enabled when the user fills in details

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> feat: Prateek | Beta | Need to enable the 'Generate Sales' and 'Generate Sales & Update A/C' buttons should be enabled when the user fills in details

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.css
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.ts
> feat: Prateek | Test | Add back button to HSN summary page in GSTR1

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/assets/css/toastr.css
> Gidk cherry pick prod commit

- apps/web-giddh/src/app/ledger/ledger.component.html
> shalinee | set width of ledger TH

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> feat: Remove popover from all the addresses dropdowns

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> feat: GIDK-1873 | Prateek | Test | Remove popover from all the addresses dropdowns

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> feat: GIDK-1873 | Prateek | Stage | Remove popover from all the addresses dropdowns

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> feat: Prateek | Prod | Need to enable the 'Generate Sales' and 'Generate Sales & Update A/C' buttons should be enabled when the user fills in details

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts
> Ledger create account tabset Issue resolved

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/overview/overview.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/overview.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/overview/summary/summary.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.css
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.ts
> feat: GIDK-1593 | Prateek | Stage | Show HSN summary page when clicked on in GSTR1

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/overview/overview.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/overview.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/overview/summary/summary.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.css
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.ts
> feat: GIDK-1593 | Prateek | Beta | Show HSN summary page when clicked on in GSTR1

- apps/web-giddh/src/app/app.module.ts
- package.json
Added strategy for quick loading of modules
> Added strategy for quick loading of modules

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/overview/overview.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/overview.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/overview/summary/summary.component.ts
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.css
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/push-to-gstin.component.ts
> feat: GIDK-1593 | Prateek | Prod | Show HSN summary page when clicked on in GSTR1

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> build issue resolved

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
> fix: Prateek | Prod | GIDK-1836 | Generate button not getting enabled without outside click

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
> fix: GIDK-1836 | Prateek | Stage | Generate button not getting enabled without outside click

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
> fix: GIDK-1836 | Prateek | Beta | Generate button not getting enabled without outside click

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> shalinee | stage | fixed  dropdown issue

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> shalinee | beta | fixed  dropdown issue

- apps/web-giddh/src/app/ledger/ledger.component.scss
> Gidk 1n93z7 ledger beta

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: GIDK-1085 | Prateek | Test | Issues related to generate voucher in adjustment and linking

- apps/web-giddh/src/app/ledger/ledger.component.scss
> Gidk 1n93z7 ledger test

- apps/web-giddh/src/app/ledger/ledger.component.scss
> Gidk 1n93z7 ledger stage

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: GIDK-1085 | Prateek | Stage | Issues related to generate voucher in adjustment and linking

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: GIDK-1085 | Prateek | Beta | Issues related to generate voucher in adjustment and linking

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1kdnwa test

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
> shalinee | UI issue fixed

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: GIDK-1085 | Prateek | Prod | Issues related to generate voucher in adjustment and linking

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
> shalinee | prod | fixed  dropdown issue

- apps/web-giddh/src/app/ledger/ledger.component.scss
> shalinee | prod | added width on ellpsis text of ledger

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.html
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts
> fix: Prateek | Test | For resolution Ipad 768*1024,User not able to select other Tax.

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
> fix: Prateek-Shalinee | Stage | Gidk 1hee58 table issue stage

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
> fix: Prateek-Shalinee | Branch | Gidk 1hee58 table issue stage

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
> fix: Prateek-Shalinee | Prod | Gidk 1hee58 table issue stage

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
> shalinee | correct alignment of icon

- apps/web-giddh/src/app/tb-pl-bs/components/export/pl-export-xls.component.ts
> feat: Add branch support to download PL report branchwise

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
> inventory overlapping and send email tooltip

- apps/web-giddh/src/app/actions/company.actions.ts
- apps/web-giddh/src/app/models/api-models/Reports.ts
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.scss
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-table-component/purchase.register.table.component.ts
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.ts
- apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.ts
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.ts
- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/services/receipt.service.ts
- apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
- apps/web-giddh/src/assets/css/style-2.scss
> feat: Add branchwise support to Sales and Purchase register

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
> inventory overlapping and send email tooltip stage

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.html
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts
> fix: Prateek | Stage | For resolution Ipad 768*1024,User not able to select other Tax.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.html
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts
> fix: Prateek | Beta | For resolution Ipad 768*1024,User not able to select other Tax.

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
Stop creation of sundry Creditors for other countries except company's country
> Stop creation of sundry Creditors for other countries except company's country

- apps/web-giddh/src/app/services/receipt.service.ts
> fix: 404 issue in sales/purchase register

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
> prod | GIDK-1naka | Aditi | ui issues fixed

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.html
- apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts
> fix: Prateek | Prod | For resolution Ipad 768*1024,User not able to select other Tax.

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/settings/permissions/form/form.component.html
- apps/web-giddh/src/app/settings/permissions/form/form.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts
> Discount and inventory issues resolved

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
> inventory overlapping and send email tooltip beta

- apps/web-giddh/src/app/actions/aging-report.actions.ts
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.html
- apps/web-giddh/src/app/models/api-models/Search.ts
- apps/web-giddh/src/app/services/agingreporting.service.ts
- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/services/contact.service.ts
- apps/web-giddh/src/app/services/inventory.service.ts
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
> feat: Add branchwise dropdown in inventory report, customer/vendor, aging report

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/models/api-models/DaybookRequest.ts
- apps/web-giddh/src/app/models/api-models/Invoice.ts
- apps/web-giddh/src/app/services/daybook.service.ts
> feat: Add branchwise dropdown to Daybook

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> feat: GIDK#1nfvuc | Prateek | Test | Enable Address field in case of bank account

- apps/web-giddh/src/app/models/api-models/Search.ts
- apps/web-giddh/src/app/models/api-models/Vat.ts
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
- apps/web-giddh/src/app/search/search.component.html
- apps/web-giddh/src/app/search/search.component.ts
- apps/web-giddh/src/app/search/search.module.ts
- apps/web-giddh/src/app/services/group.service.ts
- apps/web-giddh/src/app/services/search.service.ts
- apps/web-giddh/src/app/services/settings.branch.service.ts
- apps/web-giddh/src/app/services/vat.service.ts
- apps/web-giddh/src/app/tallysync/completed/completed.component.html
- apps/web-giddh/src/app/tallysync/completed/completed.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.ts
- apps/web-giddh/src/assets/locale/vat-report/en.json
- apps/web-giddh/src/assets/locale/vat-report/hi.json
> feat: Add branchwise support on VAT, Search Report, Tally Report

- apps/web-giddh/src/app/actions/company-import-export/company-import-export.actions.ts
- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts
- apps/web-giddh/src/app/import-excel/import-report/import-report.component.html
- apps/web-giddh/src/app/models/api-models/Reports.ts
- apps/web-giddh/src/app/models/api-models/ReverseCharge.ts
- apps/web-giddh/src/app/models/api-models/import-excel.ts
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.scss
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.scss
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.scss
- apps/web-giddh/src/app/services/companyImportExportService.ts
- apps/web-giddh/src/app/services/receipt.service.ts
- apps/web-giddh/src/app/services/reversecharge.service.ts
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
> feat: Add branchwise support on Import/Export company JSON, Reverse Charge Report, Receipt report, Previous entry import

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: GIDK-#1q8hjh | Prateek | Prod | Prod - Tax is getting remove from the invoice in the update flow without editing anything in the invoice

- apps/web-giddh/src/app/ledger/ledger.component.html
Test - On ledger when opens side menu of account creation , Esc key is not working properly
> Test - On ledger when opens side menu of account creation , Esc key is not working properly

- apps/web-giddh/src/app/ledger/ledger.component.html
Stage - On ledger when opens side menu of account creation , Esc key is not working properly
> Stage - On ledger when opens side menu of account creation , Esc key is not working properly

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
> call stack loop issue resolveds

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
Test - Default address is not coming on PO and PB create form
> Test - Default address is not coming on PO and PB create form

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
Stage - Default address is not coming on PO and PB create form
> Stage - Default address is not coming on PO and PB create form

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: GIDK-#1q8hjh | Prateek | Beta | Prod - Tax is getting remove from the invoice in the update flow without editing anything in the invoice

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: GIDK-#1q8hjh | Prateek | Prod | Beta - Tax is getting remove from the invoice in the update flow without editing anything in the invoice

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/store/Settings/Settings.reducer.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.ts
> get subscription inprogress loader issue resolved if Permission shared

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | remove menu icon from edit invoice page

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> cherry-pick and issue resolved

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Prod - When user is creating service from invoice shortcut the SAC number is not coming on create invoice page
> Prod - When user is creating service from invoice shortcut the SAC number is not coming on create invoice page

- apps/web-giddh/src/app/actions/general/general.actions.ts
- apps/web-giddh/src/app/import-excel/import-report/import-report.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.scss
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.scss
- apps/web-giddh/src/app/reports/components/report-dashboard/reports.dashboard.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.scss
- apps/web-giddh/src/app/reports/components/sales-register-component/sales.register.component.scss
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.scss
- apps/web-giddh/src/app/settings/settings.component.html
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.html
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | UI corrections

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> correct GSTR tabs

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | UI master issue hot fix

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/Settings/Settings.reducer.ts
> stock sample and permission loader issue resolved

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | added curly braces

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/welcome-inventory/welcome-inventory.component.html
> fix: Prateek | Test | Architecture inventory fixes

- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> Gidk 1q9hx4 alice test

- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> Gidk 1q9hx4 alice stage

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/welcome-inventory/welcome-inventory.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> fix: Prateek | Merge stage with architecture fixes

- apps/web-giddh/src/app/welcome/welcome.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | UI correct align of tags and tax checkbox

- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
> New datepicker implemented in Tb pl

- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.ts
- apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts
> Discount replace digit directive char issue resolved

- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/models/defaultMenus.ts
- apps/web-giddh/src/app/services/apiurls/comapny.api.ts
- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
> feat: Add sidebar API integration for showing menu items according to branch and company

- apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
Test - Unable to update the Apply Tax From date for TCS/TDS taxes
> Test - Unable to update the Apply Tax From date for TCS/TDS taxes

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
> fix: GIDK-#1qbh10 | Prateek | Test | Magic link API correction

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
Updated code to pull GST of warehouse
> Updated code to pull GST of warehouse

- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.scss
> cmd+k scroll issue fixed

- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
Test - When clicks on Invoice>template option from side menu bar then some console error is coming and page is getting blank
> Test - When clicks on Invoice>template option from side menu bar then some console error is coming and page is getting blank

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
> fix: GIDK-#1qbh10 | Prateek | Stage | Magic link API correction

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
> fix: GIDK-#1qbh10 | Prateek | Beta | Magic link API correction

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: GIDK-#1qd5qd | Prateek | Test | Prod - Taxes are not getting display on purchase bill in edit flow

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
> New datepicker implemented on import company daybook modules

- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
Stage - When clicks on Invoice>template option from side menu bar then some console error is coming and page is getting blank
> Stage - When clicks on Invoice>template option from side menu bar then some console error is coming and page is getting blank

- apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
> Tax creation issue

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
> fix: GIDK-#1qbh10 | Prateek | Prod | Magic link API correction

- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
- apps/web-giddh/src/app/welcome/welcome.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | sales invoice balance due position correction

- apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
Stage - Unable to update the Apply Tax From date for TCS/TDS taxes
> Stage - Unable to update the Apply Tax From date for TCS/TDS taxes

- apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
Beta - Unable to update the Apply Tax From date for TCS/TDS taxes
> Beta - Unable to update the Apply Tax From date for TCS/TDS taxes

- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.scss
> beta | GIDK-1kd2j8 | Aditi | cmd+k

- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.scss
> prod | GIDK-1kd2j8 | Aditi | cmd+k all issues

- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/store/Settings/Settings.reducer.ts
> permission issue on buyplan and custom field length val issue resolved

- apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
Prod - Unable to update the Apply Tax From date for TCS/TDS taxes
> Prod - Unable to update the Apply Tax From date for TCS/TDS taxes

- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/models/defaultMenus.ts
- apps/web-giddh/src/app/services/apiurls/comapny.api.ts
- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
> Architecture v2 to Alpha

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Test - Deliver To Address Not coming in 2nd consecutive PB
> Test - Deliver To Address Not coming in 2nd consecutive PB

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Stage - Deliver To Address Not coming in 2nd consecutive PB
> Stage - Deliver To Address Not coming in 2nd consecutive PB

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> Gidk 1qdat0 arch

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> Gidk 1qdat0 arch v1

- apps/web-giddh/src/app/actions/company.actions.ts
- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/models/defaultMenus.ts
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.ts
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
- apps/web-giddh/src/app/services/apiurls/comapny.api.ts
- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/services/daybook.service.ts
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.ts
> Architecture v2

- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
> New datepickr implemented on search module, invoice debit credit advance search

- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> Gidk 1q9hx4 alice archi v1

- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> Gidk 1q9hx4 alice arch v2

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1qe1af electron stage

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Beta - Tax is not updating in the update voucher flow
> Beta - Tax is not updating in the update voucher flow

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Stage - Tax is not updating in the update voucher flow
> Stage - Tax is not updating in the update voucher flow

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1qe1af electron beta

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1qe1af electron prod

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: Prateek | Test | Tax getting duplicated

- cypress/integration/Giddh/02_signup.js
- cypress/integration/Giddh/03_sundryDebtors.js
- cypress/integration/Giddh/04_sundryCreditors.js
- cypress/integration/Giddh/05_globalsearch.js
> fix: Prateek | Test |  Suppress test cases

- cypress/integration/Giddh/01_login.js
- cypress/integration/Giddh/03_sundryDebtors.js
- cypress/integration/Giddh/04_sundryCreditors.js
- cypress/integration/Giddh/05_globalsearch.js
> fix: Suppress test cases

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: GIDK-#1qd5qd | Prateek | Stage | Prod - Taxes are not getting display on purchase bill in edit flow

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: GIDK-#1qd5qd | Prateek | Beta | Prod - Taxes are not getting display on purchase bill in edit flow

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: GIDK-#1qd5qd | Prateek | Prod | Prod - Taxes are not getting display on purchase bill in edit flow

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
Prod - User is unable to add HSN/SAC number in decimal for 10 digits from inventory creation page
> Prod - User is unable to add HSN/SAC number in decimal for 10 digits from inventory creation page

- cypress/integration/Giddh/login.js
> Suppress test cases

- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.scss
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1qe44q datepicker tb stage

- cypress/integration/Giddh/01_login.js
- cypress/integration/Giddh/02_signup.js
- cypress/integration/Giddh/03_sundryDebtors.js
- cypress/integration/Giddh/04_sundryCreditors.js
- cypress/integration/Giddh/05_globalsearch.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/pageObjects/GlobalSearchPage.js
- cypress/support/pageObjects/HeaderPage.js
> +Chirag | fixed TC for cypress

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/onboarding/onboarding.component.ts
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
Test - Change the support number in help section and from onboarding page of giddh
> Test - Change the support number in help section and from onboarding page of giddh

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
> shalinee | chat icon , master padding issue fixed

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
> Gidk 1t7tbn chat icon v2

- apps/web-giddh/src/app/daybook/daybook.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | added padding left 0

- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> Gidk 1t88zt vat report

- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> Gidk 1t88zt vat report beta

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
> shalinee | correct history Icon

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> shalinee | added padding  0 on master

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.html
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
Removed validation from SAC number
> Removed validation from SAC number

- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
On Inventory page, need to show New Transfer button also when stock is selected
> On Inventory page, need to show New Transfer button also when stock is selected

- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
On recurring page remove check box to select any recurring invoice
> On recurring page remove check box to select any recurring invoice

- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.scss
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.scss
> shalinee | correct chat icon position

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
Test - Every time When user clicks on another tab while expanded view it is switching back to collapsed view
> Test - Every time When user clicks on another tab while expanded view it is switching back to collapsed view

- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
> shalinee | added padding on button wrapper

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.scss
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.scss
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.scss
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | Ui design updated

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/onboarding/onboarding.component.ts
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
> Beta - Merging 4 cards

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/onboarding/onboarding.component.ts
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
> Production - Merging 4 cards

- apps/web-giddh/src/app/shared/header/header.component.ts
Removed not required function call
> Removed not required function call

- apps/web-giddh/src/app/contact/contact.component.ts
Mobile app - Slowness issue in mobile app on customer/vendor page
> Mobile app - Slowness issue in mobile app on customer/vendor page

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> fix: Prateek | GIDK-#1katj9 | Test | For partially adjusted invoice, due amount is not correctly displaye, when the Adjustment pop up is opened again

- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
Prod/ test. - On refreshing the buy plan page the system is redirecting to subscription page
> Prod/ test. - On refreshing the buy plan page the system is redirecting to subscription page

- cypress/integration/Giddh/03_sundryDebtors.js
- cypress/integration/Giddh/04_sundryCreditors.js
- cypress/support/commands.js
> +Chirag | fixed failing TC

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.scss
- apps/web-giddh/src/app/shared/aside-menu-recurring-entry/aside.menu.recurringEntry.component.html
> feat: In company mode hide the create/edit button instead of disabling

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.html
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.ts
Test - Fixed Page Tab Change Refresh Issue
> Test - Fixed Page Tab Change Refresh Issue

- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
Fixed address issue on refresh
> Fixed address issue on refresh

- .github/workflows/main.yml
> Create main.yml for tests

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/shared/header/components/group-export-ledger-modal/export-group-ledger.component.ts
Stage - Client is not able to delete the credit note even with admin permission and the credit note is cancelled still it is appearing in GSTR1 report
> Stage - Client is not able to delete the credit note even with admin permission and the credit note is cancelled still it is appearing in GSTR1 report

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1t9jr6 msg icon v2

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/shared/header/components/group-export-ledger-modal/export-group-ledger.component.ts
Beta - Client is not able to delete the credit note even with admin permission and the credit note is cancelled still it is appearing in GSTR1 report
> Beta - Client is not able to delete the credit note even with admin permission and the credit note is cancelled still it is appearing in GSTR1 report

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/shared/header/components/group-export-ledger-modal/export-group-ledger.component.ts
Prod - Client is not able to delete the credit note even with admin permission and the credit note is cancelled still it is appearing in GSTR1 report
> Prod - Client is not able to delete the credit note even with admin permission and the credit note is cancelled still it is appearing in GSTR1 report

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/shared/header/components/group-export-ledger-modal/export-group-ledger.component.ts
Test - Client is not able to delete the credit note even with admin permission and the credit note is cancelled still it is appearing in GSTR1 report
> Test - Client is not able to delete the credit note even with admin permission and the credit note is cancelled still it is appearing in GSTR1 report

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- cypress/integration/Giddh/03_sundryDebtors.js
- cypress/integration/Giddh/04_sundryCreditors.js
- cypress/integration/Giddh/05_globalsearch.js
The entry date should be changed automatically according to the invoice date and also as per the universal date
> The entry date should be changed automatically according to the invoice date and also as per the universal date

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.html
> Reverted HSN/SAC changes

- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
> test | GIDK-1t8wmc | Aditi | ui issues for inventory, checkbox and vendor page

- apps/web-giddh/src/meta/magic.html
> fix: Prateek | Test | Prod - While sharing ledger through magic link the C/F balance is mismatching in actual ledger and shared link

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: Prateek | Test | GIDK-#1tax6x | Handle null balance due value in adjustment

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/actions/common.actions.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.ts
- apps/web-giddh/src/app/store/Common/common.reducer.ts
User is not able to preview the invoice if customer account unique name is changed.
> User is not able to preview the invoice if customer account unique name is changed.

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.ts
Add Id’s on cmd+k menu/hamburger menu
> Add Id’s on cmd+k menu/hamburger menu

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
> fix: Error popup coming on magic link

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> fix: Prateek | GIDK-#1katj9 | Prod | For partially adjusted invoice, due amount is not correctly displaye, when the Adjustment pop up is opened again

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/meta/magic.html
…s mismatching in actual ledger and shared link
> fix: Prateek | Stage | Prod - While sharing ledger through magic link the C/F balance is mismatching in actual ledger and shared link

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/meta/magic.html
> fix: Prateek | Beta | Prod - While sharing ledger through magic link the C/F balance is mismatching in actual ledger and shared link

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/meta/magic.html
> fix: Prateek | Prod | Prod - While sharing ledger through magic link the C/F balance is mismatching in actual ledger and shared link

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/inventory/inventory.component.html
- apps/web-giddh/src/app/invoice/invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/sales-register-component/sales.register.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.html
> Gidk 1nd65d page id stage

- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1b74u6 beta

- apps/web-giddh/src/app/expenses/expenses.component.html
> shalinee | add closing  div

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/models/api-models/Company.ts
- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
> feat: Last state branch wise

- apps/web-giddh/src/app/expenses/expenses.component.html
> added closing div

- cypress/integration/Giddh/04_sundryCreditors.js
> fix: Failing test cases

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | added typography css on style-2

- cypress/integration/Giddh/03_sundryDebtors.js
> Failing test cases

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Fixed invalid due date issue

- apps/web-giddh/src/app/app.module.ts
- package.json
Added strategy for quick loading ka modules
> Added strategy for quick loading ka modules

- apps/web-giddh/src/app/ledger/components/shareLedger/shareLedger.component.ts
- apps/web-giddh/src/app/models/api-models/Ledger.ts
- apps/web-giddh/src/app/services/ledger.service.ts
> fix: Magic link generated for HO or other branches is showing data of all the branches i.e. of Company

- apps/web-giddh/src/app/tb-pl-bs/components/export/data-formatter.class.ts
- apps/web-giddh/src/app/tb-pl-bs/components/export/tb-export-pdf.component.ts
> fix: Distorted total values on large amount in TB PDF

- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | switch branch tooltip design corrected

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-receiver-details.component.ts
- apps/web-giddh/src/app/invoice/invoice.routing.module.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.scss
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
- apps/web-giddh/src/app/magic-link/magic-link.component.ts
- apps/web-giddh/src/app/services/apiurls/bulkvoucherexport.api.ts
- apps/web-giddh/src/app/services/bulkvoucherexport.service.ts
- apps/web-giddh/src/app/services/service.module.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/helpers/customValidationHelper.ts
- apps/web-giddh/src/app/shared/helpers/helperFunctions.ts
Test - Integrate API for providing bulk invoice export support
> Test - Integrate API for providing bulk invoice export support

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> shalinee | UI task cherry-pick

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
> shalinee | beta | conflict resolved

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
> new date picker implemented on inventory modules

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Test - While changing the month in voucher date it is opening the date change confirmation pop
> Test - While changing the month in voucher date it is opening the date change confirmation pop

- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> test | GIDK-1tc599 | Aditi | magic link issue fixed

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | correct UI of bulk export

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Fixed entry date popup check

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- apps/web-giddh/src/app/gst/gstR1/gstR1.component.scss
- apps/web-giddh/src/app/gst/gstR2/gstR2.component.scss
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/helpers/pageTabs.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | UI issue fixes

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- apps/web-giddh/src/app/gst/gstR1/gstR1.component.scss
- apps/web-giddh/src/app/gst/gstR1/gstR1.component.ts
- apps/web-giddh/src/app/gst/gstR2/gstR2.component.scss
- apps/web-giddh/src/app/gst/gstR2/gstR2.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/helpers/pageTabs.ts
- apps/web-giddh/src/assets/css/color.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1t9q4z im stage

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- apps/web-giddh/src/app/gst/gstR1/gstR1.component.scss
- apps/web-giddh/src/app/gst/gstR1/gstR1.component.ts
- apps/web-giddh/src/app/gst/gstR2/gstR2.component.scss
- apps/web-giddh/src/app/gst/gstR2/gstR2.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/helpers/pageTabs.ts
- apps/web-giddh/src/assets/css/color.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1t9q4z im beta

- apps/web-giddh/src/app/actions/company-import-export/company-import-export.actions.ts
- apps/web-giddh/src/app/services/apiurls/company-import-export.api.ts
Prod>User not able export data from from date range 1 Apr 19 - 31 Mar20  in Company All Mobile Shop (Testing).
> Prod>User not able export data from from date range 1 Apr 19 - 31 Mar20  in Company All Mobile Shop (Testing).

- .github/workflows/main.yml
> Update main.yml (Remove TC run on TEST env.)

- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
> daybook advance search datepicker close model issue resolved

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/login/token-verify.component.ts
> fix: GIDK-#1q9gga | Prateek | Test | While login, it is showing error "Missing Auth-Key / Session Id header in request'

- apps/web-giddh/src/app/common/confirmation-modal/confirmation-modal.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
> shalinee | dev | showmore ui and modal ui fixed

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/accounting/tally-service.ts
- apps/web-giddh/src/app/accounting/voucher-grid/voucher-grid.component.ts
- apps/web-giddh/src/app/contact/aside-menu-account/aside.menu.account.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/services/authentication.service.ts
- apps/web-giddh/src/app/services/companyService.service.ts
Please check the exceptions here - https://app.clickup.com/t/1tewhz
> Test - Fixed few exceptions

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- apps/web-giddh/src/app/gst/gstR1/gstR1.component.scss
- apps/web-giddh/src/app/gst/gstR1/gstR1.component.ts
- apps/web-giddh/src/app/gst/gstR2/gstR2.component.scss
- apps/web-giddh/src/app/gst/gstR2/gstR2.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.scss
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.scss
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.html
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/helpers/pageTabs.ts
- apps/web-giddh/src/assets/css/color.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1t9q4z im prod

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.ts
> Added Id's in CMD+K

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/general.service.ts
Stage - While changing the month in voucher date it is opening the date change confirmation pop
> Stage - While changing the month in voucher date it is opening the date change confirmation pop

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.ts
> Stage - Added Id's in CMD+K

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
> Fixed exceptions

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/login/token-verify.component.ts
> fix: GIDK-#1q9gga | Prateek | Prod | While login, it is showing error "Missing Auth-Key / Session Id header in request'

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/login/token-verify.component.ts
> fix: GIDK-#1q9gga | Prateek | Stage | While login, it is showing error "Missing Auth-Key / Session Id header in request'

- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
> shalinee | stage |  correcrt code of report-details

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts
> import export company date issue fixed

- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.ts
Prod - Cmd+k is not working with copy and paste the data
> Prod - Cmd+k is not working with copy and paste the data

- apps/web-giddh/src/app/shared/header/header.component.ts
> Added code

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
Test < Export option is displayed in credit and debit module.
> Test < Export option is displayed in credit and debit module.

- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
> new datepicker implemented on stock inventory

- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.ts
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.ts
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
> new date picker integration code reverted

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/login/token-verify.component.ts
> fix: GIDK-#1q9gga | Prateek | Beta | While login, it is showing error "Missing Auth-Key / Session Id header in request'

- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.ts
> Show warehouse add button in branch mode

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
Test/stage - Expected delivery date is not updating in purchase order page
> Test/stage - Expected delivery date is not updating in purchase order page

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
Test < User is not able to export the bulk invoice within particular date range with few invoice are checked at different date.
> Test < User is not able to export the bulk invoice within particular date range with few invoice are checked at different date.

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/settings/services/settings-utility.service.ts
- apps/web-giddh/src/app/shared/helpers/pageTabs.ts
> fix: Architecture fixes

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
Test - On GSTR1 for B2B invoice pagination and invoices are repeating
> Test - On GSTR1 for B2B invoice pagination and invoices are repeating

- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/services/general.service.ts
> Merge test arch v2

- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/services/general.service.ts
> Merge stage arch v2

- apps/web-giddh/src/app/ledger/ledger.component.html
> fix: Disabled action button for company mode in ledger

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
https://app.clickup.com/t/1v7tfy
> Stage - On GSTR1 for B2B invoice pagination and invoices are repeating

- apps/web-giddh/src/app/shared/header/header.component.ts
> fix: Remove old permission code

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: Prateek | Prod | GIDK-#1tax6x | Handle null balance due value in adjustment

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- cypress/integration/Giddh/01_login.js
- cypress/integration/Giddh/03_sundryDebtors.js
- cypress/integration/Giddh/04_sundryCreditors.js
- cypress/integration/Giddh/05_globalsearch.js
- cypress/integration/Giddh/06_TrailBalanace.js
https://app.clickup.com/t/1v7tfy
> Beta - On GSTR1 for B2B invoice pagination and invoices are repeating

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- cypress/integration/Giddh/01_login.js
- cypress/integration/Giddh/03_sundryDebtors.js
- cypress/integration/Giddh/04_sundryCreditors.js
- cypress/integration/Giddh/05_globalsearch.js
- cypress/integration/Giddh/06_TrailBalanace.js
https://app.clickup.com/t/1v7tfy
> Prod - On GSTR1 for B2B invoice pagination and invoices are repeating

- apps/web-giddh/src/app/audit-logs/audit-logs.component.html
- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
> proforma date issue resolved

- apps/web-giddh/src/app/shared/header/components/group-export-ledger-modal/export-group-ledger.component.html
- apps/web-giddh/src/app/shared/header/components/group-export-ledger-modal/export-group-ledger.component.ts
> implement export account date picker

- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
Test - Cursor should not remove when removing the item from any input field
> Test - Cursor should not remove when removing the item from any input field

- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> double line issue and right border issue fixed

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.scss
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.scss
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.scss
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | correct datepicker UI and cherry-pick from test env

- apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts
https://app.clickup.com/t/1v80md
> fix: Prateek | GIDK-#1v80md | Test | Discount is not working correctly for the specific case

- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss
> Eway bill tab issue resolved

- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
> custom field issue resolved

- apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts
https://app.clickup.com/t/1v80md
> fix: Prateek | GIDK-#1v80md | Prod | Discount is not working correctly for the specific case

- apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts
https://app.clickup.com/t/1v80md
> fix: Prateek | GIDK-#1v80md | Stage | Discount is not working correctly for the specific case

- apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts
https://app.clickup.com/t/1v80md
> fix: Prateek | GIDK-#1v80md | Beta | Discount is not working correctly for the specific case

- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.scss
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> shalinee | TEST | vat report and PO calender issue fixed

- apps/web-giddh/src/app/invoice/invoice.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.ts
- apps/web-giddh/src/app/ledger/components/ledgerAsidePane/component/ledger-aside-pane-account/ledger-aside.pane.account.component.ts
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerDiscount/updateLedgerDiscount.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/login/token-verify.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
> Fixed UI Exceptions

- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.ts
> discount ledger total on change issue resolved

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> fix: Prateek | Stage | Architecture issues

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> fix: Prateek | Test | Architecture issues

- apps/web-giddh/src/app/vat-report/vatReport.component.ts
> Fixed Exception on vat report

- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.scss
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> shalinee | Stage | resolved conflicts

- apps/web-giddh/src/app/welcome/welcome.component.html
- apps/web-giddh/src/app/welcome/welcome.component.ts
There should be a loader while creating the company
> There should be a loader while creating the company

- apps/web-giddh/src/app/purchase/purchase.component.ts
Test - local date picker is not updating as per the universal date picker
> Test - local date picker is not updating as per the universal date picker

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
> test | GIDK-1v9aeg | Aditi | icon svg issue fix

- apps/web-giddh/src/app/userDetails/components/company-details-sidebar/company-details-sidebar.component.html
Prod - Remaining transaction are not showing in the balance column at subscription page
> Prod - Remaining transaction are not showing in the balance column at subscription page

- apps/web-giddh/src/app/login/token-verify.component.ts
https://app.clickup.com/t/1v9c88
It in not ready for prod since it will be tested on prod only.
> Prod - On sign up with google/email id page is keep loading

- apps/web-giddh/src/app/ledger/ledger.component.html
> fix: Prateek | Test | Add missing company icon

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> fix: Prateek | Stage | Add missing company icon

- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
> class name change

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
> initial discount added and change issue resolved for ledger

- apps/web-giddh/src/app/inventory/inventory.component.ts
https://app.clickup.com/t/1v8pgd
> fix: GIDK-#1v8pgd | Prateek | Test | API to save State details is not getting called on Inventory

- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
> Fixed UI Exception

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
Test - Show all the income accounts / all expense accounts in sales and purchase information respectively
> Test - Show all the income accounts / all expense accounts in sales and purchase information respectively

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.html
- apps/web-giddh/src/app/settings/permissions/form/form.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
> delete icon fixed

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.html
- apps/web-giddh/src/app/settings/permissions/form/form.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
> delete icon fixed stage

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.html
- apps/web-giddh/src/app/settings/permissions/form/form.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
> delete icon fixed prod

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
> fix: Prateek | Test | Hide Update button in branch transfer when company mode

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/contact/contact.module.ts
> Test - On customer/vendor page minus sign is displaying with Zero value

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/models/api-models/Account.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
> custom field and taxes issues resolved

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/mobile-home/mobile-search-branch/mobile-search-branch.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/tallysync/completed/completed.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> shalinee | replace HO icon to branch icon

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/mobile-home/mobile-search-branch/mobile-search-branch.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/tallysync/completed/completed.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> shalinee | TEST | resolved conflict

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/mobile-home/mobile-search-branch/mobile-search-branch.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/tallysync/completed/completed.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.html
> shalinee | resolve bart report conflict

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
> Discount api changed issue resolved

- cypress/config/production.json
- cypress/config/test.json
- cypress/integration/Giddh/01_login.js
- cypress/integration/Giddh/02_signup.js
- cypress/integration/Giddh/03_sundryDebtors.js
- cypress/integration/Giddh/04_sundryCreditors.js
- cypress/integration/Giddh/05_globalsearch.js
- cypress/integration/Giddh/06_TrailBalanace.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/pageObjects/CreateNewCompanyPage.js
- cypress/support/pageObjects/GlobalSearchPage.js
- cypress/support/pageObjects/HeaderPage.js
- cypress/support/pageObjects/TrialBalancePage.js
- package.json
> +Chirag | fixed TC for entry and added trial balance

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> test | GIDK-1vbaq3 | Aditi | delivery challan and receipt note ui

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
https://app.clickup.com/t/1kf7n5
https://app.clickup.com/t/1kec9t
> fix: Prateek | Test | GIDK-#1kf7n5, GIDK-#1kec9t, With resolution 375*667, on create address>link entity flickering issue

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
https://app.clickup.com/t/1tb2jv
> fix: GIDK-#1tb2jv | Prateek | Test | Prod>Invoice no is not displayed when user create Sales Entry in Customer Ledger with Voucher Selected.

- apps/web-giddh/src/app/ledger/ledger.vm.ts
https://app.clickup.com/t/1tb2jv
> fix: GIDK-#1tb2jv | Prateek | Test | Prod>Invoice no is not displayed when user create Sales Entry in Customer Ledger with Voucher Selected. 

- cypress.json
- cypress/support/commands.js
> +Chirag | added wait and retry option for fail TC

- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> fix: Show error message

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> stage | GIDK-1vbaq3 | Aditi | delivery challan and receipt note ui

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> beta | GIDK-1vbaq3 | Aditi | delivery challan and receipt note ui

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> prod | GIDK-1vbaq3 | Aditi | delivery challan and receipt note ui

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
> etaxes issue resolved once api add and remove account's taxes

- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.ts
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.ts
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
> electron build issue fix

- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> stage | GIDK-1t8rcy | Aditi | datepicker border

- apps/electron-giddh/src/AppUpdater.ts
- apps/electron-giddh/src/WindowManager.ts
- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/loader/loader.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
> update ledger other tax aside pane issue resolved

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/accounting/tally-service.ts
- apps/web-giddh/src/app/accounting/voucher-grid/voucher-grid.component.ts
- apps/web-giddh/src/app/actions/company-import-export/company-import-export.actions.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/services/apiurls/company-import-export.api.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/helpers/directives/digitsOnly/digitsOnly.directive.ts
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/pl/pl.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.ts
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
- apps/web-giddh/src/app/welcome/welcome.component.ts
https://app.clickup.com/t/1t870y
> Prod>User not able export data from from date range 1 Apr 19 - 31 Mar20 in Company All Mobile Shop (Testing)

- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/1t8pyq
> Stage - Every time When user clicks on another tab while expanded view it is switching back to collapsed view

- .github/workflows/main.yml
- cypress/integration/Giddh/06_TrailBalanace.js
- cypress/support/commands.js
- cypress/support/pageObjects/GlobalSearchPage.js
- cypress/support/pageObjects/HeaderPage.js
- cypress/support/pageObjects/TrialBalancePage.js
> +Chirag | Updated Tc as per production date 25/12/2020

- cypress/integration/Giddh/05_globalsearch.js
- package.json
> +Chirag |removed recorded key and fix fail TC

- .github/workflows/main.yml
- cypress/integration/Giddh/05_globalsearch.js
- package.json
> +Chirag | Fixed TC and removed recording 

- cypress/integration/Giddh/01_login.js
- cypress/integration/Giddh/05_globalsearch.js
> +Chirag | fixed fail TC and uncommented TC

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
https://app.clickup.com/t/1v9ryf
> Stage - Show all the income accounts / all expense accounts in sales and purchase information respectively

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
https://app.clickup.com/t/1v9ryf
> Beta - Show all the income accounts / all expense accounts in sales and purchase information respectively

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
https://app.clickup.com/t/1v9ryf
> Prod - Show all the income accounts / all expense accounts in sales and purchase information respectively

- cypress/integration/Giddh/05_globalsearch.js
> +Chirag | fixed globalsearch.js file syntax error

- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/assets/css/style-2.scss
- cypress/integration/Giddh/05_globalsearch.js
> beta | GIDK-1t8rcy | Aditi | datepicker border

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
Stage sanity - Invoice date is getting change with current date when use is copying the data
> Stage sanity - Invoice date is getting change with current date when use is copying the data

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
https://app.clickup.com/t/1kf7n5
https://app.clickup.com/t/1kec9t
> fix: Prateek | Stage | GIDK-#1kf7n5, GIDK-#1kec9t, With resolution 375*667, on create address>link entity flickering issue

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1vdgz3
> fix: GIDK-#1vdgz3 | Prateek | Test | Prod sanity - Not able to create PB when clicking on save button

- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> prod | GIDK-1t8rcy | Aditi | datepicker border

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/services/sales.service.ts
> fix: Prateek | Test | Replace flatten-accounts API call with lighter API brief-accounts

- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.ts
Test - if user is on choose plan page and he clicks on subscription tab, it should move to subscription details page
> Test - if user is on choose plan page and he clicks on subscription tab, it should move to subscription details page

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
Test - on create entry other taxes are getting remove when user clicks outside
> Test - on create entry other taxes are getting remove when user clicks outside

- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss
Test - When user click on the link twice, email verified message should be displayed.
> Test - When user click on the link twice, email verified message should be displayed.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1vdgz3
> fix: GIDK-#1vdgz3 | Prateek | Beta | Prod sanity - Not able to create PB when clicking on save button

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1vdgz3
> fix: GIDK-#1vdgz3 | Prateek | Stage | Prod sanity - Not able to create PB when clicking on save button

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1vdgz3
> fix: GIDK-#1vdgz3 | Prateek | Prod | Prod sanity - Not able to create PB when clicking on save button

- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> Fixed Code issue

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
> fix: Replace flatten-accounts API call with lighter API brief-accounts in invoice

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
Test - Hide amazon integration feature from prod
> Test - Hide amazon integration feature from prod

- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
> test | GIDK-1vdmue | Aditi | dropdown flickering issue

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
> test | GIDK-1vay1t | Aditi | Alignment issue of amount field

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/services/sales.service.ts
https://app.clickup.com/t/1vfyv9
> fix: Prateek | Beta | Replace flatten-accounts API call with lighter API brief-accounts

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/services/sales.service.ts
https://app.clickup.com/t/1vfyv9
> fix: Prateek | Stage | Replace flatten-accounts API call with lighter API brief-accounts

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/services/sales.service.ts
https://app.clickup.com/t/1vfyv9
> fix: Prateek | Prod | Replace flatten-accounts API call with lighter API brief-accounts

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
https://app.clickup.com/t/1ve39f
https://app.clickup.com/t/1x7wxb
> Merging 2 cards

- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss
> shalinee | TEST | correct UI of Purchase and invoice setting module

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/models/api-models/BranchTransfer.ts
- apps/web-giddh/src/app/models/interfaces/nameUniqueName.interface.ts
https://app.clickup.com/t/1vbrhu
> feat: Gidk #1vbrhu | Prateek | Test | Allow branch transfer only when either the sender/receiver branches have same GSTIN or doesn't have any GSTIN

- cypress/integration/Giddh/06_TrailBalanace.js
- cypress/support/commands.js
- cypress/support/pageObjects/MainPage.js
- cypress/support/pageObjects/PLAndBSPage.js
- cypress/support/pageObjects/TrialBalancePage.js
> +Chirag | added TC  for TB and P&L and BS

- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
> stage | GIDK-1vdmue | Aditi | dropdown flickering issue

- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
> prod | GIDK-1vdmue | Aditi | dropdown flickering issue

- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
> beta | GIDK-1vdmue | Aditi | dropdown flickering issue

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.ts
> fix: Stage sanity bug fixes

- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
> fix: On changing the page , branch switcher pop up is not closing

- .github/workflows/main.yml
> Update main.yml: Add parallelization containers for Cypress

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
> fix: Warehouse getting reset in update deliverly/receipt note, add clear filter button

- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.html
- apps/web-giddh/src/app/welcome/welcome.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> test | GIDK-1ve3ez | GIDK-1vd0t9 | GIDK-1tfq0z | Aditi | ui issues

- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.scss
- apps/web-giddh/src/app/reports/components/report-dashboard/reports.dashboard.component.html
> test | GIDK-1tfrcu | Aditi | Alignment issue in discount dropdown

- apps/web-giddh/src/assets/css/style-2.scss
> stage | GIDK-1vd0t9 | Aditi | dashboard circle

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.scss
- apps/web-giddh/src/app/proforma-invoice/components/proforma-last-invoices/proforma-last-invoices.component.scss
https://app.clickup.com/t/1v7rj8
> test | GIDK-1v7rj8 | Aditi | architecture stage sanity

- apps/web-giddh/src/assets/css/style-2.scss
> beta | GIDK-1vd0t9 | Aditi | dashboard circle

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/models/api-models/Search.ts
- apps/web-giddh/src/app/services/apiurls/comapny.api.ts
- apps/web-giddh/src/app/services/companyService.service.ts
Test - On vendor page, the opening balance is not getting consider in total due amount.
> Test - On vendor page, the opening balance is not getting consider in total due amount.

- apps/web-giddh/src/app/theme/command-k/command.k.component.ts
Stage sanity - Scroll is not working if using arrow key on cmd+k
> Stage sanity - Scroll is not working if using arrow key on cmd+k

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss
- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
- apps/web-giddh/src/app/invoice/recurring/recurring.component.scss
- apps/web-giddh/src/app/settings/discount/discount.component.html
- apps/web-giddh/src/app/settings/discount/discount.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> shalinee | stage | resolved conflict

- apps/web-giddh/src/app/common/confirmation-modal/confirmation-modal.component.scss
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerDiscount/updateLedgerDiscount.component.html
> shalinee | TEST | reverse charg flickring issue fixed on ledger

- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
Test - Search result is not highlighted in blue color in master
> Test - Search result is not highlighted in blue color in master

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
Test - Stop creation of sundry Creditors for other countries except company's country
> Test - Stop creation of sundry Creditors for other countries except company's country

- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss
- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.ts
https://app.clickup.com/t/1vfh80
https://app.clickup.com/t/1v7pyg
> Stage - When user click on the link twice, email verified message should be displayed.

- apps/web-giddh/src/app/ledger/ledger.component.ts
Always call Yodlee API without checking Yodlee parameter in api call
> Always call Yodlee API without checking Yodlee parameter in api call

- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss
- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.ts
https://app.clickup.com/t/1vfh80
https://app.clickup.com/t/1v7pyg
> Beta - When user click on the link twice, email verified message should be displayed

- .github/workflows/main.yml
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#6891
> Revert "Update main.yml: Add parallelization containers for Cypress"

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/1xbd4v
> Stage - Always call Yodlee API without checking Yodlee parameter in api call

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | resolved conflicts

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1vcmf6
> fix: GIDK-#1vcmf6 | Prateek | Test | Fixes related to stock rate and reverting 16 digit changes

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | correct height css of customer page

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/1xbd4v
> Beta - Always call Yodlee API without checking Yodlee parameter in api call

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/1xbd4v
> Prod - Always call Yodlee API without checking Yodlee parameter in api call

- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 1vd0t9 chart test

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
https://app.clickup.com/t/1xbq8g
> fix: GIDK-#1xbq8g | Prateek | Beta | Reverse charge data is not going on GSTR 3B when PB is created from ledger

- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss
- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.ts
https://app.clickup.com/t/1vfh80
https://app.clickup.com/t/1v7pyg
> Prod - When user click on the link twice, email verified message should be displayed

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | resolved css conflict

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.ts
https://app.clickup.com/t/1vdubj
https://app.clickup.com/t/1vcfkk
https://app.clickup.com/t/1nfx5y
> Prod - Scroll is not working if using arrow key on cmd+k

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.ts
https://app.clickup.com/t/1vdubj
https://app.clickup.com/t/1vcfkk
https://app.clickup.com/t/1nfx5y
> Beta - Scroll is not working if using arrow key on cmd+k

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
https://app.clickup.com/t/1vdrj5
> fix: GIDK-#1vdrj5 | Prateek | TEST | In Delivery Challan and Receipt Note, in case of a single warehouse, in warehouse dropdown is getting displayed

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Test - In vouchers when account country is different it is showing states of different country
> Test - In vouchers when account country is different it is showing states of different country

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
Test - While creating PB and linking PO then entry date is getting change with PO date
> Test - While creating PB and linking PO then entry date is getting change with PO date

- cypress/support/commands.js
- cypress/support/pageObjects/GlobalSearchPage.js
> +Chirag | added wait to fix the flaky TC

- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
Test - RCM checkbox issue and advance search amount exclude issue
> Test - RCM checkbox issue and advance search amount exclude issue

- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/1vd8xz
> fix: GIDK-#1vd8xz | Prateek | Test | Windows/Mac Electron - From back button on setting page system is redirecting us on Dashboard

- apps/web-giddh/src/assets/css/style-2.scss
> prod | GIDK-1vd0t9 | Aditi | dashboard circle

- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/1vd8xz
> fix: GIDK-#1vd8xz | Prateek | Stage | Windows/Mac Electron - From back button on setting page system is redirecting us on Dashboard

- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/1vd8xz
> fix: GIDK-#1vd8xz | Prateek | Beta | Windows/Mac Electron - From back button on setting page system is redirecting us on Dashboard

- .github/workflows/cypress_parallel.yml
- apps/electron-giddh/src/AppUpdater.ts
- apps/electron-giddh/src/WindowManager.ts
- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/loader/loader.component.ts
- apps/web-giddh/src/app/models/api-models/Account.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
- cypress/integration/Giddh/06_TrailBalanace.js
- cypress/support/commands.js
- cypress/support/pageObjects/GlobalSearchPage.js
- cypress/support/pageObjects/LedgerPage.js
- package.json
> Production to Beta

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
> fix: GIDK-#1x87fq | Prateek | Test | User is not able to see vouchers for adjustment

- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.scss
- apps/web-giddh/src/app/daybook/daybook.component.ts
> Fixed daybook issues

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/1xe22f
> fix: Gidk-#1xe22f | Prateek | Test | User not able to see the Purchase Bill no as -,

- apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts
https://app.clickup.com/t/1xbng5
> Electron Build < Blank page is displayed when user clicks on any invoice to preview in GST module.

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/1xe22f
> fix: GIDK-#1x87fq | Prateek | Stage | User is not able to see vouchers for adjustment

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/1xe22f
> fix: GIDK-#1x87fq | Prateek | Beta | User is not able to see vouchers for adjustment

- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/1vd8xz
> fix: GIDK-#1vd8xz | Prateek | Prod | Windows/Mac Electron - From back button on setting page system is redirecting us on Dashboard

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/1xe22f
> fix: GIDK-#1x87fq | Prateek | Prod | User is not able to see vouchers for adjustment

- apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts
https://app.clickup.com/t/1xbng5
> Electron Build < Blank page is displayed when user clicks on any invoice to preview in GST module

- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.ts
Test < Clear option is not working as expected for advance search of daybook module.
> Test < Clear option is not working as expected for advance search of daybook module.

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/models/api-models/Search.ts
- apps/web-giddh/src/app/services/apiurls/comapny.api.ts
- apps/web-giddh/src/app/services/companyService.service.ts
https://app.clickup.com/t/1x78tk
> Stage - On vendor page, the opening balance is not getting consider in total due amount.

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/models/api-models/Search.ts
- apps/web-giddh/src/app/services/apiurls/comapny.api.ts
- apps/web-giddh/src/app/services/companyService.service.ts
https://app.clickup.com/t/1x78tk
> Beta - On vendor page, the opening balance is not getting consider in total due amount.

- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
Test - On ledger, advance search for cheque details is not working
> Test - On ledger, advance search for cheque details is not working

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> shalinee | TEST | manufacture entity alinged

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
> shalinee | TEST | correct label spell

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/ledger.vm.ts
https://app.clickup.com/t/1tb2jv
> fix: GIDK-#1tb2jv | Prateek | Stage | Prod>Invoice no is not displayed when user create Sales Entry in Customer Ledger with Voucher Selected. 

- apps/web-giddh/src/app/daybook/daybook.component.ts
Fixed advance search reset issue
> Fixed advance search reset issue

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/models/api-models/Search.ts
- apps/web-giddh/src/app/services/apiurls/comapny.api.ts
- apps/web-giddh/src/app/services/companyService.service.ts
https://app.clickup.com/t/1x78tk
> Prod - On vendor page, the opening balance is not getting consider in total due amount.

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
> shalinee | TEST | correct alignemnt if no branch in company

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> shalinee | prod | resolved conflict

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/models/api-models/Inventory.ts
Test - Tax allotment in Stock Group
> Test - Tax allotment in Stock Group

- apps/web-giddh/src/app/actions/daybook/daybook.actions.ts
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
- apps/web-giddh/src/app/models/api-models/Daybook.ts
- apps/web-giddh/src/app/models/api-models/DaybookRequest.ts
- apps/web-giddh/src/app/services/apiurls/daybook.api.ts
Test - Changed daybook export api and removed export button from advance search popup
> Test - Changed daybook export api and removed export button from advance search popup

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
Multiple GST in Voucher creation
> Test - Multiple GST in Voucher creation

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> shalinee | added clearfix and update css of manufacture

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> shalinee | stage | resovled conflict f manufacture

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/1z8kh7
> Test - For PO TCS calculation on Total value is not working

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xemrd
> Issue if two much data in eledger

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> shalinee | prod | added clearfix and update css of manufacture

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- cypress/integration/Giddh/04_sundryCreditors.js
> shalinee | beta | resolved colflict of manufacturing

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- cypress/integration/Giddh/04_sundryCreditors.js
> fix: Not able to update petty cash entry

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
> feat: GIDK-#1xfvvc | Prateek | Test | Add loader when inventory report is in progress
