- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
> feat: GIDK-#1xfvvc | Prateek | Test | Add loader in branch transfer report

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
> feat: GIDK-#1xfvvc | Prateek | Stage | Add loader when inventory report is in progress

- apps/web-giddh/src/app/models/api-models/DaybookRequest.ts
https://app.clickup.com/t/1z8uzu
> Test - When user clicks on 'Today' latest 100 transactions should be displayed irrespective of date range

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
> feat: GIDK-#1xfvvc | Prateek | Prod | Add loader when inventory report is in progress

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
> feat: GIDK-#1xfvvc | Prateek | Beta | Add loader when inventory report is in progress

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
https://app.clickup.com/t/1z95w8
> Test - TCS calculation on total amouount is not displayed when CESS applied

- apps/web-giddh/src/app/daybook/daybook.component.html
https://app.clickup.com/t/1za26m
> Test - Export button will be disabled when there is no transaction present within selected date range

- apps/web-giddh/src/app/models/api-models/DaybookRequest.ts
https://app.clickup.com/t/1z8uzu
> Reverting the code and will show 50 per page

- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> Gidk 1x8dv1 magic prod

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
https://app.clickup.com/t/1z8va2
> Test - When user try to edit the created group selected tax is not visible.

- apps/web-giddh/src/assets/css/toastr.css
> Gidk 1vcwu9 beta v2

- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/assets/css/toastr.css
> shalinee | TEST | correct width of import and toaster message font fixed

- apps/web-giddh/src/assets/css/toastr.css
> shalinee | stage | toaster font fixed

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
- apps/web-giddh/src/app/services/apiurls/ledger.api.ts
- apps/web-giddh/src/app/services/ledger.service.ts
https://app.clickup.com/t/1xemrd
> Test - Added pagination in bank transactions data on ledger

- apps/web-giddh/src/assets/css/toastr.css
> shalinee | prod | correct toaster error font

- apps/web-giddh/src/app/new-inventory/component/about-product-service-detail/about-product-service-detail.component.html
- apps/web-giddh/src/app/new-inventory/component/adjust-group/adjust-group.component.html
- apps/web-giddh/src/app/new-inventory/component/adjust-inventory-aside/adjust-inventory-aside.component.ts
- apps/web-giddh/src/app/new-inventory/component/adjust-product-service/adjust-product-service.component.html
- apps/web-giddh/src/app/new-inventory/component/create-combo/create-combo.component.html
- apps/web-giddh/src/app/new-inventory/component/create-combo/create-combo.component.ts
- apps/web-giddh/src/app/new-inventory/component/create-new-group/create-new-group.component.html
- apps/web-giddh/src/app/new-inventory/component/create-new-group/create-new-group.component.ts
- apps/web-giddh/src/app/new-inventory/component/create-new-inventory-aside-pane/create-new-inventory-aside.component.ts
- apps/web-giddh/src/app/new-inventory/component/create-new-inventory-component/create-new-inventory.component.html
- apps/web-giddh/src/app/new-inventory/component/create-new-item/create-new-item.component.html
- apps/web-giddh/src/app/new-inventory/component/create-new-item/create-new-item.component.ts
- apps/web-giddh/src/app/new-inventory/component/create-unit/create-unit.component.html
- apps/web-giddh/src/app/new-inventory/component/create-unit/create-unit.component.ts
- apps/web-giddh/src/app/new-inventory/component/inventory-adjust-bulk-entry/inventory-adjust-bulk-entry.component.html
- apps/web-giddh/src/app/new-inventory/component/inventory-adjustment-aside/inventory-adjustment-aside.component.ts
> shalinee | TEST | PR failed issue fixed

- apps/web-giddh/src/app/new-inventory/component/adjust-group/adjust-group.component.html
- apps/web-giddh/src/app/new-inventory/component/adjust-product-service/adjust-product-service.component.html
- apps/web-giddh/src/app/new-inventory/component/create-combo/create-combo.component.html
- apps/web-giddh/src/app/new-inventory/component/create-new-inventory-component/create-new-inventory.component.html
> shalinee | TEST | PR failed issue solved

- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gst.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.ts
https://app.clickup.com/t/1zb0z8
> Test - In case of single GSTIN/TRN number on GST/VAT report it is not getting auto select

- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.html
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/services/apiurls/group.api.ts
- apps/web-giddh/src/app/services/group.service.ts
> perf: GIDK-d2cfuz | Prateek | Test | Remove flatten accounts, flatten-groups API from ledger advance search component and paginate stocks API

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
https://app.clickup.com/t/1z7hp5
> Import bank statement - date issue

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1z97v0
> Test - on Estimate/Proforma TCS calculation for Total value is not working

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.html
- apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.ts
> perf: Gidk-d2cfuz | Prateek | Test | Add Group API integration in Settings > Trigger

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xeqw3
> Stage - Multiple GST in Voucher creation

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xeqw3
> Prod - Multiple GST in Voucher creation

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xeqw3
> Beta - Multiple GST in Voucher creation

- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xeqw3
> Test - Added css to make link similar

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
https://app.clickup.com/t/1x86cn
> Prod - Balance due of Purchase bill is different from balance of ledger.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
https://app.clickup.com/t/1x86cn
> Beta - Balance due of Purchase bill is different from balance of ledger.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.ts
https://app.clickup.com/t/1x86cn
> Stage - Balance due of Purchase bill is different from balance of ledger.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1zb88j
> fix: GIDK-#1zb88j | Prateek | Test | Prod - When changing the debtor on sales invoice form the entry details is not updating as per new debtor

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
https://app.clickup.com/t/1ng0h7
> fix: Gidk-#1ng0h7 | Prateek | TEST | Prateek | Test - Two cash account are getting display on update ledger

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: Dropdown issue

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/1zdpzn
> Test - Transactions count and number of pages are not getting displayed above the pagination bar

- apps/web-giddh/src/app/contact/aside-menu-account/aside.menu.account.component.ts
- apps/web-giddh/src/app/ledger/components/ledgerAsidePane/component/ledger-aside-pane-account/ledger-aside.pane.account.component.html
- apps/web-giddh/src/app/ledger/components/ledgerAsidePane/component/ledger-aside-pane-account/ledger-aside.pane.account.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/sales/sales-aside-menu-account/sales.aside.menu.account.component.ts
- apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.ts
- apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.html
- apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/theme/ng-select/select-dropdown.component.ts
- apps/web-giddh/src/app/theme/ng-select/select.component.html
- apps/web-giddh/src/app/theme/ng-select/select.component.ts
> perf: GIDK-#d2cfuz | Prateek | Test | Remove flatten API calls from ledger and voucher modules

- apps/web-giddh/src/app/new-inventory/component/create-new-group/create-new-group.component.html
- apps/web-giddh/src/app/new-inventory/component/create-new-group/create-new-group.component.scss
> shalinee | TEST | added CSS of create new item

- apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
- apps/web-giddh/src/app/permissions/components/model/permission.model.component.scss
- apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | correct dropdown icon

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add/company-add.component.html
- apps/web-giddh/src/app/shared/on-boarding/on-boarding.component.html
- apps/web-giddh/src/app/userDetails/components/add-company/add-company.component.html
- apps/web-giddh/src/app/userDetails/components/move-company/move-company.component.html
- apps/web-giddh/src/app/welcome/welcome.component.html
> Stage - Reverted code designing changes

- apps/web-giddh/src/app/actions/daybook/daybook.actions.ts
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.scss
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/models/api-models/Daybook.ts
- apps/web-giddh/src/app/models/api-models/DaybookRequest.ts
- apps/web-giddh/src/app/services/apiurls/daybook.api.ts
https://app.clickup.com/t/1xbf68
> Stage - Daybook

- apps/web-giddh/src/app/contact/aside-menu-account/aside.menu.account.component.html
- apps/web-giddh/src/app/contact/aside-menu-account/aside.menu.account.component.ts
- apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.html
- apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.ts
- apps/web-giddh/src/app/settings/discount/discount.component.html
- apps/web-giddh/src/app/settings/discount/discount.component.ts
> perf: GIDK-#d2cfuz | Prateek | Test | Remove flatten APIs from Columnar Report, JV, Settings > Discount, Customer/Vendor

- apps/web-giddh/src/app/actions/daybook/daybook.actions.ts
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.scss
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/models/api-models/Daybook.ts
- apps/web-giddh/src/app/models/api-models/DaybookRequest.ts
- apps/web-giddh/src/app/services/apiurls/daybook.api.ts
https://app.clickup.com/t/1xbf68
> Beta - Daybook

- apps/web-giddh/src/app/actions/daybook/daybook.actions.ts
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html
- apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.scss
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/models/api-models/Daybook.ts
- apps/web-giddh/src/app/models/api-models/DaybookRequest.ts
- apps/web-giddh/src/app/services/apiurls/daybook.api.ts
https://app.clickup.com/t/1xbf68
> Prod - Daybook

- apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/1zdpzn
> Test - Displayed pagination even if 1 page of data is available

- apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/1za04e
> feat: GIDK-#1za04e | Prateek | Test | Need to show assigned taxes on top of the list in tax dropdown

- apps/web-giddh/src/app/welcome/welcome.component.html
> branch condition change test case run

- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
https://app.clickup.com/t/1qdhqt
> fix: GIDK-#1qdhqt | Prateek | Test | Test - With the invalid mobile number user is able to create new company

- apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
- apps/web-giddh/src/app/permissions/components/model/permission.model.component.scss
- apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | stage | conflict resolved

- apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
- apps/web-giddh/src/app/permissions/components/model/permission.model.component.scss
- apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | beta | resolved conflict

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1zb88j
> fix: GIDK-#1zb88j | Prateek | Stage | Prod - When changing the debtor on sales invoice form the entry details is not updating as per new debtor

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1zb88j
> fix: GIDK-#1zb88j | Prateek | Beta | Prod - When changing the debtor on sales invoice form the entry details is not updating as per new debtor

- apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
- apps/web-giddh/src/app/permissions/components/model/permission.model.component.scss
- apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | Prod | conflict resolved

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
https://app.clickup.com/t/1ng0h7
> fix: Gidk-#1ng0h7 | Prateek | PROD | Prateek | Test - Two cash account are getting display on update ledger

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- cypress/integration/Giddh/06_TrailBalanace.js
https://app.clickup.com/t/1zb88j
> fix: GIDK-#1zb88j | Prateek | Prod | Prod - When changing the debtor on sales invoice form the entry details is not updating as per new debtor

- apps/web-giddh/src/app/proforma-invoice/components/proforma-last-invoices/proforma-last-invoices.component.html
> bracket issue resolved

- apps/web-giddh/src/app/invoice/templates/edit-template/modals/template-modal/template-modal.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
> width 100 issue stage

- apps/web-giddh/src/app/all-modules/all-modules.component.html
- apps/web-giddh/src/app/create/components/invoice/templates/letter/letter.template.component.html
- apps/web-giddh/src/app/home/components/live-accounts/live-accounts.component.html
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/app/inventory-in-out/components/sidebar-components/inventory.sidebar.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/custom-stock-components/inventory.customstock.component.html
- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerDiscount/updateLedgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/new-inventory/component/create-unit/create-unit.component.html
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/sales/tax-list/sales.tax.list.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/style-magic.css
> width 100 issue fixed

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/forms/branch-transfer/branch-transfer-note.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
- apps/web-giddh/src/app/login/login.component.html
- apps/web-giddh/src/app/login/login.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
> Stage - Fixed UI exception

- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/217unh
> Test - Getting something went wrong when sharing ledger through magic link

- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- cypress/integration/Giddh/06_TrailBalanace.js
- package.json
> Remove commented code

- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
https://app.clickup.com/t/1qdhqt
> fix: GIDK-#1qdhqt | Prateek | Stage | Test - With the invalid mobile number user is able to create new company

- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
https://app.clickup.com/t/1qdhqt
> fix: GIDK-#1qdhqt | Prateek | Beta | Test - With the invalid mobile number user is able to create new company

- apps/web-giddh/src/app/invoice/templates/edit-template/modals/template-modal/template-modal.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> width 100 issue fixed prod

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
https://app.clickup.com/t/218ckk
> fix: GIDK-#218ckk | Prateek | TEST | GST composition not visible

- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/217unh
> Stage - Getting something went wrong when sharing ledger through magic link

- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/217unh
> Prod - Getting something went wrong when sharing ledger through magic link

- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
https://app.clickup.com/t/1qdhqt
> fix: GIDK-#1qdhqt | Prateek | Prod | Test - With the invalid mobile number user is able to create new company

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts
https://app.clickup.com/t/218ckk
> fix: GIDK-#218ckk | Prateek | PROD | GST composition not visible

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/forms/branch-transfer/branch-transfer-note.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
- apps/web-giddh/src/app/login/login.component.html
- apps/web-giddh/src/app/login/login.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
> Prod - Fixed UI Exception

- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/217unh
> Beta - Getting something went wrong when sharing ledger through magic link

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/forms/branch-transfer/branch-transfer-note.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
- apps/web-giddh/src/app/login/login.component.html
- apps/web-giddh/src/app/login/login.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
> Beta - Fixed UI Exceptions

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts
https://app.clickup.com/t/218ckk
> fix: GIDK-#218ckk | Prateek | Beta | GST composition not visible

- apps/web-giddh/src/app/audit-logs/audit-logs.component.ts
- apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.html
- apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.ts
- apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.html
- apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.ts
> perf: GIDK-#d2cfuz | Prateek | Test | Remove flatten APIs from Audit log (old/new)

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/2186e2
> fix: GIDK-#2186e2 | Prateek | Test | Application got hanged when user click on Adjust amount in Invoice module

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/2186e2
> fix: GIDK-#2186e2 | Prateek | Stage | Application got hanged when user click on Adjust amount in Invoice module

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/2186e2
> fix: GIDK-#2186e2 | Prateek | Beta | Application got hanged when user click on Adjust amount in Invoice module

- apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/1za04e
> feat: GIDK-#1za04e | Prateek | Stage | Need to show assigned taxes on top of the list in tax dropdown

- apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/1za04e
> feat: GIDK-#1za04e | Prateek | Beta | Need to show assigned taxes on top of the list in tax dropdown

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
> test | GIDK-218pkv | Aditi | ledger checkbox and download icon fix

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/2186e2
> fix: GIDK-#2186e2 | Prateek | Prod | Application got hanged when user click on Adjust amount in Invoice module

- apps/web-giddh/src/app/ledger/components/updateLedger-tax-control/updateLedger-tax-control.component.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/1za04e
> feat: GIDK-#1za04e | Prateek | Prod | Need to show assigned taxes on top of the list in tax dropdown

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
> beta | GIDK-218pkv | Aditi | ledger checkbox and download icon fix

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
> stage | GIDK-218pkv | Aditi | ledger checkbox and download icon fix

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
> prod | GIDK-218pkv | Aditi | ledger checkbox and download icon fix

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
> fix: Gidk-#218a1q | Prateek | Test | User not able to Reset and Delete the adjustment when click on delete button or click on save button

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
> fix: GIDK-#218a1q | Prateek | Reset button not working

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
> fix: GIDK-#218a1q | Prateek | Test | Form reset issue

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> test | GIDK-218pkv | Aditi | padding margin guideline updated

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
> shalinee | stage | resolve conflict

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
> shalinee | beta  | resolved conflict

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/magic-link/magic-link.component.css
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> stage | GIDK-218pkv | Aditi | padding margin guideline updated

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/magic-link/magic-link.component.css
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> beta | GIDK-218pkv | Aditi | padding margin guideline updated

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
> test | GIDK-1t8q8y | Aditi | faded checkbox

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/magic-link/magic-link.component.css
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> prod | GIDK-218pkv | Aditi | padding margin guideline updated

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
> fix: Gidk-#218a1q | Prateek | Stage | User not able to Reset and Delete the adjustment when click on delete button or click on save button

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
> fix: Gidk-#218a1q | Prateek | Beta | User not able to Reset and Delete the adjustment when click on delete button or click on save button

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
> fix: Gidk-#218a1q | Prateek | Prod | User not able to Reset and Delete the adjustment when click on delete button or click on save button

- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.html
> test | GIDK-1xbw08 | Aditi | scroll issue fixed

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.ts
- apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.ts
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/models/interfaces/dashboard.interface.ts
- apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.ts
- apps/web-giddh/src/app/settings/discount/discount.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.html
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
> perf: GIDK-#d2cfuz | Prateek | Test | Remove flatten api from Settings > Integration, Settings > Linked Accounts, Invoice > Paid

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> Test - Allowed zero amount voucher for all vouchers/ledger entry and from JV

- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
https://app.clickup.com/t/21bwme
> Prod - Due to exception on inventory page, footer details are not coming

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/1t8q8y
> beta | GIDK-1t8q8y | Aditi | faded checkbox

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/1t8q8y
> stage | GIDK-1t8q8y | Aditi | faded checkbox

- apps/web-giddh/src/app/store/General/general.reducer.ts
> Beta - Fixed UI Exception

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/1t8q8y
> prod | GIDK-1t8q8y | Aditi | faded checkbox

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.html
> test | GIDK-1v9aeg | Aditi | refresh icon

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/21cbn9
> Test - Voucher adjustment issue

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
> test | GIDK-21abq1 | Aditi | refresh button

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/audit-logs/audit-logs.component.ts
- apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.html
- apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.ts
- apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.html
- apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.ts
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/models/interfaces/dashboard.interface.ts
- apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.html
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- Audit log (old & new)
- Setting > Integration
- Setting > Linked accounts
- Invoice > Paid
> perf: Gidk-#d2cfuz | Prateek | Stage | CORS policy issue 

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/audit-logs/audit-logs.component.ts
- apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.html
- apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.ts
- apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.html
- apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.ts
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/models/interfaces/dashboard.interface.ts
- apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.html
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- Audit log (old & new)
- Setting > Integration
- Setting > Linked accounts
- Invoice > Paid
> perf: Gidk-#d2cfuz | Prateek | Beta | CORS policy issue 

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/audit-logs/audit-logs.component.ts
- apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.html
- apps/web-giddh/src/app/audit-logs/components/audit-logs-form/audit-logs-form.component.ts
- apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.html
- apps/web-giddh/src/app/audit-logs/components/sidebar-components/audit-logs.sidebar.component.ts
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/models/interfaces/dashboard.interface.ts
- apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.html
- apps/web-giddh/src/app/settings/linked-accounts/setting.linked.accounts.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- Audit log (old & new)
- Setting > Integration
- Setting > Linked accounts
- Invoice > Paid
> perf: Gidk-#d2cfuz | Prateek | Prod | CORS policy issue 

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/21abq1
> beta | GIDK-21abq1 | Aditi | remove button

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/21abq1
> stage | GIDK-21abq1 | Aditi | remove button

- apps/web-giddh/src/app/inventory/inventory.component.ts
https://app.clickup.com/t/21dt6g
> fix: GIDK-#21dt6g | Prateek | Test | Prod - Normal email login with Google login credential is not switching to last visited company

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zccbq
> fix: GIDK-#1zccbq | Prateek | Test | Prod <  Black screen appearing when user is searching for a module using Ctrl+G before loading the desired page.

- apps/web-giddh/src/app/inventory/inventory.component.ts
https://app.clickup.com/t/1v7815
> fix: GIDK-#1v7815 | Prateek | Test | Prod - Warehouse dropdown for branch is blank for first time on Inventory report page

- apps/web-giddh/src/app/import-excel/import-excel.module.ts
- apps/web-giddh/src/app/invoice/download-bulk-invoice/download-bulk-invoice.component.html
- apps/web-giddh/src/app/invoice/download-bulk-invoice/download-bulk-invoice.component.scss
- apps/web-giddh/src/app/invoice/download-bulk-invoice/download-bulk-invoice.component.ts
- apps/web-giddh/src/app/invoice/invoice.module.ts
- apps/web-giddh/src/app/invoice/invoice.routing.module.ts
> Gidk 21e40p html download

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/21ej1r
> fix: GIDK-#21ej1r | Prateek | Test | Save button got disable when User reset the voucher adjustment

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zccbq
> fix: GIDK-#1zccbq | Prateek | Stage | Prod <  Black screen appearing when user is searching for a module using Ctrl+G before loading the desired page.

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zccbq
> fix: GIDK-#1zccbq | Prateek | Beta | Prod <  Black screen appearing when user is searching for a module using Ctrl+G before loading the desired page.

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zccbq
> fix: GIDK-#1zccbq | Prateek | Prod | Prod < Black screen appearing when user is searching for a module using Ctrl+G before loading the desired page.

- apps/web-giddh/src/app/inventory/inventory.component.ts
https://app.clickup.com/t/1v7815
> fix: GIDK-#1v7815 | Prateek | Beta | Prod - Warehouse dropdown for branch is blank for first time on Inventory report page

- apps/web-giddh/src/app/inventory/inventory.component.ts
https://app.clickup.com/t/1v7815
> fix: GIDK-#1v7815 | Prateek | Stage | Prod - Warehouse dropdown for branch is blank for first time on Inventory report page

- apps/web-giddh/src/app/inventory/inventory.component.ts
https://app.clickup.com/t/1v7815
> fix: GIDK-#1v7815 | Prateek | Prod | Prod - Warehouse dropdown for branch is blank for first time on Inventory report page 

- apps/web-giddh/src/app/new-inventory/component/about-product-service-detail/about-product-service-detail.component.html
- apps/web-giddh/src/app/new-inventory/component/about-product-service-detail/about-product-service-detail.component.scss
- apps/web-giddh/src/app/new-inventory/component/create-new-inventory-component/create-new-inventory.component.html
- apps/web-giddh/src/app/new-inventory/component/create-new-inventory-component/create-new-inventory.component.scss
- apps/web-giddh/src/app/new-inventory/component/create-new-inventory-component/create-new-inventory.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 21a7a4 variant addone

- apps/web-giddh/src/app/new-inventory/component/about-product-service-detail/about-product-service-detail.component.html
- apps/web-giddh/src/app/new-inventory/component/about-product-service-detail/about-product-service-detail.component.ts
> shalinee | TEST | remove condition from html

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/models/api-models/Ledger.ts
- apps/web-giddh/src/app/services/apiurls/ledger.api.ts
https://app.clickup.com/t/21dgu8
> Test - Displayed Pending Cheque with new api and new variable

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/21abq1
> prod | GIDK-21abq1 | Aditi | remove button

- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/invoice/create/invoice.create.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.ts
- apps/web-giddh/src/app/welcome/welcome.component.ts
> feat: GIDK-#1zcrr3 | Prateek | Test | Remove Validation from GSTIN number for 'Government Entity' party type in account creation

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/invoice/invoice.component.ts
- apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.ts
https://app.clickup.com/t/21dt6g
> fix: GIDK-#21dt6g | Prateek | Stage | Prod - Normal email login with Google login credential is not switching to last visited company

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/invoice/invoice.component.ts
- apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.ts
https://app.clickup.com/t/21dt6g
> fix: GIDK-#21dt6g | Prateek | Beta | Prod - Normal email login with Google login credential is not switching to last visited company

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/models/api-models/Ledger.ts
- apps/web-giddh/src/app/services/apiurls/ledger.api.ts
https://app.clickup.com/t/21dgu8
> Displayed Pending Cheque with new api and new variable

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/invoice/invoice.component.ts
- apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.ts
https://app.clickup.com/t/21dt6g
> fix: GIDK-#21dt6g | Prateek | Prod | Prod - Normal email login with Google login credential is not switching to last visited company

- apps/web-giddh/src/app/app.routes.ts
- apps/web-giddh/src/app/new-inventory/component/about-product-service-detail/about-product-service-detail.component.html
- apps/web-giddh/src/app/new-inventory/component/create-new-inventory-component/create-new-inventory.component.html
> shalinee | correct recipe design and update app.route file

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/routes-array.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | UI corrections

- cypress/integration/Giddh/06_TrailBalanace.js
- cypress/support/commands.js
- cypress/support/pageObjects/TrialBalancePage.js
- package.json
> +Chirag | fixed cypress version

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/inventory-in-out/components/inventory-in-out-report/inventory-in-out-report.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/edit-template.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/purchase-invoice/purchase.invoice.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html
- apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-magic.css
> test | GIDK-218e46 | Aditi | template full name fixed

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory-in-out/components/inventory-in-out-report/inventory-in-out-report.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/purchase-invoice/purchase.invoice.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html
- apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.html
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-magic.css
https://app.clickup.com/t/1xbw08
> stage | GIDK-1xbw08 | Aditi | scroll issue fixed

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory-in-out/components/inventory-in-out-report/inventory-in-out-report.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/purchase-invoice/purchase.invoice.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html
- apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.html
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-magic.css
https://app.clickup.com/t/1xbw08
> beta | GIDK-1xbw08 | Aditi | scroll issue fixed

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> test | GIDK-1x9nuh | Aditi | scroll bar issue fixed

- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
> shalinee | TEST | remove loader from schedule now calendar

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
> test | GIDK-1x9b10 | Aditi | textarea scroll fixed

- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
> shalinee | stage | remove loader from schedule now calendar

- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
> shalinee | prod | remove loader from schedule now calendar

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory-in-out/components/inventory-in-out-report/inventory-in-out-report.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/purchase-invoice/purchase.invoice.component.html
- apps/web-giddh/src/app/sales/create/sales.invoice.component.html
- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html
- apps/web-giddh/src/app/shared/header/components/accounts-side-bar/accounts-side-bar.component.html
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select-menu.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-magic.css
https://app.clickup.com/t/1xbw08
> prod | GIDK-1xbw08 | Aditi | scroll issue fixed

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-receiver-details.component.ts
- apps/web-giddh/src/app/invoice/invoice.routing.module.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.scss
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
- apps/web-giddh/src/app/magic-link/magic-link.component.ts
- apps/web-giddh/src/app/services/apiurls/bulkvoucherexport.api.ts
- apps/web-giddh/src/app/services/bulkvoucherexport.service.ts
- apps/web-giddh/src/app/services/service.module.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/helpers/customValidationHelper.ts
- apps/web-giddh/src/app/shared/helpers/helperFunctions.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1qfu9h
> Stage - Integrate API for providing bulk invoice export support

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-receiver-details.component.ts
- apps/web-giddh/src/app/invoice/invoice.routing.module.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.scss
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
- apps/web-giddh/src/app/magic-link/magic-link.component.ts
- apps/web-giddh/src/app/services/apiurls/bulkvoucherexport.api.ts
- apps/web-giddh/src/app/services/bulkvoucherexport.service.ts
- apps/web-giddh/src/app/services/service.module.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/helpers/customValidationHelper.ts
- apps/web-giddh/src/app/shared/helpers/helperFunctions.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1qfu9h
> Prod - Integrate API for providing bulk invoice export support

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/inventory/components/aside-sender-receiver-details/aside-sender-receiver-details.component.ts
- apps/web-giddh/src/app/invoice/invoice.routing.module.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.scss
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
- apps/web-giddh/src/app/magic-link/magic-link.component.ts
- apps/web-giddh/src/app/services/apiurls/bulkvoucherexport.api.ts
- apps/web-giddh/src/app/services/bulkvoucherexport.service.ts
- apps/web-giddh/src/app/services/service.module.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/helpers/customValidationHelper.ts
- apps/web-giddh/src/app/shared/helpers/helperFunctions.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1qfu9h
> Beta - Integrate API for providing bulk invoice export support

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/21cbn9
https://app.clickup.com/t/21ej1r
> Stage - Voucher Adjustment Dropdown Autoselect issue

- apps/web-giddh/src/app/actions/general/general.actions.ts
- apps/web-giddh/src/app/models/db/db.ts
- apps/web-giddh/src/app/search/components/search-filter/search-filter.component.html
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.html
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
- apps/web-giddh/src/app/settings/bunch/components-modal/create-bunch/create-bunch.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.ts
- apps/web-giddh/src/app/theme/command-k/command.k.component.ts
> Test - Fixed UI Exceptions

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/21g8pj
> Test - from vouchers flow when user is creating new account then cursor is shifting in background

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/21gd0y
> Test - Zero is not displayed for Amount field on edit credit note page in account currency

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/21cbn9
https://app.clickup.com/t/21ej1r
> Beta - Voucher Adjustment Dropdown Autoselect issue

- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/shared/header/header.component.html
> shalinee | beta | remove loader from schedule now calendar

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/21cbn9
https://app.clickup.com/t/21ej1r
> Prod - Voucher Adjustment Dropdown Autoselect issue

- cypress/integration/Giddh/06_TrailBalanace.js
> +Chirag |  TC's run on beta

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.scss
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> test | GIDK-21d7zd | Aditi | minor ui issues

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
> date-picker-class

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1zd2p5
> fix: Gidk-#1zd2p5 | Prateek | Test | Prod - Getting error 'Amount should not be greater that balance while updating paid invoice

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1zd2p5
> fix: Gidk-#1zd2p5 | Prateek | Beta | Prod - Getting error 'Amount should not be greater that balance while updating paid invoice

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1zd2p5
> fix: Gidk-#1zd2p5 | Prateek | Stage | Prod - Getting error 'Amount should not be greater that balance while updating paid invoice

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
> receipt-note-scroll fixed

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> Test - Hiding elements from Collections tab (Settings> Integration)

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
https://app.clickup.com/t/1x9nuh
> stage | GIDK-1x9nuh | Aditi | scroll bar issue fixed

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
https://app.clickup.com/t/1x9b10
> stage | GIDK-1x9b10 | Aditi | textarea scroll fixed

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
https://app.clickup.com/t/1x9b10
> beta | GIDK-1x9b10 | Aditi | textarea scroll fixed

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
https://app.clickup.com/t/1x9nuh
> beta | GIDK-1x9nuh | Aditi | scroll bar issue fixed

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
https://app.clickup.com/t/1x9nuh
> prod | GIDK-1x9nuh | Aditi | scroll bar issue fixed

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1zd2p5
> fix: Gidk-#1zd2p5 | Prateek | Prod | Prod - Getting error 'Amount should not be greater that balance while updating paid invoice

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.ts
https://app.clickup.com/t/2397nm
> Sales Bifurcation (New vs Old) Changes related to default selection and current year 2021

- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> Test - Removed unused api calls

- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> Stage - Removed unused api calls

- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> Beta - Removed unused api calls

- apps/web-giddh/webpack.electron.prod.partial.js
https://app.clickup.com/t/23de04
> Stage - Electron build < User is not able to export the invoices in electron build

- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> Prod - Removed unused api calls

- apps/web-giddh/src/app/accounting/accounting.component.ts
- apps/web-giddh/src/app/accounting/invoice-grid/invoice-grid.component.html
- apps/web-giddh/src/app/accounting/journal-voucher/invoice/invoice.component.html
- apps/web-giddh/src/app/accounting/journal-voucher/journal-voucher.component.ts
- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html
- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list-menu.component.html
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list-menu.component.ts
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.html
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.ts
- apps/web-giddh/src/app/accounting/tally-service.ts
- apps/web-giddh/src/app/accounting/voucher-grid/voucher-grid.component.html
- apps/web-giddh/src/app/settings/Taxes/setting.taxes.component.ts
- apps/web-giddh/src/app/store/Sales/sales.reducer.ts
> perf: Gidk-#d2cfuz | Prateek | Stage | CORS policy issue

- apps/web-giddh/src/app/accounting/accounting.component.ts
- apps/web-giddh/src/app/accounting/invoice-grid/invoice-grid.component.html
- apps/web-giddh/src/app/accounting/journal-voucher/invoice/invoice.component.html
- apps/web-giddh/src/app/accounting/journal-voucher/journal-voucher.component.ts
- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html
- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list-menu.component.html
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list-menu.component.ts
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.html
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.ts
- apps/web-giddh/src/app/accounting/tally-service.ts
- apps/web-giddh/src/app/accounting/voucher-grid/voucher-grid.component.html
- apps/web-giddh/src/app/settings/Taxes/setting.taxes.component.ts
- apps/web-giddh/src/app/store/Sales/sales.reducer.ts
> perf: Gidk-#d2cfuz | Prateek | Beta | CORS policy issue

- apps/web-giddh/webpack.electron.prod.partial.js
https://app.clickup.com/t/23de04
> Beta - Electron build < User is not able to export the invoices in electron build

- apps/web-giddh/webpack.electron.prod.partial.js
https://app.clickup.com/t/23de04
> Prod - Electron build < User is not able to export the invoices in electron build

- apps/web-giddh/src/app/accounting/accounting.component.ts
- apps/web-giddh/src/app/accounting/invoice-grid/invoice-grid.component.html
- apps/web-giddh/src/app/accounting/journal-voucher/invoice/invoice.component.html
- apps/web-giddh/src/app/accounting/journal-voucher/journal-voucher.component.ts
- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html
- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list-menu.component.html
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list-menu.component.ts
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.html
- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.ts
- apps/web-giddh/src/app/accounting/tally-service.ts
- apps/web-giddh/src/app/accounting/voucher-grid/voucher-grid.component.html
- apps/web-giddh/src/app/settings/Taxes/setting.taxes.component.ts
- apps/web-giddh/src/app/store/Sales/sales.reducer.ts
> perf: Gidk-#d2cfuz | Prateek | PROD | CORS policy issue

- apps/web-giddh/src/app/theme/ng-select/select-dropdown.component.ts
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.ts
> fix: Remove console log

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> test | GIDK-21d7zd | Aditi | setting integration and prod issue of tax

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/23dg6c
> Test - User is not able to adjust more than one invoice with single receipt

- apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.ts
https://app.clickup.com/t/23feyv
> feat: Gidk-23feyv | Prateek | Test | Show default accounts in bulk modal

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/23dg6c
> Stage - User is not able to adjust more than one invoice with single receipt

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/23dg6c
> Prod - User is not able to adjust more than one invoice with single receipt

- apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.ts
https://app.clickup.com/t/23feyv
> feat: Gidk-23feyv | Prateek | Stage | Show default accounts in bulk modal

- apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.ts
https://app.clickup.com/t/23feyv
> feat: Gidk-23feyv | Prateek | Beta | Show default accounts in bulk modal

- apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.ts
https://app.clickup.com/t/23feyv
> feat: Gidk-23feyv | Prateek | Prod | Show default accounts in bulk modal

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.scss
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> stage | GIDK-21d7zd | Aditi | minor ui issues

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/23dg6c
> Beta - User is not able to adjust more than one invoice with single receipt

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.scss
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> beta | GIDK-21d7zd | Aditi | minor ui issues

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
https://app.clickup.com/t/1detn7
> Test - Manufacturing raw details are material details are not getting display in stock details in inventory

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Test - Fixed UI Exception

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.scss
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> prod | GIDK-21d7zd | Aditi | minor ui issues

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/21ac6e
> test | GIDK-21ac6e | Aditi | electron issue of button

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/21ac6e
> beta | GIDK-21ac6e | Aditi | electron issue of button

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/21ac6e
> stage | GIDK-21ac6e | Aditi | electron issue of button

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> shalinee | TEST | makes table correct of manufacturing

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
https://app.clickup.com/t/23cjeg
> Test - Fixed date format and date filter

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
https://app.clickup.com/t/258zef
> Test - Remove "amount upto, Select Otp and Approver name" from integration>payment page

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/21ac6e
> prod | GIDK-21ac6e | Aditi | electron issue of button

- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/shared/helpers/directives/keyboardShortcut/navigationWalker.directive.ts
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.html
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
> fix: GIDK-#23caqm | Prateek | Test | Prod - While adding bulk items from voucher create/update flow UI is getting hanged (Freeze)

- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
https://app.clickup.com/t/258zef
> Test - Fixed submit button disable issue

- apps/web-giddh/src/app/app.constant.ts
https://app.clickup.com/t/259rmz
> Test - Postman documenter url changed

- apps/web-giddh/src/app/app.constant.ts
https://app.clickup.com/t/259rmz
> Stage - Postman documenter url changed

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
> fix: Indexing issue

- apps/web-giddh/src/app/app.constant.ts
https://app.clickup.com/t/259rmz
> Beta - Postman documenter url changed

- apps/web-giddh/src/app/app.constant.ts
https://app.clickup.com/t/259rmz
> Prod - Postman documenter url changed

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
> fix: Remove redundant API call from Petty cash

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
https://app.clickup.com/t/259u07
> Test - On manufacturing page change word "Qty Inward" to "Qty Outward" in search by filter and also pass this in request params

- apps/web-giddh/src/app/app.routes.ts
- apps/web-giddh/src/app/routes-array.ts
https://app.clickup.com/t/23b8qg
> fix: GIDK-#23b8qg | Prateek | Test | Sales Invoice module is displayed in Company view when we switch company

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.ts
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.ts
https://app.clickup.com/t/258gy0
> feat: GIDK-#258gy0 | Prateek | Test | Remove dropdown in branch view from report pages

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> fix: GIDK-#1zcrr3 | Prateek | Test | Issue in Remove Validation from GSTIN number for 'Government Entity' party type in account creation

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
https://app.clickup.com/t/25agu1
> Test - On manufacturing page in company view warehouse should come according to branches.

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> shalinee | TEST | update class and condition on manufacturing

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/models/interfaces/manufacturing.interface.ts
- apps/web-giddh/src/app/models/interfaces/stocksItem.interface.ts
- apps/web-giddh/src/app/services/manufacturing.service.ts
- apps/web-giddh/src/assets/css/color.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/23cjeg
https://app.clickup.com/t/1detn7
https://app.clickup.com/t/21brbd
> Stage - Manufacturing get all page design correction

- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
https://app.clickup.com/t/25b0xz
> Test - From invoice get all page when user is doing payment then payment mode option are not coming in dropdown.

- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
> shalinee | TEST | correct button and table design

- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
https://app.clickup.com/t/25ccx0
> Test - On billing details page, in state dropdown, duplicate entries are getting displayed

- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
https://app.clickup.com/t/25b0xz
> Stage - From invoice get all page when user is doing payment then payment mode option are not coming in dropdown.

- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
https://app.clickup.com/t/25b0xz
> Beta - From invoice get all page when user is doing payment then payment mode option are not coming in dropdown.

- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
https://app.clickup.com/t/25b0xz
> Prod - From invoice get all page when user is doing payment then payment mode option are not coming in dropdown.

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/models/interfaces/manufacturing.interface.ts
- apps/web-giddh/src/app/models/interfaces/stocksItem.interface.ts
- apps/web-giddh/src/app/services/manufacturing.service.ts
- apps/web-giddh/src/assets/css/color.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/23cjeg
https://app.clickup.com/t/1detn7
https://app.clickup.com/t/21brbd
> Beta - Manufacturing get all page design correction

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/models/interfaces/manufacturing.interface.ts
- apps/web-giddh/src/app/models/interfaces/stocksItem.interface.ts
- apps/web-giddh/src/app/services/manufacturing.service.ts
- apps/web-giddh/src/assets/css/color.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/23cjeg
https://app.clickup.com/t/1detn7
https://app.clickup.com/t/21brbd
> Prod - Manufacturing get all page design correction

- apps/web-giddh/src/app/app.routes.ts
- apps/web-giddh/src/app/routes-array.ts
https://app.clickup.com/t/23b8qg
> fix: GIDK-#23b8qg | Prateek | Prod | Sales Invoice module is displayed in Company view when we switch company

- apps/web-giddh/src/app/app.routes.ts
- apps/web-giddh/src/app/routes-array.ts
https://app.clickup.com/t/23b8qg
> fix: GIDK-#23b8qg | Prateek | Stage | Sales Invoice module is displayed in Company view when we switch company

- apps/web-giddh/src/app/app.routes.ts
- apps/web-giddh/src/app/routes-array.ts
https://app.clickup.com/t/23b8qg
> fix: GIDK-#23b8qg | Prateek | Beta | Sales Invoice module is displayed in Company view when we switch company

- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
https://app.clickup.com/t/25dt1w
> Test - Need to update socket url

- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
https://app.clickup.com/t/25dt1w
> Stage - Need to update socket url

- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
https://app.clickup.com/t/25dt1w
> Prod - Need to update socket url

- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
https://app.clickup.com/t/25dt1w
> Beta - Need to update socket url

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
> feat: GIDK-#1zcrr3 | Prateek | Prod | Remove Validation from GSTIN number for 'Government Entity' party type in account creation

- apps/web-giddh/src/app/shared/shared.module.ts
> shalinee | correct currencyModule declaration

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/models/api-models/Inventory.ts
https://app.clickup.com/t/258q5v
https://app.clickup.com/t/257z93
> Test - Fixed Create/Update Stock and Group Bugs

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1vcmy5
> fix: GIDK-#1vcmy5 | Prateek | Test | Test/Stage/Prod>Customer name is not displayed when user click on preview and Generate Debit note

- apps/web-giddh/src/app/actions/company.actions.ts
- apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
> Test < Client created a new company but its navigating to the previously created company

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/models/api-models/Inventory.ts
https://app.clickup.com/t/23d8f3
> Stage - Taxes and Stock Unit issue

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/models/api-models/Inventory.ts
https://app.clickup.com/t/23d8f3
> Prod - Taxes and Stock Unit issue

- apps/web-giddh/src/meta/.htaccess
> fix: Prateek | Test | .htaccess redirect http to https

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/models/api-models/Inventory.ts
https://app.clickup.com/t/23d8f3
> Beta - Taxes and Stock Unit issue

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Stage - Fixed UI Exceptions

- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
https://app.clickup.com/t/25ggyg
> fix: GIDK-#25ggyg | Prateek | Test | Prod>User not able to see all bank Account in Payment mode

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Prod - Fixed UI Exceptions

- apps/web-giddh/src/meta/.htaccess
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#7377
> Revert "fix: Prateek | Test | .htaccess redirect http to https"

- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
https://app.clickup.com/t/25ggyg
> fix: GIDK-#25ggyg | Prateek | Prod | Prod>User not able to see all bank Account in Payment mode

- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
https://app.clickup.com/t/25ggyg
> fix: GIDK-#25ggyg | Prateek | Beta | Prod>User not able to see all bank Account in Payment mode

- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts
https://app.clickup.com/t/25ggyg
> fix: GIDK-#25ggyg | Prateek | Stage | Prod>User not able to see all bank Account in Payment mode

- apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
https://app.clickup.com/t/2786mw
> Test - Purchase Bill not found with uniquename, error is getting displayed when Vendor name is updated

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/ledger/ledger.module.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
- apps/web-giddh/src/app/shared/amount-field/amount-field.component.ts
> Gidk 23ghp7 amount ledger test

- apps/web-giddh/src/app/ledger/ledger.module.ts
> shalinee | TEST | removed amountField from declaration

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/277z9a
> Test < User is not able to view the account's HSN/SAC in voucher generation page.

- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
- apps/web-giddh/src/app/shared/header/components/group-add/group-add.component.html
- apps/web-giddh/src/app/shared/header/components/group-add/group-add.component.ts
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/278253
> Test - User is not able to provide HSN/SAC for the account group in master

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/helpers/pipes/currencyPipe/currencyType.pipe.ts
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.ts
> fix: Prateek | Test | Issue fixes related to bulk item

- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/invoice/create/invoice.create.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.ts
- apps/web-giddh/src/app/welcome/welcome.component.ts
> feat: GIDK-#1zcrr3 | Prateek | Stage | Remove Validation from GSTIN number for 'Government Entity' party type in account creation

- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/invoice/create/invoice.create.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.ts
- apps/web-giddh/src/app/welcome/welcome.component.ts
> feat: GIDK-#1zcrr3 | Prateek | Beta | Remove Validation from GSTIN number for 'Government Entity' party type in account creation

- apps/web-giddh/src/app/shared/header/components/group-add/group-add.component.ts
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/278253
> Test - Enabled HSN/SAC for purchase groups as well

- apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
https://app.clickup.com/t/2786mw
> Stage - Purchase Bill not found with uniquename, error is getting displayed when Vendor name is updated

- apps/web-giddh/src/app/shared/header/components/group-add/group-add.component.ts
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#7397
> Revert "Test - Enabled HSN/SAC for purchase groups as well"

- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
- apps/web-giddh/src/app/shared/header/components/group-add/group-add.component.html
- apps/web-giddh/src/app/shared/header/components/group-add/group-add.component.ts
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#7395
> Revert "Test - User is not able to provide HSN/SAC for the account group in master"

- apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
https://app.clickup.com/t/2786mw
> Prod - Purchase Bill not found with uniquename, error is getting displayed when Vendor name is updated

- apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
https://app.clickup.com/t/2786mw
> Beta - Purchase Bill not found with uniquename, error is getting displayed when Vendor name is updated

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
> fix: GIDK-23caqm | Prateek | Test | Issues related to calculation values in bulk entries

- apps/web-giddh/src/app/accounting/ng-virtual-list/virtual-list.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/shared/helpers/directives/keyboardShortcut/navigationWalker.directive.ts
- apps/web-giddh/src/app/shared/helpers/pipes/currencyPipe/currencyType.pipe.ts
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.html
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
> fix: GIDK-#23caqm | Prateek | Beta | Prod - While adding bulk items from voucher create/update flow UI is getting hanged (Freeze)

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
> fix: GIDK-#23caqm | Prateek | Test | Correct the code of PO

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.ts
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.ts
https://app.clickup.com/t/258gy0
> feat: GIDK-258gy0 | Prateek | Stage | Remove dropdown in branch view from report pages

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.ts
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.ts
https://app.clickup.com/t/258gy0
> feat: GIDK-258gy0 | Prateek | Prod | Remove dropdown in branch view from report pages

- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.html
- apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.html
- apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.ts
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
- apps/web-giddh/src/app/vat-report/vatReport.component.html
- apps/web-giddh/src/app/vat-report/vatReport.component.ts
https://app.clickup.com/t/258gy0
> feat: GIDK-258gy0 | Prateek | Beta | Remove dropdown in branch view from report pages

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> removed commented code and fix UI issue

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
https://app.clickup.com/t/27bf8h
https://app.clickup.com/t/27bw8p
> Test - Fixed Hsn/Sac issues

- apps/web-giddh/src/meta/.htaccess
https://app.clickup.com/t/27b7dq
> fix: GIDK-27b7dq | Test | Prateek | Redirect from http to https

- apps/web-giddh/src/meta/.htaccess
> Revert Redirect https to http

- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.scss
> shalinee | TEST | correct clear filter button alignement

- apps/web-giddh/src/meta/.htaccess
> Redirect https stage

- apps/web-giddh/src/meta/.htaccess
> Redirect http to https

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/meta/.htaccess
https://app.clickup.com/t/25f8m8
> fix: Gidk #25f8m8 | Test | Prateek | Double entries shown in customer dropdown in UPDATE flow

- apps/web-giddh/src/meta/.htaccess
> Navigate from http to https

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/27b9ma
> fix: GIDK-#27b9ma | Prateek | Test>User not able to delele the Entries in Ledger and getting Exception in network call

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
- apps/web-giddh/src/app/models/api-models/BranchTransfer.ts
- apps/web-giddh/src/app/models/api-models/Sales.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.html
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zfthb
> Stage - Prod - HSN data is not coming in GST>HSN summary details when creating invoice with service account having HSN number

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> Stage - Allowed zero amount voucher for all vouchers/ledger entry and from JV

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/amount-field/amount-field.component.html
- apps/web-giddh/src/app/shared/amount-field/amount-field.component.ts
- apps/web-giddh/src/app/shared/shared.module.ts
> Gidk 23ghp7 sales amount beta

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/amount-field/amount-field.component.html
- apps/web-giddh/src/app/shared/amount-field/amount-field.component.ts
- apps/web-giddh/src/app/shared/shared.module.ts
> Gidk 23ghp7 sales amount stage

- apps/web-giddh/src/app/shared/shared.module.ts
> shalinee | import currencyModule

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.ts
https://app.clickup.com/t/2397nm
> Test - Fixed Sales bifurcation report logic

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/inventory.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.scss
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.scss
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.scss
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.html
- apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.scss
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- cypress/integration/Giddh/06_TrailBalanace.js
> Gidk 1nerfb selected hover beta

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/27bz8p
> Test - State field is not displayed as Mandatory when we try to create account under sub-group of Sundry Debtor/Sundry Creditor

- apps/web-giddh/src/app/shared/shared.module.ts
> shalinee | correct currency module

- apps/web-giddh/src/app/shared/shared.module.ts
> shalinee | remove currencyModule from decalration

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/environments/environment.stage.ts
- apps/web-giddh/src/meta/.htaccess
- apps/web-giddh/src/meta/yodlee-success.html
- apps/web-giddh/webpack.stage.partial.js
> Revert htaccess change and point to API release

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/amount-field/amount-field.component.html
- apps/web-giddh/src/app/shared/amount-field/amount-field.component.ts
- apps/web-giddh/src/app/shared/shared.module.ts
> Gidk 23ghp7 sales amount prod

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: Reset the voucher on successful entry creation

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
- apps/web-giddh/src/app/models/api-models/BranchTransfer.ts
- apps/web-giddh/src/app/models/api-models/Sales.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.html
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zfthb
> Prod - HSN data is not coming in GST>HSN summary details when creating invoice with service account having HSN number

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
- apps/web-giddh/src/app/models/api-models/BranchTransfer.ts
- apps/web-giddh/src/app/models/api-models/Sales.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.html
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zfthb
> Beta - HSN data is not coming in GST>HSN summary details when creating invoice with service account having HSN number

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.ts
https://app.clickup.com/t/2397nm
> Test - Sales Bifurcation (New vs Old) Changes related to default selection and current year 2021

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/27dwdx
> Test - PO transactions are not coming on PB form when user is linking PO with PB at the time of creation.

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | beta | correct css

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
https://app.clickup.com/t/27e14g
> Test - In PO/PB, company and warehouse state is not getting fetch from company details

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | correct css code

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
https://app.clickup.com/t/27e14g
> Stage - In PO/PB, company and warehouse state is not getting fetch from company details

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | prod | correct css

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/27bz8p
> Stage - State field is not displayed as Mandatory when we try to create account under sub-group of Sundry Debtor/Sundry Creditor

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
https://app.clickup.com/t/27e14g
> Beta - In PO/PB, company and warehouse state is not getting fetch from company details

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/27bz8p
> Beta - State field is not displayed as Mandatory when we try to create account under sub-group of Sundry Debtor/Sundry Creditor

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
https://app.clickup.com/t/27e14g
> Prod - In PO/PB, company and warehouse state is not getting fetch from company details

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/27bz8p
> Prod - State field is not displayed as Mandatory when we try to create account under sub-group of Sundry Debtor/Sundry Creditor

- apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/27f429
> Test - Unable to go to daybook page 2 on test as it is calling multiple req in the loop.

- apps/web-giddh/src/app/settings/financial-year/financial-year.component.html
https://app.clickup.com/t/27f5gx
> Test - Financial year is not getting locked and user facing hang issue while navigating away using browser back button

- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.scss
> test | GIDK-27f53q | Aditi | discount dropdown in ledger

- apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/27fcu9
https://app.clickup.com/t/27fdd1
> Test - Reset filter issue and export issue

- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.scss
https://app.clickup.com/t/27f53q
> beta | GIDK-27f53q | Aditi | discount dropdown in ledger

- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.scss
https://app.clickup.com/t/27f53q
> stage | GIDK-27f53q | Aditi | discount dropdown in ledger

- apps/web-giddh/src/app/services/apiurls/settings.integration.api.ts
- apps/web-giddh/src/app/services/settings.integraion.service.ts
- apps/web-giddh/src/app/settings/integration/beneficiary/beneficiary.component.html
- apps/web-giddh/src/app/settings/integration/beneficiary/beneficiary.component.scss
- apps/web-giddh/src/app/settings/integration/beneficiary/beneficiary.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/settings.module.ts
https://app.clickup.com/t/23fzyu
> Test - ICICI bank integration task

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
> Stage - Removed redundant code

- apps/web-giddh/src/app/shared/header/components/company-add/company-add.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> test | GIDK-27f53q | Aditi | search ui

- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.html
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.scss
> shalinee | TEST | design choose file button

- apps/web-giddh/src/assets/css/style-2.scss
> stage | GIDK-27f53q | Aditi | search ui

- apps/web-giddh/src/assets/css/style-2.scss
> beta | GIDK-27f53q | Aditi | search ui

- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.html
- apps/web-giddh/src/app/ledger/components/ledgerDiscount/ledgerDiscount.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/27f53q
> prod | GIDK-27f53q | Aditi | discount dropdown in ledger

- apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/27fdd1
https://app.clickup.com/t/27fcu9
> Stage - Reset filter issue and export issue

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/27dwdx
> Stage - PO transactions are not coming on PB form when user is linking PO with PB at the time of creation.

- apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/27f429
> Stage - Unable to go to daybook page 2 on test as it is calling multiple req in the loop

- apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/27fdd1
https://app.clickup.com/t/27fcu9
> Prod - Reset filter issue and export issue

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/27dwdx
> Prod - PO transactions are not coming on PB form when user is linking PO with PB at the time of creation.

- apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/27f429
> Prod - Unable to go to daybook page 2 on test as it is calling multiple req in the loop.

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> Prod - Allowed zero amount voucher for all vouchers/ledger entry and from JV

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> Beta - Allowed zero amount voucher for all vouchers/ledger entry and from JV

- apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/27fdd1
https://app.clickup.com/t/27fcu9
> Beta - Reset filter issue and export issue

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/27dwdx
> Beta - PO transactions are not coming on PB form when user is linking PO with PB at the time of creation.

- apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/27f429
> Beta - Unable to go to daybook page 2 on test as it is calling multiple req in the loop.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/27dfkz
> fix: GIDK-27dfkz | Prateek | PROD | Prod < User is not able to generate the invoice by providing the custom invoice number.

- apps/web-giddh/src/app/settings/integration/beneficiary/beneficiary.component.ts
https://app.clickup.com/t/23fzyu
> Test - Fixed api binding

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/summary/summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/b2cs-summary/b2cs-summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/hsn-summary/hsn-summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/nil-summary/nil-summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.html
> Gidk 23ghp7 daybook test

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/environments/environment.stage.ts
- apps/web-giddh/src/meta/yodlee-success.html
- apps/web-giddh/webpack.stage.partial.js
> fix: Prateek | STAGE | Point STAGE to API TEST

- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
> fix: GIDK-d2cfuz | Prateek | Test | Remove flatten call on app launch

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/27dfkz
> fix: GIDK-27dfkz | Prateek | PROD | Prod < User is not able to generate the invoice by  providing the custom invoice number.

- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
> Test - Fixed Form validation issue

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html
- apps/web-giddh/src/app/expenses/components/filter-list/filter-list.component.ts
- apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedger.vm.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
https://app.clickup.com/t/298arj
> Test - Fixed Nulity Issues

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
https://app.clickup.com/t/23bz15
> fix: GIDK-#23bz15 | Test | Prateek | Prod < User is not able to view the error message in UI for Link entity field of warehouse

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
https://app.clickup.com/t/29cqm5
> Test - Due to exception, while creating stock Inventory unit is not coming in unit dropdown

- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
https://app.clickup.com/t/29cr87
> fix: Gidk-#29cr87 | Prateek | Test | Prod - Due to exception, while creating account from vouchers short cut save button is getting freeze

- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/29cua8
> fix: GIDK-#29cua8 | Prateek | Test | Prod - While sharing ledger through magic link, stock information is not coming

- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/29cua8
> fix: GIDK-#29cua8 | Prateek | Prod | Prod - While sharing ledger through magic link, stock information is not coming

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
https://app.clickup.com/t/29cr87
> fix: Gidk-#29cr87 | Prateek | Prod | Prod - Due to exception, while creating account from vouchers short cut save button is getting freeze

- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/29cua8
> fix: GIDK-#29cua8 | Prateek | Beta | Prod - While sharing ledger through magic link, stock information is not coming

- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/29cua8
> fix: GIDK-#29cua8 | Prateek | Stage | Prod - While sharing ledger through magic link, stock information is not coming

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
https://app.clickup.com/t/29cr87
> fix: Gidk-#29cr87 | Prateek | Beta | Prod - Due to exception, while creating account from vouchers short cut save button is getting freeze

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
https://app.clickup.com/t/29cr87
> fix: Gidk-#29cr87 | Prateek | Stage | Prod - Due to exception, while creating account from vouchers short cut save button is getting freeze

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
https://app.clickup.com/t/29cqm5
> Stage - Due to exception, while creating stock Inventory unit is not coming in unit dropdown

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
https://app.clickup.com/t/29cqm5
> Prod - Due to exception, while creating stock Inventory unit is not coming in unit dropdown

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
https://app.clickup.com/t/29cqm5
> Beta - Due to exception, while creating stock Inventory unit is not coming in unit dropdown

- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/29caam
> Test - The subscription expiry warning message is not being displayed to user before 7 days

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
> shalinee | TEST | added message for branch transfer

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts
https://app.clickup.com/t/1xcu6q
> fix: Issues related to API call and accounts not visible

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/mobile-home/mobile-search-branch/mobile-search-branch.component.scss
> Gidk 1x8ekb android sanity test

- apps/web-giddh/src/app/mobile-home/mobile-search-branch/mobile-search-branch.component.scss
- apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.scss
> Gidk 25d5h7 bulk item stage

- apps/web-giddh/src/app/mobile-home/mobile-search-branch/mobile-search-branch.component.scss
- apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.scss
> shalinee | prod | correct height

- apps/web-giddh/src/app/inventory/components/aside-inventory.components/aside-inventory.components.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/1z9572
> feat: GIDK-1z9572 | Prateek | Test | Show taxes in priority order in ledger, voucher

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/27cwq1
> feat: GIDK-#27cwq1 | Prateek | Test | Whenever a new item is added in Product/Service then automatically open the search dropdown.

- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/css/typography.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
https://app.clickup.com/t/1x9p9d
> fix: GIDK-1x9p9d | Prateek | Test | Prod - Console errors 'Rejected by sanitizer' is displayed on Sales Invoice page

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
https://app.clickup.com/t/23bz15
> fix: GIDK-#23bz15 | Stage | Prateek | Prod < User is not able to view the error message in UI for Link entity field of warehouse

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
https://app.clickup.com/t/23bz15
> fix: GIDK-#23bz15 | Beta | Prateek | Prod < User is not able to view the error message in UI for Link entity field of warehouse

- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
https://app.clickup.com/t/23bz15
> fix: GIDK-#23bz15 | Prod | Prateek | Prod < User is not able to view the error message in UI for Link entity field of warehouse

- apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
> shalinee | correct | button height

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.ts
https://app.clickup.com/t/2b83a3
> fix: GIDK-2b83a3 | Prateek | Test | Test < User is not able to view the applied tax for the stock items in the update page

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
> fix: Remove async keyword

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
https://app.clickup.com/t/1xbz0k
> Test - Fixed multiple api call issue

- apps/web-giddh/src/app/actions/groupwithaccounts.actions.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
https://app.clickup.com/t/2b83jv
> fix: GIDK-2b83jv | Prateek | Test | Remove flatten account logic after any operation in performed on account in master

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/aside-inventory.components/aside-inventory.components.html
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/models/api-models/Inventory.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/1z9572
> feat: GIDK-1z9572 | Prateek | Prod | Show taxes in priority order in ledger, voucher

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/aside-inventory.components/aside-inventory.components.html
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/models/api-models/Inventory.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/1z9572
> feat: GIDK-1z9572 | Prateek | Beta | Show taxes in priority order in ledger, voucher

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/aside-inventory.components/aside-inventory.components.html
- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/models/api-models/Inventory.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/1z9572
> feat: GIDK-1z9572 | Prateek | Stage | Show taxes in priority order in ledger, voucher

- apps/web-giddh/src/app/inventory/components/aside-inventory.components/aside-inventory.components.html
> fix: Stock details not reflecting in update flow

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/Sales/sales.reducer.ts
https://app.clickup.com/t/2badjj
> fix: GIDK-#2badjj | Prateek | Test | Prod < User is not able to update the unique name of the customer

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/Sales/sales.reducer.ts
https://app.clickup.com/t/2badjj
> fix: GIDK-#2badjj | Prateek | Prod | Prod < User is not able to update the unique name of the customer

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/Sales/sales.reducer.ts
https://app.clickup.com/t/2badjj
> fix: GIDK-#2badjj | Prateek | Beta | Prod < User is not able to update the unique name of the customer

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/Sales/sales.reducer.ts
https://app.clickup.com/t/2badjj
> fix: GIDK-#2badjj | Prateek | Stage | Prod < User is not able to update the unique name of the customer

- apps/web-giddh/src/app/actions/accounts.actions.ts
https://app.clickup.com/t/2b8498
> fix: GIDK-#2b8498 | Test | Prateek | Remove flatten groups call on merge account

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
https://app.clickup.com/t/2ba1r2
> fix: GIDK-#2ba1r2 | Prateek | Test | While opening invoice preview user not able to close that chat pop-up

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
> shalinee | stage | ledger height fixed

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.scss
- apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html
- apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.scss
- apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | correct button alignemnt for hindi/en

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
> shalinee | TEST | correct btn

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
https://app.clickup.com/t/2ba1r2
> fix: GIDK-#2ba1r2 | Prateek | Prod | While opening invoice preview user not able to close that chat pop-up

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
https://app.clickup.com/t/2ba1r2
> fix: GIDK-#2ba1r2 | Prateek | Stage | While opening invoice preview user not able to close that chat pop-up

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
https://app.clickup.com/t/2ba1r2
> fix: GIDK-#2ba1r2 | Prateek | Beta | While opening invoice preview user not able to close that chat pop-up

- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/29caam
> Prod - The subscription expiry warning message is not being displayed to user before 7 days

- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/29caam
> Beta - The subscription expiry warning message is not being displayed to user before 7 days

- apps/web-giddh/src/app/actions/company.actions.ts
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
- apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
> Stage - Client created a new company but its navigating to the previously created company

- apps/web-giddh/src/app/actions/company.actions.ts
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
- apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
> Beta - Client created a new company but its navigating to the previously created company

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
https://app.clickup.com/t/1xbz0k
> Beta - Fixed multiple api call issue

- apps/web-giddh/src/app/actions/company.actions.ts
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts
- apps/web-giddh/src/app/store/authentication/authentication.reducer.ts
> Prod - Client created a new company but its navigating to the previously created company

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
https://app.clickup.com/t/1xbz0k
> Prod - Fixed multiple api call issue

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/1n9w45
> fix: GIDK-#1n9w45 | Prateek | Test | Reset the select all status of ledger when ledger is changed

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/27cwq1
> fix: GIDK-#27cwq1 | Prateek | Test | Dropdown not opening in UPDATE flow

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/27cwq1
> feat: GIDK-#27cwq1 | Prateek | Beta | Whenever a new item is added in Product/Service then automatically open the search dropdown.

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.ts
https://app.clickup.com/t/1dcu0p
> Test - Fixed PR Issues

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.ts
https://app.clickup.com/t/2397nm
> Stage - Sales Bifurcation (New vs Old) Changes related to default selection and current year 2021

- apps/web-giddh/src/app/theme/confirm-modal/confirm-modal.component.ts
> Test - Added nulity check

- apps/web-giddh/src/app/theme/confirm-modal/confirm-modal.component.ts
> Stage - Added nulity check

- apps/web-giddh/src/app/onboarding/onboarding.component.html
> Stage - Fixed code

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.ts
- apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.html
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.html
> Stage - Fixed code merging issues

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/27cwq1
> feat: GIDK-#27cwq1 | Prateek | Prod | Whenever a new item is added in Product/Service then automatically open the search dropdown.

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/services/locale.service.ts
> Stage - Electron path bug

- apps/web-giddh/src/app/services/locale.service.ts
> Test - Fixed Code merge issue and url

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
> shalinee | TEST |correct currency icon issue

- apps/web-giddh/src/app/ledger/ledger.component.html
> Test - Fixed shouldShowItcSection

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/2bgwfx
> Test - Fixed exception

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/2bgwfx
> Stage - Fixed exception

- apps/web-giddh/src/app/theme/ng-virtual-select/virtual-scroll.ts
> test | GIDK-2bbg5h | Aditi | alignment on create new company

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
https://app.clickup.com/t/2bf1kp
> fix: GIDK-#2bf1kp | Test | Prateek | Prod < Need to remove 'Tax to be paid on reverse charge' and 12.

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
https://app.clickup.com/t/2bey9b
> fix: GIDK-#2bey9b | Prateek | Test | Prod < Transport Details fields are automatically unchecked if user uncheck Shipping Details in Template A

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
https://app.clickup.com/t/2bezv7
> fix: GIDK-#2bezv7 | Prateek | Test | Prod < User uncheck Total field GST Column is automatically removed

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
https://app.clickup.com/t/2bf0t5
> fix: GIDK-#2bf0t5 | Test | Prateek | Prod < If user is creating a new template it is fetching the previous template logo.

- apps/web-giddh/src/app/theme/ng-virtual-select/virtual-scroll.ts
> revert dropdown change

- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/onboarding/onboarding.component.ts
- apps/web-giddh/src/app/services/apiurls/ecommerce.api.ts
- apps/web-giddh/src/app/services/ecommerce.service.ts
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.html
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.scss
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.ts
- apps/web-giddh/src/app/shared/shared.module.ts
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Test - Change the Form of Schedule now at Onboarding page

- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.html
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.scss
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.ts
> Test - Added phone code field

- apps/web-giddh/src/app/settings/settings.component.ts
https://app.clickup.com/t/2d9ta2
> Test - User not able to integrate Gmail

- apps/web-giddh/src/app/settings/settings.component.ts
https://app.clickup.com/t/2d9ta2
> Prod - User not able to integrate Gmail

- apps/web-giddh/src/app/settings/settings.component.ts
https://app.clickup.com/t/2d9ta2
> Beta - User not able to integrate Gmail

- apps/web-giddh/src/app/settings/settings.component.ts
https://app.clickup.com/t/2d9ta2
> Stage - User not able to integrate Gmail

- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/onboarding/onboarding.component.ts
- apps/web-giddh/src/app/services/apiurls/ecommerce.api.ts
- apps/web-giddh/src/app/services/ecommerce.service.ts
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.html
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.scss
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.ts
- apps/web-giddh/src/app/shared/shared.module.ts
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Stage - Change the Form of Schedule now at Onboarding page

- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/onboarding/onboarding.component.ts
- apps/web-giddh/src/app/services/apiurls/ecommerce.api.ts
- apps/web-giddh/src/app/services/ecommerce.service.ts
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.html
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.scss
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.ts
- apps/web-giddh/src/app/shared/shared.module.ts
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Beta - Change the Form of Schedule now at Onboarding page

- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/onboarding/onboarding.component.ts
- apps/web-giddh/src/app/services/apiurls/ecommerce.api.ts
- apps/web-giddh/src/app/services/ecommerce.service.ts
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.html
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.scss
- apps/web-giddh/src/app/shared/schedule-now/schedule-now.component.ts
- apps/web-giddh/src/app/shared/shared.module.ts
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.html
- apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Prod - Change the Form of Schedule now at Onboarding page

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/2bf5hz
> fix: GIDK-#2bf5hz | Prateek | Test | Prod < User is not able to find the option to hide the company name in template E

- apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | Test | multilang issue fixed

- apps/web-giddh/src/app/home/components/revenue/revenue-chart.component.html
- apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 2bgwey multilang stage

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/2bf9xv
> fix: GIDK-#2bf9xv | Prateek | Test | Data[amount] calculations displayed in the template E should be correct

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
> shalinee | TEST | correct button design

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
> stage | resolved

- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
https://app.clickup.com/t/2d8nez
> fix: GIDK-#2d8nez | Prateek | Test  Remove redundant API calls

- apps/web-giddh/src/app/ledger/ledger.component.html
> Test- Option to reconcile bank a/c is missing for all the languages

- apps/web-giddh/src/app/ledger/ledger.component.html
> Stage - Option to reconcile bank a/c is missing for all the languages

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/2bf6bn
> fix: GIDK-#2bf6bn | Test | Prateek | Prod < User should be provided with the option to hide and show shipping address details from template E

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/2bgwaj
> Test - While copying the PO and generating new PO getting error "The purchase order this already exist for the company."

- apps/web-giddh/src/app/ledger/ledger.component.html
> Beta - Option to reconcile bank a/c is missing for all the languages

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/298b0r
> Test - Fixed Translation Issues

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/298b0r
> Stage - Fixed Translation Issues

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/298b0r
> Beta - Fixed Translation Issues

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
https://app.clickup.com/t/2bf4h8
> test | GIDK-2bf4h8 | Aditi | PDF change of date alignment

- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/css/typography.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
https://app.clickup.com/t/1x9p9d
> fix: GIDK-1x9p9d | Prateek | Stage | Prod - Console errors 'Rejected by sanitizer' is displayed on Sales Invoice page

- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/css/typography.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
https://app.clickup.com/t/1x9p9d
> fix: GIDK-1x9p9d | Prateek | Beta | Prod - Console errors 'Rejected by sanitizer' is displayed on Sales Invoice page

- apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | UI issue fixed of multilang

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
> fix: GIDK-#2db2z8 | Prateek | Test | Remove text not visible in Update ledger

- apps/web-giddh/src/app/ledger/components/exportLedger/exportLedger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | beta | resolved

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> test | GIDK-2d8505 | Aditi | tax bifurcation table

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
> fix: GIDK-#2db2z8 Prateek | Test | Remove text not visible in Update ledger

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
https://app.clickup.com/t/2bf4h8
> beta | GIDK-2bf4h8 | Aditi | PDF change of date alignment

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
https://app.clickup.com/t/2bf4h8
> stage | GIDK-2bf4h8 | Aditi | PDF change of date alignment

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/search/components/search-filter/search-filter.component.html
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
> fix: GIDK-#2db2z8 | Prateek | Stage | Remove text not visible in Update ledger

- apps/web-giddh/src/app/search/components/search-filter/search-filter.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
> fix: Add reverted code

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/search/components/search-filter/search-filter.component.html
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
> fix: GIDK-#2db2z8 | Prateek | Beta | Remove text not visible in Update ledger

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
> test | GIDK-2d8505 | tax bifurcation in template A

- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/css/typography.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
https://app.clickup.com/t/1x9p9d
> fix: GIDK-1x9p9d | Prateek | Prod | Prod - Console errors 'Rejected by sanitizer' is displayed on Sales Invoice page

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2bey9b
https://app.clickup.com/t/2bf0t5
https://app.clickup.com/t/2bf1kp
https://app.clickup.com/t/2bf5hz
https://app.clickup.com/t/2bf6bn
https://app.clickup.com/t/2bfa5b
> fix: GIDK-#2bey76 | Prateek | Stage | Prod < Issue card related to the template[A &E]

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2bey9b
https://app.clickup.com/t/2bf0t5
https://app.clickup.com/t/2bf1kp
https://app.clickup.com/t/2bf5hz
https://app.clickup.com/t/2bf6bn
https://app.clickup.com/t/2bfa5b
> fix: GIDK-#2bey76 | Prateek | Beta | Prod < Issue card related to the template[A &E]

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
https://app.clickup.com/t/2bf4h8
> prod | GIDK-2bf4h8 | Aditi | PDF change of date alignment

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2bey9b
https://app.clickup.com/t/2bf0t5
https://app.clickup.com/t/2bf1kp
https://app.clickup.com/t/2bf5hz
https://app.clickup.com/t/2bf6bn
https://app.clickup.com/t/2bfa5b
> fix: GIDK-#2bey76 | Prateek | Prod | Prod < Issue card related to the template[A &E]

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/2bf717
> email mobile large name issue

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> beta | GIDK-2d8505 | Aditi | tax bifurcation table

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> stage | GIDK-2d8505 | Aditi | tax bifurcation table

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> prod | GIDK-2d8505 | Aditi | tax bifurcation table

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.ts
- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> Test - Loader and Sales Bifurcation PR Issues

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.ts
- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> Stage - Loader and Sales Bifurcation PR Issues

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/environments/environment.stage.ts
- apps/web-giddh/src/meta/yodlee-success.html
- apps/web-giddh/webpack.stage.partial.js
> Change API pointing to apirelease

- apps/web-giddh/src/app/services/apiurls/settings.integration.api.ts
- apps/web-giddh/src/app/services/settings.integraion.service.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
https://app.clickup.com/t/23fzyu
> Test - Integrated Account Registration Status API

- apps/web-giddh/src/app/audit-logs/components/audit-logs-grid/audit-logs-grid.component.ts
- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> Beta - Loader and Sales Bifurcation PR Issues

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
> Resolve code comments in template PR

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/summary/summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/b2cs-summary/b2cs-summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/hsn-summary/hsn-summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/nil-summary/nil-summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.html
> Gidk 23ghp7 daybook stage

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/summary/summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/b2cs-summary/b2cs-summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/hsn-summary/hsn-summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/nil-summary/nil-summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/search/components/search-grid/search-grid.component.html
> Gidk 23ghp7 daybook beta

- apps/web-giddh/src/app/shared/amount-field/amount-field.component.html
> shalinee | TEST | makes dynamic giddhCurrency pipe

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> test | GIDK-2f9qkf | Aditi | note scroll

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> shalinee | correc div tag

- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.scss
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> test | GIDK-2bbg5h | Aditi | Alignment issue on create new company

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
https://app.clickup.com/t/2bf717
> test| GIDK-2bf717 | new change of merging id and number

- apps/web-giddh/src/app/import-excel/import-type-select/import-type-select.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/modals/template-preview-modal/template-preview.modal.component.html
- apps/web-giddh/src/app/manufacturing/edit/modal/confirmation.model.component.html
- apps/web-giddh/src/app/permissions/components/confirmation/permission.model.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> test | padding and margin classes fixed

- apps/web-giddh/src/app/import-excel/import-type-select/import-type-select.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/modals/template-preview-modal/template-preview.modal.component.html
- apps/web-giddh/src/app/manufacturing/edit/modal/confirmation.model.component.html
- apps/web-giddh/src/app/permissions/components/confirmation/permission.model.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
> stage | GIDK-2bbg5h | Aditi | Alignment issue on create new company

- apps/web-giddh/src/app/import-excel/import-type-select/import-type-select.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/modals/template-preview-modal/template-preview.modal.component.html
- apps/web-giddh/src/app/manufacturing/edit/modal/confirmation.model.component.html
- apps/web-giddh/src/app/permissions/components/confirmation/permission.model.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/2bbg5h
> beta | GIDK-2bbg5h | Aditi | Alignment issue on create new company

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/2f9qkf
> beta | GIDK-2f9qkf | Aditi | note scroll

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> shalinee | stage | UI issue resolved

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
- apps/web-giddh/src/app/theme/translate/translate.directive.ts
https://app.clickup.com/t/2fatd6
> Test - While mapping ICICI transactions the save button and other UI fields is not showing

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
- apps/web-giddh/src/app/theme/translate/translate.directive.ts
https://app.clickup.com/t/2fatd6
> Stage - While mapping ICICI transactions the save button and other UI fields is not showing

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/2f9qkf
> stage | GIDK-2f9qkf | Aditi | note scroll

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
- apps/web-giddh/src/app/theme/translate/translate.directive.ts
https://app.clickup.com/t/2fatd6
> Beta - While mapping ICICI transactions the save button and other UI fields is not showing

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
- apps/web-giddh/src/app/theme/translate/translate.directive.ts
https://app.clickup.com/t/2fatd6
> Prod - While mapping ICICI transactions the save button and other UI fields is not showing

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/1v8uyy
> feat: GIDK-#1v8uyy | Prateek | Test | Move invoice notes on last page

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/1v8uyy
> fix: Enter key not working in notes of last page and reset checkbox

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
> fix: GIDK-#2bf7qr | Prateek | Test | Prod < Entry date should be displayed in template E and hide and show of date field should also work

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
https://app.clickup.com/t/2bf717
> stage |  GIDK-2bf717 | new change of merging id and number

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
https://app.clickup.com/t/2bf93v
> fix: GIDK-2bf93v | Prateek | Test | Prod < Taxable amount column is not displayed in template E

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/2d83c1
> fix: GIDK-2d83c1 | Prateek | Test | Prod < Need to remove some type of tax from tax Bifurcation in template A&E

- apps/web-giddh/src/app/import-excel/import-type-select/import-type-select.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/modals/template-preview-modal/template-preview.modal.component.html
- apps/web-giddh/src/app/manufacturing/edit/modal/confirmation.model.component.html
- apps/web-giddh/src/app/permissions/components/confirmation/permission.model.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.html
- apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/style-magic.css
- apps/web-giddh/src/assets/magic-link-assets/magic.css
- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/2bbg5h
> prod | GIDK-2bbg5h | Aditi | Alignment issue on create new company

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/2f9qkf
> prod | GIDK-2f9qkf | Aditi | note scroll

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> Test - Added User field in settings integration

- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
> shalinee | prod | correct code

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | prod | remove css

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/invoice.templates.module.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.module.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/shared/helpers/directives/has-focus/has-focus.directive.ts
- apps/web-giddh/src/app/shared/helpers/directives/has-focus/has-focus.module.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/2d8a5j
> feat: GIDK-#2d8a5j | Prateek | Test | Prod < Need to provide support for word limit in fields

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
https://app.clickup.com/t/2bf9xv
> fix: Resolve merge conflict issue

- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | correct code

- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
> Pr issue picked test

- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
> shalinee | stage | correct code

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/25feva
> GIDK-##25feva | Anish | Test | Prod <  On account, state is getting removed when user clicks on GSTIN filed and again clicked outside

- apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/2h9kae
> fix: GIDK-#2h9kae | Prateek | Test | Prod - On ledger checkboxes are not getting display on entry when user hover on it.

- apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/2h9kae
> fix: GIDK-#2h9kae | Prateek | Prod | Prod - On ledger checkboxes are not getting display on entry when user hover on it.

- apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/2h9kae
> fix: GIDK-#2h9kae | Prateek | Beta | Prod - On ledger checkboxes are not getting display on entry when user hover on it.

- apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/2h9kae
> fix: GIDK-#2h9kae | Prateek | Stage | Prod - On ledger checkboxes are not getting display on entry when user hover on it. 

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/2h906g
> Test - Update button is not displayed in edit page of all vouchers

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/2bgwaj
> Stage - While copying the PO and generating new PO getting error "The purchase order this already exist for the company."

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
> shalinee | TEST | UI issue fixed of ledger and invoice page

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
https://app.clickup.com/t/2hbydj
> shalinee | TEST | added static message

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
https://app.clickup.com/t/2hbydj
> feat: GIDK-#2hbydj | Prateek | Test | Add "Open a new current account" after submit button

- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | beta | correct code

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/2bgwaj
> Beta - While copying the PO and generating new PO getting error "The purchase order this already exist for the company."

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- cypress/integration/Giddh/06_TrailBalanace.js
> shalinee | prod | correct alignemnt on update ledger

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/25feva
> GIDK-#25feva | Anish | Stage | Prod < On account, state is getting removed when user clicks on GSTIN filed and again clicked outside

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/2bgwaj
> Prod - While copying the PO and generating new PO getting error "The purchase order this already exist for the company."

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
> shalinee | test | correct inventory design

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.scss
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.scss
> shalinee | TEST | correct alignemnt of manufacture

- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
> shalinee | test | correct code for the inventory stock

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.scss
> Gidk 2hdd8y alignment test

- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
> shalinee | TEST | correct alignemnt of inventory advance search

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.scss
> shalinee | stage | correct inventory design

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.scss
> shalinee | beta | correct inventory design

- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.scss
> shalinee | prod | correct inventory design

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/contact/aside-menu-account/aside.menu.account.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
https://app.clickup.com/t/2harb1
> fix: GIDK-#2ba5u7 | Prateek | Test - Bank Details are not updated on Vendor Payment pop up window unless page is refreshed

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> shalinee | correct cmd+G label

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/25feva
> GIDK-##25feva-beta | Anish | Beta | Prod < On account, state is getting removed when user clicks on GSTIN filed and again clicked outside

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/25feva
> GIDK-##25feva-prod | Anish | Prod | Prod < On account, state is getting removed when user clicks on GSTIN filed and again clicked outside

- apps/web-giddh/src/app/contact/contact.component.ts
> fix: Duplicate identifier issue

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | correct invoice preview page design

- apps/web-giddh/src/app/models/api-models/SettingsIntegraion.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> feat: GIDK-#2b9cfy | Prateek | Test | Add Login ID support to ICICI integration

- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> fix: GIDK-#2b9cfy | Prateek | Test | Conditional change for login ID

- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.scss
- apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html
- apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | correct alignment of form in master

- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.scss
- apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html
- apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | stage | resolved

- apps/web-giddh/src/app/new-inventory/component/inventory-sidebar/inventory-sidebar.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-help-support/aside-help-support.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 2bbvtz icon update

- apps/web-giddh/src/app/inventory/inventory.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/2bbvtz
> feat GIDK-#2bbvtz | Prateek | Test | Add active class on menu item, refactor primary component, arrange menu items alphabetically

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> feat: GIDK-#2b9cfy | Prateek | Test | Add support to multiple users and email IDs in ICICI integration

- apps/web-giddh/src/app/invoice/invoice.routing.module.ts
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/2d8a5j
> feat: GIDK-#2d8a5j | Prateek | Test | Add max length check on bulk notes update in invoice

- .gitignore
> Remove package-lock from gitignore

- .gitignore
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#7800
> Revert "Remove package-lock from gitignore"

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.scss
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
> feat: GIDK-#2b9cfy | Prateek | Test | Show selected user count in ICICI bank users

- apps/web-giddh/src/app/all-items/all-item.component.html
- apps/web-giddh/src/app/all-items/all-item.component.scss
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> shalinee | TEST | correct UI issues

- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/2bbvtz
> fix: GIDK-#2bbvtz | Prateek | Test | Issue #2kgx2b, #2n8ckn, #2n8wme

- apps/web-giddh/src/app/all-items/all-item.component.html
- apps/web-giddh/src/app/all-items/all-item.component.scss
- apps/web-giddh/src/app/all-items/all-item.component.ts
https://app.clickup.com/t/2kh7vy
> feat: GIDK-#2kh7vy | Prateek | Test | Add keyboard shortcut to all items page

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 2kgvjv sidebar

- apps/web-giddh/src/app/all-items/all-item.component.ts
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.html
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.ts
https://app.clickup.com/t/2bbvtz
> fix: GIDK-#2bbvtz | Prateek | Test | Profit loss tab highlight issue, all item page user unable to enter text

- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
https://app.clickup.com/t/2nbfmh
> fix: Gidk-#2nbfmh | Prateek | Test | Prod - Account is not deleted properly from Masters

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
> fix: Uppercase on branch and company initials

- apps/electron-giddh/src/package.json
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#7821
> Revert "Update package.json"

- apps/web-giddh/src/app/all-items/all-item.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/2kgttk
> fix: GIDK-#2kgttk | Prateek | Test | Remove dependency from notBranchViewable & notCompanyViewable

- apps/web-giddh/src/app/settings/financial-year/financial-year.component.html
https://app.clickup.com/t/27f5gx
> fix: GIDK-27f5gx | Prateek | Stage - Financial year is not getting locked and user facing hang issue while navigating away using browser back button

- apps/web-giddh/src/app/settings/financial-year/financial-year.component.html
https://app.clickup.com/t/27f5gx
> fix: GIDK-27f5gx | Prateek | Beta - Financial year is not getting locked and user facing hang issue while navigating away using browser back button

- apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.scss
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.scss
- apps/web-giddh/src/app/invoice/preview/models/purchase-bill-template-preview/purchase-bill-template-preview.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/shared/purchase-order-preview/purchase-order-preview.component.html
https://app.clickup.com/t/2kbqcf
> test | GIDK-2kbqcf | Aditi | scroll working in invoice

- apps/web-giddh/src/app/settings/financial-year/financial-year.component.html
https://app.clickup.com/t/27f5gx
> fix: GIDK-27f5gx | Prateek | Prod - Financial year is not getting locked and user facing hang issue while navigating away using browser back button

- apps/web-giddh/src/app/all-items/all-item.component.ts
- apps/web-giddh/src/app/services/general.service.ts
https://app.clickup.com/t/2nb1he
https://app.clickup.com/t/2nemxf
> fix: All items not updating on creation of new branch

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
https://app.clickup.com/t/2bf39t
> refactor: GIDK-#2bf39t | Prateek | Test | Resolve code review comments

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
> test | GIDK-2q99pj | Aditi | logo size in template

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
> feat: GIDK-#2bf7qr | Prateek | Test | Prod < Entry date should be displayed in template E and hide and show of date field should also work 

- apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | correct CSS code for GST

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/2bf5q7
> feat: GIDK-#2bf5q7 | Prateek | Test | Prod < Two separate checkbox needs to be provided for company address and warehouse address in template A & E

- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2bf5q7
> feat: GIDK-#2bf5q7 | Prateek | Test | Update the default value of show company address

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
> feat: GIDK-#2d8hq1 | Prateek | Test | Prod < Need to give option to hide/show and edit company name underneath slogan.

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> fix: GIDK-#2d8hq1 | Prateek | Test | Label for text underneath slogan/signature

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
> test | Aditi | table data issue fixed

- apps/web-giddh/src/app/actions/settings/settings.integration.action.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> feat: GIDK-#2b9cfy | Prateek | Test | Change ICICI login URL, add 'portal' keyword, show API returned message in place of hard coded text

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
> fix: GIDK-#2bf9u7 | Prateek | Test | Add reverted changes

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/environments/environment.stage.ts
- apps/web-giddh/src/meta/yodlee-success.html
- apps/web-giddh/webpack.stage.partial.js
> Revert API release

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | update  UI

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | stage | UI correction on invoice and proforma preview page

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 2qcge3 menu collapse stage

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 2qcge3 menu collapse beta

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
> fix: Gidk-#2d8hq1 | Prateek | Test | Text under slogan not showing company name for new template

- apps/web-giddh/src/app/inventory/inventory.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 2qcge3 menu collapse prod

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2bf013
> fix: GIDK-#2bf013 | Prateek | Test | Delete image scenario

- apps/web-giddh/src/assets/sample-files/group-sample.csv
https://app.clickup.com/t/1ta844
> fix: Prod < For importing group and inventory CSV sample file message is displayed at last row of the file.

- apps/web-giddh/src/app/inventory/inventory.component.scss
> Master hover stage

- apps/web-giddh/src/app/inventory/inventory.component.scss
> Master hover test

- apps/web-giddh/src/app/inventory/inventory.component.scss
> Master hover beta

- apps/web-giddh/src/app/inventory/components/sidebar-components/stockList.component.scss
> shalinee | beta | correct alignement of inventory sidebar

- apps/web-giddh/src/app/actions/settings/settings.integration.action.ts
> fix: GIDK-#2b9cfy | Prateek | Test | Binding with ICICI response

- apps/web-giddh/src/app/shared/helpers/allItems.ts
> fix: Prateek | Test | Menu changes

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> shalinee | TEST | correct sidebar menu height

- apps/web-giddh/src/app/shared/helpers/allItems.ts
> fix: Remove the permissions page

- apps/web-giddh/src/app/shared/helpers/allItems.ts
https://app.clickup.com/t/2bbvtz
> fix: GIDK-#2bbvtz | Prateek | Stage | Menu items changes

- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> shalinee | TEST | correct scroll issue

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> shalinee | TEST | correct height

- apps/web-giddh/src/app/inventory/components/sidebar-components/stockList.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> shalinee | prod | correct alignement of inventory sidebar

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> Gidk 2tfbuj icon align test

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | removed scroll form body if invoice preview page open

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/services/apiurls/invoice.api.ts
- apps/web-giddh/src/app/services/invoice.service.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/services/ledger.service.ts
- apps/web-giddh/src/assets/locale/ledger/en.json
- apps/web-giddh/src/assets/locale/ledger/hi.json
- apps/web-giddh/src/assets/locale/ledger/mr.json
https://app.clickup.com/t/2bf013
> feat: Gidk-#2bf013 | Prateek | Stage | Prod < User is not able to remove image signature in both template [A&E]

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/2bf39t
> feat: GIDK-#2bf39t | Prateek | Stage | Prod < Need to give setting to hide/show Note 2 (Note from invoice) and Note 2 will show under Note 1.

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
> fix: GIDK-#2bf7qr | Prateek | Stage | Prod < Entry date should be displayed in template E and hide and show of date field should also work 

- apps/web-giddh/src/app/invoice/invoice.routing.module.ts
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/invoice.templates.module.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.module.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/shared/helpers/directives/has-focus/has-focus.directive.ts
- apps/web-giddh/src/app/shared/helpers/directives/has-focus/has-focus.module.ts
https://app.clickup.com/t/2d8a5j
> feat: GIDK-#2d8a5j | Prateek | Stage | Prod < Need to provide support for word limit in fields

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/2bf5q7
>  feat: GIDK-#2bf5q7 | Prateek | Stage | Prod < Two separate checkbox needs to be provided for company address and warehouse address in template A & E

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/services/apiurls/invoice.api.ts
- apps/web-giddh/src/app/services/invoice.service.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/services/ledger.service.ts
- apps/web-giddh/src/assets/locale/ledger/en.json
- apps/web-giddh/src/assets/locale/ledger/hi.json
- apps/web-giddh/src/assets/locale/ledger/mr.json
https://app.clickup.com/t/2bf013
> feat: Gidk-#2bf013 | Prateek | Beta | Prod < User is not able to remove image signature in both template [A&E]

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/2bf39t
> feat: GIDK-#2bf39t | Prateek | Beta | Prod < Need to give setting to hide/show Note 2 (Note from invoice) and Note 2 will show under Note 1.

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
> fix: GIDK-#2bf7qr | Prateek | Beta | Prod < Entry date should be displayed in template E and hide and show of date field should also work

- apps/web-giddh/src/app/invoice/invoice.routing.module.ts
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/invoice.templates.module.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.module.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/shared/helpers/directives/has-focus/has-focus.directive.ts
- apps/web-giddh/src/app/shared/helpers/directives/has-focus/has-focus.module.ts
https://app.clickup.com/t/2d8a5j
> feat: GIDK-#2d8a5j | Prateek | Beta | Prod < Need to provide support for word limit in fields

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/2bf5q7
> feat: GIDK-#2bf5q7 | Prateek | Beta | Prod < Two separate checkbox needs to be provided for company address and warehouse address in template A & E

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/services/apiurls/invoice.api.ts
- apps/web-giddh/src/app/services/invoice.service.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/services/ledger.service.ts
- apps/web-giddh/src/assets/locale/ledger/en.json
- apps/web-giddh/src/assets/locale/ledger/hi.json
- apps/web-giddh/src/assets/locale/ledger/mr.json
https://app.clickup.com/t/2bf013
> feat: Gidk-#2bf013 | Prateek | Prod | Prod < User is not able to remove image signature in both template [A&E]

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/2bf39t
> feat: GIDK-#2bf39t | Prateek | Prod | Prod < Need to give setting to hide/show Note 2 (Note from invoice) and Note 2 will show under Note 1.

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
> fix: GIDK-#2bf7qr | Prateek | Prod | Prod < Entry date should be displayed in template E and hide and show of date field should also work

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> shalinee | STAGE | correct sidebar menu height

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.scss
- apps/web-giddh/src/app/shared/header/header.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> shalinee | BETA | correct sidebar menu height

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> Gidk 2tfbuj icon align
