- apps/web-giddh/src/app/billing-details/billingDetail.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
- apps/web-giddh/src/app/models/api-models/Purchase.ts
- apps/web-giddh/src/app/models/api-models/Sales.ts
- apps/web-giddh/src/app/models/interfaces/invoice.setting.interface.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/welcome/welcome.component.html
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/locale/en.json
- apps/web-giddh/src/assets/locale/hi.json
- apps/web-giddh/src/assets/locale/invoice/settings/en.json
- apps/web-giddh/src/assets/locale/invoice/settings/hi.json
- apps/web-giddh/src/assets/locale/invoice/settings/mr.json
- apps/web-giddh/src/assets/locale/mr.json
https://app.clickup.com/t/2nef64
> feat: Gidk-#2nef64 | Shalinee-Prateek | Add E-invoice support to invoice

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> test | GIDK-2d8hq1 | Aditi | space under image in temp E

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.html
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | correct UI of existing responsive module

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.html
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 2tgrzr responsive stage

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.html
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 2tgrzr responsive beta

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> shalinee | beta | correct TD tag

- apps/web-giddh/src/app/billing-details/billingDetail.component.html
- apps/web-giddh/src/app/invoice/create/invoice.create.component.html
- apps/web-giddh/src/app/models/api-models/Sales.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
- apps/web-giddh/src/app/settings/services/settings-utility.service.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/assets/locale/en.json
- apps/web-giddh/src/assets/locale/hi.json
- apps/web-giddh/src/assets/locale/mr.json
https://app.clickup.com/t/2qg7w1
> feat: GIDK-#2qg7w1 | Prateek | Test | Add PIN code support on Address, Master, Customer, Company/Branch Profile

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/settings/branch/create-branch/create-branch.component.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.html
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/shared/helpers/directives/decimalDigits/decimalDigits.directive.ts
https://app.clickup.com/t/2vb8hh
https://app.clickup.com/t/2vb8mq
https://app.clickup.com/t/2vbkxg
https://app.clickup.com/t/2vbmtk
> fix: GIDK-#2kg77j | Prateek | Test | Issue #2vb8hh, #2vb8mq, #2vbkxg, #2vbmtk

- apps/web-giddh/src/app/models/api-models/Company.ts
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/welcome/welcome.component.html
- apps/web-giddh/src/app/welcome/welcome.component.ts
https://app.clickup.com/t/2qg7w1
> feat: GIDK-#2qg7w1 | Prateek | Test | Add PIN code support on company onboarding

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.html
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.scss
- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Shalinee | prod | resolved issue

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/models/api-models/BranchTransfer.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.html
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.scss
- apps/web-giddh/src/app/settings/warehouse/warehouse.component.ts
https://app.clickup.com/t/2vb8mq
https://app.clickup.com/t/2vbjqk
https://app.clickup.com/t/2vc04d
> feat: Gidk-#2nef64 | Test | Prateek | Add Pin code option in branch transfer and bug fixes

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> test | GIDK-2bf9u7 | Aditi | table alignment

- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.scss
- apps/web-giddh/src/app/reports/components/columnar-report-component/columnar.report.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.scss
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.scss
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.scss
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/table.scss
> Gidk 2vanv0 report test

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> color variable

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> beta | GIDK-2d8hq1 | Aditi | space under image in temp E

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
https://app.clickup.com/t/2tggu2
> test | GIDK-2tggu2 | Aditi | text length for registered column

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/2tghmt
> test | GIDK-2tghmt | Aditi | text length temp E

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> stage | GIDK-2d8hq1 | Aditi | space under image in temp E

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
https://app.clickup.com/t/27c2u2
> fix: GIDK-#27c2u2 | Prateek | Test | Prod>Balance Due and Status is not showing correctly while adjusting sales Debit note with Cash Receipt

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
> prod | GIDK-2d8hq1 | Aditi | space under image in temp E

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/2v8nk5
> feat: GIDK-#2v8nk5 | Prateek | Test | Add IRN support in template A & E

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2vc04d
> fix: GIDK-#2vc04d | Prateek | Test | Pin code added on the address is not getting auto fill in deliver to section of PB

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/2nbh9c
> test | GIDK-2nbh9c | Aditi | template E re-design

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
> feat: Gidk-#2d8hq1 | Aditi-Prateek | Stage | Prod < Need to give option to hide/show and edit company name underneath slogan.

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
> feat: Gidk-#2d8hq1 | Aditi-Prateek | Beta | Prod < Need to give option to hide/show and edit company name underneath slogan. 

- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gst.component.scss
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid-row.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid-row.component.scss
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid-row.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.scss
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.scss
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid-row.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/tb-pl-bs-grid-row.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/tb-pl-bs-grid-row.component.scss
- apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | worked on responsive on TB,PL,BS

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
https://app.clickup.com/t/2tggu2
> test | Aditi | template preview

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
> feat: Gidk-#2d8hq1 | Aditi-Prateek | Prod | Prod < Need to give option to hide/show and edit company name underneath slogan.

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/helpers/directives/decimalDigits/decimalDigits.directive.ts
- apps/web-giddh/src/app/welcome/welcome.component.ts
https://app.clickup.com/t/2kg77j
> fix: GIDK-#2kg77j | Prateek | Test | Issue #2vefv6, #2x9zf1, #2vd3wc

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/2x9t1q
> Test - Error "refreshCompanies is not a function" is getting displayed on trying to refresh company list

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/2x9t1q
> Stage - Error "refreshCompanies is not a function" is getting displayed on trying to refresh company list

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/2x9t1q
> Beta - Error "refreshCompanies is not a function" is getting displayed on trying to refresh company list

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/2x9t1q
> Prod - Error "refreshCompanies is not a function" is getting displayed on trying to refresh company list

- apps/web-giddh/src/index.dev.html
- apps/web-giddh/src/index.electron.prod.html
- apps/web-giddh/src/index.html
- apps/web-giddh/src/index.local.html
- apps/web-giddh/src/index.prod.html
- apps/web-giddh/src/index.stage.html
- apps/web-giddh/src/index.test.html
> feat: Add global catch handler

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/2x9gx8
> Test - Country field is displayed as blank for the Account in master on accessing the account for the first time after login

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/daybook/daybook.module.ts
> Test - Provide the support of update entry/voucher from daybook module.

- apps/web-giddh/src/app/daybook/daybook.component.html
> Test - Fixed build error

- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.scss
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.scss
- apps/web-giddh/src/app/invoice/preview/models/purchase-bill-template-preview/purchase-bill-template-preview.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/shared/purchase-order-preview/purchase-order-preview.component.html
https://app.clickup.com/t/2kbqcf
> prod | GIDK-2kbqcf | Aditi | scroll working in invoice

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/expenses/components/filter-list/filter-list.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.ts
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
> Stage - Fixed nulity issues

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/expenses/components/filter-list/filter-list.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.ts
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
> Beta - Fixed nulity issues

- apps/web-giddh/src/assets/css/style-1.scss
> shalinee | TEST | correct table alignment

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
https://app.clickup.com/t/1ka5xk
> Test - In compound entry user is unable to remove one of the entry

- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.scss
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.scss
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.scss
- apps/web-giddh/src/app/reports/components/purchase-register-table-component/purchase.register.table.component.scss
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.scss
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.scss
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | correct UI issues of report module for responsive

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/expenses/components/filter-list/filter-list.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.ts
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.ts
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.ts
- apps/web-giddh/src/app/settings/warehouse/create-warehouse/create-warehouse.component.ts
> Prod - Fixed nulity issues

- apps/web-giddh/src/assets/css/toastr.css
> shalinee | TEST  | makes toaster responsive

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1zg79g
> feat: GIDK-#1zg79g | Prateek | Test | Add multicurrency support to PB

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> refactor: Update PB multicurrency condition in Update flow

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/1zg79g
> feat: GIDK-#1zg79g | Prateek | Test | Add multi-currency support to PO

- apps/web-giddh/src/app/shared/shared.module.ts
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.module.ts
- apps/web-giddh/src/app/theme/translate/translate.directive.module.ts
> fix: Translate directive build issue

- angular.json
> Temporary bump up of bundle size

- apps/web-giddh/src/app/services/ledger.service.ts
- apps/web-giddh/src/assets/locale/ledger/en.json
https://app.clickup.com/t/1zcge6
> fix: GIDK-#1zcge6 | Prateek | Test- Map Transactions not working in eledger

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Test - Stop customer dropdown to open in case of pending

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: Prateek | Test | Calculation issue in invoice

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
https://app.clickup.com/t/2tcveb
https://app.clickup.com/t/319fwp
> feat: Prateek | Test | Hide E-invoice status for CN/DN as API work is not done

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/1qd5yw
> Test - Show description as new row invoice template settings

- apps/web-giddh/src/assets/sample-files/group-sample.csv
https://app.clickup.com/t/1ta844
> fix: Gidk-1ta844 | Prateek | Stage | Prod < For importing group and inventory CSV sample file message is displayed at last row of the file.

- apps/web-giddh/src/assets/sample-files/group-sample.csv
https://app.clickup.com/t/1ta844
> fix: Gidk-1ta844 | Prateek | Beta | Prod < For importing group and inventory CSV sample file message is displayed at last row of the file.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Beta - Stop customer dropdown to open in case of pending

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Stage - Stop customer dropdown to open in case of pending

- apps/web-giddh/src/assets/sample-files/group-sample.csv
https://app.clickup.com/t/1ta844
> fix: Gidk-1ta844 | Prateek | Prod | Prod < For importing group and inventory CSV sample file message is displayed at last row of the file.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Prod - Stop customer dropdown to open in case of pending

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/2tcveb
https://app.clickup.com/t/319fwp
> feat: GIDK-2tcveb | Prateek | Stage | Add NA status to E-invoice

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/2tcveb
https://app.clickup.com/t/319fwp
> feat: GIDK-2tcveb | Prateek | Test | Add NA status to E-invoice

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
https://app.clickup.com/t/318v4z
> Test - Displayed dummy item description on invoice preview based on settings

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts
- apps/web-giddh/src/app/shared/header/header.component.html
https://app.clickup.com/t/31a8wy
> Test - Scroll is not working on any get all page when setting and help menu closes from outside click.

- apps/web-giddh/src/app/daybook/daybook.component.html
> Test - Fixed Issues

- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/2qb0p4
https://app.clickup.com/t/2qb23h
https://app.clickup.com/t/2xc5zq
> fix: Prateek | Test | Issue #2xc5zq, #2qb23h, #2qb0p4

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/models/api-models/Sales.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/d2cfwa
> Test - Account not found errod error is getting displayed on Sales Invoice

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2zhuw4
> feat: GIDK-#2zhuw4 | Prateek | Test | Need to increase the word limit to 50 characters for Text under image signature field

- apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/31fyc2
> Test - When clicking on switch branch arrow on daybook page the background page is loading

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> shalinee | TEST | UI issue fixed

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Test - When Preview and Generate invoice from invoice>pending list then most of the information is coming as blank

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Prod - When Preview and Generate invoice from invoice>pending list then most of the information is coming as blank

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Beta - When Preview and Generate invoice from invoice>pending list then most of the information is coming as blank

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> Stage - When Preview and Generate invoice from invoice>pending list then most of the information is coming as blank

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/d2cg48
> Test - Invoice with status Cancel is getting deleted even when the Checkbox is unchecked on Invoice management page

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/models/api-models/Sales.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/d2cfwa
> Stage - Account not found errod error is getting displayed on Sales Invoice

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/models/api-models/Sales.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/d2cfwa
> Beta - Account not found errod error is getting displayed on Sales Invoice

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
https://app.clickup.com/t/33cexe
> fix: GIDK-#33cexe | Prateek | Test < Vendor search is not working in PB get all page

- apps/web-giddh/src/app/settings/integration/beneficiary/beneficiary.component.html
- apps/web-giddh/src/app/settings/integration/beneficiary/beneficiary.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/assets/locale/settings/integration/en.json
- apps/web-giddh/src/assets/locale/settings/integration/hi.json
- apps/web-giddh/src/assets/locale/settings/integration/mr.json
https://app.clickup.com/t/2z9dgp
> Test - Implement multi-language in giddh v3

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/models/api-models/Sales.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/d2cfwa
> Prod - Account not found errod error is getting displayed on Sales Invoice

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/d2cg48
> Beta - Invoice with status Cancel is getting deleted even when the Checkbox is unchecked on Invoice management page

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/d2cg48
> Stage - Invoice with status Cancel is getting deleted even when the Checkbox is unchecked on Invoice management page

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
> fix: Remove duplicate code block

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/33dpnz
> feat: GIDK-33dpnz Prateek | Test | Increase taxable value label to 14 characters

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/daybook/daybook.module.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> Stage - Provide the support of update entry/voucher from daybook module.

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/daybook/daybook.module.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> Beta - Provide the support of update entry/voucher from daybook module.

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/daybook/daybook.component.ts
- apps/web-giddh/src/app/daybook/daybook.module.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> Prod - Provide the support of update entry/voucher from daybook module.

- apps/web-giddh/src/app/common/confirmation-modal/confirmation-modal.component.scss
https://app.clickup.com/t/33cf2e
> test | GIDK-33cf2e | Aditi | Alignment issue of Date

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
https://app.clickup.com/t/33hhu5
> fix: GIDK-#33hhu5 | Prateek | Test | Prod < send invoice button is not working at preview invoice page.

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
https://app.clickup.com/t/33hhu5
> fix: GIDK-#33hhu5 | Prateek | Prod | Prod < send invoice button is not working at preview invoice page.

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
https://app.clickup.com/t/33hhu5
> fix: GIDK-#33hhu5 | Prateek | Beta | Prod < send invoice button is not working at preview invoice page.

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
https://app.clickup.com/t/33hhu5
> fix: GIDK-#33hhu5 | Prateek | Stage | Prod < send invoice button is not working at preview invoice page.

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/assets/locale/ledger/en.json
- apps/web-giddh/src/assets/locale/ledger/hi.json
- apps/web-giddh/src/assets/locale/ledger/mr.json
https://app.clickup.com/t/1zg79g
> feat: GIDK-#1zg79g | Prateek | Stage| Add multi-currency support to PO-PB

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/35axw4
> fix: Gidk-#35axw4 | Prateek | Stage | User is facing warning message as invalid date

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/35axw4
> fix: Gidk-#35axw4 | Prateek | Test | User is facing warning message as invalid date

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/1zg79g
> fix: Prateek | Test | PO stock conversion correction for multi-currency

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/shared/revision-history/revision-history.component.ts
- apps/web-giddh/src/app/theme/discount-control/discount-control-component.html
- apps/web-giddh/src/app/theme/discount-control/discount-control.component.ts
https://app.clickup.com/t/2fbq2z
> Test - Fixed Multi language v2 bugs

- apps/web-giddh/src/app/invoice/invoice.component.html
- apps/web-giddh/src/app/invoice/invoice.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.html
- apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
- apps/web-giddh/src/assets/locale/invoice/receipt/en.json
- apps/web-giddh/src/assets/locale/invoice/receipt/hi.json
- apps/web-giddh/src/assets/locale/purchase-record/en.json
- apps/web-giddh/src/assets/locale/purchase-record/hi.json
- apps/web-giddh/src/assets/locale/purchase-record/mr.json
https://app.clickup.com/t/2fbq2z
> Test - Added missing translations for v2

- apps/web-giddh/src/app/settings/profile/setting.profile.component.html
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
- apps/web-giddh/src/assets/locale/settings/profile/en.json
- apps/web-giddh/src/assets/locale/settings/profile/hi.json
- apps/web-giddh/src/assets/locale/settings/profile/mr.json
https://app.clickup.com/t/35ay6j
> Test - Removed Settings from sidebar and all items and displayed company/branch conditionally

- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/2zhuw4
> test | GIDK-2zhuw4 | Aditi | footer text under slogan fixed

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35d4nh
> Test - Recurring invoice are not getting created from Invoice>pending page

- .github/workflows/build.yml
> Giddh builder

- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/2b84ey
> GIDK-#2b84ey | Sagar | TEST| User is not able to remove the tax applied on the account group in master 

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/35fjax
> fix: GIDK-#35fjax | Prateek | Test | Prod < Credit note template issues

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
> Merge with giddh-2.0

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/sales/create/sales.invoice.component.scss
https://app.clickup.com/t/238hy0
> GIDK-#238hy0| SAGAR |TEST | On invoice get all page, a information message is keep coming when there is no advance receipt to adjust invoice

- apps/web-giddh/src/app/shared/helpers/pageTabs.ts
- apps/web-giddh/src/assets/locale/aside-setting/en.json
- apps/web-giddh/src/assets/locale/aside-setting/hi.json
- apps/web-giddh/src/assets/locale/aside-setting/mr.json
> shalinee | remove font class and update icon class

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35hjp3
> Test - Wrong address is getting displayed in PB PDF when changing at the time of creation

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/branch/branch.component.html
https://app.clickup.com/t/2z9dgp
> Test - Fixed translation variable issue

- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
https://app.clickup.com/t/33cd09
> Stage - Update button is getting hang on recurring invoice page

- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
https://app.clickup.com/t/33cd09
> Beta - Update button is getting hang on recurring invoice page

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35d4nh
> Stage - Recurring invoice are not getting created from Invoice>pending page

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35d4nh
> Beta - Recurring invoice are not getting created from Invoice>pending page

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/assets/locale/aside-setting/en.json
> shalinee | TEST | correct UI

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2q99pj
> feat: GIDK-#2q99pj | Prateek | Test | Changes in logo size in invoice template

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2zhuw4
> feat: GIDK-2zhuw4 | Aditi-Prateek | Stage | Need to increase the word limit to 50 characters for Text under image signature field

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2zhuw4
> feat: GIDK-2zhuw4 | Aditi-Prateek | Beta | Need to increase the word limit to 50 characters for Text under image signature field

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/33cdnr
> Test - Round off is not getting applied on update invoice flow

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.scss
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.scss
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
> feat: GIDK-2zhuw4 | Aditi-Prateek | Prod | Need to increase the word limit to 50 characters for Text under image signature field

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35d4nh
> Prod - Recurring invoice are not getting created from Invoice>pending page

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/35fjax
> fix: GIDK-#35fjax | Prateek | Beta | Prod < Credit note template issues

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/35fjax
> fix: GIDK-#35fjax | Prateek | Stage | Prod < Credit note template issues

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/35d6n9
> fix: GIDK-#35d6n9 | Prateek | Test | Advance search is not working as expected for Due date in PO PB module

- apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/37dnmk
> test | GIDK-37dnmk | Aditi | RCM pop up in ledger

- apps/web-giddh/src/assets/css/style-1.scss
> test | GIDK-37dnmk | Aditi | fix RCM for PB

- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
> shalinee | TEST | added margin

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/services/apiurls/invoice.api.ts
- apps/web-giddh/src/app/services/invoice.service.ts
- apps/web-giddh/src/assets/locale/en.json
- apps/web-giddh/src/assets/locale/hi.json
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
- apps/web-giddh/src/assets/locale/mr.json
https://app.clickup.com/t/37gdx1
> feat: GIDK-#37gdx1 | Prateek | Test | Add status on CN/DN get all page

- apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.html
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
> Test - Updated changes on test

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/33dp7r
> feat: Gidk-#33dp7r | Prateek | Test | Add multi-lingual for cancellation text

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/35d6n9
> fix: GIDK-#35d6n9 | Prateek | Stage | Advance search is not working as expected for Due date in PO PB module

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/35d6n9
> fix: GIDK-#35d6n9 | Prateek | Beta | Advance search is not working as expected for Due date in PO PB module

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/35d6n9
> fix: GIDK-#35d6n9 | Prateek | Prod | Advance search is not working as expected for Due date in PO PB module

- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/1v8ut7
> fix: GIDK-#1v8ut7  | Prateek | Test | Prod - From template when user removes the notes then also it is displaying default notes

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/services/invoice.service.ts
https://app.clickup.com/t/33dp7r
> fix: Prateek | Test | Incorrect Invoice uniquename

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
https://app.clickup.com/t/33dp7r
> feat: Prateek | Test | Add cancel button functionality

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35hjp3
> Stage - Wrong address is getting displayed in PB PDF when changing at the time of creation

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35hjp3
> Beta - Wrong address is getting displayed in PB PDF when changing at the time of creation

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/1zdprp
> GIDK-#1zdprp | SAGAR | TEST | Imported transactions are getting displayed after the page is refreshed

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35hjp3
> Prod - Wrong address is getting displayed in PB PDF when changing at the time of creation

- apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/37dnmk
> beta | GIDK-37dnmk | Aditi | RCM pop up in ledger and PB

- apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/37dnmk
> stage | GIDK-37dnmk | Aditi | RCM pop up in ledger and PB

- apps/web-giddh/src/app/invoice/invoice.routing.module.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/shared/helpers/pipes/trim/trim.module.ts
- apps/web-giddh/src/app/shared/helpers/pipes/trim/trim.pipe.ts
https://app.clickup.com/t/33dp7r
> feat: Prateek | Test | Make cancellation remark field mandatory

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/gst.component.ts
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
> shalinee | TEST| added clickoutside funcationality to GSTR sidebar

- apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/39a4c2
> Stage sanity - Taxes are not coming on pending>preview page and generate page when applied on the entry

- apps/web-giddh/src/assets/css/style-1.scss
> prod | GIDK-37dnmk | Aditi | RCM pop up in ledger and PB

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | text issue fixed

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts
- apps/web-giddh/src/app/shared/purchase-send-email/purchase-send-email.component.html
- apps/web-giddh/src/assets/locale/en.json
- apps/web-giddh/src/assets/locale/hi.json
- apps/web-giddh/src/assets/locale/mr.json
- apps/web-giddh/src/assets/locale/purchase-order/en.json
- apps/web-giddh/src/assets/locale/purchase-order/hi.json
- apps/web-giddh/src/assets/locale/purchase-order/mr.json
https://app.clickup.com/t/39ee66
> Test - Fixed Prod Sanity Issues

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | stage | resolved CSS conflict

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | beta | resolved CSS conflict

- apps/web-giddh/src/app/userDetails/userDetails.component.scss
> test | GIDK-39aj49 | Aditi | table design of user profile>session

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/33cdnr
> Stage - Round off is not getting applied on update invoice flow

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/33cdnr
> Beta - Round off is not getting applied on update invoice flow

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/3bc3d4
> Test - Do not show Change entry date pop up in update purchase bill date flow

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/33cdnr
> Prod - Round off is not getting applied on update invoice flow

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/2qf6cp
> beta | GIDK-2qf6cp | Aditi | inventory and ledger issues

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/2qf6cp
> stage | GIDK-2qf6cp | Aditi | inventory and ledger issues

- apps/web-giddh/src/app/userDetails/userDetails.component.scss
https://app.clickup.com/t/39aj49
> beta | GIDK-39aj49 | Aditi | table design of user profile>session

- apps/web-giddh/src/app/userDetails/userDetails.component.scss
https://app.clickup.com/t/39aj49
> stage | GIDK-39aj49 | Aditi | table design of user profile>session

- apps/web-giddh/src/app/gst/gstR3/gstR3.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/33bjv6
https://app.clickup.com/t/2xc5zq
> fix: Prateek | Test | GST issues #33bjv6, #2xc5zq

- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.scss
- apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.ts
- apps/web-giddh/src/app/gst/gstR1/gstR1.component.ts
- apps/web-giddh/src/app/gst/gstR2/gstR2.component.ts
> refactor: Prateek | Test | Resolve code review comments

- apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.scss
> fix: Top of GST sidebar

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/environments/environment.stage.ts
- apps/web-giddh/src/meta/yodlee-success.html
- apps/web-giddh/webpack.stage.partial.js
> Change API release URL

- apps/web-giddh/src/app/userDetails/userDetails.component.scss
https://app.clickup.com/t/39aj49
> prod | GIDK-39aj49 | Aditi | table design of user profile>session

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/2qf6cp
> prod | GIDK-2qf6cp | Aditi | inventory and ledger issues

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.html
- apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.ts
- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.ts
https://app.clickup.com/t/2k9fpj
> fix: GIDK-#2k9fpj | Prateek | Test | Disable GSTR3B and GSTR2 in sidebar on custom range selection

- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/1v8ut7
> fix: GIDK-#1v8ut7 | Prateek | Stage | Prod - From template when user removes the notes then also it is displaying default notes

- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/1v8ut7
> fix: GIDK-#1v8ut7 | Prateek | Beta | Prod - From template when user removes the notes then also it is displaying default notes

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.html
- apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.ts
- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.ts
https://app.clickup.com/t/2k9fpj
> fix: GIDK-#2k9fpj | Prateek | Stage | Disable GSTR3B and GSTR2 in sidebar on custom range selection

- apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | reasponsive work

- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.scss
> shalinee | TEST | correct border issue on CMD+K popup

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/2xgr6j
> fix: Prateek | Test | Issue #3bgjmq, #39j8zg, #39j85a, #3bgmdf, #3bgezr, #3bhzzv

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2xgr6j
> fix: #3db5vj | Prateek | Test |  Test < User is not able to view the 'Remove' option in credit note page when there is only one linked sales invoice

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
https://app.clickup.com/t/3dbnx8
> Test - Pagination is not appearing on the aging report page

- README.md
https://app.clickup.com/t/3dbkde
> GIDK-#3dbkde | SAGAR | TEST | Create user guide in readme file for new joinee

- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.scss
> shalinee | stage | correct close button border

- apps/web-giddh/src/app/theme/command-k/command.k.component.html
- apps/web-giddh/src/app/theme/command-k/command.k.component.scss
> shalinee | prod | resolved UI issue

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
https://app.clickup.com/t/3dbnx8
> Stage - Pagination is not appearing on the aging report page

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
https://app.clickup.com/t/3dbnx8
> Prod - Pagination is not appearing on the aging report page

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
https://app.clickup.com/t/3dbnx8
> Beta - Pagination is not appearing on the aging report page

- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
> Stage - Updated translation

- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
> Test - Updated translation

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.ts
- apps/web-giddh/src/app/invoice/invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/vat-report/transactions/vatReportTransactions.component.ts
> Test - Removed unused imports and removed code to set page title from component

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.ts
- apps/web-giddh/src/app/invoice/invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/vat-report/transactions/vatReportTransactions.component.ts
> Stage - Removed unused imports and removed code to set page title from component

- apps/web-giddh/src/app/models/api-models/AdvanceReceiptsAdjust.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/2xgr6j
> fix: Prateek | Test | Issue #3bfu9c

- apps/web-giddh/src/meta/.ebextensions/spelling.config
> Stage - Updated config file to fix build issue

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
https://app.clickup.com/t/39f9v2
> fix: GIDK-#39f9v2 | Prateek | Test | Test - Cancel invoice pop up is not closing in one time

- apps/web-giddh/src/app/settings/settings.component.html
https://app.clickup.com/t/3dj912
> stage | GIDK-3dj912 | Aditi | tabs issue fixed

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
https://app.clickup.com/t/39f9v2
> fix: GIDK-#39f9v2 | Prateek | Beta | Test - Cancel invoice pop up is not closing in one time

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
https://app.clickup.com/t/39f9v2
> fix: GIDK-#39f9v2 | Prateek | Stage | Test - Cancel invoice pop up is not closing in one time

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
https://app.clickup.com/t/39f9v2
> fix: GIDK-#39f9v2 | Prateek | Prod | Test - Cancel invoice pop up is not closing in one time

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | correct width of hamburger icon

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2q99pj
> feat: GIDK-#2q99pj | Prateek | Stage | Changes in logo size in invoice template

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2q99pj
> feat: GIDK-#2q99pj | Prateek | Beta | Changes in logo size in invoice template

- apps/web-giddh/src/app/services/ledger.service.ts
- apps/web-giddh/src/assets/locale/ledger/en.json
https://app.clickup.com/t/1zcge6
> fix: clickup-#1zcge6 | Prateek | Beta | Test- Map Transactions not working in eledger

- apps/web-giddh/src/app/services/ledger.service.ts
- apps/web-giddh/src/assets/locale/ledger/en.json
https://app.clickup.com/t/1zcge6
> fix: clickup-#1zcge6 | Prateek | Stage | Test- Map Transactions not working in eledger

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/3dj9dr
> Test - Side menu data is not changing when language setting changes

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/3dj9dr
> Stage - Side menu data is not changing when language setting changes

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/3bfu9c
> fix: Prateek | Test | Roundoff issue

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | TEST | correct pageheading issue

- apps/web-giddh/src/app/services/ledger.service.ts
- apps/web-giddh/src/assets/locale/ledger/en.json
https://app.clickup.com/t/1zcge6
> fix: clickup-#1zcge6 | Prateek | Prod | Test- Map Transactions not working in eledger

- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
https://app.clickup.com/t/2q99pj
> feat: GIDK-#2q99pj | Prateek | Prod | Changes in logo size in invoice template

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: clickup-#2zgx8y | Prateek | Test | Prod - PDF is not coming after invoice update

- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/assets/locale/aside-setting/en.json
> Test - Fixed pagination issue on ledger

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/assets/locale/aside-setting/en.json
- apps/web-giddh/src/assets/locale/aside-setting/mr.json
- apps/web-giddh/src/assets/locale/settings/integration/en.json
- apps/web-giddh/src/assets/locale/settings/integration/hi.json
- apps/web-giddh/src/assets/locale/settings/integration/mr.json
> Stage - Added translation for settings integration

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
https://app.clickup.com/t/3ddpd1
> test | GIDK-3ddpd1 | Aditi | selected page highlighted on menu

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> fix: clickup-#2zgx8y | Prateek | Test | Update condition

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/2x8weq
> fix: clickup-2x8weq | Prateek | Test | Prod - After switching company previous company account is coming and giving error

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: clickup-#2zgx8y | Prateek | Stage | Prod - PDF is not coming after invoice update

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: clickup-#2zgx8y | Prateek | Beta | Prod - PDF is not coming after invoice update

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: clickup-#2zgx8y | Prateek | Prod | Prod - PDF is not coming after invoice update

- apps/web-giddh/src/meta/.ebextensions/spelling.config
> Updated config file to fix build issue

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/services/toaster.service.ts
- apps/web-giddh/src/app/signup/signup.component.html
- apps/web-giddh/src/app/signup/signup.component.ts
> GIDK-#27arn6 | SAGAR |TEST | Wrong Passwords error notifs & description.

- apps/web-giddh/src/app/settings/settings.component.html
https://app.clickup.com/t/3dj912
> test | GIDK-3dj912 | Aditi | tabs issue fixed

- apps/web-giddh/src/app/settings/settings.component.html
https://app.clickup.com/t/3dj912
> beta | GIDK-3dj912 | Aditi | tabs issue fixed

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
> test | GIDK-3ddpd1 | Aditi | hovered item color

- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.html
> Beta - Removed conflict

- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
https://app.clickup.com/t/2hcrq6
email address appearing as per need
> GIDK-#2hcrq6 | SAGAR | TEST | Owner's email id should be automatically displayed in the Receipient's email id tab of export option.

- apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html
> fix: Prateek | Test | Hide the amount in company currency for due when voucher is receipt, adv. receipt, payment or JV when due is 0

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/ledger/components/advance-search/advance-search.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.scss
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.scss
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.scss
- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
> test | GIDK-3ddpcf| button issues solved

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.scss
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/create/components/invoice/templates/template.component.scss
> search-icon border fix

- apps/web-giddh/src/app/models/api-models/tally-sync.ts
- apps/web-giddh/src/app/services/apiurls/tally-sync.ts
- apps/web-giddh/src/app/services/tally-sync.service.ts
- apps/web-giddh/src/app/tallysync/completed/completed.component.html
- apps/web-giddh/src/app/tallysync/completed/completed.component.ts
- apps/web-giddh/src/app/tallysync/inprogress/inprogress.component.html
- apps/web-giddh/src/app/tallysync/inprogress/inprogress.component.ts
- apps/web-giddh/src/assets/locale/tallysync/en.json
- apps/web-giddh/src/assets/locale/tallysync/hi.json
- apps/web-giddh/src/assets/locale/tallysync/mr.json
https://app.clickup.com/t/3hf10g
> Test - Implement progress bar for Voucher import status on Tally Import page

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts
- apps/web-giddh/src/app/shared/purchase-send-email/purchase-send-email.component.html
- apps/web-giddh/src/assets/locale/en.json
- apps/web-giddh/src/assets/locale/hi.json
- apps/web-giddh/src/assets/locale/mr.json
- apps/web-giddh/src/assets/locale/purchase-order/en.json
- apps/web-giddh/src/assets/locale/purchase-order/hi.json
> Fixed v2 Prod Sanity Issues

- apps/web-giddh/src/app/theme/command-k/command.k.component.html
> Test - Fixed code

- apps/web-giddh/src/app/inventory/components/aside-pane/aside-pane.components.scss
- apps/web-giddh/src/app/invoice/settings/invoice.setting.component.scss
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> test | GIDK-3ddpcf | Aditi | button borders

- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/3kb01m
> fix: clickup-#3kb01m | Prateek | Stage | Prod - Entries on the right side i.e. CR side in ledger is not getting displayed when user access magic

- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/3kb01m
> fix: clickup-#3kb01m | Prateek | Beta | Prod - Entries on the right side i.e. CR side in ledger is not getting displayed when user access magic

- apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/3kb01m
> fix: clickup-#3kb01m | Prateek | Prod | Prod - Entries on the right side i.e. CR side in ledger is not getting displayed when user access magic

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.component.scss
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/inventory.component.html
- apps/web-giddh/src/app/inventory/inventory.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.html
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.html
- apps/web-giddh/src/app/purchase/purchase-record/component/purchase-record.component.scss
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.scss
- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.scss
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.html
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.html
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.html
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/3ddpcw
> test | GIDK-3ddpcw | Aditi | hamburger shifting and remove header

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/39ht08
> fix: clickup-#39ht08 | In update debit note flow linked sales invoice is getting removed

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/3ddpd1
> fix: Close the rest opened item when a new item is clicked in primary sidebar

- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.scss
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
> test | header remove done

- apps/web-giddh/src/app/gst/gst-sidebar/gst-sidebar.component.ts
> refactor: Change the type of @Input for GST sidebar

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 27by7a hamburger user

- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
https://app.clickup.com/t/25aukk
> fix: clickup-#25aukk | Prateek | Test | Prod -In company mode update manufacturing should be in view only mode

- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.ts
> test | PR changes of website issues

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35d52e
> fix: clickup-#35d52e | Prateek | Test | Prod - Cash/bank accounts are not coming in payment mode while generating invoice from invoice>pending page.

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/xfbpjq
> fix: clickup-#xfbpjq | Prateek | Test | Prod - ITC section not visible in ledger

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/onboarding/onboarding.component.html
> number fix

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/xfbpjq
> fix: clickup-#xfbpjq | Prateek | Prod | Prod - ITC section not visible in ledger

- apps/web-giddh/src/app/app.constant.ts
https://app.clickup.com/t/3n9q0b
> Somya | prod | GIDK-3n9q0b | contact number fix

- apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.html
- apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.html
https://app.clickup.com/t/3ddpcw
> beta | GIDK-3ddpcw | Aditi | remove mobile screen

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
https://app.clickup.com/t/3ndx3z
> Test - Unable to change the Expected Delivery Date on Create PO page

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
https://app.clickup.com/t/3ndx3z
> Stage - Unable to change the Expected Delivery Date on Create PO page

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
https://app.clickup.com/t/3ndx3z
> Beta - Unable to change the Expected Delivery Date on Create PO page

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
https://app.clickup.com/t/3ndx3z
> Prod - Unable to change the Expected Delivery Date on Create PO page

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/3ddpd1
> fix: clickup-#3ddpd1 | Prateek | Test | Popover not closing when navigation occurs

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.ts
- apps/web-giddh/src/app/models/api-models/Invoice.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/3ncu17
> feat: clickup-#3ncu17 | Prateek | Test | Add advance search in E-invoice v4

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35d52e
> fix: clickup-#35d52e | Prateek | Stage | Prod - Cash/bank accounts are not coming in payment mode while generating invoice from invoice>pending page.

- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
https://app.clickup.com/t/25aukk
> fix: clickup-#25aukk | Prateek | Stage | Prod -In company mode update manufacturing should be in view only mode

- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
https://app.clickup.com/t/25aukk
> fix: clickup-#25aukk | Prateek | Beta | Prod -In company mode update manufacturing should be in view only mode

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/39ht08
> fix: clickup-#39ht08 | Prateek | Stage | In update debit note flow linked sales invoice is getting removed 

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35d52e
> fix: clickup-#35d52e | Prateek | Beta | Prod - Cash/bank accounts are not coming in payment mode while generating invoice from invoice>pending page.

- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.html
- apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts
https://app.clickup.com/t/25aukk
> fix: clickup-#25aukk | Prateek | Prod | Prod -In company mode update manufacturing should be in view only mode

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/35d52e
> fix: clickup-#35d52e | Prateek | Prod | Prod - Cash/bank accounts are not coming in payment mode while generating invoice from invoice>pending page.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/39ht08
> fix: clickup-#39ht08 | Prateek | Beta | In update debit note flow linked sales invoice is getting removed 

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/39ht08
> fix: clickup-#39ht08 | Prateek | Prod | In update debit note flow linked sales invoice is getting removed 

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/services/toaster.service.ts
- apps/web-giddh/src/app/signup/signup.component.html
- apps/web-giddh/src/app/signup/signup.component.ts
> clickup-#27arn6 | Sagar | Stage | Wrong Passwords error notifs & description.

- apps/web-giddh/src/app/signup/signup.component.html
- apps/web-giddh/src/app/signup/signup.component.ts
> refactor: Prateek | Test | Remove commented code

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/services/toaster.service.ts
- apps/web-giddh/src/app/signup/signup.component.html
- apps/web-giddh/src/app/signup/signup.component.ts
> clickup-#27arn6 | Sagar | Beta | Wrong Passwords error notifs & description.

- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/services/toaster.service.ts
- apps/web-giddh/src/app/signup/signup.component.html
- apps/web-giddh/src/app/signup/signup.component.ts
> clickup-#27arn6 | Sagar | Prod | Wrong Passwords error notifs & description.

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: clickup-#2deebn | Prateek | Test | Test - On clicking 'other tax' check box the side panel is not displaying proper

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/environments/environment.stage.ts
- apps/web-giddh/src/meta/yodlee-success.html
- apps/web-giddh/webpack.stage.partial.js
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#8257
> Revert "Change API release URL"

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/1v8uj0
> fix: clickup-#1v8uj0 | Prateek | Test | Cannot create templates other than A & E

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/1v8uj0
> fix: clickup-#1v8uj0 | Prateek | Stage | Cannot create templates other than A & E

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: clickup-#2deebn | Prateek | Stage | Test - On clicking 'other tax' check box the side panel is not displaying proper

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: clickup-#2deebn | Prateek | Beta | Test - On clicking 'other tax' check box the side panel is not displaying proper

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
> shalinee | test | correct amount field  currency symbol and code

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
> Gidk 23ghp7 amount beta

- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.html
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.scss
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/3nj6b6
https://app.clickup.com/t/3nj73t
> fix: clickup-#3nj6b6 | Prateek | Test | Import bank statement points raise by sales team

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/ledger.component.html
> Gidk 23ghp7 amount prod

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html
- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.scss
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.html
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.scss
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.scss
> test | Aditi | petty cash header fix

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/1v8uj0
> clickup-#1v8uj0 | Prateek | Beta | Cannot create templates other than A & E 

- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/1v8uj0
> fix: clickup-#1v8uj0 | Prateek | Prod | Cannot create templates other than A & E

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
> fix: clickup-#2deebn | Prateek | Prod | Test - On clicking 'other tax' check box the side panel is not displaying proper

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html
- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.scss
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.html
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.scss
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.scss
> beta | Aditi | petty cash header fix

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html
- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.scss
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.html
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.scss
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.scss
> stage | Aditi | petty cash header fix

- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html
- apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.scss
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.html
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.scss
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.scss
> prod | Aditi | petty cash header fix

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> Test - Readded removed code

- apps/web-giddh/src/app/all-items/all-item.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/helpers/allItems.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/3qbuaa
> Test - Collapse view is not retaining when switching module in collapse view

- apps/web-giddh/src/app/settings/settings.component.ts
> Test - Blank sidebar issue on settings > taxes

- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.html
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.scss
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/3nj6b6
https://app.clickup.com/t/3nj73t
> fix: clickup-#3nj6b6 | Prateek | Beta | Import bank statement points raise by sales team

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.ts
- apps/web-giddh/src/app/models/api-models/Invoice.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/3ncu17
> feat: clickup-#3ncu17 | Prateek | Stage | Add advance search in E-invoice v4

- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.html
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.scss
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/3nj6b6
https://app.clickup.com/t/3nj73t
> fix: clickup-#3nj6b6 | Prateek | Stage | Import bank statement points raise by sales team

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
https://app.clickup.com/t/3dbpte
> fix: clickup-#3dbpte | Prateek | Test | Not able to see the uploaded PB

- apps/web-giddh/src/app/settings/settings.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/tax-sidebar/tax-sidebar.component.html
- apps/web-giddh/src/app/shared/tax-sidebar/tax-sidebar.component.scss
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
> Sidebar issue

- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/3qe50m
https://app.clickup.com/t/3qbu0v
> Test - Fixed bugs

- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.html
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.scss
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.ts
> fix: clickup-3nj6gx | Prateek | Beta | Revert client side check for PDF password protection

- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.html
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.scss
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.ts
> fix: clickup-3nj6gx | Prateek | Test | Revert client side check for PDF password protection

- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.html
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.scss
- apps/web-giddh/src/app/ledger/components/import-statement/import-statement.component.ts
> fix: clickup-3nj6gx | Prateek | Stage | Revert client side check for PDF password protection

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/environments/environment.stage.ts
- apps/web-giddh/src/meta/yodlee-success.html
- apps/web-giddh/webpack.stage.partial.js
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#8454
> Revert "Change to API release URL"

- apps/web-giddh/src/app/services/db.service.ts
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
- apps/web-giddh/src/assets/locale/en.json
- apps/web-giddh/src/assets/locale/hi.json
- apps/web-giddh/src/assets/locale/mr.json
https://app.clickup.com/t/3ng46v
> fix: clickup-#3ng46v | Prateek | Test | Accounts are not updating in side menu bar

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> refactor: Remove commented code

- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/services/http.interceptor.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
> feat: clickup-#3qftyd | Prateek | Test | Add support of voucherVersion

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/318v4z
> Ravinder | Stage | On vouchers set word limit to 100 characters on the entry description

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | plan-wrapper UI fixed

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.scss
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
> test | GIDK-3ddpcq | Aditi | branch address

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.scss
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
> beta | GIDK-3ddpcq | Aditi | branch address

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.scss
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
> stage | GIDK-3ddpcq | Aditi | branch address

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/3dbpte
> fix: clickup-#3dbpte | Aditi-Prateek | Stage | Prod - Unable to see attachment on Purchase bill it is PDF type

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/3dbpte
> fix: clickup-#3dbpte | Aditi-Prateek | Beta | Prod - Unable to see attachment on Purchase bill it is PDF type

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/3dbpte
> fix: clickup-#3dbpte | Aditi-Prateek | Prod | Prod - Unable to see attachment on Purchase bill it is PDF type

- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.scss
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.html
- apps/web-giddh/src/app/settings/other-settings/other-settings.component.scss
- apps/web-giddh/src/app/settings/personal-information/personal-information.component.scss
> prod | GIDK-3ddpcq | Aditi | branch address

- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/3qe50m
https://app.clickup.com/t/3qbu0v
> Ravinder | Stage | From Setting>back button user is not navigating to previously accessed page

- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/3qe50m
https://app.clickup.com/t/3qbu0v
> Ravinder | Beta | From Setting>back button user is not navigating to previously accessed page

- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/3qe50m
https://app.clickup.com/t/3qbu0v
> Ravinder | Prod | From Setting>back button user is not navigating to previously accessed page

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/318v4z
> Ravinder | Beta | On vouchers set word limit to 100 characters on the entry description

- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/3qbuaa
> Ravinder - Test - Fixed auto expand issue

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.ts
- apps/web-giddh/src/app/models/api-models/Invoice.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/3ncu17
> feat: clickup-#3ncu17 | Prateek | Beta | Add advance search in E-invoice v4

- apps/web-giddh/src/app/actions/settings/profile/settings.profile.action.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> fix: clickup-3qftyd | Prateek | Test | Voucher version issue

- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/vat-report/transactions/vatReportTransactions.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | updated shoGst function

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | added css nesting

- apps/electron-giddh/src/index.ts
- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/services/general.service.ts
https://app.clickup.com/t/3keu2z
> Ravinder - Test - Fixed Google login isue

- apps/electron-giddh/src/index.ts
- apps/web-giddh/src/app/actions/login.action.ts
- apps/web-giddh/src/app/services/general.service.ts
https://app.clickup.com/t/3keu2z
> Ravinder - Stage - Fixed Google login isue

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts
- apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
- apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/invoice.ui.data.service.ts
- apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/318v4z
> Ravinder | Prod | On vouchers set word limit to 100 characters on the entry description

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.ts
- apps/web-giddh/src/app/models/api-models/Invoice.ts
- apps/web-giddh/src/assets/locale/invoice/en.json
- apps/web-giddh/src/assets/locale/invoice/hi.json
- apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/3ncu17
> feat: clickup-#3ncu17 | Prateek | Prod | Add advance search in E-invoice v4

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | corrected css code

- apps/web-giddh/src/meta/.htaccess
https://app.clickup.com/t/27b7dq
> Ravinder | Test | Redirecting http to https for TEST env

- apps/web-giddh/src/meta/.htaccess
> Test - Redirecting http to https for TEST env

- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/invoice/preview/models/confirmation/confirmation.model.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/VM.ts
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.ts
- apps/web-giddh/src/app/welcome/welcome.component.ts
> Ravinder | Test | Fixed UI Exceptions

- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/invoice/preview/models/confirmation/confirmation.model.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/VM.ts
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.ts
- apps/web-giddh/src/app/welcome/welcome.component.ts
> Ravinder | Stage | Fixed UI Exceptions

- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/invoice/preview/models/confirmation/confirmation.model.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/VM.ts
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.ts
- apps/web-giddh/src/app/welcome/welcome.component.ts
> Ravinder | Beta | Fixed UI Exceptions

- apps/web-giddh/src/app/vat-report/vatReport.component.html
> shalinee | stage | correct DIV tag

- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html
- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
https://app.clickup.com/t/1v9ake
> Ravinder | Test | details of different company's plan showing on the subscription page when user have multiple companies

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/1n9wxk
> Ravinder - Test - Purchase ledger is highlighted in Ledger Menu when we navigate to ledger from Vendor module via Go to ledger option

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
> shalinee | test| added function

- apps/web-giddh/src/app/all-items/all-item.component.ts
- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/tax-sidebar/tax-sidebar.component.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/3va5ww
> Ravinder | Test | GSTR1, GSTR2 and GSTR3 options should not display as disabled in case of Single GSTIN number

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/services/apiurls/ledger.api.ts
- apps/web-giddh/src/app/services/ledger.service.ts
- apps/web-giddh/src/assets/locale/ledger/en.json
- apps/web-giddh/src/assets/locale/ledger/hi.json
- apps/web-giddh/src/assets/locale/ledger/mr.json
https://app.clickup.com/t/39dc9v
> Ravinder | Test | Provide support of refresh and delete bank transaction from ledger

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/1n9wxk
> Ravinder | Stage | Purchase ledger is highlighted in Ledger Menu when we navigate to ledger from Vendor module via "Go to ledger" option

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/1n9wxk
> Ravinder | Beta | Purchase ledger is highlighted in Ledger Menu when we navigate to ledger from Vendor module via "Go to ledger" option

- apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.html
- apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
https://app.clickup.com/t/29dagr
> feat: clickup-#29dagr | Prateek | Test |  Modifications in download voucher options (Invoice)

- apps/web-giddh/src/app/all-items/all-item.component.ts
- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/tax-sidebar/tax-sidebar.component.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/3va5ww
> Ravinder | Stage | GSTR1, GSTR2 and GSTR3 options should not display as disabled in case of Single GSTIN number

- apps/web-giddh/src/app/all-items/all-item.component.ts
- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/tax-sidebar/tax-sidebar.component.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/3va5ww
> Ravinder | Beta | GSTR1, GSTR2 and GSTR3 options should not display as disabled in case of Single GSTIN number

- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/invoice/preview/models/confirmation/confirmation.model.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/settings/create-address/create-address.component.ts
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/VM.ts
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.ts
- apps/web-giddh/src/app/welcome/welcome.component.ts
> Ravinder | Prod | Fixed UI Exceptions

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/1n9wxk
> Ravinder | Prod | Purchase ledger is highlighted in Ledger Menu when we navigate to ledger from Vendor module via "Go to ledger" option

- apps/web-giddh/src/app/all-items/all-item.component.ts
- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/gst.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/tax-sidebar/tax-sidebar.component.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/3va5ww
> Ravinder | Prod | GSTR1, GSTR2 and GSTR3 options should not display as disabled in case of Single GSTIN number

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
https://app.clickup.com/t/27c2u2
> fix: GIDK-#27c2u2 | Prateek | Stage | Prod>Balance Due and Status is not showing correctly while adjusting sales Debit note with Cash Receipt

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
https://app.clickup.com/t/27c2u2
> fix: GIDK-#27c2u2 | Prateek | Beta | Prod>Balance Due and Status is not showing correctly while adjusting sales Debit note with Cash Receipt

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
https://app.clickup.com/t/27c2u2
> fix: GIDK-#27c2u2 | Prateek | Prod | Prod>Balance Due and Status is not showing correctly while adjusting sales Debit note with Cash Receipt

- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
https://app.clickup.com/t/1v9vt2
> Ravinder | Test | Error 400 Redirect Uri Mismatch

- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
https://app.clickup.com/t/1v9vt2
> Ravinder | Stage | Error 400 Redirect Uri Mismatch

- apps/web-giddh/src/app/invoice/invoice.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
> shalinee | test | pr issue solved

- apps/web-giddh/src/app/invoice/invoice.component.ts
- apps/web-giddh/src/app/settings/profile/setting.profile.component.ts
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.component.ts
> shalinee | stage | PR issue solved

- apps/web-giddh/src/app/shared/header/header.component.html
https://app.clickup.com/t/35ajdc
> Ravinder | Test | Fixed Issue

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
> shalinee | stage | margin correction

- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
https://app.clickup.com/t/1v9vt2
> Ravinder | Beta | Error 400 Redirect Uri Mismatch

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/2x9gx8
> Ravinder | Stage | Country field is displayed as blank for the Account in master on accessing the account for the first time after login

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/2x9gx8
> Ravinder | Beta | Country field is displayed as blank for the Account in master on accessing the account for the first time after login

- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html
- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
https://app.clickup.com/t/1v9ake
> Ravinder | Stage | details of different company's plan showing on the subscription page when user have multiple companies

- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html
- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
https://app.clickup.com/t/1v9ake
> Ravinder | Beta | details of different company's plan showing on the subscription page when user have multiple companies

- apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts
- apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.html
- apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts
- apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.html
- apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/shared/send-email-invoice/send-email-invoice.component.html
- apps/web-giddh/src/app/shared/send-email-invoice/send-email-invoice.component.ts
- apps/web-giddh/src/assets/locale/invoice/download-or-send-mail/en.json
- apps/web-giddh/src/assets/locale/invoice/download-or-send-mail/hi.json
- apps/web-giddh/src/assets/locale/invoice/download-or-send-mail/mr.json
- apps/web-giddh/src/assets/locale/invoice/send-email/en.json
- apps/web-giddh/src/assets/locale/invoice/send-email/hi.json
- apps/web-giddh/src/assets/locale/invoice/send-email/mr.json
https://app.clickup.com/t/29dagr
> feat: clickup-#29dagr |  Prateek | Test | Add Original copy support on all the modules that have Send or Download modal

- apps/web-giddh/src/app/vat-report/vatReport.component.html
> shalinee | stage | correct multilang code

- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/2x9gx8
> Ravinder | Prod | Country field is displayed as blank for the Account in master on accessing the account for the first time after login

- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
https://app.clickup.com/t/1v9vt2
> Ravinder | Prod | Error 400 Redirect Uri Mismatch

- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.html
- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
https://app.clickup.com/t/1v9ake
> Ravinder | Prod | details of different company's plan showing on the subscription page when user have multiple companies

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
> test | GIDK-3nfxzv | Aditi | repeated icons issue

- apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
https://app.clickup.com/t/3xfm9q
> Ravinder | Test | Prod sanity - Tax apply from date is not updating on UI

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
> shalinee | test | added missing double quote

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
> Gidk 3xfxc6 z index

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://github.com/Walkover-Web-Solution/Giddh-New-Angular4-App.git
> GIDK-#2nct1q | SAGAR | TEST | Ledger transactions are not showing when changing local date range after applying advance search

- apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
https://app.clickup.com/t/3xfm9q
> Ravinder | Stage | Prod sanity - Tax apply from date is not updating on UI

- apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
https://app.clickup.com/t/3xfm9q
> Ravinder | Beta | Prod sanity - Tax apply from date is not updating on UI

- apps/web-giddh/src/app/shared/aside-menu-create-tax/aside-menu-create-tax.component.ts
https://app.clickup.com/t/3xfm9q
> Ravinder | Prod | Prod sanity - Tax apply from date is not updating on UI

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/permissions/components/details/permission.details.html
> shalinee | test | added hamburger icon and align ledger thead

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/permissions/components/details/permission.details.html
> shalinee | stage | added hamburger icon and align ledger thead

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/permissions/components/details/permission.details.html
> shalinee | beta | added hamburger icon and align ledger thead

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/purchase-advance-search/purchase-advance-search.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | stage | PO responsive code cherrypick

- apps/web-giddh/src/app/ledger/ledger.component.ts
> GIDK-#2nct1q | SAGAR | STAGE | Ledger transactions are not showing when changing local date range after applying advance search

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
> shalinee | stage | correct HSN code dropdown

- README.md
https://app.clickup.com/t/3dbkde
> GIDK-#39dc9v | SAGAR | STAGE | Create user guide in readme file for new joinee

- README.md
https://app.clickup.com/t/3dbkde
> GIDK-#39dc9v | SAGAR | BETA | Create user guide in readme file for new joinee

- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
> shalinee | stage | remove mr-0 class

- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
- apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
- apps/web-giddh/src/assets/locale/en.json
https://app.clickup.com/t/2785bj
> Ravinder | Stage | User is not able to access the ledger shared with it via Ledger > Share Ledger option

- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
- apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
- apps/web-giddh/src/assets/locale/en.json
https://app.clickup.com/t/2785bj
> Ravinder | Beta | User is not able to access the ledger shared with it via Ledger > Share Ledger option

- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
- apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
- apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
- apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
- apps/web-giddh/src/assets/locale/en.json
https://app.clickup.com/t/2785bj
> Ravinder | Prod | User is not able to access the ledger shared with it via Ledger > Share Ledger option

- apps/web-giddh/src/app/ledger/ledger.component.scss
- apps/web-giddh/src/app/permissions/components/details/permission.details.html
> shalinee | prod | added hamburger icon and align ledger thead

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/purchase-advance-search/purchase-advance-search.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 318zae po beta

- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.module.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.module.ts
- apps/web-giddh/src/app/sales/aside-menu-sales-other-taxes/aside-menu-sales-other-taxes.module.ts
- apps/web-giddh/src/app/sales/sales.module.ts
- apps/web-giddh/src/app/services/ledger.service.ts
https://app.clickup.com/t/3xdked
> perf(Ledger): clickup-3xdked | Prateek | Test | Optimize giddh v3

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/3tca9y
> Ravinder | Test | Fixed branch list issue with api permission error

- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/2b84ey
> GIDK-#2b84ey | Sagar | STAGE | User is not able to remove the tax applied on the account group in master

- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/2b84ey
> GIDK-#2b84ey | Sagar | BETA| User is not able to remove the tax applied on the account group in master

- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
https://app.clickup.com/t/2hcrq6
> GIDK-#2hcrq6 | SAGAR | STAGE | Owner's email id should be automatically displayed in the Receipient's email id tab of export option.

- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
https://app.clickup.com/t/2hcrq6
> GIDK-#2hcrq6 | SAGAR | BETA | Owner's email id should be automatically displayed in the Receipient's email id tab of export option.

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/238hy0
> GIDK-#238hy0| SAGAR |STAGE| On invoice get all page, a information message is keep coming when there is no advance receipt to adjust invoice

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/238hy0
> GIDK-#238hy0| SAGAR| BETA | On invoice get all page, a information message is keep coming when there is no advance receipt to adjust invoice

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss
- apps/web-giddh/src/app/purchase/purchase-advance-search/purchase-advance-search.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> Gidk 318zae po prod

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
> Ravinder | Test | Implemented Today functionality on customer/vendor page

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> Ravinder | Test | Fixed Code Issue

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> Ravinder | Stage | Fixed Code Issue

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> Ravinder | Beta | Fixed Code Issue

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | UI sidebar correction done

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/models/api-models/Contact.ts
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/services/general.service.ts
https://app.clickup.com/t/3xjkxg
> fix: clickup-3nfxzv | Prateek | Test | Issues related to Customer/Vendor new design

- apps/web-giddh/src/app/new-vs-old-Invoices/new-vs-old-Invoices.component.html
> Ravinder | Prod | Fixed Code Issue

- apps/web-giddh/src/app/expenses/expenses.component.ts
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/models/api-models/Invoice.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/store/Invoice/invoice.reducer.ts
> Ravinder | Test | Local date range is not updated when Today option is selected in Universal Date picker

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/238hy0
> GIDK-#238hy0| SAGAR |PROD | On invoice get all page, a information message is keep coming when there is no advance receipt to adjust invoice

- README.md
https://app.clickup.com/t/3dbkde
> GIDK-#39dc9v | SAGAR | PROD | Create user guide in readme file for new joinee

- apps/web-giddh/src/app/shared/validate-section-permission/validate-section-permission.directive.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/3xcgd1
> Ravinder | Test | Updated design of no permission text

- apps/web-giddh/src/app/ledger/ledger.component.scss
https://app.clickup.com/t/39dc9v
> Ravinder | Test | Adjusted Refresh icon size

- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.scss
https://app.clickup.com/t/39dc9v
> test | GIDK-39dc9v | Aditi | refresh icon

- apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.scss
- apps/web-giddh/src/app/expenses/expenses.component.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
> Ravinder | Test | Integrated  on petty cash and fixed issues

- apps/web-giddh/src/app/settings/settings.component.scss
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/header/header.component.html
- apps/web-giddh/src/app/shared/header/header.component.scss
> shalinee | test | setting sidebar issue fixed

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts
> shalinee | test | remove search option function

- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/2b84ey
> GIDK-#2b84ey | Sagar | PROD| User is not able to remove the tax applied on the account group in master

- apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts
https://app.clickup.com/t/2hcrq6
> GIDK-#2hcrq6 | SAGAR | PROD | Owner's email id should be automatically displayed in the Receipient's email id tab of export option.

- apps/web-giddh/src/app/expenses/expenses.module.ts
- apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.html
- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/3xdked
> fix: clickup-#3xdked | Prateek | Test | Ledger issues

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.html
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.scss
- apps/web-giddh/src/app/shared/header/components/hamburger-menu/hamburger-menu.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.ts
https://app.clickup.com/t/41jy1n
> Ravinder | Test | Functionality issues of Update setting sidebar and remove disability from setting and menu icon from setting page

- .github/workflows/manual.yml
- angular.json
- apps/web-giddh/tsconfig.app.json
- package.json
https://app.clickup.com/t/3xdked
> fix: clickup-#3xdked | Prateek | Test | Electron build failure issue and Enable Win build for lower env.

- .github/workflows/build.yml
https://app.clickup.com/t/41cdv7
> feat: clickup-#41cdv7 | Prateek | Test | Update variable names in workflow

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
> test | GIDK-3xfxc6 | Aditi | changes after testing

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
> shalinee | test | company branch name ellipsis

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
> test | GIDK-3xfxc6 | Aditi | icon remove

- apps/web-giddh/src/app/app.module.ts
- apps/web-giddh/src/app/app.routes.ts
- apps/web-giddh/src/app/models/defaultMenus.ts
- apps/web-giddh/src/app/routes-array.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
> feat: Prateek | Test | Prod - Hide Tally from Giddh and Wordpress website

- apps/web-giddh/src/app/app.module.ts
> fix: Prateek | Test | Store issue of immutability, compress runtime check for some time

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/3ng8jj
> test | GIDK-3ng8jj | Aditi | company branch work done

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/43jk1m
> fix: clickup-#43jk1m | Prateek | Test | Prod - State not provided error is displayed on second try of creating the cash invoice

- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
> feat: clickup-#43jtew | Prateek | Test | Prod - Hide Tally from Giddh and Wordpress website

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Ravinder | Test | Hide SMS tab and settings from UI

- apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
- apps/web-giddh/src/environments/environment.stage.ts
- apps/web-giddh/src/meta/yodlee-success.html
- apps/web-giddh/webpack.stage.partial.js
> Revert: Prod pointing of STAGE

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/43jk1m
> fix: clickup-#43jk1m | Prateek | Stage | Prod - State not provided error is displayed on second try of creating the cash invoice

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/43jk1m
> fix: clickup-#43jk1m | Prateek | Beta | Prod - State not provided error is displayed on second try of creating the cash invoice

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/search/components/search-filter/search-filter.component.html
> Ravinder | Test | Hide sms option from customer/vendor and search page

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/43jk1m
> fix: clickup-#43jk1m | Prateek | Prod | Prod - State not provided error is displayed on second try of creating the cash invoice

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/search/components/search-filter/search-filter.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Ravinder | Stage | Prod UI - Hide "Send Invoice/PB via SMS" option from UI

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/search/components/search-filter/search-filter.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Ravinder | Beta | Prod UI - Hide "Send Invoice/PB via SMS" option from UI

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html
- apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
- apps/web-giddh/src/app/purchase/purchase-setting/purchase-setting.component.html
- apps/web-giddh/src/app/search/components/search-filter/search-filter.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
- apps/web-giddh/src/app/settings/settings.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> Ravinder | Prod | Prod UI - Hide "Send Invoice/PB via SMS" option from UI

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
> Aditi - testing issues of company sidebar

- apps/web-giddh/src/app/onboarding/onboarding.component.html
> fix: clickup-#43jtew | Prateek | Test | Hide Tally on Onboarding page

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
https://app.clickup.com/t/43k7ez
> Ravinder | Test | Add active class on setting sidebar items and apply design same as hover effect and add active class on company name list

- apps/web-giddh/src/app/app.module.ts
- apps/web-giddh/src/app/app.routes.ts
- apps/web-giddh/src/app/models/defaultMenus.ts
- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/routes-array.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
> feat: Prateek | Beta | Prod - Hide Tally from Giddh and Wordpress website

- apps/web-giddh/src/app/app.module.ts
- apps/web-giddh/src/app/app.routes.ts
- apps/web-giddh/src/app/models/defaultMenus.ts
- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/routes-array.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
> feat: Prateek | Stage | Prod - Hide Tally from Giddh and Wordpress website

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2ncuym
> Ravinder | Test | Purchase bill screen is kept loading when linking with purchase order

- apps/web-giddh/src/app/app.module.ts
- apps/web-giddh/src/app/app.routes.ts
- apps/web-giddh/src/app/models/defaultMenus.ts
- apps/web-giddh/src/app/onboarding/onboarding.component.html
- apps/web-giddh/src/app/routes-array.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
> feat: Prateek | Prod | Prod - Hide Tally from Giddh and Wordpress website

- apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
https://app.clickup.com/t/35e2zk
> Ravinder | Test | Inventory setting updated successfully message is displayed even when Decimal After Decimal settings is updated

- apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html
- apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
- apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html
- apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
- apps/web-giddh/src/app/models/api-models/Expences.ts
- apps/web-giddh/src/app/models/api-models/Ledger.ts
https://app.clickup.com/t/33d4n9
> Ravinder | Test | Exchange rate is getting changed when clicked first in exchange rate field and then outside of it

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/1zdprp
> Ravinder | Stage | Imported transactions are getting displayed after the page is refreshed

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/1zdprp
> Ravinder | Beta | Imported transactions are getting displayed after the page is refreshed

- apps/web-giddh/src/app/ledger/ledger.component.ts
> Ravinder | Test | Ledger transactions are not showing when changing local date range after applying advance search

- apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/1zdprp
> Ravinder | Prod | Imported transactions are getting displayed after the page is refreshed

- apps/web-giddh/src/app/ledger/pipes/particular/particular.pipe.ts
https://app.clickup.com/t/3xdked
> fix: Prateek | Test | Resolve code review comments

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
> feat: clickup-#45bmcq | Prateek | Test | Inventory group delete API implementation at UI

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/3ng8jj
> test | GIDK-3ng8jj | Aditi | testing issues of company-branch-1

- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/45f60j
> Ravinder | Test | While refreshing branches from any setting module side bar is getting closed

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/assets/locale/contact/en.json
- apps/web-giddh/src/assets/locale/contact/hi.json
- apps/web-giddh/src/assets/locale/contact/mr.json
https://app.clickup.com/t/45f3a7
> fix: clickup-#45f3a7 | Prateek | Test | Functionality issues in new design implementation

- apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html
https://app.clickup.com/t/45gxy9
> fix: clickup-#45gxy9 | Test - Company currency symbol is not displayed in the foreign debtor ledger

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
https://app.clickup.com/t/45ez9c
> test | Aditi | scroller fix

- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/45f0a2
> Ravinder | Test | Branch sorting issue solved and displayed create branch only for company view

- apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html
- apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
- apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html
- apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
- apps/web-giddh/src/app/models/api-models/Expences.ts
- apps/web-giddh/src/app/models/api-models/Ledger.ts
https://app.clickup.com/t/33d4n9
> Ravinder | Stage | Exchange rate is getting changed when clicked first in exchange rate field and then outside of it

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2ncuym
> Ravinder | Stage | Purchase bill screen is kept loading when linking with purchase order

- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.scss
https://app.clickup.com/t/3xjzyj
> test | GIDK-3nfxzv | Aditi | responsive issues

- apps/web-giddh/src/app/ledger/ledger.component.ts
> Ravinder | Stage | Ledger transactions are not showing when changing local date range after applying advance search

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
- apps/web-giddh/src/app/models/api-models/Expences.ts
- apps/web-giddh/src/app/models/api-models/Ledger.ts
https://app.clickup.com/t/33d4n9
> Ravinder | Beta | Exchange rate is getting changed when clicked first in exchange rate field and then outside of it

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2ncuym
> Ravinder | Beta | Purchase bill screen is kept loading when linking with purchase order

- apps/web-giddh/src/app/ledger/ledger.component.ts
> Ravinder | Beta | Ledger transactions are not showing when changing local date range after applying advance search

- apps/web-giddh/src/app/tb-pl-bs/components/export/bs-export-xls.component.ts
https://app.clickup.com/t/45hm32
> Ravinder | Test | Balance sheet downloaded file name is coming as profitloss.xlsx

- apps/web-giddh/src/app/tb-pl-bs/components/export/bs-export-xls.component.ts
https://app.clickup.com/t/45hm32
> Ravinder | Stage | Balance sheet downloaded file name is coming as profitloss.xlsx

- apps/web-giddh/src/app/tb-pl-bs/components/export/bs-export-xls.component.ts
https://app.clickup.com/t/45hm32
> Ravinder | Beta | Balance sheet downloaded file name is coming as profitloss.xlsx

- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/newLedgerEntryPanel/newLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.html
- apps/web-giddh/src/app/ledger/components/updateLedgerEntryPanel/updateLedgerEntryPanel.component.ts
- apps/web-giddh/src/app/ledger/ledger.component.ts
- apps/web-giddh/src/app/ledger/ledger.vm.ts
- apps/web-giddh/src/app/models/api-models/Expences.ts
- apps/web-giddh/src/app/models/api-models/Ledger.ts
https://app.clickup.com/t/33d4n9
> Ravinder | Prod | Exchange rate is getting changed when clicked first in exchange rate field and then outside of it

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2ncuym
> Ravinder | Prod | Purchase bill screen is kept loading when linking with purchase order

- apps/web-giddh/src/app/ledger/ledger.component.ts
> Ravinder | Prod | Ledger transactions are not showing when changing local date range after applying advance search

- apps/web-giddh/src/app/tb-pl-bs/components/export/bs-export-xls.component.ts
https://app.clickup.com/t/45hm32
> Ravinder | Prod | Balance sheet downloaded file name is coming as profitloss.xlsx

- .github/workflows/manual.yml
https://app.clickup.com/t/41cdv7
> feat: clickup-#41cdv7 | Prateek | Test | Remove credentials from code repo

- apps/web-giddh/src/app/shared/helpers/defaultDateFormat.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.ts
https://app.clickup.com/t/45bqrn
> fix: clickup-#45bqrn | Prateek | Test | Expression change issue in User detail > Session

- apps/web-giddh/src/app/shared/helpers/defaultDateFormat.ts
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.ts
https://app.clickup.com/t/45bqrn
> fix: clickup-#45bqrn | Prateek | Stage | Expression change issue in User detail > Session

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
> test | GIDK-3ng8jj | Aditi | company size

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/aside-inventory.components/aside-inventory.components.ts
- apps/web-giddh/src/app/inventory/inventory.component.html
- apps/web-giddh/src/app/inventory/inventory.component.ts
> fix: clickup-#45bmcq | Prateek | Test | Issue #45hzbt, #45hzbt

- apps/web-giddh/src/app/inventory/inventory.component.ts
> refactor: Rename variable

- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/41deu0
> Ravinder | Test | On sundry debtor/creditors group to assign tax and discount option is not coming

- apps/web-giddh/src/app/settings/financial-year/financial-year.component.html
- apps/web-giddh/src/app/settings/financial-year/financial-year.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/locale/settings/financial-year/en.json
- apps/web-giddh/src/assets/locale/settings/financial-year/hi.json
- apps/web-giddh/src/assets/locale/settings/financial-year/mr.json
https://app.clickup.com/t/2kffkq
> Ravinder | Test | Remove switch financial year option from Financial year module

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/actions/groupwithaccounts.actions.ts
- apps/web-giddh/src/app/actions/inventory/sidebar.actions.ts
- apps/web-giddh/src/app/actions/ledger/ledger.actions.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/VM.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
> Ravinder | Test | Fixed UI Exception

- angular.json
https://app.clickup.com/t/41cdv7
> fix: Prateek | Stage | Add baseHref for development configuration

- angular.json
https://app.clickup.com/t/41cdv7
> fix: Prateek | Test | Add baseHref for development configuration

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts
- apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.ts
https://app.clickup.com/t/45hzbt
> fix: clickup-#45hzbt | Prateek | Test | Show the top group in hierarchy when a group is deleted

- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/47h3dn
> Ravinder | Test | Design angular material datepicker like bootstrap datepicker

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/actions/groupwithaccounts.actions.ts
- apps/web-giddh/src/app/actions/inventory/sidebar.actions.ts
- apps/web-giddh/src/app/actions/ledger/ledger.actions.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/VM.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
> Ravinder | Stage | Fixed UI Exception

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/actions/groupwithaccounts.actions.ts
- apps/web-giddh/src/app/actions/inventory/sidebar.actions.ts
- apps/web-giddh/src/app/actions/ledger/ledger.actions.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/VM.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
> Ravinder | Beta | Fixed UI Exception

- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/41deu0
> Ravinder | Stage | On sundry debtor/creditors group to assign tax and discount option is not coming

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/aside-inventory.components/aside-inventory.components.ts
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts
- apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.html
- apps/web-giddh/src/app/inventory/inventory.component.ts
> feat: clickup-#45bmcq | Prateek | Stage | Inventory group delete API implementation at UI

- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/41deu0
> Ravinder | Beta | On sundry debtor/creditors group to assign tax and discount option is not coming

- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/3xfxc6
> Ravinder | Test | Fixed settings sidebar issues

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/aside-inventory.components/aside-inventory.components.ts
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts
- apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.html
- apps/web-giddh/src/app/inventory/inventory.component.ts
> feat: clickup-#45bmcq | Prateek | Beta | Inventory group delete API implementation at UI 

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/aside-inventory.components/aside-inventory.components.ts
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts
- apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.ts
- apps/web-giddh/src/app/inventory/inventory.component.html
- apps/web-giddh/src/app/inventory/inventory.component.ts
> feat: clickup-#45bmcq | Prateek | Prod | Inventory group delete API implementation at UI 

- apps/web-giddh/src/app/actions/accounts.actions.ts
- apps/web-giddh/src/app/actions/groupwithaccounts.actions.ts
- apps/web-giddh/src/app/actions/inventory/sidebar.actions.ts
- apps/web-giddh/src/app/actions/ledger/ledger.actions.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/VM.ts
- apps/web-giddh/src/app/store/General/general.reducer.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
> Ravinder | Prod | Fixed UI Exception

- apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/41deu0
> Ravinder | Prod | On sundry debtor/creditors group to assign tax and discount option is not coming

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.html
https://app.clickup.com/t/3bj6zw
> Ravinder | Test | In update credit note flow sometimes customer name is not getting prefilled

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/45fg6z
> Ravinder | Test | HO branch should not come in branch dropdown is side bar if company has no branches

- apps/web-giddh/src/app/app.constant.ts
https://app.clickup.com/t/47jt1z
> feat: clickup-#47jt1z | Prateek | Test | Increase the item description limit up to 300 in the voucher template

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/2tgeb8
> Ravinder | Stage | Remove double scroll form invoice preview

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/45fg6z
> Ravinder | Stage | HO branch should not come in branch dropdown is side bar if company has no branches

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/2tgeb8
> Ravinder | Beta | Remove double scroll form invoice preview

- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | issue 10 and zindex issue solved

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2hdc77
> Ravinder | Test | From GSTR 1 page while updating the invoice twice user is getting error

- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/41jy12
> Ravinder | Test | Help side bar is not opening on any of the page of giddh

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> Ravinder | Test | Removed unused code from new company/branch sidebar

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
> Ravinder | Stage | Removed Company branch unused code stage

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.module.ts
- apps/web-giddh/src/app/inventory/inventory.module.ts
- apps/web-giddh/src/app/theme/confirm-modal/confirm-modal.component.ts
> feat: clickup-#3b97q0 | Prateek | Test | Add delete button and confirmation popup on update group and stock on inventory module

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/2tgeb8
> Ravinder | Prod | Remove double scroll form invoice preview

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
> refactor: clickup-#3b97q0 | Prateek | Test | Add access modifier to methods

- apps/web-giddh/src/app/all-items/all-item.component.html
https://app.clickup.com/t/47k6ev
> Ravinder | Test | At all items page GSTR modules are not looking highlighted when

- apps/web-giddh/src/app/contact/contact.component.html
https://app.clickup.com/t/47jxxf
> stage | Aditi | stage-sanity issues

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.scss
- apps/web-giddh/src/app/expenses/expenses.component.ts
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/models/api-models/Invoice.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/store/Invoice/invoice.reducer.ts
> Ravinder | Stage | Local date range is not updated when Today option is selected in Universal Date picker

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2hdc77
> Ravinder | Stage | From GSTR 1 page while updating the invoice twice user is getting error

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2hdc77
> Ravinder | Beta | From GSTR 1 page while updating the invoice twice user is getting error

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
> test | Aditi | PR changes of PROD

- apps/web-giddh/src/app/all-items/all-item.component.html
- apps/web-giddh/src/app/all-items/all-item.component.ts
https://app.clickup.com/t/47k6ev
> Ravinder | Stage | At all items page GSTR modules are not looking highlighted when

- apps/web-giddh/src/app/all-items/all-item.component.html
- apps/web-giddh/src/app/all-items/all-item.component.ts
https://app.clickup.com/t/47k6ev
> Ravinder | Beta | At all items page GSTR modules are not looking highlighted when

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
> stage | Aditi | PR changes of PROD

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/41jy12
> Ravinder | Test | Collapse sidebar by default on invoice/pb/po preview page

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/2hdc77
> Ravinder | Prod | From GSTR 1 page while updating the invoice twice user is getting error

- apps/web-giddh/src/app/all-items/all-item.component.html
- apps/web-giddh/src/app/all-items/all-item.component.ts
https://app.clickup.com/t/47k6ev
> Ravinder | Prod | At all items page GSTR modules are not looking highlighted when

- apps/web-giddh/src/app/app.constant.ts
https://app.clickup.com/t/47jt1z
> feat: clickup-#47jt1z | Prateek | Beta | Increase the item description limit up to 300 in the voucher template

- apps/web-giddh/src/app/app.constant.ts
https://app.clickup.com/t/47jt1z
> feat: clickup-#47jt1z | Prateek | Stage | Increase the item description limit up to 300 in the voucher template

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.scss
- apps/web-giddh/src/app/expenses/expenses.component.ts
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/models/api-models/Invoice.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/store/Invoice/invoice.reducer.ts
> Ravinder | Beta | Local date range is not updated when Today option is selected in Universal Date picker

- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/47h3dn
> Ravinder | Stage | Design angular material datepicker like bootstrap datepicker

- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/47h3dn
> Ravinder | Beta | Design angular material datepicker like bootstrap datepicker

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
- apps/web-giddh/src/app/contact/contact.component.ts
- apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts
- apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts
- apps/web-giddh/src/app/expenses/expenses.component.html
- apps/web-giddh/src/app/expenses/expenses.component.scss
- apps/web-giddh/src/app/expenses/expenses.component.ts
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
- apps/web-giddh/src/app/models/api-models/Invoice.ts
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts
- apps/web-giddh/src/app/store/Invoice/invoice.reducer.ts
> Ravinder | Prod | Local date range is not updated when Today option is selected in Universal Date picker

- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/47h3dn
> Ravinder | Prod | Design angular material datepicker like bootstrap datepicker

- apps/web-giddh/src/app/app.constant.ts
https://app.clickup.com/t/47jt1z
> feat: clickup-#47jt1z | Prateek | Prod | Increase the item description limit up to 300 in the voucher template

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
> feat: clickup-#3b97q0 | Prateek | Test | Change delete group and stock confirmation message

- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/43an1w
> Ravinder | Test | From cmd+G user should redirect to directly on particular group if clicks on create new (group/account)

- apps/web-giddh/src/app/models/api-models/recipt.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/proforma-invoice/services/proforma-invoice-utility.service.ts
- apps/web-giddh/src/app/services/apiurls/sales.api.ts
- apps/web-giddh/src/app/services/sales.service.ts
> feat: clickup-#3qftyd | Prateek | Test | Initial commit: New voucher API integration in voucher module

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.module.ts
- apps/web-giddh/src/app/inventory/inventory.module.ts
- apps/web-giddh/src/app/theme/confirm-modal/confirm-modal.component.ts
> feat: clickup-#3b97q0 | Prateek | Stage | Add delete button and confirmation popup on update group and stock on inventory module

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
https://app.clickup.com/t/41jy12
> Ravinder | Test | Primary Sidebar issue on invoice preview page

- apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
- apps/web-giddh/src/app/accounting/voucher-grid/voucher-grid.component.ts
- apps/web-giddh/src/app/actions/gst-reconcile/GstReconcile.actions.ts
- apps/web-giddh/src/app/billing-details/billingDetail.component.ts
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory-in-out/components/forms/inward-note/inward-note.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/forms/inward-note/inward-note.component.html
- apps/web-giddh/src/app/inventory/components/sidebar-components/stockList.component.ts
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/components/create-stock/sales.create.stock.component.ts
- apps/web-giddh/src/app/proforma-invoice/components/proforma-print-inplace/proforma-print-in-place.component.ts
- apps/web-giddh/src/app/services/account.service.ts
- apps/web-giddh/src/app/services/companyService.service.ts
- apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.ts
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
- apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts
- apps/web-giddh/src/app/tb-pl-bs/components/filter/tb-pl-bs-filter.component.ts
- apps/web-giddh/src/app/theme/quick-account-component/quickAccount.component.ts
> Ravinder | Stage | Fixed UI  Exception

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.module.ts
- apps/web-giddh/src/app/inventory/inventory.module.ts
- apps/web-giddh/src/app/theme/confirm-modal/confirm-modal.component.ts
> feat: clickup-#3b97q0 | Prateek | Prod | Add delete button and confirmation popup on update group and stock on inventory module 

- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.html
- apps/web-giddh/src/app/inventory/components/add-group-components/inventory.addgroup.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.html
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.component.ts
- apps/web-giddh/src/app/inventory/components/add-stock-components/inventory.addstock.module.ts
- apps/web-giddh/src/app/inventory/inventory.module.ts
- apps/web-giddh/src/app/theme/confirm-modal/confirm-modal.component.ts
> feat: clickup-#3b97q0 | Prateek | Beta | Add delete button and confirmation popup on update group and stock on inventory module

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: Prateek | Test | Remove unwanted code

- apps/web-giddh/src/index.prod.html
> fix: Remove extra character

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
- apps/web-giddh/src/assets/css/color.scss
> test | GIDK-49d5yb | Aditi | demo-issues

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.html
https://app.clickup.com/t/3bj6zw
> Ravinder | Stage | In update credit note flow sometimes customer name is not getting prefilled

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/theme/sales-ng-virtual-select/sh-select.component.html
https://app.clickup.com/t/3bj6zw
> Ravinder | Prod | In update credit note flow sometimes customer name is not getting prefilled

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.scss
- apps/web-giddh/src/assets/css/color.scss
- apps/web-giddh/src/assets/locale/all-items/en.json
- apps/web-giddh/src/assets/locale/all-items/hi.json
- apps/web-giddh/src/assets/locale/all-items/mr.json
> stage | GIDK-49d5yb | Aditi | demo-issues

- .github/workflows/build.yml
> Email notification stage

- .github/workflows/build.yml
> Email notification prod

- .github/workflows/build.yml
> Email notification beta

- .github/workflows/build.yml
> refactor: Correct spelling

- apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
https://app.clickup.com/t/35e2zk
> Ravinder | Stage | Inventory setting updated successfully message is displayed even when Decimal After Decimal settings is updated

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> test | Aditi | design in case of no branch

- apps/web-giddh/src/app/settings/other-settings/other-settings.component.ts
https://app.clickup.com/t/35e2zk
> Ravinder | Prod | Inventory setting updated successfully message is displayed even when Decimal After Decimal settings is updated

- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/41jy12
> Ravinder | Test | Fixed Left sidebar issues

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
> fix: Prateek | Test | Remove check causing issue in new item

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/49ff51
> fix: clickup-#49ff51 | Test | PROD- Sales Invoice is not getting created for multi-currency, if customer is created from Invoice page.

- apps/web-giddh/src/app/shared/header/pipe/tbsearch.pipe.ts
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid-row.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid-row.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/bs/bs-grid/bs-grid.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid-row.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid-row.component.scss
- apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid-row.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/pl/pl-grid/pl-grid.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/tb-pl-bs-grid-row.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/tb-pl-bs-grid-row.component.scss
- apps/web-giddh/src/app/tb-pl-bs/components/tb-pl-bs-grid-row.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.html
- apps/web-giddh/src/app/tb-pl-bs/components/tb/tb-grid/tb-grid.component.ts
- apps/web-giddh/src/app/tb-pl-bs/components/tb/tb.component.ts
- apps/web-giddh/src/app/tb-pl-bs/constants/trial-balance-profit.constant.ts
- apps/web-giddh/src/app/tb-pl-bs/pipes/accounts-filter.pipe.ts
- apps/web-giddh/src/app/tb-pl-bs/tb-pl-bs.module.ts
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
> perf(Trial Balance, Balance Sheet, Profit Loss): clickup-#3xdkee | Prateek | Beta | Improve module performance

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/49ff51
> fix: clickup-#49ff51 | Beta | PROD- Sales Invoice is not getting created for multi-currency, if customer is created from Invoice page.

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/49ff51
> fix: clickup-#49ff51 | Stage | PROD- Sales Invoice is not getting created for multi-currency, if customer is created from Invoice page.

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.html
- apps/web-giddh/src/app/home/components/profit-loss/profile-loss.component.ts
- apps/web-giddh/src/app/home/components/profit-loss/profit-loss.component.html
- apps/web-giddh/src/app/home/components/revenue/revenue-chart.component.html
- apps/web-giddh/src/app/home/components/total-overdues/total-overdues-chart.component.html
- apps/web-giddh/src/app/home/components/total-overdues/total-overdues-chart.component.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/columnar-report-table-component/columnar.report.table.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-table-component/purchase.register.table.component.html
- apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
> Gidk 298zrq currency code stage

- apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
- apps/web-giddh/src/app/gst/filing/tabs/overview/summary/summary.component.html
- apps/web-giddh/src/app/gst/filing/tabs/reconcilation/reconcilation.component.html
- apps/web-giddh/src/app/gst/gst.component.scss
- apps/web-giddh/src/assets/css/style-2.scss
> shalinee | test | gst responsive issue fixed

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.html
- apps/web-giddh/src/app/home/components/profit-loss/profile-loss.component.ts
- apps/web-giddh/src/app/home/components/profit-loss/profit-loss.component.html
- apps/web-giddh/src/app/home/components/revenue/revenue-chart.component.html
- apps/web-giddh/src/app/home/components/total-overdues/total-overdues-chart.component.html
- apps/web-giddh/src/app/home/components/total-overdues/total-overdues-chart.component.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/columnar-report-table-component/columnar.report.table.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-table-component/purchase.register.table.component.html
- apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
> Gidk 298zrq currency code beta

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.html
- apps/web-giddh/src/app/home/home.module.ts
- apps/web-giddh/src/app/ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.html
- apps/web-giddh/src/app/ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.ts
- apps/web-giddh/src/app/ledger/ledger.module.ts
- apps/web-giddh/src/app/settings/Taxes/setting.taxes.component.html
- apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.html
- apps/web-giddh/src/app/settings/discount/discount.component.html
- apps/web-giddh/src/app/settings/financial-year/financial-year.component.html
- apps/web-giddh/src/app/settings/settings.module.ts
- apps/web-giddh/src/app/settings/tags/tags.component.html
- apps/web-giddh/src/app/userDetails/userDetails.component.html
- apps/web-giddh/src/app/userDetails/userDetails.module.ts
> feat: clickup-#49h5qh | Prateek | Test | Prod - If data is not there on listing page then remove table header and totals

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/settings/Taxes/setting.taxes.component.html
- apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
- apps/web-giddh/src/app/settings/discount/discount.component.html
- apps/web-giddh/src/app/settings/tags/tags.component.html
> fix: clickup-#49h5qh | Prateek | Test | Minor update in no data text

- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/4bf0yp
> Ravinder | Test | Yes/No button is not displaying

- apps/web-giddh/src/app/contact/aging-report/aging-report.component.html
- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.ts
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.ts
- apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html
- apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
- apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html
- apps/web-giddh/src/app/invoice/recurring/recurring.component.html
- apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
- apps/web-giddh/src/app/settings/address-settings/address-settings.component.html
> feat: clickup-#49h5qh | Prateek | Test | The table header should not hide when user has searched in columns

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/49ff51
> fix: clickup-#49ff51 | Prod | PROD- Sales Invoice is not getting created for multi-currency, if customer is created from Invoice page.

- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
https://app.clickup.com/t/4bhde0
> Ravinder | Test | Invalid date should not come in case of no financial year exist in the company

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/4bhgjv
> Ravinder | Test | For Company/branch side bar make 1st Design (tab design) permanent and remove 2nd one

- apps/web-giddh/src/app/models/api-models/recipt.ts
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/proforma-invoice/services/proforma-invoice-utility.service.ts
- apps/web-giddh/src/app/services/apiurls/sales.api.ts
- apps/web-giddh/src/app/services/bulkvoucherexport.service.ts
- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/services/http.interceptor.ts
- apps/web-giddh/src/app/services/invoice.service.ts
- apps/web-giddh/src/app/services/ledger.service.ts
- apps/web-giddh/src/app/services/purchase-record.service.ts
- apps/web-giddh/src/app/services/receipt.service.ts
- apps/web-giddh/src/app/services/sales.service.ts
> feat: clickup-#3qftyd | Prateek | Test | Integrate API with new voucher version

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
> stage | Aditi | design in case of no branch

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/home/components/cr-dr-list/cr-dr-list.component.html
- apps/web-giddh/src/app/home/components/profit-loss/profile-loss.component.ts
- apps/web-giddh/src/app/home/components/profit-loss/profit-loss.component.html
- apps/web-giddh/src/app/home/components/revenue/revenue-chart.component.html
- apps/web-giddh/src/app/home/components/total-overdues/total-overdues-chart.component.html
- apps/web-giddh/src/app/home/components/total-overdues/total-overdues-chart.component.ts
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html
- apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts
- apps/web-giddh/src/app/reports/components/columnar-report-table-component/columnar.report.table.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-expand-component/purchase.register.expand.component.html
- apps/web-giddh/src/app/reports/components/purchase-register-table-component/purchase.register.table.component.html
- apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.html
- apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html
- apps/web-giddh/src/app/reports/components/salesRegister-expand-component/sales.register.expand.component.html
> Gidk 298zrq currency code prod

- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
- apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/4bhgjv
> Ravinder | Stage | For Company/branch side bar make 1st Design (tab design) permanent and remove 2nd one

- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/4bf0yp
> Ravinder | Stage | Yes/No button is not displaying

- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
https://app.clickup.com/t/4bhde0
> Ravinder | Stage | Invalid date should not come in case of no financial year exist in the company

- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
https://app.clickup.com/t/4bhde0
> Ravinder | Beta | Invalid date should not come in case of no financial year exist in the company

- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/4bf0yp
> Ravinder | Beta | Yes/No button is not displaying

- apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.ts
https://app.clickup.com/t/4bhde0
> Ravinder | Prod | Invalid date should not come in case of no financial year exist in the company

- apps/web-giddh/src/app/app.component.ts
- apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/4bf0yp
> Ravinder | Prod | Yes/No button is not displaying

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
> Ravinder | Test | Fixed Bug

- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/4bf9ge
> fix: clickup-#4bf9ge | Prateek | Test | Stage sanity - Design is getting distorted on GST page when creating account from cmd+K

- apps/web-giddh/src/app/services/general.service.ts
- apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
- apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/4bf9ge
> fix: clickup-#4bf9ge | Prateek | Stage | Stage sanity - Design is getting distorted on GST page when creating account from cmd+K

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html
- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
> fix: clickup-#49h5qh | Prateek | Test | Make the no data UI consistent across Giddh UI (Inventory)

- apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.html
- apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html
> fix: clickup-#49h5qh | Prateek | Test | Minor fixes

- apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
https://app.clickup.com/t/4bfdq6
> Ravinder | Test | Address field is enabled in create account side bar when creating it from cmd+g

- apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.html
- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
https://app.clickup.com/t/4bfdq6
> Ravinder | Stage | Address field is enabled in create account side bar when creating it from cmd+g

- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.html
- apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.html
- apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.html
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.scss
- apps/web-giddh/src/app/userDetails/components/company-details-sidebar/company-details-sidebar.component.html
- apps/web-giddh/src/assets/css/style-1.scss
- apps/web-giddh/src/assets/css/style-2.scss
- apps/web-giddh/src/assets/css/table.scss
https://app.clickup.com/t/4bhxvr
> test | GIDK-4bhxvr | Aditi | design issues

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
- apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.ts
https://app.clickup.com/t/49d69d
> feat: clickup-#49d69d | Prateek | Test | Prod < Need to hide the GST return filing and Trigger options from UI

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/contact/contact.component.scss
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.html
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.scss
https://app.clickup.com/t/4bhxvr
> test | Aditi | remove arrow from dropdown

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
- apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.ts
https://app.clickup.com/t/49d69d
> feat: clickup-#49d69d | Prateek | Beta | Prod < Need to hide the GST return filing and Trigger options from UI

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
- apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.ts
https://app.clickup.com/t/49d69d
> feat: clickup-#49d69d | Prateek | Stage | Prod < Need to hide the GST return filing and Trigger options from UI

- apps/web-giddh/src/app/contact/contact.component.html
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.scss
> test | Aditi | negative values in a line

- apps/web-giddh/src/app/app.constant.ts
- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/gst/filing/filing.component.ts
- apps/web-giddh/src/app/gst/filing/header/filing-header.component.html
- apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.html
- apps/web-giddh/src/app/gst/gstR3/gstR3.component.ts
https://app.clickup.com/t/49d69d
> feat: clickup-#49d69d | Prateek | Prod | Prod < Need to hide the GST return filing and Trigger options from UI

- apps/web-giddh/src/app/contact/contact.component.html
> stage | Aditi | negative values in a line

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
https://app.clickup.com/t/4bfdq6
> Ravinder | Test | Fixed tab enable/disable issue

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
https://app.clickup.com/t/4bfdq6
> Ravinder | Stage | Fixed tab enable/disable issue

- apps/web-giddh/src/app/services/general.service.ts
> fix: Remove redundant method

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/home/home.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.scss
https://app.clickup.com/t/41atuy
> test | GIDK-41atuy | Aditi | chat-icon overlapping fixed

- apps/web-giddh/src/app/daybook/daybook.component.html
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts
- apps/web-giddh/src/app/shared/shared.module.ts
> fix: Prateek | Stage | Remove unwanted code

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> Ravinder | Test | Address field is displaying disable for sundry debtors/creditors a/c in update flow from Customer/vendor module

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
https://app.clickup.com/t/4dckk9
> Ravinder | Beta | Setting side bar is getting closed automatically when going to setting modules

- apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html
https://app.clickup.com/t/4dckk9
> Ravinder | Prod | Setting side bar is getting closed automatically when going to setting modules

- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/assets/css/style-1.scss
> test | GIDK-4ddp1g | Aditi | discount issue fix

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
> Ravinder | Test | State field required issue

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> Ravinder | Stage | Address field is displaying disable for sundry debtors/creditors a/c in update flow from Customer/vendor module

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> Ravinder | Beta | Address field is displaying disable for sundry debtors/creditors a/c in update flow from Customer/vendor module

- apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
- apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
> Ravinder | Prod | Address field is displaying disable for sundry debtors/creditors a/c in update flow from Customer/vendor module

- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
> test | Aditi | edit voucher space

- apps/web-giddh/src/app/settings/integration/setting.integration.component.html
- apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
> Ravinder | Test | Fixed sh-select dropdown issue if searched clear

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/home/home.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/41atuy
https://app.clickup.com/t/4ddp1g
> stage | GIDK-41atuy | Aditi | chat-icon overlapping fixed

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/home/home.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/41atuy
https://app.clickup.com/t/4ddp1g
> beta | GIDK-41atuy | Aditi | chat-icon overlapping fixed

- apps/web-giddh/src/app/gst/filing/filing.component.html
- apps/web-giddh/src/app/home/home.component.scss
- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
- apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
- apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss
- apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
- apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html
- apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss
- apps/web-giddh/src/app/reports/components/report-table-components/report.table.component.scss
- apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/41atuy
https://app.clickup.com/t/4ddp1g
> prod | GIDK-41atuy | Aditi | chat-icon overlapping fixed

- apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
- apps/web-giddh/src/app/services/invoice.service.ts
- apps/web-giddh/src/app/services/sales.service.ts
> feat: clickup-#3qftyd | Prateek | Test | Add new voucher API support to Pending, PB, Generate Pending

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
https://app.clickup.com/t/4dffj9
> test | GIDK-4dffj9 | inventory design bottom

- apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
> stage | GIDK-4dffj9 | inventory design bottom
