Walkover-Web-Solution/Giddh-New-Angular4-App

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
=> beta | GIDK-4dffj9 | inventory design bottom

apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html, apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.scss, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 4dffj9 stage

apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html, apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.scss, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> shalinee | beta | inventory sidebar issue fixed

apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html, apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.scss, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Shalinee | beta | correct double scroll issue

apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html, apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.scss, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Gidk 4dffj9 test

apps/web-giddh/src/app/daybook/daybook.module.ts
https://app.clickup.com/t/4dga6p
=> Ravinder | Test | Getting exception on daybook when opening entry in edit flow

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss, apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.html, apps/web-giddh/src/app/inventory/components/sidebar-components/inventory.sidebar.component.scss, apps/web-giddh/src/app/inventory/components/sidebar-components/stockgrplist.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> prod | GIDK-4dffj9 | inventory design bottom

apps/web-giddh/src/app/daybook/daybook.module.ts
https://app.clickup.com/t/4dga6p
=> Ravinder | Stage | Getting exception on daybook when opening entry in edit flow

apps/web-giddh/src/app/daybook/daybook.module.ts
https://app.clickup.com/t/4dga6p
=> Ravinder | Beta | Getting exception on daybook when opening entry in edit flow

apps/web-giddh/src/app/daybook/daybook.module.ts
https://app.clickup.com/t/4dga6p
=> Ravinder | Prod | Getting exception on daybook when opening entry in edit flow

apps/web-giddh/src/app/daybook/daybook.component.html
https://app.clickup.com/t/4dgcy7
=> Ravinder | Beta | Export button is not coming on daybook

apps/web-giddh/src/app/daybook/daybook.component.html
https://app.clickup.com/t/4dgcy7
=> Ravinder | Prod | Export button is not coming on daybook

.github/workflows/manual.yml
=> feat: Prateek | Beta | Integration email notification for desktop builds

.github/workflows/manual.yml
=> feat: Prateek | Stage | Integration email notification for desktop builds

.github/workflows/manual.yml
=> feat: Prateek | Test | Integration email notification for desktop builds

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/4de6mg
=> fix: clickup-#4de6mg | Prateek | Test | Incorrect country code is sent in billing and shipping details

apps/web-giddh/src/app/theme/account-detail-modal/account-detail-modal.component.html
=> shalinee | test | comment send SMS option for now

apps/web-giddh/src/app/theme/account-detail-modal/account-detail-modal.component.html
=> shalinee | stage | comment send SMS option for now

apps/web-giddh/src/app/theme/account-detail-modal/account-detail-modal.component.html
=> shalinee | beta | comment send SMS option for now

apps/web-giddh/src/app/theme/account-detail-modal/account-detail-modal.component.html
=> shalinee | prod | comment send SMS option for now

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: clickup-#4bh5rt | Prateek | Test | Prod - Instead of 'Vendor name' on debit note page showing customer page.

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.html, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html
=> Ravinder | Test | Fixed ICICI Bugs

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: Prateek | Test | Placeholder text in dropdown in DN

apps/web-giddh/src/app/services/ledger.service.ts
=> feat: Add support to voucherVersion 2 in ledger download API

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: clickup-#4bh5rt | Prateek | Stage | Prod - Instead of 'Vendor name' on debit note page showing customer page.

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: clickup-#4bh5rt | Prateek | Beta | Prod - Instead of 'Vendor name' on debit note page showing customer page.

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
=> fix: clickup-#4bh5rt | Prateek | Prod | Prod - Instead of 'Vendor name' on debit note page showing customer page.

.github/workflows/manual.yml, electron-sign/electron-builder-test.json
=> feat: Prateek | Prod | Integration email notification for desktop builds

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/models/api-models/Sales.ts, apps/web-giddh/src/app/models/api-models/Voucher.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/proforma-invoice/services/proforma-invoice-utility.service.ts
=> feat: clickup-3qftyd | Prateek | Test | Integrate the form API response to make dynamic voucher form

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.html, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.ts, apps/web-giddh/src/app/settings/integration/payment/icici/payor-create-edit/payor-create-edit.component.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.scss, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.ts, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.html, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts, apps/web-giddh/src/assets/locale/settings/integration/en.json, apps/web-giddh/src/assets/locale/settings/integration/hi.json, apps/web-giddh/src/assets/locale/settings/integration/mr.json
=> Ravinder | Test | Fixed ICICI task bugs

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
=> shalinee | stage | correct alignment of button

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.ts, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
=> fix: Prateek | PROD | UI exception

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.ts, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
=> fix: Prateek | BETA | UI exception

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.ts, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
=> fix: Prateek | STAGE | UI exception

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.ts, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
=> fix: Prateek | Test | UI exception

apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
=> shalinee | test | added tooltip on company branch name of sidebar

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.ts, apps/web-giddh/src/app/settings/integration/payment/icici/payor-create-edit/payor-create-edit.component.html, apps/web-giddh/src/app/settings/integration/payment/icici/payor-create-edit/payor-create-edit.component.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.scss, apps/web-giddh/src/assets/locale/aside-setting/en.json, apps/web-giddh/src/assets/locale/settings/integration/en.json, apps/web-giddh/src/assets/locale/settings/integration/hi.json, apps/web-giddh/src/assets/locale/settings/integration/mr.json
https://app.clickup.com/t/4fbk3d
=> Ravinder | Test | ICICI task issues

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
=> shalinee | beta | correct alignment of button

apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
=> Gidk 4fjy2c tootlip stage

apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
=> Gidk 4fjy2c tootlip beta

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss
=> shalinee | prod | correct alignment of button

apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
=> Gidk 4fjy2c tootlip prod

apps/web-giddh/src/app/financial-reports/financial-reports.module.ts
=> fix: Build issue (will be reverted soon)

apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/components/balance-sheet-grid-row/balance-sheet-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.ts, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/trial-balance.component.ts, apps/web-giddh/src/app/financial-reports/directives/financial-accordion.directive.ts, apps/web-giddh/src/app/financial-reports/financial-reports.module.ts, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html, apps/web-giddh/src/app/shared/header/pipe/financial-search.pipe.ts
https://app.clickup.com/t/4hcn6p
=> fix: clickup-#3xdkee | Prateek | Beta | Rename files and fix Branch uniquename not been passed when user reloads the tab 657ce87

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.html, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.scss, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
=> Ravinder | Test | Fixed Stage sanity issues

apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.html, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.scss, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
=> Ravinder | Stage | Fixed Stage sanity issues

apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json
=> fix: Prateek | Prod | Key names

apps/web-giddh/src/assets/locale/en.json, apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json
=> fix: Prateek | Stage | Add Missing label

apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json
=> fix: Prateek | Test | Key names

apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json
=> fix: Prateek | Beta | Key names

apps/web-giddh/src/app/models/api-models/recipt.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/receipt.service.ts
=> fix: clickup-#3qftyd | Prateek | Test | PB merge scenario not working, GET/GET ALL PB API integration for voucher version 2

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js, apps/web-giddh/src/environments/environment.stage.ts, apps/web-giddh/src/meta/yodlee-success.html, apps/web-giddh/webpack.stage.partial.js
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#8487
=> Change to API release URL

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/models/api-models/Sales.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/proforma-invoice/services/proforma-invoice-utility.service.ts, apps/web-giddh/src/app/services/receipt.service.ts, apps/web-giddh/src/app/services/sales.service.ts
=> feat: clickup-#3qftyd | Prateek | Test | UI - Implement new voucher logic

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
=> refactor: Prateek | Test | Remove unwanted code from HTML

apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.html, apps/web-giddh/src/app/theme/account-detail-modal/account-detail-modal.component.html, apps/web-giddh/src/app/theme/account-detail-modal/account-detail-modal.component.ts
https://app.clickup.com/t/4hf3fe
https://app.clickup.com/t/4hf29f
=> fix: clickup-#3xdkee | Prateek | Test | Issue #4hf3fe, #4hf29f

apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.html, apps/web-giddh/src/app/theme/account-detail-modal/account-detail-modal.component.html, apps/web-giddh/src/app/theme/account-detail-modal/account-detail-modal.component.ts
https://app.clickup.com/t/4hf3fe
https://app.clickup.com/t/4hf29f
=> fix: clickup-#3xdkee | Prateek | Beta | Issue #4hf3fe, #4hf29f

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/51ce0y
=> fix: clickup-#51ce0y | Prateek | Test | Remove deliver to section which is showing in sales invoice creation page and margin issue

apps/web-giddh/src/app/gst/gst.component.ts
https://app.clickup.com/t/4hf474
=> fix: clickup-#4hf474 | Prateek | Test | Getting error 'GSTIN number does not exist in the company' after switching from one company to another

apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
=> fix: clickup-#51bqvz | Prateek | Test | Remove GST Taxes option from dropdown  Sundry Debtor group and Sundry Creditor Group in Masters.

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, package.json
https://app.clickup.com/t/4hdc0e
=> Ravinder | Test | On sales invoice page totals are not updating when changing unit of the stock

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.scss, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts, apps/web-giddh/src/assets/locale/settings/integration/en.json, apps/web-giddh/src/assets/locale/settings/integration/hi.json, apps/web-giddh/src/assets/locale/settings/integration/mr.json
=> Ravinder | Test | Fixed Bugs

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/4hdc0e
=> Ravinder | Stage | On sales invoice page totals are not updating when changing unit of the stock

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/4hdc0e
=> Ravinder | Beta | On sales invoice page totals are not updating when changing unit of the stock

apps/web-giddh/src/app/gst/gst.component.ts, apps/web-giddh/src/app/store/GstR/GstR.reducer.ts
https://app.clickup.com/t/4hf474
=> fix: clickup-#4hf474 | Prateek | Test | GST number getting reset

apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
=> fix: clickup-#51bqvz | Prateek | Test| Show only normal taxes when group/account is not sundry creditor/debtor

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/4hdc0e
=> Ravinder | Prod | On sales invoice page totals are not updating when changing unit of the stock

apps/web-giddh/src/app/financial-reports/components/balance-sheet/balance-sheet.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/balance-sheet.component.ts, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.html, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.ts, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/profit-loss.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/profit-loss.component.ts, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/trial-balance/trial-balance.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/trial-balance.component.ts, apps/web-giddh/src/app/financial-reports/pipes/accounts-filter.pipe.ts
=> fix: clickup-#3xdkee | Prateek | Test | Issues related to TB/PL/BS optimization

apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
=> feat: clickup-#51bqvz | Prateek | Stage | Remove GST Taxes option from dropdown Sundry Debtor group and Sundry Creditor Group in Masters.

apps/web-giddh/src/app/settings/constants/settings.constant.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Ravinder | Test | Changing code to check if account is connected

apps/web-giddh/src/app/settings/constants/settings.constant.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.html, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Ravinder | Stage | Changing code to check if account is connected

apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
=> feat: clickup-#51bqvz | Prateek | Beta | Remove GST Taxes option from dropdown Sundry Debtor group and Sundry Creditor Group in Masters.

apps/web-giddh/src/app/gst/gst.component.ts, apps/web-giddh/src/app/store/GstR/GstR.reducer.ts
https://app.clickup.com/t/4hf474
=> fix: clickup-#4hf474 | Prateek | Stage | Getting error 'GSTIN number does not exist in the company' after switching from one company to another

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/45gyvz
=> fix: clickup-#45gyvz | Prateek | Test | Converted amount not being calculated when exchange rate is changed

apps/web-giddh/src/app/gst/gst.component.ts, apps/web-giddh/src/app/store/GstR/GstR.reducer.ts
https://app.clickup.com/t/4hf474
=> fix: clickup-#4hf474 | Prateek | Prod | Getting error 'GSTIN number does not exist in the company' after switching from one company to another

apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
=> feat: clickup-#51bqvz | Prateek | Prod | Remove GST Taxes option from dropdown Sundry Debtor group and Sundry Creditor Group in Masters.

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
=> feat: Prateek | Test | Enable 'Total before discount' for in template settings for all vouchers

apps/web-giddh/src/app/expenses/expenses.module.ts
=> Ravinder | Test | Other tax aside pan not showing on petty cash

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.html, apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts, apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/expenses/expenses.component.scss, apps/web-giddh/src/assets/locale/expenses/en.json, apps/web-giddh/src/assets/locale/expenses/hi.json, apps/web-giddh/src/assets/locale/expenses/mr.json
https://app.clickup.com/t/5cxcmy
https://app.clickup.com/t/5cxt2j
https://app.clickup.com/t/5cy3tb
=> Ravinder | Test | Fixed Petty cash bugs

apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.html, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.ts
=> Ravinder | Test | Made Account number editable in edit account

apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.html, apps/web-giddh/src/app/settings/integration/payment/icici/account-create-edit/account-create-edit.component.ts
=> Ravinder | Stage | Made Account number editable in edit account

apps/web-giddh/src/app/settings/integration/setting.integration.component.html
=> Ravinder | Test | Commented get instant overdraft button

apps/web-giddh/src/app/settings/integration/setting.integration.component.html
=> Ravinder | Stage | Commented get instant overdraft button

apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Ravinder | Stage | Edited JS Doc

apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/components/balance-sheet-grid-row/balance-sheet-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/components/balance-sheet-grid-row/balance-sheet-grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.ts, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.ts, apps/web-giddh/src/app/financial-reports/pipes/accounts-filter.pipe.ts
=> fix: Prateek | Test | Issues related to TB/PL/BS optimization

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/assets/locale/contact/en.json, apps/web-giddh/src/assets/locale/contact/hi.json, apps/web-giddh/src/assets/locale/contact/mr.json
https://app.clickup.com/t/6f54t4
=> Ravinder | Test | ICICI task changes

apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/components/balance-sheet-grid-row/balance-sheet-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.html, apps/web-giddh/src/app/financial-reports/pipes/accounts-filter.pipe.ts
=> fix: clickup-#3xdkee Prateek | Test | Issues related to TB/PL/BS optimization

apps/web-giddh/src/app/daybook/daybook.component.ts
https://app.clickup.com/t/6f4en4
=> Ravinder | Test | On daybook Message toaster is not properly coming when checking data for future data

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts, apps/web-giddh/src/assets/locale/contact/en.json, apps/web-giddh/src/assets/locale/contact/hi.json, apps/web-giddh/src/assets/locale/contact/mr.json
https://app.clickup.com/t/6f54t4
=> Ravinder | Stage | ICICI task changes

apps/web-giddh/src/app/financial-reports/components/balance-sheet/balance-sheet.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/balance-sheet.component.ts, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/components/balance-sheet-grid-row/balance-sheet-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/components/balance-sheet-grid-row/balance-sheet-grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.html, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.ts, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/profit-loss.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/profit-loss.component.ts, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/trial-balance/trial-balance.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/trial-balance.component.ts, apps/web-giddh/src/app/financial-reports/pipes/accounts-filter.pipe.ts
=> fix: clickup-#3xdkee | Prateek | Stage | Issues related to TB/PL/BS optimization

apps/web-giddh/src/app/financial-reports/components/balance-sheet/balance-sheet.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/balance-sheet.component.ts, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/balance-sheet-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/components/balance-sheet-grid-row/balance-sheet-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/balance-sheet/components/balance-sheet-grid/components/balance-sheet-grid-row/balance-sheet-grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.html, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.ts, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/grid-row/grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/profit-loss-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/profit-loss/profit-loss.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/profit-loss.component.ts, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.ts, apps/web-giddh/src/app/financial-reports/components/trial-balance/trial-balance.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/trial-balance.component.ts, apps/web-giddh/src/app/financial-reports/pipes/accounts-filter.pipe.ts
=> fix: clickup-#3xdkee | Prateek | Beta | Issues related to TB/PL/BS optimization

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
=> fix: Prateek | Beta | Spacing issue in template A

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html
=> fix: Prateek | Stage | Spacing issue in template A

apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts, apps/web-giddh/src/app/permissions/components/details/permission.details.html, apps/web-giddh/src/app/permissions/components/list/permission-list.html, apps/web-giddh/src/app/permissions/permission-data.service.ts
https://app.clickup.com/t/6f7ptx
=> Ravinder | Test | Ui Exception

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
https://app.clickup.com/t/6f4yac
=> feat: clickup-#6f4yac | Prateek | Test | Hide Total before discount for CN/DN in template E

apps/web-giddh/src/app/daybook/daybook.component.html
=> Ravinder | Prod | Removed duplicate code block

apps/web-giddh/src/app/settings/constants/settings.constant.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Ravinder | Test | Gmail Integration Error from Company View

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/4hb2qf
=> Ravinder | Test | Left side bar is automatically changing from expand view to collapse view

apps/web-giddh/src/app/settings/constants/settings.constant.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Ravinder | Stage | Gmail Integration Error from Company View

apps/web-giddh/src/app/settings/constants/settings.constant.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Ravinder | Beta | Gmail Integration Error from Company View

apps/web-giddh/src/app/settings/Trigger/setting.trigger.component.ts
https://app.clickup.com/t/6fbn0f
=> Ravinder | Test | On trigger page, all data is not getting cleared with cancel button

apps/web-giddh/src/app/settings/constants/settings.constant.ts, apps/web-giddh/src/app/settings/integration/setting.integration.component.ts
=> Ravinder | Prod | Gmail Integration Error from Company View

apps/web-giddh/src/app/actions/accounts.actions.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/5d2qdp
=> Ravinder | Stage | Error coming when user updating account from vendor

apps/web-giddh/src/app/actions/accounts.actions.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/5d2qdp
=> Ravinder | Prod | Error coming when user updating account from vendor

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/4hb2qf
=> Ravinder | Stage | Left side bar is automatically changing from expand view to collapse view

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/4hb2qf
=> Ravinder | Beta | Left side bar is automatically changing from expand view to collapse view

apps/web-giddh/src/app/invoice/invoice.component.html, apps/web-giddh/src/app/invoice/invoice.component.ts
=> fix: clickup-#3qftyd | Prateek | Test |  Retain the Recurring tab position

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/4hb2qf
=> Ravinder | Prod | Left side bar is automatically changing from expand view to collapse view

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/expenses/expenses.component.ts
https://app.clickup.com/t/6myf8f
=> Ravinder | Test | Petty Cash - Preview Page after approving the entry.

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html
https://app.clickup.com/t/5d2nr9
=> test | GIDK-5d2nr9 | Aditi | generate voucher UI

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/expenses/expenses.component.ts
https://app.clickup.com/t/6myf8f
=> Ravinder | Stage | Petty Cash - Preview Page after approving the entry

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/expenses/expenses.component.ts
https://app.clickup.com/t/6myf8f
=> Ravinder | Beta | Petty Cash - Preview Page after approving the entry

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/expenses/expenses.component.ts
https://app.clickup.com/t/6myf8f
=> Ravinder | Prod | Petty Cash - Preview Page after approving the entry

apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/6mzyg7
=> Ravinder | Test | User's email id is not showing in new company/branch switch side bar.

apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/6mzyg7
=> Ravinder | Stage | User's email id is not showing in new company/branch switch side bar.

apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/6mzyg7
=> Ravinder | Beta | User's email id is not showing in new company/branch switch side bar.

apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/6mzyg7
=> Ravinder | Prod | User's email id is not showing in new company/branch switch side bar.

apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html
=> test | GIDK-6my9ze | Aditi | voucher no box

apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html
https://app.clickup.com/t/5d2g37
=> test | GIDK-5d2g37 | Aditi | debit side of ledger UI

apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/4fh7dg
=> test | GIDK-4fh7dg | Aditi | sidebar in sales invoice

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html
https://app.clickup.com/t/5d2nr9
=> stage | GIDK-5d2nr9 | Aditi | generate voucher UI

apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html
https://app.clickup.com/t/5d2g37
=> stage | GIDK-5d2g37 | Aditi | debit side of ledger UI

apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/6mz00f
=> test | GIDK-6mz00f | Aditi | reconciliation of bank ledger

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html
https://app.clickup.com/t/5d2nr9
=> beta | GIDK-5d2nr9 | Aditi | generate voucher UI

apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html
https://app.clickup.com/t/5d2g37
=> beta | GIDK-5d2g37 | Aditi | debit side of ledger UI

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html
https://app.clickup.com/t/5d2nr9
=> prod | GIDK-5d2nr9 | Aditi | generate voucher UI

apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html
https://app.clickup.com/t/5d2g37
=> prod | GIDK-5d2g37 | Aditi | debit side of ledger UI

apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/6mz00f
=> stage | GIDK-6mz00f | Aditi | reconciliation of bank ledger

apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/6mz00f
=> beta | GIDK-6mz00f | Aditi | reconciliation of bank ledger

apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/6mz00f
=> prod | GIDK-6mz00f | Aditi | reconciliation of bank ledger

apps/web-giddh/src/app/shared/header/header.component.html
https://app.clickup.com/t/7hfhy1
=> Ravinder | Test | Design is getting distorted on on sales invoice page.

apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.scss
https://app.clickup.com/t/6my9ze
=> test | GIDK-6my9ze | Aditi | new issues in petty cash

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
https://app.clickup.com/t/6f4yac
=> feat: clickup-#6f4yac | Prateek | Beta | Hide Total before discount for CN/DN in template E

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
https://app.clickup.com/t/6f4yac
=> feat: clickup-#6f4yac | Prateek | Stage | Hide Total before discount for CN/DN in template E

apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.scss
https://app.clickup.com/t/5cuqdn
=> test | GIDK-5cuqdn | Aditi | sales register dropdown

apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.ts
https://app.clickup.com/t/6f4yac
=> feat: clickup-#6f4yac | Prateek | Prod | Hide Total before discount for CN/DN in template E

apps/web-giddh/src/app/invoice/eWayBill/eWayBillcredentialsModal/eWayBillCredentials.component.html, apps/web-giddh/src/app/invoice/eWayBill/eWayBillcredentialsModal/eWayBillCredentials.component.scss, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html, apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/45f3tg
=> stage | GIDK-45f3tg | Aditi | Design issues 

apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.scss
https://app.clickup.com/t/5cuqdn
=> stage | GIDK-5cuqdn | Aditi | sales register dropdown

apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html, apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/43k7ez
=> test | GIDK-43k7ez | Aditi | active class on setting sidebar items

apps/web-giddh/src/app/invoice/eWayBill/eWayBillcredentialsModal/eWayBillCredentials.component.html, apps/web-giddh/src/app/invoice/eWayBill/eWayBillcredentialsModal/eWayBillCredentials.component.scss, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html, apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/45f3tg
=> beta | GIDK-45f3tg | Aditi | Design issues

apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.scss
https://app.clickup.com/t/5cuqdn
=> beta | GIDK-5cuqdn | Aditi | sales register dropdown

apps/web-giddh/src/app/invoice/eWayBill/eWayBillcredentialsModal/eWayBillCredentials.component.html, apps/web-giddh/src/app/invoice/eWayBill/eWayBillcredentialsModal/eWayBillCredentials.component.scss, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html, apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.scss, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/45f3tg
=> prod | GIDK-45f3tg | Aditi | Design issues

apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.scss
https://app.clickup.com/t/5cuqdn
=> prod | GIDK-5cuqdn | Aditi | sales register dropdown

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts
https://app.clickup.com/t/4dfty7
=> Ravinder | Test | Fixed Design Issues

apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.html, apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.ts, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.scss, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/components/filter-list/filter-list.component.html, apps/web-giddh/src/app/expenses/components/filter-list/filter-list.component.scss, apps/web-giddh/src/app/expenses/components/filter-list/filter-list.component.ts, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.html, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.scss, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts, apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.html, apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.scss, apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts, apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/expenses/expenses.component.scss, apps/web-giddh/src/app/expenses/expenses.component.ts, apps/web-giddh/src/app/expenses/expenses.module.ts, apps/web-giddh/src/app/models/api-models/Expences.ts, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/6n147m
=> Ravinder | Test | Integrate Angular material on petty cash

apps/web-giddh/src/app/shared/header/header.component.html
https://app.clickup.com/t/7hfhy1
=> Ravinder | Stage | Design is getting distorted on on sales invoice page.

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.scss, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts, apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.scss, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/daybook/daybook.module.ts, apps/web-giddh/src/app/daybook/export-daybook/export-daybook.component.html, apps/web-giddh/src/app/daybook/export-daybook/export-daybook.component.scss, apps/web-giddh/src/app/daybook/export-daybook/export-daybook.component.ts, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/7hhh87
=> Ravinder | Test | Integrated angular material on daybook

apps/web-giddh/src/app/material-ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/theme/new-confirm-modal/confirm-modal.component.html, apps/web-giddh/src/app/theme/new-confirmation-modal/confirmation-modal.component.html, apps/web-giddh/src/app/theme/new-confirmation-modal/confirmation-modal.component.scss
=> Ravinder | Test | Fixed Ledger Bugs

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.html, apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.html, apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts, apps/web-giddh/src/app/expenses/expenses.component.ts
=> Ravinder | Test | Fixed Petty cash issues

apps/web-giddh/src/app/all-items/all-item.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/assets/locale/all-items/en.json, apps/web-giddh/src/assets/locale/all-items/hi.json, apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/7hkc69
=> Ravinder | Test | IN UAE BASED COMPANY GSTR-1,2,3B and E-way Bill MODULE SHOWN

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.scss, apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/export-daybook/export-daybook.component.html, apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html
=> Ravinder | Test | Fixed CSS PR Fixes

apps/web-giddh/src/assets/css/color.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/7hny4x
=> test | GIDK-7hny4x | Aditi | petty cash approve

apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.html, apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts
https://app.clickup.com/t/7q6e0a
=> Ravinder | Test | On responsive update entry pop up is not opening.

apps/web-giddh/src/assets/magic-link-assets/magic.css
=> fix: Remove redundant code

apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/7x0fr7
=> test | GIDK-7x0fr7 | Aditi | Select date option is not proper

apps/web-giddh/src/app/actions/ledger/ledger.actions.ts, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.html, apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.html, apps/web-giddh/src/app/material-ledger/components/export-ledger/export-ledger.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger.vm.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/6n147b
=> Ravinder | Test | Fixed Ledger, daybook issues

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts, apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.html, apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.ts
=> Ravinder | Test | Fixed Advance filter mat expansion issue

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.ts
https://app.clickup.com/t/7q9g36
=> Ravinder | Test | Fixed Daybook filter date range field reset issue

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/webpack.test.partial.js
https://app.clickup.com/t/7hhh87
=> Ravinder | Test | Fixed daybook table issue

apps/web-giddh/src/app/common/confirmation-modal/confirmation-modal.component.html, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/invoice/templates/edit-template/edit-template.component.scss, apps/web-giddh/src/app/invoice/templates/edit-template/modals/confirmation-modal/confirmation.modal.component.html, apps/web-giddh/src/app/permissions/components/model/permission.model.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss, apps/web-giddh/src/app/settings/permissions/form/form.component.html, apps/web-giddh/src/app/settings/permissions/setting.permission.component.html, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.html, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/userDetails/components/move-company/move-company.component.html, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/webpack.partial.js
https://app.clickup.com/t/8tjca9
=> test | GIDK-8tjca9 | Aditi | design issues of website

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/edit.filters.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/modals/confirmation-modal/confirmation.modal.module.ts
https://app.clickup.com/t/8tjca9
=> Ravinder | Test | Fixed Invoice Close popup blank message issue

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.scss, apps/web-giddh/src/app/expenses/expenses.component.scss, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.scss, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/ledger/ledger.component.scss, apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.scss, apps/web-giddh/src/app/material-ledger/components/update-ledger-discount/update-ledger-discount.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.scss, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.scss, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/webpack.partial.js
https://app.clickup.com/t/7q6gxn
https://app.clickup.com/t/7q8690
https://app.clickup.com/t/8tjca9
https://app.clickup.com/t/8tp81u
https://app.clickup.com/t/8tp7p3
https://app.clickup.com/t/7q6649
https://app.clickup.com/t/8tj69w
https://app.clickup.com/t/8tp8jj
=> test | Gidk -7hnc32 | Aditi | remaining testing issues

apps/web-giddh/webpack.test.partial.js
=> Ravinder | Test | Reverted API url

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/8tp8r5
=> Ravinder | Test | Allow Fixed Assets Module in PB, CN, DN and sales invoice Modules

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/8tp8r5
=> Ravinder | Test | Allowed fixed assets group accounts for all vouchers including PO

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts
=> Ravinder | Test | Chat icon overlap issue on ledger

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.scss, apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.scss, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/expenses.component.scss, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.html, apps/web-giddh/src/app/inventory/components/stock-report-component/inventory.stockreport.component.scss, apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.scss, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.scss, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss
=> test | GIDK-6n147b | Aditi | testing final issues

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.scss, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts
https://app.clickup.com/t/8tp7bz
=> Ravinder | Test | while selecting voucher type as receipt error is coming

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/expenses/expenses.component.scss, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/7q94d4
https://app.clickup.com/t/8tpb84
=> test | GIDK-7q94d4 | Aditi | testing issue

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/8tp3ec
=> Ravinder | Stage | Multiple PO are getting created if button clicked twice

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/8tp3ec
=> Ravinder | Beta | Multiple PO are getting created if button clicked twice

apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/8tp1hu
=> test | GIDK-8tp1hu | Aditi | Unable to delete custom filed from master

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.scss, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.scss, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/shared/header/components/group-export-ledger-modal/export-group-ledger.component.html, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/7q6gxn
https://app.clickup.com/t/7q94d4
=> test | GIDK-7q6gxn | Aditi | daybook fix

apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/8tp1hu
=> stage | GIDK-8tp1hu | Aditi | Unable to delete custom filed from master

apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/8tp1hu
=> beta | GIDK-8tp1hu | Aditi | Unable to delete custom filed from master

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.scss
https://app.clickup.com/t/7q94d4
=> test | GIDK-7q6gxn | Aditi | large entry issue fixed

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/8tp3ec
=> Ravinder | Prod | Multiple PO are getting created if button clicked twice

apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/8tp1hu
=> prod | GIDK-8tp1hu | Aditi | Unable to delete custom filed from master

apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.scss
https://app.clickup.com/t/8zcja9
=> test | GIDK-8zcja9 | daybook mobile ipad

apps/web-giddh/src/assets/css/table.scss
=> test | GIDK-6faugx | Aditi | One line is showing in Purchase management

apps/web-giddh/src/assets/css/table.scss
=> test | GIDK-6faugx | Aditi | border remove

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts
https://app.clickup.com/t/94zr4z
=> Ravinder | Test | Fixed Ledger Sanity Issues

apps/web-giddh/src/app/invoice/recurring/recurring.component.html, apps/web-giddh/src/app/login/login.component.html, apps/web-giddh/src/app/login/login.component.scss, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.scss, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.scss, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/signup/signup.component.html, apps/web-giddh/src/app/signup/signup.component.scss, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss
=> stage | GIDK-6n147b | Aditi | testing issues done

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts, apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-discount/update-ledger-discount.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-discount/update-ledger-discount.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html, apps/web-giddh/src/app/settings/tags/tags.component.html, apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.html, apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/assets/css/style-1.scss
=> Ravinder | Test | Fixed Sanity issues

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/apiurls/purchase-record.api.ts
https://app.clickup.com/t/950w5r
=> Ravinder | Test | User is not able to update the PB from PB module.

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts, apps/web-giddh/src/app/invoice/settings/invoice.settings.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-discount/update-ledger-discount.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-discount/update-ledger-discount.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html, apps/web-giddh/src/app/settings/tags/tags.component.html, apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.html, apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/assets/css/style-1.scss
=> Ravinder | Stage | Fixed Sanity issues

apps/web-giddh/src/app/ledger/ledger.component.ts
https://app.clickup.com/t/956j0d
=> Ravinder | Test | After getting merge for PB, pop-up for merge is not closing automatically.

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/94zb9j
=> Ravinder | Test | On ledger generate voucher checkbox is removed automatically when change voucher type

apps/web-giddh/src/app/theme/giddh-datepicker/giddh-datepicker.component.ts
https://app.clickup.com/t/7x0fr7
=> Ravinder | Test | Select date option is not proper in filter option in sales invoice get all page.

apps/web-giddh/src/app/material-ledger/components/generate-voucher-confirm-modal/generate-voucher-confirm-modal.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/settings/linked-accounts/connect-bank-modal/connect.bank.modal.component.html, apps/web-giddh/src/app/settings/tags/tags.component.html, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss
=> test | GIDK-950u87 | Aditi | stage sanity

apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/component.ts
https://app.clickup.com/t/8tp01k
=> Ravinder | Test | Create product/service side bar is not getting closed in one time from cross icon.

apps/web-giddh/src/app/material-ledger/ledger.component.html
=> Ravinder | Test | Fixed blank row issue in ledger

apps/web-giddh/src/assets/css/table.scss
=> stage | GIDK-6faugx | Aditi | One line is showing in Purchase management

apps/web-giddh/src/app/material-ledger/ledger.component.html
=> Ravinder | Stage | Fixed blank row issue in ledger

apps/web-giddh/src/assets/css/table.scss
=> beta | GIDK-6faugx | Aditi | One line is showing in Purchase management

apps/web-giddh/src/assets/css/table.scss
=> prod | GIDK-6faugx | Aditi | One line is showing in Purchase management

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.html, apps/web-giddh/src/app/material-ledger/components/generate-voucher-confirm-modal/generate-voucher-confirm-modal.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.scss, apps/web-giddh/src/app/search/components/search-grid/search-grid.component.html, apps/web-giddh/src/app/theme/account-detail-modal/account-detail-modal.component.html, apps/web-giddh/src/assets/css/style-1.scss
=> test |  GIDK-950u87 | Aditi | re-testing

apps/web-giddh/src/app/material-ledger/components/generate-voucher-confirm-modal/generate-voucher-confirm-modal.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts
=> Ravinder | Test | Fixed Material sanity issues

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts
=> Ravinder | Stage | Fixed Material sanity issues

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
=> test | Aditi | scroll in create flow

apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.html
=> test | Aditi | reject page sorting icon

apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/b415q1
=> test | GIDK-b415q1 | Aditi | table text color

apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/b415q1
=> stage | GIDK-b415q1 | Aditi | table text color

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts
https://app.clickup.com/t/8tny9q
=> Deep | Test | Fix the HSN/SAC option that is coming on sundry/debtor/creditor create account side bar

apps/web-giddh/src/assets/magic-link-assets/magic.css, apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/94z543
=> test | GIDK-94z543 | Aditi | Download voucher and attachment icon

apps/web-giddh/src/app/material-ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.ts
https://app.clickup.com/t/b9pwte
=> Ravinder | Test | On ledger columnar report last column is not coming

apps/web-giddh/src/assets/css/color.scss, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/b9q18m
=> test | GIDK-b9q18m | Aditi | daybook table border

apps/web-giddh/src/assets/css/color.scss, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/b9q18m
=> stage | GIDK-b9q18m | Aditi | daybook table border

apps/web-giddh/src/assets/css/color.scss, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/b9q18m
=> beta | GIDK-b9q18m | Aditi | daybook table border

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/assets/css/style-1.scss
=> test | GIDK-b9r2dz | Aditi | prod sanity fix

apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html
=> test | GIDK-b9r2dz | Aditi | share button align

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/assets/css/style-1.scss
=> stage | GIDK-b9r2dz | Aditi | prod sanity fix

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/assets/css/style-1.scss
=> beta | GIDK-b9r2dz | Aditi | prod sanity fix

apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts, apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/document-issued/document-issued.component.ts, apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/failed-transactions/failed-transactions.component.ts
https://app.clickup.com/t/8zbdn2
=> Deep | Test  | Type Error: Cannot read property current Value  of undefined

apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.html, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.scss, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/assets/css/style-1.scss
=> prod | GIDK-b9r2dz | Aditi | prod sanity fix

apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts
=> Ravinder | Test | On ledger before selecting particular entry detail pop up should not open

apps/web-giddh/src/app/contact/aging-dropdown/aging.dropdown.component.ts
https://app.clickup.com/t/b9n9a9
=> Ravinder | Test | user can give all time interval input in one go

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.scss, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/locale/en.json, apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json, apps/web-giddh/src/assets/locale/proforma-invoice/en.json
https://app.clickup.com/t/b40g0a
=> Ravinder | Test | Add an option in UI for putting custom voucher number for Purchase Debit note and Credit note.

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/94zb9j
=> Ravinder | Stage | On ledger generate voucher checkbox is removed automatically when change voucher type

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/94zb9j
=> Ravinder | Beta | On ledger generate voucher checkbox is removed automatically when change voucher type

apps/web-giddh/src/assets/magic-link-assets/magic.css, apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/94z543
=> prod | GIDK-94z543 | Aditi | Download voucher and attachment icon

apps/web-giddh/src/assets/magic-link-assets/magic.css, apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/94z543
=> beta | GIDK-94z543 | Aditi | Download voucher and attachment icon

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/proforma-invoice/components/aside-menu-product-service/component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/94zb9j
=> Ravinder | Prod | On ledger generate voucher checkbox is removed automatically when change voucher type

apps/web-giddh/src/assets/magic-link-assets/magic.css, apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/94z543
=> stage | GIDK-94z543 | Aditi | Download voucher and attachment icon

apps/web-giddh/src/app/material-ledger/ledger.component.ts
=> Ravinder | Test | Fixed double popup issue

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/ledger/ledger.component.html
https://app.clickup.com/t/6f7aa2
=> Deep |Test | Type Error: Cannot read property 'label' of undefined

apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts
=> Ravinder | Stage | On ledger before selecting particular entry detail pop up should not open

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/proforma-invoice/services/proforma-invoice-utility.service.ts
https://app.clickup.com/t/bfd31j
=> Ravinder | Test | User is not able to create debit note number manually form debit note module.

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/8z9dvz
=> test | GIDK-8z9dvz | Aditi | create customer side bar

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.scss, apps/web-giddh/src/app/daybook/daybook.module.ts, apps/web-giddh/src/app/settings/integration/payment/icici/payor-create-edit/payor-create-edit.component.html, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/b9vmw0
=> test | GIDK-b9vmw0 | Aditi | Daybook page design changes as per demo

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/invoice/proforma/proforma-list.component.html, apps/web-giddh/src/app/invoice/recurring/recurring.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
https://app.clickup.com/t/6f6e0q
=> Deep | Test |Added Safe Navigation Operator

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/models/api-models/Ledger.ts, apps/web-giddh/src/app/services/ledger.service.ts
https://app.clickup.com/t/951g76
=> Ravinder | Test | Download voucher in ledger through voucherUniqueName

apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts
https://app.clickup.com/t/43k7ez
=> Ravinder | Test | active class issue on subscription

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/8z9dvz
=> stage | GIDK-8z9dvz | Aditi | create customer side bar

apps/web-giddh/src/app/daybook/advance-search/daybook-advance-search.component.html, apps/web-giddh/src/app/daybook/daybook.component.html, apps/web-giddh/src/app/daybook/daybook.component.scss, apps/web-giddh/src/app/daybook/daybook.module.ts, apps/web-giddh/src/app/settings/integration/payment/icici/payor-create-edit/payor-create-edit.component.html, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/b9vmw0
=> stage | GIDK-b9vmw0 | Aditi | Daybook page design changes as per demo

apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/bn5z45
=> Ravinder | Test | Duplicate vendors are showing on payment pop up

apps/web-giddh/src/app/all-items/all-item.component.ts
https://app.clickup.com/t/8zbdev
=> Deep |Stage |Cannot read property 'for Each' of undefined

apps/web-giddh/src/app/material-ledger/ledger.component.ts
https://app.clickup.com/t/bn603t
https://app.clickup.com/t/bn607g
=> Ravinder | Test | Ledger Bug fixes

apps/web-giddh/src/app/import-excel/import-report/import-report.component.ts
https://app.clickup.com/t/8zbdvd
=> Deep | Stage | Cannot read property 'map' of null

apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/bn5z45
=> Ravinder | Test | Check/Uncheck issue on vendor

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
https://app.clickup.com/t/218e46
=> Ravinder | Test | When template name is large then it is not fully displayed even on hovering the dots

apps/web-giddh/src/app/models/api-models/proforma.ts, apps/web-giddh/src/app/proforma-invoice/components/proforma-last-invoices/proforma-last-invoices.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/bnb1pf
=> Ravinder | Test | Multi-currency - User is not able to copy previous sales

apps/web-giddh/src/app/ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html
https://app.clickup.com/t/7x3gzg
=> Deep | Stage | Cannot set property 'name' of undefined

apps/web-giddh/src/app/permissions/components/list/permission.list.component.ts, apps/web-giddh/src/app/permissions/components/model/permission.model.component.html
https://app.clickup.com/t/951fxm
=> Deep |Stage | Cannot read property 'unique Name' of null

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/41hubz
=> Ravinder | Test | Whole screen is getting black on sales invoice page, while clicking edit icon of adjust amount option in deposit section

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/41hubz
=> Ravinder | Stage | Whole screen is getting black on sales invoice page, while clicking edit icon of adjust amount option in deposit section

apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.html, apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.scss, apps/web-giddh/src/app/shared/header/components/aside-setting/aside-setting.component.ts, apps/web-giddh/src/assets/locale/aside-setting/en.json, apps/web-giddh/src/assets/locale/aside-setting/hi.json, apps/web-giddh/src/assets/locale/aside-setting/mr.json
https://app.clickup.com/t/43k7ez
=> Ravinder | Stage | Add active class on setting sidebar items and apply design same as hover effect

apps/web-giddh/src/app/all-items/all-item.component.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/assets/locale/all-items/en.json, apps/web-giddh/src/assets/locale/all-items/hi.json, apps/web-giddh/src/assets/locale/all-items/mr.json
https://app.clickup.com/t/7hkc69
=> Ravinder | Stage | IN UAE BASED COMPANY GSTR-1,2,3B and E-way Bill MODULE SHOWN

apps/web-giddh/src/app/new-inventory/component/combo-list/inventory-combo-list.component.html, apps/web-giddh/src/app/new-inventory/component/combo-list/inventory-combo-list.component.scss, apps/web-giddh/src/app/new-inventory/component/inventory-group/inventory-group.component.html, apps/web-giddh/src/app/new-inventory/component/inventory-group/inventory-group.component.scss, apps/web-giddh/src/app/new-inventory/component/inventory-product-service-list/inventory-product-service-list.component.html, apps/web-giddh/src/app/new-inventory/component/inventory-product-service-list/inventory-product-service-list.component.scss, apps/web-giddh/src/app/new-inventory/component/inventory-sidebar/inventory-sidebar.component.scss, apps/web-giddh/src/app/new-inventory/component/inventory-transaction-list/inventory-transaction-list.component.html, apps/web-giddh/src/app/new-inventory/new-inventory.component.scss
=> test | GIDK-chrp2x | Aditi | inventory design fix

apps/web-giddh/src/app/inventory/components/custom-stock-components/inventory.customstock.component.html, apps/web-giddh/src/app/inventory/components/custom-stock-components/inventory.customstock.component.ts, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts, apps/web-giddh/src/app/inventory/inventory.component.ts, apps/web-giddh/src/app/inventory/jobwork/jobwork.component.html
https://app.clickup.com/t/8zbdwu
=> Deep | Stage | Cannot read property 'code' of null

apps/web-giddh/src/app/financial-reports/components/filter/filter.component.html, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.ts
https://app.clickup.com/t/6n484u
=> Ravinder | Test | Previously visited company's name is showing entity switch dropdown in new company

apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts
https://app.clickup.com/t/chy82n
=> Ravinder | Test | not able to remove inherent discount

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/cqfjry
=> Ravinder | Test | User is not able to generate invoice when user hit Copy previous invoice option in module page.

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/8tp4bx
=> Ravinder | Test | On invoice page, select all checkbox is not coming when closing bulk update pop up

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/material-ledger/ledger.vm.ts
https://app.clickup.com/t/7hqtyw
=> Ravinder | Stage | Particular is getting autofill in mapped transaction on ledger

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/material-ledger/ledger.vm.ts
=> Ravinder | Test | Revert - On ledger before selecting particular entry detail pop up should not open for bank transaction

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/8tp4bx
=> Ravinder | Stage | On invoice page, select all checkbox is not coming when closing bulk update pop up

apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts
=> Ravinder | Stage | Revert - On ledger before selecting particular entry detail pop up should not open for bank transaction

apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts
=> Ravinder | Beta | Revert - On ledger before selecting particular entry detail pop up should not open for bank transaction

apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts
=> Beta to Prod

apps/web-giddh/src/app/shared/header/components/custom-fields/custom-fields.component.ts
=> Ravinder | Test | Fixed custom fields not showing

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.html, apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.html, apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.html, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html, apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html
https://app.clickup.com/t/cqmmt0
=> Deep | Test | Cannot read property 'name' of undefined

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
https://app.clickup.com/t/cqmzaf
=> Ravinder | Test | discount column issue in debit note for customer

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/8zbf47
=> Revert "Deep | Test | Invalid event target"

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
https://app.clickup.com/t/cqmzaf
=> Ravinder | Stage | discount column issue in debit note for customer

apps/web-giddh/src/app/material-ledger/ledger.component.html
https://app.clickup.com/t/dm0xdx
=> Ravinder | Stage | Date picker is not working on ledger

apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts, apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.html, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.ts, apps/web-giddh/src/app/import-excel/import-report/import-report.component.ts, apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/out.template.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts, apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.ts, apps/web-giddh/src/app/reports/components/report-details-components/report.details.component.ts, apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.ts, apps/web-giddh/src/app/search/components/sidebar-components/search.sidebar.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/6n484u
=> Ravinder | Stage | Previously visited company's name is showing entity switch dropdown in new company

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts
https://app.clickup.com/t/dm11ct
=> Deep| Test| Cannot read properties of null (reading 'voucher Adjustments')

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/29d8wq
=> Ravinder | Stage | Status of address tab in accounts in Master section

apps/electron-giddh/src/offline-api/helpers/general.ts, apps/electron-giddh/src/offline-api/helpers/nedb_async.ts, apps/electron-giddh/src/offline-api/services/local/companies.ts, apps/electron-giddh/src/offline-api/services/local/company.ts, apps/electron-giddh/src/package.json, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/services/http.interceptor.ts, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts, package.json
=> Ravinder | Test | Fixed File create issue

apps/web-giddh/src/app/actions/groupwithaccounts.actions.ts, apps/web-giddh/src/app/contact/aside-menu-account/aside.menu.account.component.html, apps/web-giddh/src/app/contact/aside-menu-account/aside.menu.account.component.ts, apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.html, apps/web-giddh/src/app/shared/generic-aside-menu-account/generic.aside.menu.account.component.ts, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html, apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/custom-fields/custom-fields.component.ts, apps/web-giddh/src/app/shared/header/components/new-manage-groups-accounts/manage-groups-accounts.component.ts, apps/web-giddh/src/app/store/GroupWithAccounts/groupwithaccounts.reducer.ts, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1tea76
=> Ravinder | Test | Provide option to add custom field on sundry debtor/creditor account at the time of a/c creation when no custom field is created

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/8za5xu
=> Ravinder | Test | User is not able to delete PB created for Fixed Asset.

apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts, apps/web-giddh/src/app/welcome/welcome.component.ts
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#9379
=> Revert "Deep |Test | Cannot set properties of undefined (setting 'name')"

apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts, apps/web-giddh/src/app/welcome/welcome.component.ts
https://app.clickup.com/t/dtqvbd
=> Deep | Test | Cannot set properties of undefined (setting 'name')

apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts, apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.html, apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts, apps/web-giddh/src/app/models/api-models/GstReconcile.ts, apps/web-giddh/src/app/models/api-models/recipt.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/dm1h2g
=> Ravinder | Test | GST report section:- user not able to fetch invoice through report section

apps/web-giddh/src/app/contact/contact.component.ts
=> Ravinder | Test | Sorted by closing balance by default

apps/web-giddh/src/app/contact/contact.component.ts
=> Ravinder | Stage | Sorted by closing balance by default

apps/web-giddh/src/app/contact/contact.component.ts
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#9385
=> Revert "Ravinder | Stage | Sorted by closing balance by default"

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger.vm.ts
https://app.clickup.com/t/dm11kk
=> Deep| Test | Added Safe Navigation Operator

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/services/apiurls/invoice.api.ts, apps/web-giddh/src/app/services/invoice.service.ts
https://app.clickup.com/t/bnaw0k
=> Ravinder | Test | Cancellation of einvoice for voucher version 2

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/7hgtdw
=> Deep |Stage| Type Error: Cannot read property 'label' of undefined

apps/web-giddh/src/app/manufacturing/report/mf.report.component.html, apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.html, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.html, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts, apps/web-giddh/src/app/welcome/welcome.component.html, apps/web-giddh/src/app/welcome/welcome.component.ts
https://app.clickup.com/t/dm5vuq
=> Deep| Stage | Cannot read properties of undefined (reading 'label')

apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger.vm.ts
https://app.clickup.com/t/dm11kk
=> Deep | Test | Added Safe Navigation Operator

apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/8zbdcp
=> Deep | Stage | Added Safe Navigation Operator

apps/web-giddh/src/app/manufacturing/report/mf.report.component.html, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.html
https://app.clickup.com/t/8zbdjd
=> Deep| Stage| Cannot read property 'label' of undefined

package.json
=> fix: ngx-lightbox version issue

apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.html, apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.scss
https://app.clickup.com/t/dtvhgk
=> stage | GIDK-dtvhgk | Aditi | Customer name and Status GSTR

apps/web-giddh/src/app/gst/filing/header/filing-header.component.ts, apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/document-issued/document-issued.component.ts, apps/web-giddh/src/app/gst/filing/tabs/push-to-gstin/components/failed-transactions/failed-transactions.component.ts
https://app.clickup.com/t/8zbdn2
=> Deep | Stage | Cannot read property 'current Value' of undefined

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/invoice/recurring/recurring.component.ts, apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/edit.invoice.component.ts, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.ts
https://app.clickup.com/t/6f6e0q
=> Deep | Stage | Cannot read property 'unique Name' of undefined

README.md
=> doc: Add contributing guideline in README.md

README.md, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
=> Update readme test

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts
https://app.clickup.com/t/dm11ct
=> Deep | Added Safe Navigation Operator

apps/web-giddh/src/app/all-items/all-item.component.ts
https://app.clickup.com/t/8zbdev
=> Deep |Stage | Cannot read property 'for Each' of undefined

apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts
https://app.clickup.com/t/dm11ct
=> Deep | Stage | Cannot read properties of null (reading 'voucher Adjustments')

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.html
https://app.clickup.com/t/6f7aa2
=> Deep | Stage | Cannot read property 'label' of undefined

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/8zbf47
=> Deep | Stage | Invalid event target

apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts, apps/web-giddh/src/app/permissions/components/list/permission.list.component.ts, apps/web-giddh/src/app/permissions/components/model/permission.model.component.ts
https://app.clickup.com/t/951fxm
=> Deep | Test | Cannot read property 'unique Name' of null

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/e584bc
=> Ravinder | Test | GST Tax is not getting added in invoice total when user trying to create sales invoice from sales invoice module.

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/services/general.service.ts
https://app.clickup.com/t/e5brpc
=> Ravinder | Test | Allowed RCM in sales/debit/credit note on voucher and ledger

apps/web-giddh/src/app/invoice/preview/models/advanceSearch/invoiceAdvanceSearch.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/design-filters/design.filters.component.html
=> Stage to Beta

apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts, apps/web-giddh/src/app/permissions/permission-data.service.ts, apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.ts, apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts, apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/company-add-new-ui/company-add-new-ui.component.ts, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-account-modal/share-account-modal.component.ts, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.html, apps/web-giddh/src/app/shared/header/components/share-group-modal/share-group-modal.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/shared/on-boarding/on-boarding.component.ts, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts, apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.html, apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts, apps/web-giddh/src/app/shared/purchase-send-email/purchase-send-email.component.ts, apps/web-giddh/src/app/shared/revision-history/revision-history.component.ts, apps/web-giddh/src/app/welcome/welcome.component.ts
https://app.clickup.com/t/951fxm
=> Deep | Test | Fixed the Issue

apps/web-giddh/src/app/login/login.component.ts, apps/web-giddh/src/app/proforma-invoice/components/proforma-add-bulk-items/proforma-add-bulk-items.component.ts, apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts, apps/web-giddh/src/app/shared/header/components/account-operations/account-operations.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts, apps/web-giddh/src/app/shared/header/components/group-update/group-update.component.ts, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
https://app.clickup.com/t/dm9are
=> Deep | Stage | this .link Handlers .filter is not a function

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/ew54z8
=> Deep | Test | Cannot read properties of undefined (reading 'bank Payment Details')

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/ew54z8
=> Deep | Stage | Cannot read properties of undefined (reading 'bank Payment Details')

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/e5brpc
=> Ravinder | Test | Fixed RCM checkbox on edit page

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger.vm.ts
https://app.clickup.com/t/f210e1
https://app.clickup.com/t/f20yrp
=> Ravinder | Test | Fixed RCM Amount replace issue

apps/web-giddh/src/app/services/apiurls/logs.api.ts, apps/web-giddh/src/app/services/logs.service.ts
https://app.clickup.com/t/1kcka1
=> Ravinder | Test | On new audit logs page, load more button is not working

apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
https://app.clickup.com/t/f7kdvq
=> Deep | Test | Cannot read properties of null (reading 'countryV2')

apps/web-giddh/src/app/invoice/settings/invoice.settings.component.ts
https://app.clickup.com/t/f7kdvq
=> Deep | Stage | Cannot read properties of null (reading 'countryV2')

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/du0145
=> stage | GIDK-du0145 | Aditi | alignment issue in sales invoice creation in foreign debtor

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/du0145
=> test | GUDK-du0145 | Aditi | alignment issue in sales invoice creation in foreign debtor

apps/web-giddh/src/app/services/logs.service.ts
https://app.clickup.com/t/1kcka1
=> Ravinder | Test | Removed unused parameter | Fixed build issue

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/bnawhw
=> Ravinder | Test | Fixed PB delete case

apps/web-giddh/src/app/actions/accounts.actions.ts
https://app.clickup.com/t/ew4ect
=> Ravinder | Test | Getting error - Entity unique name to be shared cannot be blank. while sharing account from master

apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/1te19a0
=> Ravinder | Test | Setting side bar is getting overlapped on create a/c side bar

apps/web-giddh/src/app/actions/accounts.actions.ts
https://app.clickup.com/t/ew4ect
=> Ravinder | Stage | Getting error - Entity unique name to be shared can not be blank. while sharing account from master

apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/app/shared/primary-sidebar/primary-sidebar.component.ts
https://app.clickup.com/t/1te19a0
=> Ravinder | Stage | Setting side bar is getting overlapped on create a/c side bar

apps/web-giddh/src/app/store/Inventory/inventory.reducer.ts
https://app.clickup.com/t/1tktuz3
=> Deep | Test | Cannot read properties of null (reading 'unique Name')

apps/web-giddh/src/app/proforma-invoice/services/proforma-invoice-utility.service.ts
https://app.clickup.com/t/dzjz6d
=> Ravinder | Test | Purchase from vendor ledger and module not shown in GSTR-2

apps/web-giddh/src/app/import-excel/import-wizard/import-wizard.component.ts, apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
https://app.clickup.com/t/1te4c1m
=> Deep | Test | Cannot read properties of undefined (reading 'items')

apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts, apps/web-giddh/src/app/contact/aside-menu-account/aside.menu.account.component.ts, apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts
https://app.clickup.com/t/1rwyz4u
=> Deep | Stage | Cannot read properties of null (reading 'unique Name')

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1ttkc4r
=> Ravinder | Test | PB is not getting updated when user add one more line item in created PB.

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/shared/layout/layout.component.ts
https://app.clickup.com/t/4dckk9
=> Ravinder | Test | Setting side bar is getting closed automatically when going to setting modules

apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.scss
https://app.clickup.com/t/1k99qu
=> Deep | Test | Fixed text Overflow issue

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/1tz5tb5
=> Deep | Test | Cannot read properties of undefined (reading 'display')

apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1k99qu
=> Deep | Stage | Fixed Text-overflow Issue

apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.ts, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.html, apps/web-giddh/src/app/shared/header/components/new-group-account-sidebar/groups-account-sidebar.component.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1te4c0k
=> Deep | Test | Cannot read properties of undefined (reading 'data')

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/1tz5tb5
=> Deep | Stage | Cannot read properties of undefined (reading 'display')

apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.ts
https://app.clickup.com/t/1te4c0k
=> Deep | Stage | Cannot read properties of undefined (reading 'data')

apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts
https://app.clickup.com/t/1rwyy82
=> Deep | Stage |  Cannot read properties of null (reading 'class List')

apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
https://app.clickup.com/t/1u51ph1
=> Deep | Test | Cannot read properties of undefined (reading 'map')

apps/web-giddh/src/app/all-items/all-item.component.ts
https://app.clickup.com/t/1uakqxd
=> Deep | Test | Cannot read property 'to Lower Case' of undefined

apps/web-giddh/src/app/app.routes.ts, apps/web-giddh/src/app/routes-array.ts, apps/web-giddh/src/app/services/apiurls/invoice.api.ts, apps/web-giddh/src/app/services/apiurls/purchase-order.api.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/services/purchase-order.service.ts, apps/web-giddh/src/app/verify-email/verify-email.component.html, apps/web-giddh/src/app/verify-email/verify-email.component.ts, apps/web-giddh/src/app/verify-email/verify-email.module.ts, apps/web-giddh/src/app/verify-email/verify-email.routing.module.ts
https://app.clickup.com/t/51cn6z
=> Ravinder | Test | Proper page should come when user click on verify email link

apps/web-giddh/src/app/app.routes.ts, apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/routes-array.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
https://app.clickup.com/t/e5dxr7
=> Ravinder | Test | Left side bar is automatically changing from collapsed to expanded view

apps/web-giddh/src/app/material-ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.ts
https://app.clickup.com/t/1uandn3
=> Ravinder | Test | Ledger columnar page is not getting displayed if user goes to 2nd page of columnar report.

apps/web-giddh/src/app/app.routes.ts, apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/routes-array.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions/subscriptions.component.ts
https://app.clickup.com/t/e5dxr7
=> Ravinder | Stage | Left side bar is automatically changing from collapsed to expanded view

apps/web-giddh/src/app/material-ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.ts
https://app.clickup.com/t/1uandn3
=> Ravinder | Stage | Ledger columnar page is not getting displayed if user goes to 2nd page of columnar report.

apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.ts, apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/1uanfvn
=> Ravinder | Test | On pending invoice page pop up is not opening properly.

apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html, apps/web-giddh/src/app/import-excel/map-excel-data/map-excel-data.component.ts, apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts
https://app.clickup.com/t/1tktrf3
=> Deep | Test | Cannot read properties of undefined (reading '_raw Validators')

apps/web-giddh/src/app/store/General/general.reducer.ts
https://app.clickup.com/t/b3z5b4
=> Deep| Stage | Cannot read property 'length' of null

apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/1uanfvn
=> Ravinder | Stage | On pending invoice page pop up is not opening properly

apps/web-giddh/src/app/import-excel/import-wizard/import-wizard.component.ts, apps/web-giddh/src/app/import-excel/upload-file/upload-file.component.ts
https://app.clickup.com/t/1te4c1m
=> Deep | Stage | Cannot read properties of undefined (reading 'items')

apps/web-giddh/src/app/permissions/components/details/permission.details.component.ts
https://app.clickup.com/t/1u51ph1
=> Deep | Stage | Cannot read properties of undefined (reading 'map')

apps/web-giddh/src/app/all-items/all-item.component.ts
https://app.clickup.com/t/1uakqxd
=> Deep | Stage | Cannot read property 'to Lower Case' of undefined

apps/web-giddh/src/app/app.routes.ts, apps/web-giddh/src/app/routes-array.ts, apps/web-giddh/src/app/services/apiurls/invoice.api.ts, apps/web-giddh/src/app/services/apiurls/purchase-order.api.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/services/purchase-order.service.ts, apps/web-giddh/src/app/verify-email/verify-email.component.html, apps/web-giddh/src/app/verify-email/verify-email.component.ts, apps/web-giddh/src/app/verify-email/verify-email.module.ts, apps/web-giddh/src/app/verify-email/verify-email.routing.module.ts
https://app.clickup.com/t/51cn6z
=> Ravinder | Stage | Proper page should come when user click on verify email link

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts
=> Ravinder | Stage | Enable bulk payment

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
https://app.clickup.com/t/1uatr00
=> Deep | Test | Cannot read properties of undefined (reading 'replace')

apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.html
https://app.clickup.com/t/1ugafvx
=> Ravinder | Stage | Cross icon in not in correct position. It should be in corner.

apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/1uatqjn
=> Deep | Test |  Cannot read properties of null (reading 'template Unique Name')

apps/web-giddh/src/app/app.module.ts, apps/web-giddh/src/app/app.routes.ts, apps/web-giddh/src/app/models/defaultMenus.ts, apps/web-giddh/src/app/onboarding/onboarding.component.html, apps/web-giddh/src/app/routes-array.ts, apps/web-giddh/src/assets/locale/all-items/en.json, apps/web-giddh/src/assets/locale/all-items/hi.json, apps/web-giddh/src/assets/locale/all-items/mr.json
=> Ravinder | Test | Revert Hide Tally on Test ENV

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/1ugd4jm
=> Ravinder | Test | Hide company address option from template setting>footer section.

apps/web-giddh/src/app/accounting/accouting-sidebar/accounting-sidebar.component.html, apps/web-giddh/src/app/accounting/accouting-sidebar/accounting-sidebar.component.ts, apps/web-giddh/src/app/accounting/constants/accounting.constant.ts, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
https://app.clickup.com/t/1mm9gr7
=> Ravinder | Test | Not able to save contra entry

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/1ugd4jm
=> Ravinder | Stage | Hide company address option from template setting>footer section.

apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html
https://app.clickup.com/t/1tdzwv5
=> Ravinder | Stage | Loader is not coming while updating accounts from Master

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/bulkUpdateModal/invoiceBulkUpdateModal.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1ug9ygk
https://app.clickup.com/t/1uga02w
=> Ravinder | Stage | Bulk update popup close issue and due date update issue

apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/shared/send-email-invoice/send-email-invoice.component.html
https://app.clickup.com/t/7q9a6e
=> Ravinder | Test | Bad Gateway is displayed while trying to download Invoice PDF from ledger and Invoice list page

apps/web-giddh/src/app/accounting/accouting-sidebar/accounting-sidebar.component.html, apps/web-giddh/src/app/accounting/accouting-sidebar/accounting-sidebar.component.ts, apps/web-giddh/src/app/accounting/constants/accounting.constant.ts, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html, apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.ts
https://app.clickup.com/t/1mm9gr7
=> Ravinder | Stage | Not able to save contra entry

apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
https://app.clickup.com/t/29dagr
https://app.clickup.com/t/1ugetj0
=> Ravinder | Test | Fixed download icons on PB preview page and download options on voucher preview

apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.html, apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.ts
=> Ravinder | Test | Original copy allowed for voucher version 2 only

apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts, apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.html, apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts, apps/web-giddh/src/app/vat-report/transactions/vatReportTransactions.component.ts
=> Ravinder | Test | Download voucher changes on gst/vat

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1up0a3c
https://app.clickup.com/t/1up433f
=> Ravinder | Test | RCM in not applying in update sales invoice flow

apps/web-giddh/src/app/shared/send-email-invoice/send-email-invoice.component.html, apps/web-giddh/src/app/shared/send-email-invoice/send-email-invoice.component.ts
=> Ravinder | Test | Allow original option in version 2 only

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/services/apiurls/invoice.api.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/store/Invoice/Receipt/receipt.reducer.ts
https://app.clickup.com/t/1uvpwaa
https://app.clickup.com/t/1up6zdm
=> Ravinder | Test | Make customer name editable for credit/debit note

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1ugdxkr
=> Deep | Test | Cannot read properties of undefined (reading 'billing Details')

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts
https://app.clickup.com/t/1up63vg
=> Ravinder | Test | Make customer name editable from non multi-currency a/c to multi-currency a/c from ledger and invoice

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
https://app.clickup.com/t/1uvt6qm
=> Deep | Test | Cannot read properties of undefined (reading 'to Lower Case')

apps/web-giddh/src/app/material-ledger/ledger.component.html
https://app.clickup.com/t/1uvr93x
=> Ravinder | Test | Net total of ledger is showing in single line in case of multi-currency.

apps/web-giddh/src/app/vat-report/vatReport.component.ts
https://app.clickup.com/t/1uvvj6u
=> Deep | Test | Cannot read properties of undefined (reading 'unique Name')

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/locale/proforma-invoice/en.json, apps/web-giddh/src/assets/locale/proforma-invoice/hi.json, apps/web-giddh/src/assets/locale/proforma-invoice/mr.json
https://app.clickup.com/t/1uvwu7w
=> Ravinder | Test | Deletes the attachment from vouchers

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1uvwu7w
=> Ravinder | Test | Change detection issue after deleting file

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
https://app.clickup.com/t/1uvxjrv
=> Deep | Test | Cannot read properties of undefined (reading 'name')

apps/web-giddh/src/app/models/api-models/Sales.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1ug9mjg
=> Ravinder | Test | Any Update in purchase bill will remove it from report

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/1uge4t3
=> Deep | Stage | Cannot read properties of null (reading 'class List')

apps/web-giddh/src/app/accounting/journal-voucher/voucher/voucher.component.html
https://app.clickup.com/t/1tktrf3
=> Deep | Stage | Cannot read properties of undefined (reading '_rawValidators')

apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.scss, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/models/api-models/Ledger.ts, apps/web-giddh/src/app/models/api-models/recipt.ts, apps/web-giddh/src/app/services/apiurls/common.api.ts, apps/web-giddh/src/app/services/common.service.ts, apps/web-giddh/src/assets/locale/ledger/en.json, apps/web-giddh/src/assets/locale/ledger/hi.json, apps/web-giddh/src/assets/locale/ledger/mr.json, apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js, apps/web-giddh/src/meta/magic.html
=> Ravinder | Test | New download api

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1uvvzmu
https://app.clickup.com/t/1v1e4q2
=> Ravinder | Test | Allowed base account change and call voucher api for pending voucher as well

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js, apps/web-giddh/src/assets/magic-link-assets/magic.css
https://app.clickup.com/t/951dmp
=> Ravinder | Test | Handled download file new response in magic link

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js, apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/951dmp
=> Ravinder | Test | Fixed Voucher version issue on magic link page

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js, apps/web-giddh/src/environments/environment.stage.cordova.ts, apps/web-giddh/src/meta/yodlee-success.html, apps/web-giddh/webpack.partial.js, apps/web-giddh/webpack.stage.partial.js
=> Ravinder | Stage | Changed api url stage

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/ledger.service.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> Ravinder | Test | Voucher adjustment changes

apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts, apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts, apps/web-giddh/src/app/models/api-models/GstReconcile.ts, apps/web-giddh/src/app/vat-report/transactions/vatReportTransactions.component.ts
https://app.clickup.com/t/1uvv61n
=> Ravinder | Test | PDF not loading in report mode also not able to edit any entry

apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts, apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.scss, apps/web-giddh/src/app/models/api-models/Invoice.ts, apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
https://app.clickup.com/t/1v74vxd
https://app.clickup.com/t/1v78a48
=> Ravinder | Test | Magic link tooltip issue, attachment remove icon on new ledger, download voucher issue

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/sales/aside-menu-sales-other-taxes/aside-menu-sales-other-taxes.ts
=> Ravinder | Test | Fixed Other tax default tax for tcs/tds

apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts, apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
https://app.clickup.com/t/1vczbgd
https://app.clickup.com/t/1vcyagm
=> Ravinder | Test | Magic link download issue and calculation method default selection issue

apps/web-giddh/src/app/inventory/manufacturing/manufacturing.component.html, apps/web-giddh/src/app/manufacturing/report/mf.report.component.html, apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss, apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
https://app.clickup.com/t/1v7953d
=> Ravinder | Test | Space is coming in the manufacturing report

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
https://app.clickup.com/t/1v74vxd
=> Ravinder | Stage | Wrong invoice number is displaying on voucher when changing date range in magic link

apps/web-giddh/src/app/actions/invoice/invoice.actions.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/services/invoice.templates.service.ts
https://app.clickup.com/t/1uan1k1
=> Ravinder | Test | Template is getting deleted even assigned to some invoices

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1vd1egg
=> Ravinder | Test | Unable to add attachment on voucher in update voucher flow

apps/web-giddh/src/app/inventory/manufacturing/manufacturing.component.html, apps/web-giddh/src/app/manufacturing/report/mf.report.component.html, apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss, apps/web-giddh/src/app/manufacturing/report/mf.report.component.ts
https://app.clickup.com/t/1v7953d
=> Ravinder | Stage | Space is coming in the manufacturing report.

apps/web-giddh/src/app/models/api-models/Sales.ts, apps/web-giddh/src/app/models/api-models/recipt.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1vd2tu1
=> Ravinder | Test | Fixed deposit issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1kddkj
=> Ravinder | Test | While making deposit entry if you create bank account at the same time it will not come in the drop down

apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss, apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts
https://app.clickup.com/t/1t8ewtp
=> Ravinder | Stage | Aging report Issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1vju9jq
https://app.clickup.com/t/1vju94q
=> Ravinder | Test | Gst getting removed and deposit section issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1kddkj
=> Ravinder | Stage | While making deposit entry if you create bank account at the same time it will not come in the drop down

apps/web-giddh/src/app/actions/invoice/invoice.actions.ts, apps/web-giddh/src/app/proforma-invoice/components/proforma-print-inplace/proforma-print-in-place.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/send-email-invoice/send-email-invoice.component.ts
https://app.clickup.com/t/1vratcw
https://app.clickup.com/t/1vjucgv
https://app.clickup.com/t/1vju79w
https://app.clickup.com/t/1vjtw68
=> Ravinder | Test | Fixed many bugs

apps/web-giddh/src/meta/magic.html
https://app.clickup.com/t/1vjnfv2
=> Ravinder | Test | Download/attachment icon issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/3b9bbg
=> Ravinder | Test | While copy cash invoice from sales invoice page, it is changing the type of invoice from sales to cash

apps/web-giddh/src/app/actions/invoice/invoice.actions.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/services/invoice.templates.service.ts, apps/web-giddh/src/app/store/Invoice/invoice.template.reducer.ts
https://app.clickup.com/t/1uan1k1
=> Ravinder | Stage | Template is getting deleted even assigned to some invoices

apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts
https://app.clickup.com/t/6f8nfv
=> Ravinder | Test | On petty cash pending page if data is more then pagination is not coming

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/bn43yb
=> Ravinder | Test | Show company address in footer section of the template

apps/web-giddh/src/app/material-ledger/ledger.component.html
https://app.clickup.com/t/1vfm86
=> Ravinder | Test | Displayed stock unique name

apps/web-giddh/src/app/expenses/components/rejected-list/rejected-list.component.ts
https://app.clickup.com/t/6f8nfv
=> Ravinder | Stage | On petty cash pending page if data is more then pagination is not coming

apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/models/api-models/Invoice.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1vrhtcj
https://app.clickup.com/t/1vfm86
https://app.clickup.com/t/1vy3bdp
https://app.clickup.com/t/1vebw2
=> Ravinder | Stage | Fixed many bugs

apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.html, apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.ts, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.html, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts, apps/web-giddh/src/app/expenses/components/reject-petty-cash-entry-confirm-dialog/reject-petty-cash-entry-confirm-dialog.component.html, apps/web-giddh/src/app/expenses/components/reject-petty-cash-entry-confirm-dialog/reject-petty-cash-entry-confirm-dialog.component.ts, apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/expenses/expenses.module.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/6mxect
=> Ravinder | Test | Petty cash improvements

apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.ts
https://app.clickup.com/t/1vy7nxf
=> Ravinder | Test | Invalid date is passing in api when searching data with on ledger through advance search for by cheque number and clearance date

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1w3w2et
=> Ravinder | Test | Make state disable from UI if GSTIN is there in the address

apps/web-giddh/src/app/payment-receipt/components/create-edit/payment-receipt.component.html, apps/web-giddh/src/app/payment-receipt/components/create-edit/payment-receipt.component.ts, apps/web-giddh/src/assets/locale/reports/payment/en.json, apps/web-giddh/src/assets/locale/reports/payment/hi.json, apps/web-giddh/src/assets/locale/reports/payment/mr.json
=> Ravinder | Test | Fixed issues

apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.ts
=> Ravinder | Test | Stop others option from preselect

apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.ts, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts
https://app.clickup.com/t/6mxecu
=> Ravinder | Test | Fixed approval issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1w3w2et
=> Ravinder | Stage | Make state disable from UI if GSTIN is there in the address

apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts, apps/web-giddh/src/app/expenses/expenses.component.ts
https://app.clickup.com/t/6mxecu
=> Ravinder | Test | Fixed date filter issue

apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.ts
https://app.clickup.com/t/6mxecu
=> Ravinder | Test | Petty cash issue

apps/web-giddh/src/app/services/ledger.service.ts
https://app.clickup.com/t/1w9menk
=>  Ravinder | Test | Loader is not coming on ledger when deleting bulk entries

apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.ts
https://app.clickup.com/t/1vy7rrt
=> Ravinder | Test | Data is not coming on ledger when applying advance search after clearing filter

apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts
https://app.clickup.com/t/6mxecu
=> Ravinder | Test | Refreshed list of pending items in case of approval yes/no

apps/web-giddh/src/app/services/ledger.service.ts
https://app.clickup.com/t/1w9menk
=> Ravinder | Stage | Loader is not coming on ledger when deleting bulk entries

apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.html, apps/web-giddh/src/app/expenses/components/approve-petty-cash-entry-confirm-dialog/approve-petty-cash-entry-confirm-dialog.component.ts, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.html, apps/web-giddh/src/app/expenses/components/expense-details/expense-details.component.ts, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.html, apps/web-giddh/src/app/expenses/components/pending-list/pending-list.component.ts, apps/web-giddh/src/app/expenses/components/reject-petty-cash-entry-confirm-dialog/reject-petty-cash-entry-confirm-dialog.component.html, apps/web-giddh/src/app/expenses/components/reject-petty-cash-entry-confirm-dialog/reject-petty-cash-entry-confirm-dialog.component.ts, apps/web-giddh/src/app/expenses/expenses.component.html, apps/web-giddh/src/app/expenses/expenses.component.ts, apps/web-giddh/src/app/expenses/expenses.module.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/6mxect
=> Ravinder | Stage | Petty cash improvements

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/invoice/proforma/proforma-list.component.ts, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.ts, apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.ts
https://app.clickup.com/t/1w3vmr3
=> Ravinder | Test | Changes related to invoice number sequence on invoice preview page

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/invoice/proforma/proforma-list.component.ts, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.scss, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.ts, apps/web-giddh/src/app/reports/components/purchase-register-component/purchase.register.component.ts
https://app.clickup.com/t/1w3vmr3
=> Ravinder | Stage | Changes related to invoice number sequence on invoice preview page

apps/web-giddh/src/meta/.htaccess
=> Ravinder | Test | Allowing cobrowse to access assets

apps/web-giddh/src/app/contact/aging-dropdown/aging.dropdown.component.html, apps/web-giddh/src/app/contact/aging-dropdown/aging.dropdown.component.ts, apps/web-giddh/src/app/contact/aging-report/aging-report.component.html, apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts, apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/theme/form-fields/text-field/text-field.component.html, apps/web-giddh/src/app/theme/form-fields/text-field/text-field.component.ts
https://app.clickup.com/t/ew39w4
=> Ravinder | Test | Fixed Customer/vendor issues

apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.html, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.scss, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> fixed with sidebar overlapping and designing issues

apps/web-giddh/src/app/contact/aging-report/aging-report.component.html, apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/1wn5e3j
=> Ravinder | Test | Bug fixes

apps/web-giddh/src/app/material-ledger/components/advance-search/advance-search.component.ts
https://app.clickup.com/t/1vy7rrt
=> Ravinder | Stage | Data is not coming on ledger when applying advance search after clearing filter

apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html
https://app.clickup.com/t/1mm9697
=> Deep | Test |  Cannot read property 'length' of undefined

apps/web-giddh/src/app/financial-reports/components/profit-loss/components/profit-loss-grid/components/profit-loss-grid-row/profit-loss-grid-row.component.html, apps/web-giddh/src/app/financial-reports/components/trial-balance/components/trial-balance-grid/trial-balance-grid.component.ts
=> Ravinder | Stage | Cannot read property 'length' of undefined

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/8z9dvz
=>  beta | GIDK-8z9dvz | Aditi | create customer side bar

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/8z9dvz
=> prod | GIDK-8z9dvz | Aditi | create customer side bar

apps/web-giddh/src/assets/css/style-2.scss
=> Dilpreet | Test | Remove important css from form control

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/theme/attachments/attachments.component.ts, apps/web-giddh/src/assets/css/style-1.scss
https://app.clickup.com/t/1xbyk94
https://app.clickup.com/t/1xbyt40
=> Ravinder | Test | Attachment popup issues

apps/web-giddh/src/app/theme/attachments/attachments.component.ts
https://app.clickup.com/t/1xbzq7q
=> Ravinder | Test | Failed on load attachment pdf

apps/web-giddh/src/index.electron.prod.html
https://app.clickup.com/t/1xbwkr6
=> Ravinder | Test | Change Analytics code in Electron App

apps/web-giddh/src/app/theme/attachments/attachments.component.html, apps/web-giddh/src/app/theme/attachments/attachments.component.ts
https://app.clickup.com/t/1xc0kka
=> Ravinder | Test | Small design issues of attachment/voucher download new design

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/locale/proforma-invoice/en.json, apps/web-giddh/src/assets/locale/proforma-invoice/hi.json, apps/web-giddh/src/assets/locale/proforma-invoice/mr.json
https://app.clickup.com/t/1xc0nm5
https://app.clickup.com/t/1xc0nnz
=> Ravinder | Test | NV logic changes

apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/billing-details/billingDetail.component.scss, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.scss, apps/web-giddh/src/app/userDetails/components/move-company/move-company.component.html, apps/web-giddh/src/app/userDetails/components/move-company/move-company.component.scss, apps/web-giddh/src/app/userDetails/components/move-company/move-company.component.ts, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.html, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.scss, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.html, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss, apps/web-giddh/src/app/userDetails/userDetails.module.ts, apps/web-giddh/src/assets/css/color.scss, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/src/assets/locale/user-details/en.json, apps/web-giddh/src/assets/locale/user-details/hi.json, apps/web-giddh/src/assets/locale/user-details/mr.json
https://app.clickup.com/t/1xbwu8d
=> Dilpreet | Test |  Design Issue of Version 1

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.html
https://app.clickup.com/t/1xc0kka
=> Ravinder | Test | Fixed new changes

apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.scss, apps/web-giddh/src/assets/locale/user-details/en.json, apps/web-giddh/src/assets/locale/user-details/hi.json, apps/web-giddh/src/assets/locale/user-details/mr.json
https://app.clickup.com/t/1xbwu8d
=> Dilpreet | Test | fixed issues

apps/web-giddh/src/index.electron.prod.html
https://app.clickup.com/t/1xbwkr6
=> Ravinder | Stage | Change Analytics code in Electron App

apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts
https://app.clickup.com/t/45fe4n
=> Dilpreet | Test | Fixed subscription id blank in subscription page

apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.html, apps/web-giddh/src/app/userDetails/components/all-features/all-features.component.scss, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
https://app.clickup.com/t/1xbwu8d
=> Dilpreet | Test | Fixed all features popup

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.scss
=> Dilpreet fixed vendor page design issue

apps/web-giddh/src/app/contact/advanceSearch/contactAdvanceSearch.component.html, apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss, apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.scss, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xhmpey
=> Dilpreet | Test | Fixed responsive design for customer/vendor

apps/web-giddh/src/app/billing-details/billingDetail.component.scss, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.scss, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xqgbe2
=> Dilpreet | Test | Fixed other dimensions issues of subscription

apps/web-giddh/src/app/services/apiurls/settings.branch.api.ts, apps/web-giddh/src/app/services/settings.branch.service.ts, apps/web-giddh/src/app/services/settings.warehouse.service.ts, apps/web-giddh/src/app/settings/branch/branch.component.html, apps/web-giddh/src/app/settings/branch/branch.component.scss, apps/web-giddh/src/app/settings/branch/branch.component.ts, apps/web-giddh/src/app/settings/settings.module.ts, apps/web-giddh/src/app/settings/warehouse/constants/warehouse.constant.ts, apps/web-giddh/src/app/settings/warehouse/warehouse.component.html, apps/web-giddh/src/app/settings/warehouse/warehouse.component.scss, apps/web-giddh/src/app/settings/warehouse/warehouse.component.ts, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts, apps/web-giddh/src/assets/locale/en.json, apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json, apps/web-giddh/src/assets/locale/settings/branch/en.json, apps/web-giddh/src/assets/locale/settings/branch/hi.json, apps/web-giddh/src/assets/locale/settings/branch/mr.json, apps/web-giddh/src/assets/locale/settings/warehouse/en.json, apps/web-giddh/src/assets/locale/settings/warehouse/hi.json, apps/web-giddh/src/assets/locale/settings/warehouse/mr.json
https://app.clickup.com/t/1wfb0wx
=> Ravinder | Test | Completed branch/warehouse archive/unarchive and removed archived branch from left sidebar

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/shared/header/header.component.scss, apps/web-giddh/src/assets/css/style-1.scss
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#9723
=> Revert "Dilpreet | Test | Fixed responsive design issues"

apps/web-giddh/src/app/userDetails/components/move-company/move-company.component.html, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.html, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xqgbe2
=> Dilpreet | Test | Fixed expansion and move dropdown issue

apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
https://app.clickup.com/t/1y2q489
=> Dilpreet | Test | Fixed error of buy plan on subscription page

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/services/adjustment-utility.service.ts
=> Ravinder | Test | Updated adjustment json

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/services/adjustment-utility.service.ts
=> Ravinder | Test | Fixed adjustment in update

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/apiurls/advance-receipt-adjustment.api.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/services/adjustment-utility.service.ts
=> Ravinder | Test | Fixed adjustments changes

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/models/api-models/AdvanceReceiptsAdjust.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts, apps/web-giddh/src/assets/locale/invoice/en.json, apps/web-giddh/src/assets/locale/invoice/hi.json, apps/web-giddh/src/assets/locale/invoice/mr.json
=> Fixed adjustment issue

apps/web-giddh/src/app/contact/contact.component.scss, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xhmpey
=> Dillpreet | Test | Fixed vendor responsive issues

apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/1y8ebk3
=> Ravinder | Stage | By default close setting side bar on every setting page

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/1y8etjr
=> Ravinder | Test | Adjustment issue from invoices and deposit section issue

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/services/adjustment-utility.service.ts
=> Ravinder | Test | Fixed nulity issue

apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts
=> Dilpreet | Stage | Fixed change detection on no data of subscriptions issue

apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts
=> Dilpreet | Test | Fixed no subscriptions issue

apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/1y8ebk3
=> Ravinder | Test | Closed sidebar by default on all pages

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts, apps/web-giddh/src/app/models/api-models/BranchTransfer.ts
https://app.clickup.com/t/1y2vwb4
=> Ravinder | Test | Not able to change stock in update for multiple product delivery challan and receipt note

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.scss
=> Dilpreet | Test |  Fixed vendor design modifications

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html
https://app.clickup.com/t/1xqeqnx
=> Ravinder | Test | Get Payor api is not calling on vendor page when changing amount from zero to some value

apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/1wn5e3j
=> Ravinder | Test | Fixed Issue 11

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
=> Ravinder | Test | Fixed adjustment issue

apps/web-giddh/src/app/models/api-models/AdvanceReceiptsAdjust.ts, apps/web-giddh/src/app/models/api-models/Sales.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/1yebhgq
=> Ravinder | Test | In adjustment pop-up, receipt amount is shown in rupee and also converted mount of rupee is not shown.

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html
https://app.clickup.com/t/1y8fa7p
=> Ravinder | Test | Deposit section shouldnot come in case of update mode

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
https://app.clickup.com/t/1ykvmhk
=> Ravinder | Test | Not able to update branch transfer delivery challan and receipt note

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html, apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.ts, apps/web-giddh/src/app/reports/components/payment-report/payment-report.component.html, apps/web-giddh/src/app/reports/components/payment-report/payment-report.component.ts, apps/web-giddh/src/app/reports/constants/reports.constant.ts
https://app.clickup.com/t/1yky1px
=> Ravinder | Test | Fixed Exception on payment page and invoice list issue on voucher and commented create/edit/preview receipt/payment 

apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/billing-details/billingDetail.component.ts, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts
https://app.clickup.com/t/1y8nxd7
=> Dilpreet | Test | fixed billing details state issue and move company issue 

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Dilpreet | Test | Fix previews filled data issue

apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/billing-details/billingDetail.component.ts, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts
https://app.clickup.com/t/1y8nxd7
=> Dilpreet | Stage | Fixed subscription new design issues

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/shared/layout/layout.component.ts
https://app.clickup.com/t/4dckk9
=> Ravinder | Stage | Setting side bar is getting closed automatically when going to setting modules

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts
https://app.clickup.com/t/1ym2x4m
https://app.clickup.com/t/1ym2g8u
https://app.clickup.com/t/1ym2fgh
=> Ravinder | Test | Fixed voucher type and account unique name issue in adjustment invoice-list api

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.scss, apps/web-giddh/src/assets/css/style-2.scss
=> Dilpreet | Test | Fixed vendor page issues

apps/web-giddh/src/app/userDetails/components/move-company/move-company.component.html, apps/web-giddh/src/app/userDetails/components/move-company/move-company.component.ts
https://app.clickup.com/t/1y8nxd7
=> Dilpreet | Test | Fixed move company dropdown issue

apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js, apps/web-giddh/src/environments/environment.stage.ts, apps/web-giddh/src/meta/yodlee-success.html, apps/web-giddh/webpack.stage.partial.js
=> Ravinder | Stage | Updated API url for stage ENV

apps/web-giddh/src/assets/css/style-2.scss
=> Dilpreet | Test | Remove border form form control for pay now popup

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts, apps/web-giddh/src/app/models/api-models/BranchTransfer.ts
https://app.clickup.com/t/1y2vwb4
=> Ravinder | Stage | Not able to change stock in update for multiple product delivery challan and receipt note

apps/web-giddh/src/app/ledger/components/share-ledger/share-ledger.component.html, apps/web-giddh/src/app/material-ledger/components/share-ledger/share-ledger.component.html
=> Ravinder | Prod | Not able to share the ledger report

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/services/apiurls/sales.api.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/services/sales.service.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/services/adjustment-utility.service.ts
https://app.clickup.com/t/1ym4nmt
=> Ravinder | Test | Wrong voucher types is getting passed in invoice list api in update purchase voucher flow

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1ytjvx3
https://app.clickup.com/t/1ym4hqy
https://app.clickup.com/t/1yzb1un
https://app.clickup.com/t/1ym2x4m
=> Ravinder | Test | Fixed adjustment issues

apps/web-giddh/src/app/contact/advanceSearch/contactAdvanceSearch.component.html, apps/web-giddh/src/app/contact/advanceSearch/contactAdvanceSearch.component.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1z52hqa
=> Dilpreet | Test | Fixed small vendor design issues

apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/billing-details/billingDetail.component.scss, apps/web-giddh/src/app/billing-details/billingDetail.component.ts, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1z53rmd
=> Dilpreet | Test | Fixed sanity issue of subsciptions

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts, apps/web-giddh/src/app/manufacturing/edit/mf.edit.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/models/api-models/BranchTransfer.ts, apps/web-giddh/src/app/models/interfaces/nameUniqueName.interface.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts, apps/web-giddh/src/app/settings/create-address/create-address.component.ts
https://app.clickup.com/t/1wfay2z
=> Ravinder | Test | Integrated branch/warehouse archive

apps/web-giddh/src/app/contact/contact.component.html, apps/web-giddh/src/app/contact/contact.component.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1yzgjep
=> Dilpreet | Test | Fixed custom fields issue and designing issues

apps/web-giddh/src/app/models/api-models/Sales.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1z57xag
=> Ravinder | Test | Exchange rate is not getting updated when user open voucher in edit mode.

apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss
https://app.clickup.com/t/1z57w4e
=> Dilpreet | Test | Fixed dropdown issue on customer/vendor

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
https://app.clickup.com/t/1z58c5j
=> Ravinder | Test | GET stock API for rate

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts
https://app.clickup.com/t/1z58c5j
=> Ravinder | Stage | GET stock API for rate

apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
=> Ravinder | Stage | Removed free plans

apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
=> Ravinder | Beta | Removed free plans

apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
=> Ravinder | Prod | Removed free plans

apps/web-giddh/src/app/contact/aging-report/aging-report.component.html, apps/web-giddh/src/app/theme/command-k/command.k.component.html, apps/web-giddh/src/app/theme/command-k/command.k.component.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zarzkd
=> Dilpreet | Test | Fixed days popup issue and shivansh for cmd+g

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/1zaxmx8
=> Ravinder | Test | Exchange rate 1 USD = 1 Rs is getting called when user create any voucher from voucher page.

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/settings/services/settings-utility.service.ts, apps/web-giddh/src/app/shared/header/header.component.ts, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.html, apps/web-giddh/src/app/shared/primary-sidebar/company-branch/company-branch.component.ts
https://app.clickup.com/t/1zawz7y
https://app.clickup.com/t/1zayxjc
https://app.clickup.com/t/1zazrvg
=> Ravinder | Test | if all branches are archived, switch company view

apps/web-giddh/src/app/shared/header/header.component.ts
=> Fixed page reload issue

apps/web-giddh/src/app/contact/aging-dropdown/aging.dropdown.component.ts, apps/web-giddh/src/app/contact/aging-report/aging-report.component.html, apps/web-giddh/src/app/contact/aging-report/aging-report.component.scss, apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts, apps/web-giddh/src/app/theme/command-k/command.k.component.html, apps/web-giddh/src/app/theme/command-k/command.k.component.scss
https://app.clickup.com/t/1zarzkd
=> Dilpreet | Test | Fixed both issue cmd and days popup

apps/web-giddh/src/app/settings/branch/branch.component.scss, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zghx9n
=> Shivansh | Test | Fixed Design Issue on branch listing page and branch transfer page

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zghx9n
=> Dilpreet | Stage | Fixed two design issue found in Pop-up when we go on branch transfer

apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zghx9n
=> Dilpreet | Test | Fixed toast issue again

apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
https://app.clickup.com/t/1zartrr
=> Dilpreet | Test | Fixed date-picker not showing

apps/web-giddh/src/app/manufacturing/report/mf.report.component.scss
https://app.clickup.com/t/1zartrr
=> Dilpreet | Stage | Fixed datapicker not showing

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xqfnjp
=> Dilpreet | Test | Fixed dropdown issue

apps/web-giddh/src/app/settings/address-settings/address-settings.component.html, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zw5gha
=> Dilpreet | Test | Merge stage branch and resolved conflicts

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/201udkx
=> Ravinder | Stage | No warehouse found with unique name undefined in update voucher

apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/201vzbz
=> Ravinder | Stage | Setting Side Bar is not working Properly

apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/201vzbz
=> Ravinder | Beta | Setting Side Bar is not working Properly

apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zw5gha
=> Dilpreet | Test | Fixed with cherry-pick in test from stage branch

apps/web-giddh/src/app/material-ledger/ledger.component.ts
https://app.clickup.com/t/201tx09
=> Dilpreet | Test | Fixed dialog issue 

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/20d4hh5
=> Ravinder | Test | Fixed warehouse and account unique name bug

apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/20d4hh5
=> Ravinder | Test | On create PO page, warehouse option is not coming in case of stock entry

apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/20d4hh5
=> Ravinder | Stage | On create PO page, warehouse option is not coming in case of stock entry

apps/web-giddh/src/app/settings/address-settings/address-settings.component.html, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1zw5gha
=> Dilpreet | Stage | Fixed unlink wrapper

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts
https://app.clickup.com/t/207e9a8
=> Dilpreet | Stage | Fixed NaN issue on payment pop up when adding amount with commma

apps/web-giddh/src/app/contact/contact.component.html
https://app.clickup.com/t/20jxv71
=> Ravinder | Test | On customer/vendor page download CSV option is not coming without selecting any debtor

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.html, apps/web-giddh/src/app/purchase/create-purchase-order/create-purchase-order.component.ts
https://app.clickup.com/t/1zvzr22
=> Ravinder | Test | Exchange rate issue

apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.ts, apps/web-giddh/src/app/inventory/inventory.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/login/login.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/1xbzq2h
https://app.clickup.com/t/1xbzpzw
https://app.clickup.com/t/1xbznvb
 https://app.clickup.com/t/1xbznp2
https://app.clickup.com/t/1xbzn1a
https://app.clickup.com/t/1xbzm6t
https://app.clickup.com/t/1x6670d
https://app.clickup.com/t/1vy23vy 
https://app.clickup.com/t/1v79xrw
https://app.clickup.com/t/1mm9697
https://app.clickup.com/t/1xbznbg:
=> Dilpreet | Test | UI Exception bugs fixed

apps/web-giddh/src/app/contact/contact.component.html
https://app.clickup.com/t/20jxv71
=> Ravinder | Stage | On customer/vendor page download CSV option is not coming without selecting any debtor

apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.html, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss
https://app.clickup.com/t/20jy344
https://app.clickup.com/t/20jy1kc
=> Dilpreet | Test | Fixed renew button issue and subscription plan design issue

apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.html, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.scss
https://app.clickup.com/t/20jy344
https://app.clickup.com/t/20jy1kc
=> Dilpreet | Stage | Fixed renew button issue and subscription plan design issue

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
https://app.clickup.com/t/21fgj03
=> Ravinder | Test | Bonsai plan is not showing on get all plan page for other than Indian companies

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/20k2h19
=> Ravinder | Test | Open E-invoice cancellation pop up when user try to cancel E-invoice voucher from get all page

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts
https://app.clickup.com/t/21fgj03
=> Ravinder | Stage | Bonsai plan is not showing on get all plan page for other than Indian companies

apps/web-giddh/src/app/companyImportExport/component/form/company-import-export-form.ts, apps/web-giddh/src/app/financial-reports/components/filter/filter.component.ts, apps/web-giddh/src/app/inventory/inventory.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/ledger/ledger.component.ts, apps/web-giddh/src/app/login/login.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
=> Dilpreet | Stage | Fixed 8 bugs of ui exception

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/b9nn59
=> Ravinder | Stage | customer aging and invoice page issues

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/services/receipt.service.ts
https://app.clickup.com/t/3qc38x
=> Dilpreet | Test | Fixed with send params in advance receipt filter 

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/app.module.ts, apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts, apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/201tx09
=> Dilpreet | Test | Fixed all dialog close on route change 

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/21uwgvg
https://app.clickup.com/t/21fkuj6
https://app.clickup.com/t/1zvzemw
=> Ravinder | Test | Fixed voucher bugs

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/locale/proforma-invoice/en.json, apps/web-giddh/src/assets/locale/proforma-invoice/hi.json, apps/web-giddh/src/assets/locale/proforma-invoice/mr.json
https://app.clickup.com/t/21fgcj7
=> Dilpreet | Test | On voucher page copy from previous invoices dropdown is not closing when clicking outside

apps/web-giddh/src/app/theme/ng-virtual-select/sh-select.component.ts
https://app.clickup.com/t/21v40y2
=> Ravinder | Test | Reference invoice list not shown

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/locale/proforma-invoice/en.json, apps/web-giddh/src/assets/locale/proforma-invoice/hi.json, apps/web-giddh/src/assets/locale/proforma-invoice/mr.json
https://app.clickup.com/t/21fgcj7
=> Dilpreet | Stage | On voucher page copy from previous invoices dropdown is not closing when clicking outside

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts
https://app.clickup.com/t/220n4j1
=> Dilpreet | Test | Prod - Getting error Invalid value provided for Key: amount while doing payment from vendor page

apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/billing-details/billingDetail.component.scss, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.html
https://app.clickup.com/t/226ec7y
=> Dilpreet | Test | Prod - On subscription>get all plan and billing page, currency icon is not coming in companies currency

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
https://app.clickup.com/t/226efmc
=> Dilpreet | Test | Prod - On invoice>pending page, blank space is coming when scrolling the table horizontally

apps/web-giddh/src/app/billing-details/billingDetail.component.html, apps/web-giddh/src/app/billing-details/billingDetail.component.scss, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.html
https://app.clickup.com/t/226ec7y
=> Dilpreet | Stage | Prod - On subscription>get all plan and billing page, currency icon is not coming in companies currency

apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts
https://app.clickup.com/t/226efmc
=> Dilpreet | Stage |  Prod - On invoice>pending page, blank space is coming when scrolling the table horizontally

apps/web-giddh/src/app/invoice/preview/models/invoicePayment/invoice.payment.model.component.html
=> Ravinder | Test | Fixed payment save button issue

apps/web-giddh/src/app/contact/advanceSearch/contactAdvanceSearch.component.html, apps/web-giddh/src/app/contact/aging-report/aging-report.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html
https://app.clickup.com/t/22c782b
=> Dilpreet | Test | Prod - On payment pop up, sometimes border is not coming of amount and OTP field

apps/web-giddh/src/app/contact/advanceSearch/contactAdvanceSearch.component.html, apps/web-giddh/src/app/contact/aging-report/aging-report.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html
https://app.clickup.com/t/22c782b
=> Dilpreet | Stage | Prod - On payment pop up, sometimes border is not coming of amount and OTP field

apps/web-giddh/src/app/contact/advanceSearch/contactAdvanceSearch.component.html, apps/web-giddh/src/app/contact/aging-report/aging-report.component.html, apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.html, apps/web-giddh/src/app/invoice/generate/invoice.generate.component.scss
https://app.clickup.com/t/22c782b
=> Dilpreet | Beta | Stage to Beta 

apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/22c84r5
=> Dilpreet | Test | Increase login session renew time

apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.html, apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/assets/locale/invoice/ewaybill/en.json, apps/web-giddh/src/assets/locale/invoice/ewaybill/hi.json, apps/web-giddh/src/assets/locale/invoice/ewaybill/mr.json
https://app.clickup.com/t/22c8ucy
https://app.clickup.com/t/22c7mfc
=> Ravinder | Test | Fixed Ewaybill and Hide PO linking from PB

apps/web-giddh/src/app/contact/contact.component.ts, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.ts
https://app.clickup.com/t/22htzkn
=> fix: clickup-20d6pcj | Prateek | Test | Multiple custom fields in put api request

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html
https://app.clickup.com/t/22qhhgw
=> Dilpreet | Test | Remove "Previous due" from credit/debit note template

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/services/general.service.ts
https://app.clickup.com/t/22qgdjv
=> feat: Enable JV for whozzat domain

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/services/general.service.ts
https://app.clickup.com/t/22qgdjv
=> feat: clickup-22qgdjv | Prateek | Enable JV for whozzat domain

apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/generateEWayBill/generateEWayBill.component.ts, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.html, apps/web-giddh/src/app/purchase/purchase-order-preview/purchase-order-preview.component.ts, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.html, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.ts, apps/web-giddh/src/assets/locale/invoice/en.json, apps/web-giddh/src/assets/locale/invoice/hi.json, apps/web-giddh/src/assets/locale/invoice/mr.json
https://app.clickup.com/t/22c8ucy?comment=787315441
https://app.clickup.com/t/22c7mfc?comment=787396906
=> fix: Issue #22c8ucy, #22c8ucy

apps/web-giddh/src/app/invoice/templates/edit-template/filters-container/content-filters/content.filters.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-a/gst-template-a.component.html, apps/web-giddh/src/app/invoice/templates/edit-template/out-tempate/templates/gst-template-e/gst-template-e.component.html
https://app.clickup.com/t/22qhhgw
=> Dilpreet | Test | Fixed more 2 issues found

apps/web-giddh/src/app/actions/invoice/invoice.actions.ts, apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts, apps/web-giddh/src/app/invoice/preview/models/download-or-send-mail/download-or-send-mail.component.ts, apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.ts, apps/web-giddh/src/app/models/api-models/Invoice.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/proforma-invoice/services/proforma-invoice-utility.service.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/shared/purchase-send-email/purchase-send-email.component.ts, apps/web-giddh/src/app/shared/send-email-invoice/send-email-invoice.component.ts, apps/web-giddh/src/app/vat-report/transactions/vatReportTransactions.component.ts
https://app.clickup.com/t/bnaz1m
https://app.clickup.com/t/220thp9
https://app.clickup.com/t/1vy7q4q
=> Ravinder | Test | Fixed NV logic bugs

apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/src/assets/css/toastr.css
https://app.clickup.com/t/22xahrh
=> Dilpreet | Test | Prod - Design issue on toaster message when subscription got expired.

apps/web-giddh/src/app/app.routes.ts, apps/web-giddh/src/app/invoice/thermal-pdf/thermal-pdf.component.html, apps/web-giddh/src/app/invoice/thermal-pdf/thermal-pdf.component.ts, apps/web-giddh/src/app/invoice/thermal-pdf/thermal-pdf.module.ts, apps/web-giddh/src/app/invoice/thermal-pdf/thermal-pdf.routing.module.ts, apps/web-giddh/src/app/routes-array.ts, package.json
https://app.clickup.com/t/1ke3z9
=> Dilpreet | Test | Conflict resolve with include thermal node package only

apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/material-ledger/components/ledger-columnar-report-table/ledger-columnar-report-table.component.html, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/ledger.component.html, apps/web-giddh/src/app/models/api-models/Invoice.ts, apps/web-giddh/src/app/payment-receipt/components/preview/preview.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/reports/components/advance-receipt-report/advance-receipt-report.component.html, apps/web-giddh/src/app/reports/components/payment-report/payment-report.component.html, apps/web-giddh/src/app/theme/attachments/attachments.component.html, apps/web-giddh/src/assets/locale/en.json, apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json
https://app.clickup.com/t/22qq4wp
https://app.clickup.com/t/1vjnfv2
=> Ravinder | Test | Working on NV Logic tasks

apps/web-giddh/src/app/contact/aging-dropdown/aging.dropdown.component.ts
https://app.clickup.com/t/22xdftz
=> Dilpreet | Test | Not able to Change date interval

apps/web-giddh/src/app/contact/aging-dropdown/aging.dropdown.component.html, apps/web-giddh/src/app/contact/aging-dropdown/aging.dropdown.component.ts
https://app.clickup.com/t/22xdftz
=> Dilpreet | Test | Not able to Change date interval fix with suggestions

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts, apps/web-giddh/src/app/services/apiurls/invoice.api.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/shared/revision-history/revision-history.component.ts, apps/web-giddh/src/assets/locale/invoice/revision-history/en.json, apps/web-giddh/src/assets/locale/invoice/revision-history/hi.json, apps/web-giddh/src/assets/locale/invoice/revision-history/mr.json
=> Ravinder | Test | Implemented revision history for all voucher types

apps/web-giddh/src/app/contact/aging-dropdown/aging.dropdown.component.html, apps/web-giddh/src/app/contact/aging-dropdown/aging.dropdown.component.ts
https://app.clickup.com/t/22xdftz
=> Dilpreet | Stage | PROD:- "Not able to Change date interval"

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
=> Ravinder | Test | Fixed Voucher version condition

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/locale/en.json, apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json
https://app.clickup.com/t/232zvg2
=> Ravinder | Test | Fixed custom fields issues

apps/web-giddh/src/app/shared/header/components/account-add-new-details/account-add-new-details.component.html, apps/web-giddh/src/app/shared/header/components/account-update-new-details/account-update-new-details.component.html, apps/web-giddh/src/assets/css/style-1.scss, apps/web-giddh/src/assets/locale/en.json, apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json
https://app.clickup.com/t/232zvg2
=> Ravinder | Stage | Fixed custom fields issues

apps/web-giddh/src/app/inventory/components/group-stock-report-component/group.stockreport.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.html, apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.html, apps/web-giddh/src/app/reports/components/reverse-charge-report-component/reverse-charge-report.component.html, apps/web-giddh/src/app/shared/send-email-invoice/send-email-invoice.component.html
https://app.clickup.com/t/232z660
https://app.clickup.com/t/23303m6
https://app.clickup.com/t/23317r0
https://app.clickup.com/t/22qq4wp
=> Ravinder | Test | Fixed Voucher logic bugs

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/23311kv
=> Ravinder | Test | Fixed Exchange gain issue

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts
https://app.clickup.com/t/232xzq8
=> Ravinder | Stage | Stage Sanity Issue

apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/23310qg
=> Ravinder | Test | custom field values not shown on custom page with separate column

apps/web-giddh/src/app/daybook/daybook.component.ts
=> Ravinder | Test | In daybook, Financial year is not coming and in inventory report, download button is not present.

apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/23310qg
=> Ravinder | Stage | custom field values not shown on custom page with separate column

apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/23310qg
=> Ravinder | Beta | custom field values not shown on custom page with separate column

apps/web-giddh/src/app/daybook/daybook.component.ts
=> Ravinder | Stage | In daybook, Financial year is not coming and in inventory report, download button is not present.

apps/web-giddh/src/app/daybook/daybook.component.ts
=> Ravinder | Beta | In daybook, Financial year is not coming and in inventory report, download button is not present.

apps/web-giddh/src/app/contact/payment-aside/payment-aside.component.ts
https://app.clickup.com/t/220n4j1
=> Dilpreet | Stage | Prod - Getting error Invalid value provided for Key: amount while doing payment from vendor page

apps/web-giddh/src/app/contact/contact.component.ts
https://app.clickup.com/t/23310qg
=> Ravinder | Prod | custom field values not shown on custom page with separate column

apps/web-giddh/src/app/daybook/daybook.component.ts
=> Ravinder | Prod | In daybook, Financial year is not coming and in inventory report, download button is not present.

apps/web-giddh/src/app/financial-reports/components/filter/filter.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/profit-loss.component.ts
https://app.clickup.com/t/238nq2f
=> Ravinder | Test | In Profit and Loss Report In case of Gross Loss, Gross Profit is showing

apps/web-giddh/src/app/services/purchase-record.service.ts
https://app.clickup.com/t/238pm9p
=> Ravinder | Test | Fixed company unique name issue in pb v1

apps/web-giddh/src/app/services/purchase-record.service.ts
https://app.clickup.com/t/238pm9p
=> Ravinder | Stage | Fixed company unique name issue in pb v1

apps/web-giddh/src/app/financial-reports/components/filter/filter.component.html, apps/web-giddh/src/app/financial-reports/components/profit-loss/profit-loss.component.ts
https://app.clickup.com/t/238nq2f
=> Ravinder | Stage | In Profit and Loss Report In case of Gross Loss, Gross Profit is showing

apps/web-giddh/src/app/financial-reports/components/profit-loss/profit-loss.component.ts
https://app.clickup.com/t/238nq2f
=> Ravinder | Beta | In Profit and Loss Report In case of Gross Loss, Gross Profit is showing

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.html, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts, apps/web-giddh/src/app/welcome/welcome.component.ts
https://app.clickup.com/t/232zzha
=> Ravinder | Stage | User is not able to create new company in stage Env

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
(https://app.clickup.com/t/1vczr7x)
=> Dilpreet | Test | Fixed with suggestion of tester

apps/web-giddh/src/app/app.constant.ts, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.html, apps/web-giddh/src/app/userDetails/components/subscription/subscription.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts, apps/web-giddh/src/app/welcome/welcome.component.ts
https://app.clickup.com/t/232zzha
=> Ravinder | Beta | User is not able to create new company in stage Env

apps/web-giddh/src/app/material-ledger/components/new-ledger-entry-panel/new-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/1xqfnjp
=> Dilpreet | Beta | Manually writen code from test to beta

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss
https://app.clickup.com/t/1vczr7x
=> Dilpreet | Stage | Fixed button issue on stage

apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.ts, apps/web-giddh/src/assets/magic-link-assets/magic-link-script.js
https://app.clickup.com/t/238vter
=> Ravinder | Stage | Fixed Issues

apps/web-giddh/src/app/material-ledger/components/update-ledger-entry-panel/update-ledger-entry-panel.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts
https://app.clickup.com/t/1xqfnjp
=> Dilpreet | Beta | Remove body class on ng on init

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/app.module.ts, apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts, apps/web-giddh/src/assets/css/style-2.scss
Reverts Walkover-Web-Solution/Giddh-New-Angular4-App#9846
=> Revert "Dilpreet | Stage | Fixed all dialog close on route change"

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/app.module.ts, apps/web-giddh/src/app/contact/aging-report/aging-report.component.ts, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.list.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.ts, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/201tx09
=> Dilpreet | Stage | Manually write code from Old PR for fixed all dialog close on route change

apps/web-giddh/src/app/services/ledger.service.ts
https://app.clickup.com/t/238vjag
=> Ravinder | Stage | No loader is coming on ledger while deleting entries in bulk

apps/web-giddh/src/app/daybook/daybook.component.ts, apps/web-giddh/src/app/gst/filing/tabs/overview/view-transactions/view-transactions.component.ts, apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.ts, apps/web-giddh/src/app/models/api-models/recipt.ts, apps/web-giddh/src/app/shared/helpers/pipes/recType/recType.pipe.ts
https://app.clickup.com/t/23ede6z
https://app.clickup.com/t/23ecujq
https://app.clickup.com/t/23eddc9
https://app.clickup.com/t/238x9qn
=> Ravinder | Test | Fixed PROD Bugs

apps/web-giddh/src/app/shared/aside-menu-other-taxes/aside-menu-other-taxes.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/23317f4
=> Dilpreet | Test | Fixed sidebar issue on invoice preview sales

apps/web-giddh/src/app/app.component.ts, apps/web-giddh/src/app/invoice/preview/invoice.preview.component.scss, apps/web-giddh/src/app/material-ledger/ledger.component.ts, apps/web-giddh/src/app/purchase/purchase-order/purchase-order.component.scss, apps/web-giddh/src/app/userDetails/components/subscriptions-plans/subscriptions-plans.component.ts, apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/22xahrh
=> Dilpreet | Test | Pull from PR #9919 and resolved conflicts

apps/web-giddh/src/app/inventory/components/new-branch-transfer/new.branch.transfer.add.component.html, apps/web-giddh/src/app/invoice/eWayBill/create/eWayBill.create.component.html, apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.html, apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.scss, apps/web-giddh/src/app/invoice/eWayBill/eWayBill/eWayBill.component.ts, apps/web-giddh/src/app/invoice/preview/models/bulk-export-modal/bulk-export.component.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.ts, apps/web-giddh/src/assets/locale/en.json, apps/web-giddh/src/assets/locale/hi.json, apps/web-giddh/src/assets/locale/mr.json
https://app.clickup.com/t/23m9wjc
https://app.clickup.com/t/23txwxx
https://app.clickup.com/t/23u1hr9
https://app.clickup.com/t/23u1g46
https://app.clickup.com/t/23u1t15 
https://app.clickup.com/t/23mb7n7
=> Ravinder | Stage | Fixed E-way bill issues

apps/web-giddh/src/app/invoice/preview/models/download-voucher/download-voucher.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.html, apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.ts
https://app.clickup.com/t/245fe2q
=> Ravinder | Test | For credit/debit note and PB open download pop up from preview page if voucher has attachment

apps/web-giddh/src/app/shared/header/header.component.ts
https://app.clickup.com/t/22c84r5
=> Dilpreet | Stage | Increase login session renew time

apps/web-giddh/src/assets/css/style-2.scss
https://app.clickup.com/t/22xahrh
=> Dilpreet | Test | Fix nav bar overlapping issue

apps/web-giddh/src/app/onboarding/onboarding.component.scss, apps/web-giddh/src/app/theme/ngx-date-range-picker/ngx-daterangepicker.component.scss, apps/web-giddh/src/assets/css/themes/dark.scss, apps/web-giddh/src/assets/css/themes/default.scss
=> Ravinder | Test | Fixed PR issues of color theme

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/shared/helpers/currencyNumberSystem.ts
https://app.clickup.com/t/24b6061
https://app.clickup.com/t/24b5fca
https://app.clickup.com/t/24b5u6h
=> Ravinder | Test | Fixed Voucher UI bugs

apps/web-giddh/src/app/invoice/preview/invoice.preview.component.html
https://app.clickup.com/t/24guxj8
=> Ravinder | Test | Fixed NA bug

apps/web-giddh/src/app/invoice/preview/models/invoice-preview-details/invoice-preview-details.component.scss, apps/web-giddh/src/app/payment-receipt/components/preview/preview.component.scss, apps/web-giddh/src/app/theme/snackbar/snackbar.component.scss
=> Ravinder | Test | Fixed color issues

apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.html, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.ts, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.module.ts, apps/web-giddh/src/app/services/general.service.ts, apps/web-giddh/src/app/services/invoice.service.ts, apps/web-giddh/src/app/shared/advance-receipt-adjustment/advance-receipt-adjustment.component.html, apps/web-giddh/src/app/shared/advance-receipt-adjustment/services/adjustment-utility.service.ts, apps/web-giddh/src/app/shared/helpers/pipes/replace/replace.pipe.ts
https://app.clickup.com/t/24b29xc
https://app.clickup.com/t/2459hfx
https://app.clickup.com/t/201nune
https://app.clickup.com/t/23zht7h
https://app.clickup.com/t/24pgb8p
=> Ravinder | Stage | Fixed Voucher Bugs

apps/web-giddh/src/app/login/login.component.scss, apps/web-giddh/src/app/proforma-invoice/proforma-invoice.component.scss, apps/web-giddh/src/app/signup/signup.component.scss, apps/web-giddh/src/app/theme/ng-virtual-select/sh-select-menu.component.scss, apps/web-giddh/src/assets/css/style-2.scss, apps/web-giddh/src/assets/css/themes/dark.scss, apps/web-giddh/src/assets/css/themes/default.scss
=> Ravinder | Test | Fixed Color theme issues

apps/web-giddh/src/app/login/login.component.scss, apps/web-giddh/src/app/signup/signup.component.scss
=> Shivansh | Test | Fixed Login and Signup page color issue

apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/251yjua
=> fix: clickup-#251yjua | Prateek | Test | Stock rate is getting reduced if user increase the quantity of stock on voucher page.

apps/web-giddh/src/app/theme/tax-control/tax-control.component.ts
https://app.clickup.com/t/251yjua
=> fix: clickup-#251yjua | Prateek | Stage | Stock rate is getting reduced if user increase the quantity of stock on voucher page.
